### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out while downloading libraries.

### ISSUE THREAD

**Issue by KS-HTK** [itzg/docker-minecraft-server#1002]
I get this Issue:
```
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
        at net.minecraftforge.installer.DownloadUtils.getConnection(DownloadUtils.java:202)
        at net.minecraftforge.installer.DownloadUtils.downloadMirrors(DownloadUtils.java:252)
        at net.minecraftforge.installer.json.Install.getMirror(Install.java:116)
        at net.minecraftforge.installer.actions.ServerInstall.run(ServerInstall.java:53)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:127)
```
        
While trying to install a CurseForge Modpack using following Docker Compose:
```yaml
version: '3.6'
services:
  minecraft:
    container_name: val3
    image: itzg/minecraft-server:java8
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      VIEW_DISTANCE: "12"
      MOTD: "Valhelsia 3 Server"

      TYPE: "CURSEFORGE"
      VERSION: "1.16.5"
      CF_SERVER_MOD: "/modpacks/valhelsia3-server.zip"
      CF_BASE_DIR: "/data"
      FORCE_REDOWNLOAD: "true"
      REMOVE_OLD_MODS: "true"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: "7200"
      AUTOPAUSE_TIMEOUT_KN: "240"
      TZ: "Europe/Berlin"
      MEMORY: "10G"
      USE_AIKAR_FLAGS: "true"
    volumes:
      - "~/val3/data:/data"
      - "~/modpacks:/modpacks"
    restart: always
```

**Comment by itzg** [comment]
I'm afraid that's not something I can fix from the the image. As you've probably the noticed the failure is within the forge installer and is somehow influenced by network connectivity towards their library repo.

**Comment by itzg** [comment]
If you don't mind, I can convert this issue to a discussion to see if others have encountered and fixed this scenario.

**Comment by KS-HTK** [comment]
Thank you for the Info, changing this into a Discussion seems to be a good Idea.
I had tried to find a solution and have not found anything helpfull yet.
If terminating the `docker-compose` and then starting the docker container it just errors out saying to rerun the install script.
Is it possible to start the ServerStart.sh from within the Container?
Or is that what `docker start` is doing?

I was able to run the `ServerStart.bat` locally and did not run into this issue. It seems that the response to the first library download takes a lot longer than any subsequent ones. Is there a way to set a higher timeout for downloads or would the script of the Modpack have to do that?

**Comment by itzg** [comment]
> Is it possible to start the ServerStart.sh from within the Container?
Or is that what docker start is doing?

Yes, that's what it already does.

So, again, the start script provided by the modpack is beyond my control via the image.

Modpack scripts are inconsistent and some are broken, so you could also try

https://github.com/itzg/docker-minecraft-server#buggy-start-scripts
