### ISSUE TITLE
Seems to be an error in the server.  Do we report it upstream?

### ISSUE THREAD

**Issue by crahn** [itzg/docker-minecraft-server#1008]
[12:08:09] [Server thread/ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key foliage_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
[12:08:09] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at dbg.k(SourceFile:54) ~[minecraft_server.1.17.1.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at dbg.<init>(SourceFile:54) ~[minecraft_server.1.17.1.jar:?]
	at cud.a(SourceFile:151) ~[minecraft_server.1.17.1.jar:?]
	at cnj.a(SourceFile:415) ~[minecraft_server.1.17.1.jar:?]
	at cnj.a(SourceFile:175) ~[minecraft_server.1.17.1.jar:?]
	at abe.l(SourceFile:512) ~[minecraft_server.1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at aqv.c(SourceFile:151) ~[minecraft_server.1.17.1.jar:?]
	at abp$a.c(SourceFile:528) ~[minecraft_server.1.17.1.jar:?]
	at aqv.z(SourceFile:125) ~[minecraft_server.1.17.1.jar:?]
	at abp$a.z(SourceFile:537) ~[minecraft_server.1.17.1.jar:?]
	at abp.d(SourceFile:280) ~[minecraft_server.1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.bf(SourceFile:776) ~[minecraft_server.1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.z(SourceFile:764) ~[minecraft_server.1.17.1.jar:?]
	at aqv.bp(SourceFile:110) ~[minecraft_server.1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.y(SourceFile:748) ~[minecraft_server.1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.x(SourceFile:701) ~[minecraft_server.1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:270) ~[minecraft_server.1.17.1.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by itzg** [comment]
Yes, please report upstream

**Comment by crahn** [comment]
Done.  Thank you.

https://bugs.mojang.com/browse/MC-234858

**Comment by crahn** [comment]
1
