### ISSUE TITLE
error: FTB - A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by focheur91300** [itzg/docker-minecraft-server#1026]
I'm using the below docker-compose.yml file to run the server with FTB Infinity Evolved 1.7 though it exits with an error: "A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException" any ideas what i'm doing wrong?

```
version: '3.8'

services:
 minecraft_ftb:
  hostname: minecraft_ftb
  domainname: docker
  container_name: minecraft_ftb
  image: itzg/minecraft-server:latest
  volumes:
   - type: volume
     source: minecraft_ftb_data
     target: "/data"
  
  environment:
   - "EULA=TRUE"
   - "TYPE=FTBA"
   - "FTB_MODPACK_ID=23"
   - "TZ=Europe/Paris"
   - "UID=0"
   - "GID=0"
   - "MEMORY=4G"
  ports:
   - "25565:25565"
  networks:
   local:
    ipv4_address: 10.0.3.28
  restart: always  
```

Logs :
```
[init] Running as uid=0 gid=0 with /data as 'drwxrwxr-x 8 0 0 4096 Sep  1 12:10 /data'

[init] Resolved version given LATEST into 1.17.1

[init] Resolving type given FTBA

[init] FTB modpack ID 23, version ID 99 is ready to go

[init] server.properties already created, skipping

[init] Checking for JSON files.

[init] Setting initial memory to 4G and max to 4G

[init] Starting the Minecraft server...

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)

	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)

Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')

	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

	... 6 more

2021-09-01T12:36:34.857+0200	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}

2021-09-01T12:36:34.857+0200	INFO	mc-server-runner	Done
```

Thank you.

**Comment by itzg** [comment]
Try changing the image to `itzg/minecraft-server:java8-multiarch` since that looks like a Java api mismatch.

**Comment by focheur91300** [comment]
Hi @itzg 

Thank you, it works perfectly.
