### ISSUE TITLE
Failed to read chunk data Stale file handle

### ISSUE THREAD

**Issue by Spomyx** [itzg/docker-minecraft-server#1033]
Hi,
i use latest version of docker image and encounter the following error message flooding the logs
eventually causing the server to crash
"at" position varies for each log entry

version: Paper version git-Paper-251 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5960af9)
system: Kubernetes with containerd runtime and NFS provided storage

error:
[22:12:16 FATAL]: Failed to read chunk data for task: Task for world: 'world' at -53,32 poi: false, hash: 1777310071
java.io.IOException: Stale file handle
        at sun.nio.ch.FileDispatcherImpl.pread0(Native Method) ~[?:?]
        at sun.nio.ch.FileDispatcherImpl.pread(Unknown Source) ~[?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:?]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:?]
        at sun.nio.ch.FileChannelImpl.readInternal(Unknown Source) ~[?:?]
        at sun.nio.ch.FileChannelImpl.read(Unknown Source) ~[?:?]
        at net.minecraft.world.level.chunk.storage.RegionFile.a(RegionFile.java:594) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.world.level.chunk.storage.RegionFileCache.read(RegionFileCache.java:200) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.world.level.chunk.storage.RegionFileCache.read(RegionFileCache.java:192) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.world.level.chunk.storage.IChunkLoader.read(IChunkLoader.java:116) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.server.level.PlayerChunkMap.read(PlayerChunkMap.java:1680) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.server.level.WorldServer$2.readData(WorldServer.java:344) ~[patched_1.17.1.jar:git-Paper-251]
        at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:508) [patched_1.17.1.jar:git-Paper-251]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) [patched_1.17.1.jar:git-Paper-251]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) [patched_1.17.1.jar:git-Paper-251]

sometimes followed by [20:45:25 ERROR]: Could not load chunk for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (-53,32), hashcode:413982729, priority: -1, file IO thread has dumped the relevant exception above

Any idea what causes this behaviour and how to solve this?

Regards,

**Comment by itzg** [comment]
Google around for the phrase "Failed to read chunk data". Looks like something called "mc region fixer" will fix this.

I would like to either close this issue or convert to a discussion.

**Comment by Spomyx** [comment]
Hi,

This morning my users reported that all buildings had disapeared through the night. Luckily for them i had backups and was able to restore.

The server has been restarted and the error appeared again after 2 hours of running fine.
Server needs to be restarted more and more often as time goes on.

I tried to repair chunks using region fixer but i have thousands of chunks with missing tags and it keeps increasing that's why i suspect an issue in the way the server accesses the filesystem.

**Comment by itzg** [comment]
That certainly sounds like an annoying problem, but this is something to report with Paper. Docker containers are simply Linux processes, so there's nothing special about the final execution of the server process.
