### ISSUE TITLE
[Request] Add Crucible Server

### ISSUE THREAD

**Issue by spannerman79** [itzg/docker-minecraft-server#1052]
Project link: https://github.com/CrucibleMC/Crucible

Release: https://github.com/CrucibleMC/Crucible/releases

I suggest that you should be able to use the tag version by an env var. eg; `-e TYPE=CRUCIBLE -e VERSION=4.1` would pull from https://github.com/CrucibleMC/Crucible/releases/tag/v4.1

Minecraft version doesn't need to be declared - default and only 1.7.10

**Comment by itzg** [comment]
I'm sorry it took me a while to get to this. I downloaded the latest Crucible jar from https://github.com/CrucibleMC/Crucible/releases/tag/v5.1, but when running that jar it outputs

```
We appear to be missing one or more essential library files.
You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:28)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15)
```

So, I downloaded the `libraries.zip` but I'm not sure where to put the contents. The documentation on Crucible's repo page is lacking important information like that. Do you know where it goes?

**Comment by spannerman79** [comment]
Whlie using https://github.com/CrucibleMC/Crucible/releases/tag/v5.1

Inside the server directory;

```
wget https://github.com/CrucibleMC/Crucible/releases/download/v5.1/libraries.zip
wget https://github.com/CrucibleMC/Crucible/releases/download/v5.1/Crucible-1.7.10-5.1.jar
unzip libraries.zip -d ./libraries
rm libraries.zip
```

Will need the usual EULA=TRUE text file for which I see you have already for various other MC servers

Final files and directory structure;
```
.
├── Crucible-1.7.10-5.1.jar
├── eula.txt
└── libraries
    ├── com
    │   ├── beust
    │   │   └── jcommander
    │   │       └── 1.30
    │   │           └── jcommander-1.30.jar
    │   ├── google
    │   │   └── guava
    │   │       └── guava
    │   │           └── 19.0
    │   │               └── guava-19.0.jar
    │   ├── googlecode
    │   │   └── json-simple
    │   │       └── json-simple
    │   │           └── 1.1
    │   │               └── json-simple-1.1.jar
    │   ├── koloboke
    │   │   ├── koloboke-api-jdk8
    │   │   │   └── 1.0.0
    │   │   │       └── koloboke-api-jdk8-1.0.0.jar
    │   │   ├── koloboke-impl-common-jdk8
    │   │   │   └── 1.0.0
    │   │   │       └── koloboke-impl-common-jdk8-1.0.0.jar
    │   │   └── koloboke-impl-jdk8
    │   │       └── 1.0.0
    │   │           └── koloboke-impl-jdk8-1.0.0.jar
    │   └── typesafe
    │       ├── akka
    │       │   └── akka-actor_2.11
    │       │       └── 2.3.3
    │       │           └── akka-actor_2.11-2.3.3.jar
    │       └── config
    │           └── 1.2.1
    │               └── config-1.2.1.jar
    ├── commons-cli
    │   └── commons-cli
    │       └── 1.3
    │           └── commons-cli-1.3.jar
    ├── commons-codec
    │   └── commons-codec
    │       └── 1.9
    │           └── commons-codec-1.9.jar
    ├── commons-io
    │   └── commons-io
    │       └── 2.4
    │           └── commons-io-2.4.jar
    ├── commons-lang
    │   └── commons-lang
    │       └── 2.6
    │           └── commons-lang-2.6.jar
    ├── commons-logging
    │   └── commons-logging
    │       └── 1.2
    │           └── commons-logging-1.2.jar
    ├── it
    │   └── unimi
    │       └── dsi
    │           └── fastutil
    │               └── 8.2.2
    │                   └── fastutil-8.2.2.jar
    ├── java3d
    │   └── vecmath
    │       └── 1.3.1
    │           └── vecmath-1.3.1.jar
    ├── javax
    │   └── persistence
    │       └── persistence-api
    │           └── 1.0.2
    │               └── persistence-api-1.0.2.jar
    ├── jline
    │   └── jline
    │       └── 2.6
    │           └── jline-2.6.jar
    ├── lzma
    │   └── lzma
    │       └── 0.0.1
    │           └── lzma-0.0.1.jar
    ├── mysql
    │   └── mysql-connector-java
    │       └── 5.1.14
    │           └── mysql-connector-java-5.1.14.jar
    ├── net
    │   ├── java
    │   │   └── dev
    │   │       └── jna
    │   │           ├── jna
    │   │           │   └── 4.1.0
    │   │           │       └── jna-4.1.0.jar
    │   │           └── jna-platform
    │   │               └── 4.1.0
    │   │                   └── jna-platform-4.1.0.jar
    │   ├── md-5
    │   │   └── SpecialSource
    │   │       └── 1.7.4
    │   │           └── SpecialSource-1.7.4.jar
    │   ├── minecraft
    │   │   ├── launchwrapper
    │   │   │   └── 1.12
    │   │   │       └── launchwrapper-1.12.jar
    │   │   └── server
    │   │       └── 1.7.10
    │   │           └── server-1.7.10.jar
    │   ├── openhft
    │   │   └── affinity
    │   │       └── 3.0.1
    │   │           └── affinity-3.0.1.jar
    │   ├── sf
    │   │   ├── jopt-simple
    │   │   │   └── jopt-simple
    │   │   │       └── 5.0.1
    │   │   │           └── jopt-simple-5.0.1.jar
    │   │   └── opencsv
    │   │       └── opencsv
    │   │           └── 2.3
    │   │               └── opencsv-2.3.jar
    │   └── sourceforge
    │       └── argo
    │           └── argo
    │               └── 2.25
    │                   └── argo-2.25.jar
    ├── org
    │   ├── apache
    │   │   └── httpcomponents
    │   │       ├── httpclient
    │   │       │   └── 4.4.1
    │   │       │       └── httpclient-4.4.1.jar
    │   │       └── httpcore
    │   │           └── 4.4.1
    │   │               └── httpcore-4.4.1.jar
    │   ├── avaje
    │   │   └── ebean
    │   │       └── 2.7.3
    │   │           └── ebean-2.7.3.jar
    │   ├── eclipse
    │   │   └── jetty
    │   │       └── jetty-servlet
    │   │           └── 9.0.3.v20130506
    │   │               └── jetty-servlet-9.0.3.v20130506.jar
    │   ├── fusesource
    │   │   └── jansi
    │   │       └── jansi
    │   │           └── 1.11
    │   │               └── jansi-1.11.jar
    │   ├── kohsuke
    │   │   └── jetbrains
    │   │       └── annotations
    │   │           └── 9.0
    │   │               └── annotations-9.0.jar
    │   ├── ow2
    │   │   └── asm
    │   │       ├── asm-all
    │   │       │   └── 5.0.3
    │   │       │       └── asm-all-5.0.3.jar
    │   │       └── asm-debug-all
    │   │           └── 5.1
    │   │               └── asm-debug-all-5.1.jar
    │   ├── scala-lang
    │   │   ├── modules
    │   │   │   ├── scala-parser-combinators_2.11
    │   │   │   │   └── 1.0.4
    │   │   │   │       └── scala-parser-combinators_2.11-1.0.4.jar
    │   │   │   └── scala-xml_2.11
    │   │   │       └── 1.0.4
    │   │   │           └── scala-xml_2.11-1.0.4.jar
    │   │   ├── plugins
    │   │   │   ├── scala-continuations-library_2.11
    │   │   │   │   └── 1.0.2
    │   │   │   │       └── scala-continuations-library_2.11-1.0.2.jar
    │   │   │   └── scala-continuations-plugin_2.11.2
    │   │   │       └── 1.0.2
    │   │   │           └── scala-continuations-plugin_2.11.2-1.0.2.jar
    │   │   ├── scala-actors
    │   │   │   └── 2.11.0
    │   │   │       └── scala-actors-2.11.0.jar
    │   │   ├── scala-actors-migration_2.11
    │   │   │   └── 1.1.0
    │   │   │       └── scala-actors-migration_2.11-1.1.0.jar
    │   │   ├── scala-compiler
    │   │   │   └── 2.11.7
    │   │   │       └── scala-compiler-2.11.7.jar
    │   │   ├── scala-library
    │   │   │   └── 2.11.7
    │   │   │       └── scala-library-2.11.7.jar
    │   │   ├── scala-parser-combinators
    │   │   │   └── 2.11.0-M4
    │   │   │       └── scala-parser-combinators-2.11.0-M4.jar
    │   │   ├── scala-reflect
    │   │   │   └── 2.11.7
    │   │   │       └── scala-reflect-2.11.7.jar
    │   │   ├── scala-swing
    │   │   │   └── 2.11.0-M7
    │   │   │       └── scala-swing-2.11.0-M7.jar
    │   │   └── scala-xml
    │   │       └── 2.11.0-M4
    │   │           └── scala-xml-2.11.0-M4.jar
    │   ├── slf4j
    │   │   ├── slf4j-api
    │   │   │   └── 1.7.12
    │   │   │       └── slf4j-api-1.7.12.jar
    │   │   └── slf4j-simple
    │   │       └── 1.6.2
    │   │           └── slf4j-simple-1.6.2.jar
    │   ├── xerial
    │   │   └── sqlite-jdbc
    │   │       └── 3.7.2
    │   │           └── sqlite-jdbc-3.7.2.jar
    │   └── yaml
    │       └── snakeyaml
    │           └── 1.9
    │               └── snakeyaml-1.9.jar
    └── pw
        └── prok
            ├── Damask
            │   └── 0.1.2
            │       └── Damask-0.1.2.jar
            ├── KBootstrap
            │   └── 0.3.2
            │       └── KBootstrap-0.3.2.jar
            └── KImagine
                └── 0.2.0
                    └── KImagine-0.2.0.jar
```

If a new server instance - to prevent log spam (not required - optional)

```
touch banned-players.json
touch banned-ips.json
touch ops.json
touch whitelist.json
```

As a test to ensure what I outlined aboved in fact works, with the section above "to prevent log spam"

```
# java -jar Crucible-1.7.10-5.1.jar
[20:51:17 INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[20:51:17 INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[20:51:17 INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[20:51:17 INFO]: Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10 loading
[20:51:18 INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_302, running on Linux:amd64:5.10.60-qnap, installed at /share/CACHEDEV1_DATA/Data/Crucible/jdk8u302-b08/jre
[20:51:18 INFO]: [pw.prok.imagine.ImagineLoadingPlugin:<clinit>:26]: Loading plugin initialized!
[20:51:18 INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:51:18 INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[20:51:18 INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:51:18 INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:51:18 INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:51:19 INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:51:19 INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:51:19 INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[20:51:20 INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[20:51:20 INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[20:51:20 INFO]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[20:51:24 INFO]: Starting minecraft server version 1.7.10
[20:51:24 INFO]: Attempting early MinecraftForge initialization
[20:51:24 INFO]: MinecraftForge v10.13.4.1614 Initialized
[20:51:24 INFO]: Replaced 184 ore recipies
[20:51:24 INFO]: Completed early MinecraftForge initialization
[20:51:24 INFO]: Config directory created successfully
[20:51:24 INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[20:51:24 INFO]: Searching /share/CACHEDEV1_DATA/Data/Crucible/server/mods for mods
[20:51:25 INFO]: Forge Mod Loader has identified 5 mods to load
[20:51:25 INFO]: Crucible DummyMod injected successfully!
[20:51:25 INFO]: Attempting connection with missing mods [mcp, Crucible, FML, Forge, kimagine] at CLIENT
[20:51:25 INFO]: Attempting connection with missing mods [mcp, Crucible, FML, Forge, kimagine] at SERVER
[20:51:25 INFO]: Processing ObjectHolder annotations
[20:51:25 INFO]: Found 341 ObjectHolder annotations
[20:51:25 INFO]: Identifying ItemStackHolder annotations
[20:51:25 INFO]: Found 0 ItemStackHolder annotations
[20:51:25 INFO]: Configured a dormant chunk cache size of 0
[20:51:25 INFO]: Applying holder lookups
[20:51:25 INFO]: Holder lookups applied
[20:51:25 INFO]: Injecting itemstacks
[20:51:25 INFO]: Itemstack injection complete
[20:51:25 INFO]: Loading properties
[20:51:25 WARN]: server.properties does not exist
[20:51:25 INFO]: Generating new properties file
[20:51:26 WARN]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
[20:51:26 INFO]: Default game type: SURVIVAL
[20:51:26 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:815)
[20:51:26 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:768)
[20:51:26 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:717)
[20:51:26 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:689)
[20:51:26 WARN]:        at net.minecraftforge.common.ForgeVersion$1.run(ForgeVersion.java:95)
[20:51:26 WARN]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
[20:51:26 WARN]:        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
[20:51:26 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
[20:51:26 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
[20:51:26 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[20:51:26 WARN]:        ... 4 more
[20:51:26 INFO]: This server is running Cauldron version 1.7.10-5.1-v5-b9d7721 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[20:51:26 INFO]: Using 16 threads for Netty based IO
[20:51:26 INFO]: Generating keypair
[20:51:26 INFO]: Starting Minecraft server on *:25565
[20:51:27 INFO]: Injecting itemstacks
[20:51:27 INFO]: Itemstack injection complete
[20:51:27 INFO]: Forge Mod Loader has successfully loaded 5 mods
[20:51:27 INFO]: Preparing level "world"
[20:51:27 INFO]: Registered command debug with permission node vanilla.command.debug
[20:51:27 INFO]: Registered command spreadplayers with permission node vanilla.command.spreadplayers
[20:51:27 INFO]: Registered command playsound with permission node vanilla.command.playsound
[20:51:27 INFO]: Registered command scoreboard with permission node vanilla.command.scoreboard
[20:51:27 INFO]: Registered command achievement with permission node vanilla.command.achievement
[20:51:27 INFO]: Registered command summon with permission node vanilla.command.summon
[20:51:27 INFO]: Registered command setblock with permission node vanilla.command.setblock
[20:51:27 INFO]: Registered command testforblock with permission node vanilla.command.testforblock
[20:51:27 INFO]: Registered command tellraw with permission node vanilla.command.tellraw
[20:51:27 INFO]: Registered command netstat with permission node vanilla.command.netstat
[20:51:28 WARN]: Unable to find spawn biome
[20:51:28 INFO]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@42223e39)
[20:51:29 INFO]: Loading dimension 1 (DIM1) (net.minecraft.server.dedicated.DedicatedServer@42223e39)
[20:51:29 INFO]: Loading dimension -1 (DIM-1) (net.minecraft.server.dedicated.DedicatedServer@42223e39)
[20:51:29 INFO]: Preparing start region for level 0
[20:51:30 INFO]: Preparing spawn area: 33%
[20:51:31 INFO]: Preparing spawn area: 66%
[20:51:32 INFO]: Preparing spawn area: 87%
[20:51:33 INFO]: Done (5.898s)! For help, type "help" or "?"
[20:51:33 INFO]: Registered command forge with permission node net.minecraftforge.server.command.ForgeCommand
[20:51:33 INFO]: Hey, you don't have a server icon! Try out one of Thermos' Icon Generators at https://github.com/CyberdyneCC/ThermosIconGenerators !
[20:51:33 INFO]: [Thermos] Refusing to lock affinity, disabled in Crucible.yml
[20:51:33 INFO]: Timings Reset
```

**Comment by itzg** [comment]
The latest images now include support for Crucible:

https://github.com/itzg/docker-minecraft-server#running-a-crucible-server

**Comment by itzg** [comment]
Yeah, I'm gradually deprecating the Alpine variants since in the "java8" case it only saves 100MB and those base images don't support multi-architecture.

Glad to hear it's running great for you and thanks for being thorough in your testing. After I get the java8 variant fixed I'll close out the issue.
