### ISSUE TITLE
Fabric server not working with latest snapshot 21w39a

### ISSUE THREAD

**Issue by anaxios** [itzg/docker-minecraft-server#1066]
With all defaults but TYPE set to FABRIC and VERSION set to SNAPSHOT or "21w39a" the server crashes. It won't even get as far as making a log file.

**Comment by itzg** [comment]
I assume I have recreated the issue since I see it failing with:

```
[init] Starting the Minecraft server...
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
	... 2 more
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at net.fabricmc.loader.launch.common.FabricLauncherBase.<clinit>(FabricLauncherBase.java:48)
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27)
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 9 more
2021-09-30T19:00:20.282Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
2021-09-30T19:00:20.282Z	INFO	mc-server-runner	Done
```

**Comment by itzg** [comment]
This is starting to look like a problem with Fabric's build since I don't see any logging config getting in the way

```
root@9523b2a89951:/data# ls
eula.txt                    fabric-server-21w39a.jar           server.jar
fabric-installer-0.7.4.jar  fabric-server-launcher.properties  server.properties
root@9523b2a89951:/data# java -jar fabric-server-21w39a.jar
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
        ... 2 more
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at net.fabricmc.loader.launch.common.FabricLauncherBase.<clinit>(FabricLauncherBase.java:48)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 9 more
```

And the class it is trying to load is indeed missing from the jar manifest and embedded content:
```
root@9523b2a89951:/data# unzip fabric-server-21w39a.jar META-INF/MANIFEST.MF
Archive:  fabric-server-21w39a.jar
  inflating: META-INF/MANIFEST.MF
root@9523b2a89951:/data# cat META-INF/MANIFEST.MF
Manifest-Version: 1.0
Main-Class: net.fabricmc.loader.launch.server.FabricServerLauncher

root@9523b2a89951:/data# zipinfo fabric-server-21w39a.jar | grep LogManager

```

**Comment by anaxios** [comment]
Yes, that's exactly the error. Should I try to file it with the fabric team? I'm not exactly sure how all this works yet.

**Comment by itzg** [comment]
It does seem like an issue to report with Fabric. I had done a quick search to see if anybody had reported the same, but didn't find anything yet. You may want to search again just to be sure.

**Comment by sfPlayer1** [comment]
21w39a support requires Fabric Loader 0.12+, which is currently not exposed via the meta API for a gradual rollout - see https://fabricmc.net/2021/10/03/loader-0120.html

**Comment by itzg** [comment]
Thanks for the info @sfPlayer1
