### ISSUE TITLE
Problems starting Valhelsia Modpack at Version 4.0.4

### ISSUE THREAD

**Issue by dblM90** [itzg/docker-minecraft-server#1070]
Hi there,

i tried starting the Docker container together with the Valhelsia Modpack at version 4.0.4.

Here's my Docker Compose file:

version: "3.8"
services: 
  mc2:
    image: itzg/minecraft-server:multiarch-latest
    container_name: Minecraft-Valhelsia
    ports:
    # expose the Minecraft server port outside of container
    - 25566:25565
    environment:
      # REQUIRED for all types
      EULA: "TRUE"
      MOTD: "Welcome to this Minecraft Server"
      MEMORY: 6G
      OPS: player1,player2
      TYPE: CURSEFORGE
      CF_BASE_DIR: /data
      CF_SERVER_MOD: /modpacks/Valhelsia+4-4.0.4-SERVER.zip
    volumes:
    # use a named, managed volume for data volume
    - /home/shared/volumes/minecraft/valhelsia/data:/data
    # attach local host directory "mods" in same directory as this compose file
    # all mods in this directory get copied into /data/mods at startup
    - /home/shared/volumes/minecraft/valhelsia/mods:/mods:ro
    - /home/shared/volumes/minecraft/valhelsia/modpacks:/modpacks
    networks:
    - gaming-bridge

networks:
  gaming-bridge:
    name: gaming-bridge
    driver: bridge

The log output is in the attached file. 
[log_output_startup.txt](https://github.com/itzg/docker-minecraft-server/files/7276185/log_output_startup.txt)

Can someone help me figuring out, what went wrong?

Best regards,

Merlin

**Comment by dblM90** [comment]
Sorry for the bold text, i dont know, how to get rid of it.

**Comment by itzg** [comment]
That failure seems to be reported by the modpack's start script. That one might have to be treated like rlcraft as a TYPE=FORGE and a custom pack:

https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-rlcraft.yml

**Comment by dblM90** [comment]
Thanks, that helped a little. The server seems to be booting, but some if the mods dont load properly. In addition, the server.properties are not written properly according to my enironment variables.

**Comment by itzg** [comment]
Can you provide the new compose file you're using? For the server properties, make sure you have `OVERRIDE_SERVER_PROPERTIES: "true"`.

BTW, you can use this button to have it format the code block.
![image](https://user-images.githubusercontent.com/988985/135923986-a0267bda-66d2-4c07-a789-5c70209ac32f.png)

**Comment by dblM90** [comment]
Hi, my current ompose file looks like this:
  mc2:
    image: itzg/minecraft-server:latest
    container_name: Minecraft-Valhelsia
    ports:
    # expose the Minecraft server port outside of container
    - 25566:25565
    env_file:
    - mc2.env
    volumes:
    # use a named, managed volume for data volume
    - /home/shared/volumes/minecraft/valhelsia/data:/data
    # attach local host directory "mods" in same directory as this compose file
    # all mods in this directory get copied into /data/mods at startup
    - /home/shared/volumes/minecraft/valhelsia/mods:/mods:ro
    - /home/shared/volumes/minecraft/valhelsia/modpacks:/modpacks:ro
    networks:
    - gaming-bridge

mc2.env holds the following:

EULA=TRUE
# Timezone setting
TZ=Europe/Berlin
SERVER_NAME=MayNetwork-Minecraft-Valhelsia
# Message of the day
MOTD="Welcome to the Maynetwork Minecraft Server - Valhelsia Edition"
# Set min/max memory allocation
MEMORY=6G
# Enable auto pause if no users a connected
ENABLE_AUTOPAUSE=TRUE

# Set the servers difficulty (peaceful, easy, normal and hard)
DIFFICULTY=normal
# By default, Minecraft servers are configured to run in Survival mode (creative, survival, adventure, spectator)
MODE=survival
# Set friendly fire
PVP=FALSE
# Whitelist players
WHITELIST=dblM90,ISO1250
# Make users admin
OPS=dblM90,ISO1250
# Set max amount of players
MAX_PLAYERS=5

#Related to modpacks
TYPE=FORGE
GENERIC_PACK=/modpacks/Valhelsia+4-4.0.4-SERVER.zip

Best regards,

Merlin

**Comment by itzg** [comment]
Forge sure outputs a lot of logs when it installs and starts up. I wasn't able to find the exception you're seeing. The end of the logs seem to indicate successful startup.

**Comment by dblM90** [comment]
During startup the server shows many of these Exceptions:

[11:30:10] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [dash] Starting version check at https://changelogs.moddinglegacy.com/dash.json
[11:30:10] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "promos" is null
        at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.17.1-37.0.70.jar%23102!:?] {}
        at java.lang.Iterable.forEach(Unknown Source) [?:?] {}
        at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:119) [fmlcore-1.17.1-37.0.70.jar%23102!:?] {}

It seems some mods are note able to be version checked for some reason. Also there is the following error:

[11:30:04] [modloading-worker-2/INFO]: Forge mod loading, version 37.0.70, for MC 1.17.1 with MCP 20210706.113038
[11:30:04] [modloading-worker-2/INFO]: MinecraftForge v37.0.70 Initialized
[11:30:04] [modloading-worker-9/INFO]: loading json file and contents for paintings.
[11:30:04] [modloading-worker-9/INFO]: Copying Over Base Template to /paintings
[11:30:04] [modloading-worker-9/WARN]: ************************************
[11:30:04] [modloading-worker-9/WARN]: !*!*!*!*!
[11:30:04] [modloading-worker-9/ERROR]: A fatal error occurred reading the resource pack directory
[11:30:04] [modloading-worker-9/ERROR]: SKIPPING ENTIRE PROCESS
[11:30:04] [modloading-worker-9/WARN]: !*!*!*!*!
[11:30:04] [modloading-worker-9/WARN]: ************************************
[11:30:04] [modloading-worker-9/WARN]: java.nio.file.NoSuchFileException: ./resourcepacks
[11:30:04] [modloading-worker-9/INFO]: Started Reading all json files in /painting directory
[11:30:04] [modloading-worker-9/INFO]: ./paintings/paintings.json

And a big one right at the beginning:

[11:30:03] [main/ERROR] [ne.mi.co.tr.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod coremods/field_to_method.js function bucketitem
java.lang.IllegalStateException: Field f_40687_ is not private and an instance field
        at net.minecraftforge.coremod.api.ASMAPI.redirectFieldToMethod(ASMAPI.java:260) ~[coremods-5.0.1.jar%234!:?] {}
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$40$1097A$\^eval\_.initializeCoreMod#transformer-1(<eval>:33) ~[?:?] {}
        at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:648) ~[nashorn-core-15.3.jar%2319!:?] {}
        at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513) ~[nashorn-core-15.3.jar%2319!:?] {}
        at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520) ~[nashorn-core-15.3.jar%2319!:?] {}
        at org.openjdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:111) ~[nashorn-core-15.3.jar%2319!:?] {}
        at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18) ~[coremods-5.0.1.jar%234!:5.0.1+15+master.dc5a2922] {}
        at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18) ~[coremods-5.0.1.jar%234!:?] {}
        at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10) ~[coremods-5.0.1.jar%234!:?] {}
        at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) ~[coremods-5.0.1.jar%234!:?] {}
        at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) ~[modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) ~[modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:117) ~[modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.46.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.46.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.46.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.46.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.46.jar:?] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
        at net.minecraft.core.Registry.m_175449_(Registry.java:178) ~[server-1.17.1-20210706.113038-srg.jar%23101!:?] {re:classloading}
        at net.minecraft.core.Registry.lambda$static$60(Registry.java:512) ~[server-1.17.1-20210706.113038-srg.jar%23101!:?] {re:classloading}
        at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?] {}
        at net.minecraft.core.Registry.<clinit>(Registry.java:511) ~[server-1.17.1-20210706.113038-srg.jar%23101!:?] {re:classloading}
        at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:39) ~[server-1.17.1-20210706.113038-srg.jar%23101!:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:97) ~[server-1.17.1-20210706.113038-srg.jar%23101!:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.17.1-37.0.70.jar%2322!:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}
[11:30:04] [modloading-worker-2/WARN]: Configuration file /data/config/torchslabmod-server.toml is not correct. Correcting

The serve itself seems to boot, but I'm not able to connect to the server. Using the CuresForge client and selecting the valhelsia 4 modpack the startet minecraft instance tells me, that the server is not compatible for some reason.

**Comment by itzg** [comment]
OK, some of those I suspect can be ignored but most you'll need to report on the Valhelsia discord (since they don't use github issues). The image startup scripts can't do anything about mod issues.

**Comment by dblM90** [comment]
Okay, thank you very much for your help so far. I will ontact the guys there :) I like your project really much
