### ISSUE TITLE
Create Above and Beyond modpack does not work with its own start script

### ISSUE THREAD

**Issue by MirceaZisu** [itzg/docker-minecraft-server#1106]
### Describe the problem

The modpack in question can be found here: https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond

The issue I am having is that using this command, it complains about an X11 display variable. The server startup script has nogui in it.

`ServerStart.sh`
```
#!/bin/sh
. ./settings-local.sh
java ${JAVA_PARAMETERS} -Xmx${MAX_RAM} -Dfml.queryResult=confirm -jar forge-1.16.5-36.2.8-installer.jar nogui
```

`settings-local.sh`
```
export MIN_RAM="12G"
export MAX_RAM="12G"
export JAVA_PARAMETERS=" -Xms12G -Xms12G -Xmx12G  "
```

### Container definition

sudo docker run -d -v ~/mc-servers-new/above-and-beyond/:/data -e TYPE=CURSEFORGE -e CF_SERVER_MOD=Above+and+Beyond-1.0-Server.zip -e MEMORY=12G -p 25565:25565 -e ENABLE_RCON=true -e EULA=TRUE -e RCON_PASSWORD=Dummypassword -e ALLOW_FLIGHT=TRUE --name create itzg/minecraft-server:java8

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    6 1000     1000          4096 Nov  3 16:07 /data'
[init] Resolved version given LATEST into 1.17.1
[init] Resolving type given CURSEFORGE
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] detected FTB, changing properties path to /data/FeedTheBeast/Above and Beyond-1.0-Server/server.properties
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 12G and max to 12G
[init] Running FTB /data/FeedTheBeast/Above and Beyond-1.0-Server/ServerStart.sh in /data/FeedTheBeast/Above and Beyond-1.0-Server ...
JVM info: IcedTea - 1.8.0_212 - 25.212-b04
java.net.preferIPv4Stack=true
Found java version 1.8.0_212
Exception in thread "main" 
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1762)
        at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1837)
        at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
        at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:863)
        at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
        at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:177)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:147)
2021-11-03T16:14:21.396Z        WARN    mc-server-runner        sub-process failed      {"exitCode": 1}
2021-11-03T16:14:21.396Z        INFO    mc-server-runner        Done

**Comment by itzg** [comment]
As you said, it's failing in their start script, so I'm not sure what you're wanting me to change. There are documented workarounds for buggy start scripts.

**Comment by steve-thousand** [comment]
@MirceaZisu did you find a solution for this? I have been unable to find a configuration to get the Above and Beyond server to work.

**Comment by MirceaZisu** [comment]
> @MirceaZisu did you find a solution for this? I have been unable to find a configuration to get the Above and Beyond server to work.

Yes, just use the disable startup script argument, and it will work. You might need to tweak some parameters after that too, but it should work.

**Comment by AlmtyBob** [comment]
@MirceaZisu @steve-thousand Could either of you post your working container definition or docker-compose?

**Comment by lyuben-todorov** [comment]
The pack zip comes with the forge installer jar instead of the actual forge jar. I unpacked the zip, ran
`java -jar forge-x.xx.x-installer.jar --installServer` to get the forge jar and zipped it again. Also make sure to use the `itzg/minecraft-server:multiarch` image.

**Comment by dogunbound** [comment]
Wtf??? Why does it need --installServer if it is install script....
