### ISSUE TITLE
Java compat level issues with Fabric / MC1.18

### ISSUE THREAD

**Issue by Stealthii** [itzg/docker-minecraft-server#1134]
### Describe the problem

Trying to launch a fabric server using the following:
* itzg/minecraft-server:java17
* Minecraft 1.18-rc3
* Fabric Loader 0.12.5
* Fabric API 0.43.1+1.18

The compatibility level seems to be set to 16 (and not 17), resulting in a failure loading any mods.

### Container definition

```yaml
version: "3.9"

services:
    minecraft:
        image: itzg/minecraft-server:java17
        ports:
            - 25565:25565
        environment:
            EULA: "TRUE"
            TYPE: "FABRIC"
            VERSION: "1.18-rc3"
            DEBUG: TRUE
        volumes:
            - minecraft:/data
            - ./minecraft/mods:/mods:ro  # Contains Fabric API 0.43.1+1.18

volumes:
    bones: {}
```

### Container logs

```
bonesmc-bones-1  | [19:07:13] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft 1.18-rc3
bonesmc-bones-1  | [19:07:13] [INFO] [FabricLoader/GameRemap]: Fabric is preparing JARs on first launch, this may take a few seconds...
bonesmc-bones-1  | [19:07:16] [main/INFO]: Loading for game Minecraft 1.18-rc3
bonesmc-bones-1  | [19:07:16] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
bonesmc-bones-1  | [19:07:16] [main/WARN]: Warnings were found!
bonesmc-bones-1  |  - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
bonesmc-bones-1  |       - You should install any version of fabric-textures-v0 for the optimal experience.
bonesmc-bones-1  | [19:07:16] [main/INFO]: Loading 41 mods:
bonesmc-bones-1  |      - fabric 0.43.1+1.18
bonesmc-bones-1  |      - fabric-api-base 0.4.1+b4f4f6cd14
bonesmc-bones-1  |      - fabric-api-lookup-api-v1 1.3.5+3ac43d9514
bonesmc-bones-1  |      - fabric-biome-api-v1 6.0.1+3ac43d9514
bonesmc-bones-1  |      - fabric-command-api-v1 1.1.6+3ac43d9514
bonesmc-bones-1  |      - fabric-commands-v0 0.2.5+b4f4f6cd14
bonesmc-bones-1  |      - fabric-containers-v0 0.1.18+d154e2c614
bonesmc-bones-1  |      - fabric-content-registries-v0 0.4.5+6f53a73d14
bonesmc-bones-1  |      - fabric-crash-report-info-v1 0.1.8+3ac43d9514
bonesmc-bones-1  |      - fabric-dimensions-v1 2.1.7+43d2957114
bonesmc-bones-1  |      - fabric-entity-events-v1 1.4.5+6b21378a14
bonesmc-bones-1  |      - fabric-events-interaction-v0 0.4.15+3ac43d9514
bonesmc-bones-1  |      - fabric-events-lifecycle-v0 0.2.5+b4f4f6cd14
bonesmc-bones-1  |      - fabric-game-rule-api-v1 1.0.10+3ac43d9514
bonesmc-bones-1  |      - fabric-item-api-v1 1.2.7+3ac43d9514
bonesmc-bones-1  |      - fabric-item-groups-v0 0.3.3+3ac43d9514
bonesmc-bones-1  |      - fabric-lifecycle-events-v1 1.4.10+c15ca33514
bonesmc-bones-1  |      - fabric-loot-tables-v1 1.0.8+3ac43d9514
bonesmc-bones-1  |      - fabric-mining-level-api-v1 1.0.3+3ac43d9514
bonesmc-bones-1  |      - fabric-mining-levels-v0 0.1.7+b4f4f6cd14
bonesmc-bones-1  |      - fabric-networking-api-v1 1.0.18+3ac43d9514
bonesmc-bones-1  |      - fabric-networking-v0 0.3.5+b4f4f6cd14
bonesmc-bones-1  |      - fabric-object-builder-api-v1 1.10.13+3ac43d9514
bonesmc-bones-1  |      - fabric-object-builders-v0 0.7.7+3ac43d9514
bonesmc-bones-1  |      - fabric-particles-v1 0.2.9+526dc1ac14
bonesmc-bones-1  |      - fabric-registry-sync-v0 0.8.5+3ac43d9514
bonesmc-bones-1  |      - fabric-rendering-data-attachment-v1 0.3.3+d154e2c614
bonesmc-bones-1  |      - fabric-rendering-fluids-v1 0.1.18+3ac43d9514
bonesmc-bones-1  |      - fabric-resource-loader-v0 0.4.11+3ac43d9514
bonesmc-bones-1  |      - fabric-screen-handler-api-v1 1.1.11+3ac43d9514
bonesmc-bones-1  |      - fabric-structure-api-v1 2.0.8+295197a714
bonesmc-bones-1  |      - fabric-tag-extensions-v0 1.2.5+3ac43d9514
bonesmc-bones-1  |      - fabric-tool-attribute-api-v1 1.3.4+7de09f5514
bonesmc-bones-1  |      - fabric-transfer-api-v1 1.5.4+b4f4f6cd14
bonesmc-bones-1  |      - fabricloader 0.12.5
bonesmc-bones-1  |      - java 17
bonesmc-bones-1  |      - lazydfu 0.1.2
bonesmc-bones-1  |      - minecraft 1.18-rc.3
bonesmc-bones-1  |      - openloader 3.0.0
bonesmc-bones-1  |      - starlight 1.0.0+fabric.d58dc74
bonesmc-bones-1  |      - voicechat 1.18-rc3-2.1.14
bonesmc-bones-1  | [19:07:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/data/fabric-server-1.18-rc3.jar Service=Knot/Fabric Env=SERVER
bonesmc-bones-1  | [19:07:16] [main/INFO]: Compatibility level set to JAVA_16
bonesmc-bones-1  | Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
bonesmc-bones-1  |      at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:62)
bonesmc-bones-1  | Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
bonesmc-bones-1  |      at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:100)
bonesmc-bones-1  |      at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60)
bonesmc-bones-1  | Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
bonesmc-bones-1  |      at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:74)
bonesmc-bones-1  |      at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98)
bonesmc-bones-1  |      ... 1 more
bonesmc-bones-1  | Caused by: java.lang.reflect.InvocationTargetException
bonesmc-bones-1  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
bonesmc-bones-1  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
bonesmc-bones-1  |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
bonesmc-bones-1  |      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
bonesmc-bones-1  |      at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72)
bonesmc-bones-1  |      ... 2 more
bonesmc-bones-1  | Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config openloader.mixins.json
bonesmc-bones-1  |      at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
bonesmc-bones-1  |      at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
bonesmc-bones-1  |      at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
bonesmc-bones-1  |      at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:87)
bonesmc-bones-1  |      at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
bonesmc-bones-1  |      at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
bonesmc-bones-1  |      at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
bonesmc-bones-1  |      ... 7 more
bonesmc-bones-1  | Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
bonesmc-bones-1  |      at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
bonesmc-bones-1  |      at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
bonesmc-bones-1  |      at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
bonesmc-bones-1  |      at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
bonesmc-bones-1  |      at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
bonesmc-bones-1  |      at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
bonesmc-bones-1  |      ... 13 more
bonesmc-bones-1  | 2021-11-26T19:07:16.341Z     WARN    mc-server-runner        sub-process failed      {"exitCode": 1}
bonesmc-bones-1  | 2021-11-26T19:07:16.342Z     INFO    mc-server-runner        Done
bonesmc-bones-1 exited with code 1
```

**Comment by Stealthii** [comment]
Note the differences when launching the client with Fabric:
```
[19:09:33] [main/INFO]: Loading for game Minecraft 1.18-rc3
[19:09:33] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[19:09:38] [main/INFO]: Loading 55 mods:
	- fabric 0.43.1+1.18
...
[19:09:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/P:/Games/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.6+mixin.0.8.4/sponge-mixin-0.10.6+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[19:09:38] [main/INFO]: Compatibility level set to JAVA_16
[19:09:38] [main/INFO]: Compatibility level set to JAVA_17
[19:09:38] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
```
versus the server under this docker image (Compat level not re-set to JAVA_17, also non client/server error under Fabric prep)
```
bonesmc-bones-1  | [19:07:16] [main/INFO]: Loading for game Minecraft 1.18-rc3
bonesmc-bones-1  | [19:07:16] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
bonesmc-bones-1  | [19:07:16] [main/WARN]: Warnings were found!
bonesmc-bones-1  |  - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
bonesmc-bones-1  |       - You should install any version of fabric-textures-v0 for the optimal experience.
bonesmc-bones-1  | [19:07:16] [main/INFO]: Loading 41 mods:
bonesmc-bones-1  |      - fabric 0.43.1+1.18
...
bonesmc-bones-1  | [19:07:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/data/fabric-server-1.18-rc3.jar Service=Knot/Fabric Env=SERVER
bonesmc-bones-1  | [19:07:16] [main/INFO]: Compatibility level set to JAVA_16
bonesmc-bones-1  | Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
...
bonesmc-bones-1  | Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
```

**Comment by Stealthii** [comment]
This turns out to be an issue with fabric-loader itself, requiring mods to use JAVA_16 compatibility for the time being.

Closing. If anyone else encounters this issue, ask the mod developer to ensure JAVA_16 is still set for their build process, as required by the current version of fabric-loader.
