### ISSUE TITLE
1.18 Server doesnt start without explicitly selecting Java version

### ISSUE THREAD

**Issue by K1ngjulien** [itzg/docker-minecraft-server#1151]
### Describe the problem

When launching the server with out selecting a java version tag `itzg/minecraft-server` I get the following error:

```
[/opt]: docker run --name=vanilla18 -it -p 25565:25565 -v /opt/vanilla18:/data -e EULA=TRUE -e VERSION=1.18 --restart=always --cpus="4" --memory="16G" -e MEMORY=16G itzg/minecraft-server
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    5 1000     1000          4096 Dec  2 17:56 /data'
Checking version information.
Checking type information.
server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 16G and max to 16G
Starting the Minecraft server...
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
2021/12/02 17:56:52 Done
```

As per the documentation, when no tag is specified, the latest jre should be used, which is apparently not the case. https://github.com/itzg/docker-minecraft-server/blob/master/README.md#running-minecraft-server-on-different-java-version

When I select java 17 explicitly (`itzg/minecraft-server:java17`), everything works fine. 

It seems to me that for some reason "latest" means java8 (would correspond to java class version 52)

**Comment by K1ngjulien** [comment]
Oh you know what, I think docker might have cached an old version of this docker image on my machine.

**Comment by K1ngjulien** [comment]
yeah lol it seems like i have been using the same itzg/minecraft-server docker image for the last two years
