### ISSUE TITLE
java17 image does not support database connection

### ISSUE THREAD

**Issue by DerSteph** [itzg/docker-minecraft-server#1172]
### Describe the problem

Hello,
 since we've upgraded our server to 1.18 and use the java17 image we have several issues with plugins who rely on a mariadb connection. I tried it with the newest paper and spigot jars, but nothing changes. The database container is in another stack, but connection is working fine with other containers.

### Container definition

```
version: "3.5"

services:
  minecraft:
    image: itzg/minecraft-server:java17
    environment:
      EULA: "true"
      TYPE: CUSTOM
      CUSTOM_SERVER: "/data/paper.jar"
      MEMORY: 12G
      JVM_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:InitiatingHeapOccupancyPercent=20 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      EXEC_DIRECTLY: "true"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - /mcservers/server:/data
    ports:
      - 25565:25565/tcp
    networks:
      - mcserver
      
networks:
  mcserver:
    external: true


```

### Container logs

```
[21:59:31] [Craft Scheduler Thread - 23/WARN]: [Statz] Plugin Statz v1.6.2 generated an exception while executing task 91
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://mariadb:3306/statz
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:320) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:109) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[?:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
	at me.staartvin.statz.database.MySQLConnector.setupDatabaseConnection(MySQLConnector.java:61) ~[?:?]
	at me.staartvin.statz.database.MySQLConnector.getConnection(MySQLConnector.java:73) ~[?:?]
	at me.staartvin.statz.database.MySQLConnector.setBatchObjects(MySQLConnector.java:895) ~[?:?]
	at me.staartvin.statz.tasks.UpdateDatabaseTask.run(UpdateDatabaseTask.java:81) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:299) ~[java.sql:?]
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106) ~[?:?]
	... 13 more
```

**Comment by itzg** [comment]
The JDBC driver jar for MySQL is something you'll need to supply on the classpath. That never had been supplied by this docker image, so any change in behavior will be outside my control such as with PaperMC at 1.18.

**Comment by macbrayne** [comment]
For reference it works on Fabric with Ledger and Ledger Databases (connecting to a MariaDB database)
