### ISSUE TITLE
Using VERSION =1.18.0 and TYPE=fabric fails due to attempting to get FABRIC from a 400/404 page

### ISSUE THREAD

**Issue by vorpalhex** [itzg/docker-minecraft-server#1181]
### Describe the problem

Stack trace:
```
[init] Installing Fabric 1.8.0 using fabric-installer-0.10.2.jar with loader version 0.12.11
Loading Fabric Installer: 0.10.2
Installing Fabric Loader 0.12.11(1.8.0) on the server
Downloading required files
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
	at net.fabricmc.installer.Main.main(Main.java:78)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://meta.fabricmc.net/v2/versions/loader/1.18.0/0.12.11/server/json
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at net.fabricmc.installer.util.Utils.urlReader(Utils.java:84)
	at net.fabricmc.installer.util.Utils.readTextFile(Utils.java:88)
	at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:84)
	at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:67)
	at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:68)
	at net.fabricmc.installer.Main.main(Main.java:76)
```

That URL does in fact lead to a 400/404. Same 

### Container definition

```
minecraft:
    container_name: minecraft
    hostname: minecraft
    image: itzg/minecraft-server
    user: 997:997
    ports:
      - 25565:25565/tcp
      - 25575:25575/tcp
    environment:
      - UID=997
      - GID=997
      - TZ=America/Chicago
      - VERSION=1.18.0
      - EULA=true
      - TYPE=FABRIC
      - DIFFICULTY=NORMAL
      - OPS=snip
      - WHITELIST=snip
      - ENABLE_RCON=true
      - RCON_PORT=25575
      - RCON_PASSWORD=snip
      - MAX_PLAYERS=12
      - ENABLE_COMMAND_BLOCK=true
      - VIEW_DISTANCE=16
      - MEMORY=24G
      - SPAWN_PROTECTION=0
    restart: unless-stopped
    labels:
      - "traefik.enable=false" # don't serve http traffic to here
      - "com.centurylinklabs.watchtower.monitor-only" # don't restart this container automatically with updates
    volumes:
      - /var/docker/minecraft_server:/data
```

**Comment by vorpalhex** [comment]
This looks like a bug with how versions resolve. `1.18` DOES work.

**Comment by itzg** [comment]
That error is being reported by the Fabric installer itself. I'm confused though, are you wanting 1.8 or 1.18? Can you provide the container logs all the way from the start?

**Comment by vorpalhex** [comment]
Hm, you are correct that it's from the fabric installer. 

I noticed this error with 1.18 (but I accidentally typed 1.8 when attempting to recreate to capture logs). 

I can recapture the logs if you really need them but it was normal container startup up until that point. It does look like this should get posted to the fabric launcher though.
