### ISSUE TITLE
CurseForge Server not running

### ISSUE THREAD

**Issue by scidoodIe** [itzg/docker-minecraft-server#1215]
### Describe the problem

We had been running a modpack on a curseforge server.
Everything worked fine. 
We were able to join the server with the right modpack untill I exidentally removed the server while I was trying to restart it. 
Without making any changes I tried to use the same command again.
It starts a vanilla server with the latest version.

### Container definition

sudo docker run -p 25565:25565 --name mc_mod --restart always -v /home/fabian/mc_mod:/data -e TYPE:CURSEFORGE -v /home/fabian/modpacks:/modpacks -e CF_SERVER_MOD=/modpacks/FTBPresentsCrackpackServer_1.1.0.zip -e EULA=TRUE itzg/minecraft-server:java8

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwx-w----    2 1000     1000          4096 Dec 19 20:33 /data'                                                   [init] Resolved version given LATEST into 1.18.1
[init] Resolving type given VANILLA
[init] Downloading minecraft_server.1.18.1.jar ...
[init] Creating server.properties in /data/server.properties
[init] Disabling whitelist
[init] Setting whitelist to 'false' in /data/server.properties
[init] Setting white-list to 'false' in /data/server.properties
[init] Setting enable-rcon to 'true' in /data/server.properties
[init] Setting rcon.password to 'minecraft' in /data/server.properties
[init] Setting rcon.port to '25575' in /data/server.properties
[init] Setting motd to 'A Vanilla Minecraft Server powered by Docker' in /data/server.properties
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class fs file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
2021-12-19T20:36:23.867Z        WARN    mc-server-runner        sub-process failed      {"exitCode": 1}
2021-12-19T20:36:23.868Z        INFO    mc-server-runner        Done

**Comment by itzg** [comment]
Since it's reporting

```
UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class fs file versions up to 52.0
```

That means you need to be using the latest image and not the java8 tagged one.

**Comment by scidoodIe** [comment]
Thank you for answer
My problem is that it is supposed to run a curseforge server with a modpack in an older mc version (1.7.10).
By trying to run a typ vanilla latest version server what it shouldnt do it later requests another image.

**Comment by scidoodIe** [comment]
(.....)  -e TYPE:CURSEFORGE  (......)
I think I found my mistake. 
And it sure is not a bug. Everthing working fine now.
