### ISSUE TITLE
Fabric 1.18 not launching

### ISSUE THREAD

**Issue by wendigooey** [itzg/docker-minecraft-server#1285]
hi, i'm new to fabric and i'm trying to launch fabric with sodium, iris, and a couple of other of mods. but i get an error every time i launch it. here is the error code
java.lang.RuntimeException: Could not create directory C:\Users\admin\AppData\Roaming\.minecraft\iris-reserved\1.18.1
	at net.fabricmc.loader.impl.discovery.DirectoryModCandidateFinder.findCandidates(DirectoryModCandidateFinder.java:46)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:86)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:204)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.nio.file.NoSuchFileException: C:\Users\admin\AppData\Roaming\.minecraft\iris-reserved\1.18.1
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:521)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at net.fabricmc.loader.impl.discovery.DirectoryModCandidateFinder.findCandidates(DirectoryModCandidateFinder.java:44)
	... 6 more

**Comment by itzg** [comment]
The container shouldn't know or be told about any Windows. Please provide your compose file or docker run command you're using.

**Comment by Dizvx** [comment]
I was having this same problem but fixed it by creating a new folder and naming it "iris-reserved" then creating a subfolder inside called "1.18.1"
