### ISSUE TITLE
Latest Imagine for Java 8 Multiarch (java8-multiarch) Breaks McModLoader

### ISSUE THREAD

**Issue by gorf18** [itzg/docker-minecraft-server#1325]
### Describe the problem

Latest image was crashing this morning after updating overnight. I noticed that McModLauncher had reported the same issue with the latest java8 version. Either downgrade java8 or continue to monitor the bug in their space (and utilize an older image). 

https://github.com/McModLauncher/modlauncher/issues/91

### Container definition

```
Paste run command or compose file here
```
I built the container with ansible:

#https://github.com/itzg/docker-minecraft-server/blob/master/README.md
- name: Minecraft Docker Container
  docker_container:
    name: minecraft
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - 25565:25565
    pull: true
    volumes:
      - "<blank>"
    env:
      EULA: "TRUE"
      TYPE: "FTBA"
      FTB_MODPACK_ID: "91"
      MOTD: "<blank>"
      PVP: "false"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "10G"
      OPS: "<blank>"
      ALLOW_FLIGHT: "TRUE"
    restart_policy: unless-stopped

### Container logs

[init] Resolved version given LATEST into 1.18.1
[init] Resolving type given FTBA
[init] FTB modpack ID 91, version ID 2105 is ready to go
[init] server.properties already created, skipping
[init] Updating ops
[init] Koyakasha already present in ops.json, skipping
[init] Rainbow2019 already present in ops.json, skipping
[init] Gorf18 already present in ops.json, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 4G and max to 10G
[init] Starting the Minecraft server...
2022-02-03 13:16:14,279 main WARN Advanced terminal features are not available in this environment
[13:16:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.20, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[13:16:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_322 by Temurin
[13:16:14] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[13:16:14] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/data/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[13:16:15] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
Init CreativeCore coremods ...
[13:16:16] [main/ERROR] [mixin/]: Mixin config minetogether.mixins.json does not specify "minVersion" property
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.forName0(Native Method)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.forName(Class.java:348)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1290)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[13:16:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
2022-02-03T13:16:16.622Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
2022-02-03T13:16:16.622Z	INFO	mc-server-runner	Done

**Comment by gorf18** [comment]
I set the container back to: [itzg/minecraft-server:2022.1.1-java8-multiarch] and the server loaded fine.

**Comment by itzg** [comment]
I'm not sure what I'm watching for since that issue is closed and reported as fixed

https://github.com/McModLauncher/modlauncher/issues/91#issuecomment-1019527553

Perhaps it's a problem with FTBA's downloaded?

**Comment by itzg** [comment]
...looking closer at the startup logs, this line

```
FTB modpack ID 91, version ID 2105 is ready to go
```

indicates that the modpack was previously downloaded and will be re-used. You may want to contact the modpack maintainer to see if they can publish a new version with the updated McModLauncher.
