### ISSUE TITLE
"minecraft-server:java8-multiarch" error on the latest version (token recognition error at: '`')

### ISSUE THREAD

**Issue by champ8644** [itzg/docker-minecraft-server#1328]
### Describe the problem

I was able to run the server inside docker by itzg/minecraft-server:java8-multiarch (image id: 4a1df2622387) with CurseForge + Enigmatica 1.16.5 smoothly in the previous month. But after I need to pull the image from docker-hub and re-initialized the server again today I found out that I couldn't run it in itzg/minecraft-server:java8-multiarch docker environment anymore despite the very same config. And I just happen to find that itzg/minecraft-server:java8-multiarch image was being update to (image id: 725c86b7ce19) 1 day ago, which after I go back to use the old image the server in the local machine could be able to run again.

My server hosting has somewhat strict policy about image & tags, they required me to specifically define the image name and tag explicitly to have them whitelist it, so I couldn't change the image to an old one on the hosting site. Therefore this means I couldn't play my server with this new update on the image anymore.

I think I found this similar bug when I tried to use image itzg/minecraft-server:latest with CurseForge + Enigmatica modpack 1.16.5 (<1.17) so maybe this bug has something to do with the java version...

Thank you

### Container definition

```
  mc:
    image: itzg/minecraft-server:java8-multiarch
    environment:
      TYPE: CURSEFORGE
      CF_SERVER_MOD: "https://media.forgecdn.net/files/3620/129/Enigmatica6Server-0.5.25.zip"
      EULA: "true"
      MEMORY: 5G
      CF_BASE_DIR: /data
    ports:
      - 25565:25565
    volumes:
      - ./mc:/data
```

### Container logs

```
[init] Changing ownership of /data to 1000 ...

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 1 1000 1000 4096 Feb  4  2022 /data'

[init] Resolved version given LATEST into 1.18.1

[init] Resolving type given CURSEFORGE

[init] Looking for Feed-The-Beast / CurseForge server modpack.

[init] Downloading modpack from https://media.forgecdn.net/files/3620/129/Enigmatica6Server-0.5.25.zip...

[init] Unpacking FTB server modpack /data/Enigmatica6Server-0.5.25.zip ...

.....

[init] detected FTB, changing properties path to /data/server.properties

[init] Creating server.properties in /data/server.properties

[init] Disabling whitelist functionality

[init] Setting white-list to 'false' in /data/server.properties

[init] WARNING: whitelist enabled but not enforced. Set ENFORCE_WHITELIST=TRUE or update 'enforce-whitelist' in server.properties to enforce the whitelist.

[init] Setting enable-rcon to 'true' in /data/server.properties

[init] Setting rcon.password to 'minecraft' in /data/server.properties

[init] Setting rcon.port to '25575' in /data/server.properties

[init] Setting motd to 'A Curseforge Minecraft Server powered by Docker' in /data/server.properties

[init] Checking for JSON files.

[init] Setting initial memory to 5G and max to 5G

cp: '/data/eula.txt' and '/data/eula.txt' are the same file

[init] Running FTB /data/start-server.sh in /data ...

https://github.com/EnigmaticaModpacks/ServerStarter/releases/download/v2.2.0/serverstarter-2.2.0.jar

DEBUG: (curl) Downloading https://github.com/EnigmaticaModpacks/ServerStarter/releases/download/v2.2.0/serverstarter-2.2.0.jar

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100   662  100   662    0     0   4086      0 --:--:-- --:--:-- --:--:--  4086

100 3890k  100 3890k    0     0   225k      0  0:00:17  0:00:17 --:--:--  991k

[09:40:56] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

[09:40:56] [INFO]    Minecraft ServerStarter install/launcher jar

[09:40:56] [INFO]    (Created by BloodWorkXGaming with the help of Contributors)

[09:40:56] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

[09:40:56] [INFO] 

[09:40:56] [INFO]    This jar will launch a Minecraft Forge/Fabric Modded server

[09:40:56] [INFO] 

[09:40:56] [INFO]    Github:    https://github.com/BloodyMods/ServerStarter

[09:40:56] [INFO]    Discord:   https://discord.gg/enigmatica

[09:40:56] [INFO] 

[09:40:56] [INFO] You are playing Enigmatica 6

[09:40:56] [INFO] Starting to install/launch the server, lean back!

[09:40:56] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

[09:40:56] [INFO] 

[09:40:57] [INFO] Testing http://example.com.

[09:40:57] [INFO] Reached http://example.com: true

[09:40:57] [INFO] Testing http://google.com.

[09:40:57] [INFO] Reached http://google.com: true

[09:40:57] [INFO] Reached 2 out of 2 IPs.

[09:40:57] [INFO] Attempting to download modpack Zip.

[09:41:00] [INFO] Downloaded the modpack zip file to /data/modpack-download.zip

[09:41:00] [INFO] Moved the mods folder

[09:41:00] [INFO] Starting to unzip files.

[09:41:20] [INFO] Done unzipping the files.

[09:41:20] [INFO] Requesting Download links from cursemeta.

[09:41:20] [INFO] Skipping mod with projectID: 391382

[09:41:20] [INFO] Skipping mod with projectID: 521714

[09:41:20] [INFO] Skipping mod with projectID: 271740

[09:41:20] [INFO] Skipping mod with projectID: 238372

[09:41:20] [INFO] Skipping mod with projectID: 231275

[09:41:20] [INFO] Skipping mod with projectID: 358191

[09:41:20] [INFO] Skipping mod with projectID: 513857

[09:41:21] [INFO] [  1/339] Downloaded mod: FastLeafDecay-v25.2.jar

[09:41:21] [INFO] [  2/339] Downloaded mod: magicfeather-1.16.2-3.2.0.jar

[09:41:22] [INFO] [  4/339] Downloaded mod: cant-sleep-clowns-will-eat-me-1.16.4-1.0.0.1.jar

...
```
```
...

  Patching net/minecraft/client/particle/ParticleManager$AnimatedSpriteImpl 1/1

  Patching net/minecraft/client/multiplayer/ServerData$ServerResourceMode 1/1

  Patching net/minecraft/client/renderer/entity/ItemRenderer 1/1

  Patching net/minecraft/client/gui/screen/CreateWorldScreen$GameMode 1/1

  Output: /data/./libraries/net/minecraftforge/forge/1.16.5-36.2.22/forge-1.16.5-36.2.22-server.jar Checksum Validated: 0fa3afa7e3ab98aef47dc027e3e4a6558502df7e

The server installed successfully

You can delete this installer file now if you wish

[09:51:30] [INFO] Done installing loader, deleting installer!

[09:51:30] [INFO] Starting to installing Additional Files

[09:51:30] [INFO] Starting to copy local files.

[09:51:30] [INFO] Starting Loader, output incoming

2022-02-04 09:51:31,985 main WARN Advanced terminal features are not available in this environment

[09:51:32] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.22, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]

[09:51:32] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_322 by Temurin

[09:51:35] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust

[09:51:35] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/data/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER

[09:51:44] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'

[09:51:44] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at java.lang.Class.forName0(Native Method)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at java.lang.Class.forName(Class.java:348)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at java.util.HashMap.forEach(HashMap.java:1290)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)

[09:51:47] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:  at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

[09:51:47] [INFO] Server has been stopped, it has started 1 times in 60min

[09:51:47] [INFO] Restarting server in 10 seconds, press ctrl+c to stop

[09:51:57] [INFO] Starting Loader, output incoming

```

**Comment by itzg** [comment]
This seems to be the same as #1325, so the modpack author needs to update the forge version with a fixed mcmodloader
