### ISSUE TITLE
Nether portal doesn't work

### ISSUE THREAD

**Issue by AlbertoPimpo** [itzg/docker-minecraft-server#1341]
### Describe the problem

Every time a player tries to enter a nether portal server returns an error on logs about negative position (???) and on the client side the following error appears.
<img width="794" alt="image" src="https://user-images.githubusercontent.com/34674832/152893642-c099aad6-ac6d-4473-803e-76001ba87a63.png">
Have you any hints about this error? Is it a bug of the image?

Thanks you a lot.

### Container definition

```
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      OVERRIDE_SERVER_PROPERTIES: "true"
      EULA: "TRUE"
      MAX_MEMORY: "10G"
      TZ: "Europe/Rome"
      ONLINE_MODE: "TRUE"
      VERSION: "1.18.1"
      TYPE: "VANILLA"
      ENABLE_QUERY: "true"
      MAX_PLAYERS: 20
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "false"
      ENABLE_COMMAND_BLOCK: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
 
```

### Container logs

```
[01:05:16] [IO-Worker-8/ERROR]: Chunk [-2, -1] header is truncated: expected 299008 but read 0

[01:05:16] [IO-Worker-7/WARN]: Failed to read chunk [-1, -1]

java.lang.IllegalArgumentException: Negative position

at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:813) ~[?:?]

at cra.a(SourceFile:181) ~[server-1.18.1.jar:?]

at crb.a(SourceFile:52) ~[server-1.18.1.jar:?]

at cqy.c(SourceFile:100) ~[server-1.18.1.jar:?]

at cqy.a(SourceFile:150) ~[server-1.18.1.jar:?]

at aum$b.run(SourceFile:59) [server-1.18.1.jar:?]

at auk.g(SourceFile:91) [server-1.18.1.jar:?]

at auk.a(SourceFile:146) [server-1.18.1.jar:?]

at auk.run(SourceFile:102) [server-1.18.1.jar:?]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]

at java.lang.Thread.run(Thread.java:833) [?:?]

[01:05:17] [Server thread/WARN]: Failed to handle packet for /172.22.0.1:36834

z: Ticking player

at adj.l(SourceFile:543) ~[server-1.18.1.jar:?]

at aea.b(SourceFile:213) ~[server-1.18.1.jar:?]

at pl.a(SourceFile:238) ~[server-1.18.1.jar:?]

at adz.c(SourceFile:183) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.b(SourceFile:890) ~[server-1.18.1.jar:?]

at acj.b(SourceFile:324) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.a(SourceFile:823) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.w(SourceFile:684) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.a(SourceFile:270) ~[server-1.18.1.jar:?]

at java.lang.Thread.run(Thread.java:833) [?:?]

Caused by: java.lang.IllegalArgumentException: Negative position

at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:813) ~[?:?]

at cra.a(SourceFile:181) ~[server-1.18.1.jar:?]

at crb.a(SourceFile:52) ~[server-1.18.1.jar:?]

at cqy.c(SourceFile:100) ~[server-1.18.1.jar:?]

at cqy.a(SourceFile:150) ~[server-1.18.1.jar:?]

at aum$b.run(SourceFile:59) ~[server-1.18.1.jar:?]

at auk.g(SourceFile:91) ~[server-1.18.1.jar:?]

at auk.a(SourceFile:146) ~[server-1.18.1.jar:?]

at auk.run(SourceFile:102) ~[server-1.18.1.jar:?]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

... 1 more

[01:05:17] [Server thread/FATAL]: Error executing task on Server

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectSet.remove(Object)" because "$$4" is null

at adb.b(SourceFile:230) ~[server-1.18.1.jar:?]

at acv.a(SourceFile:1020) ~[server-1.18.1.jar:?]

at adg.a(SourceFile:465) ~[server-1.18.1.jar:?]

at aea.a(SourceFile:928) ~[server-1.18.1.jar:?]

at vp.a(SourceFile:114) ~[server-1.18.1.jar:?]

at vp$b.a(SourceFile:16) ~[server-1.18.1.jar:?]

at qt.a(SourceFile:21) ~[server-1.18.1.jar:?]

at yx.run(SourceFile:18) ~[server-1.18.1.jar:?]

at auh.c(SourceFile:151) ~[server-1.18.1.jar:?]

at aul.c(SourceFile:23) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.b(SourceFile:780) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.c(SourceFile:162) ~[server-1.18.1.jar:?]

at auh.y(SourceFile:125) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.bf(SourceFile:762) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.y(SourceFile:756) ~[server-1.18.1.jar:?]

at auh.bp(SourceFile:110) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.x(SourceFile:740) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.w(SourceFile:688) ~[server-1.18.1.jar:?]

at net.minecraft.server.MinecraftServer.a(SourceFile:270) ~[server-1.18.1.jar:?]

at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by AlbertoPimpo** [comment]
After getting this problem on windows 11, i tried on my Macbook pro M1 and here it does work, so it can be something related to wsl?

**Comment by itzg** [comment]
Yes, docker seems to have host volume mapping issues on Windows 11. I'm going to close this since the general situation is already being watched in #1102.

**Comment by AlbertoPimpo** [comment]
Thanks for the answer @itzg, it helped me to find a working solution (using hyper-v backend).
