### ISSUE TITLE
Curseforge Server can't startup. Many modpacks gives the same Error.

### ISSUE THREAD

**Issue by LukasKersting** [itzg/docker-minecraft-server#1542]
### Describe the problem

I tried to create a Curseforge Minecraft Server. But every time i run the container it crashes in the "init" Phase.

I tried two other things except the definition below:

1. -e FTB_LEGACYJAVAFIXER=true --> i got an error that it can't be downloaded
2. -e USE_MODPACK_START_SCRIPT=false --> does not help and i got the same error

When i searched for fixes for this error everybody said the same: "Wrong Java Version / JDK"

### Container definition

```
docker run -v /home/lukas/nomiserver:/data -e TYPE=CURSEFORGE -e CF_SERVER_MOD=nomif.zip -p 25565:25565 -e EULA=TRUE -e MEMORY=10G --name mc itzg/minecraft-server
```

### Container logs

```
[init] Resolved version given LATEST into 1.18.2 and major version 1.18
[init] Resolving type given CURSEFORGE
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] Unpacking FTB server modpack /data/nomif.zip ...
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[init] No entry script found, so building one for /data/FeedTheBeast/forge-1.12.2-14.23.5.2860.jar
[init] detected FTB, changing properties path to /data/FeedTheBeast/server.properties
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 10G and max to 10G
[init] Running FTB /data/FeedTheBeast/ServerStart.sh in /data/FeedTheBeast ...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
2022-05-30T17:03:02.826Z        WARN    mc-server-runner        Minecraft server process failed {"exitCode": 1}
2022-05-30T17:03:02.826Z        INFO    mc-server-runner        Done
```

**Comment by itzg** [comment]
Modpack is not compatible with Java 17. Use the image tag `itzg/minecraft-server:java8`.
