### ISSUE TITLE
Forge Jar Immediately Throws Exception. Nogui?

### ISSUE THREAD

**Issue by CursedDog19** [itzg/docker-minecraft-server#1597]
### Describe the problem

The exception seems to be related to a GUI initializing in a headless environment. I get the same error when running the container with -e GUI: "TRUE" I had to manually download the forge jar from https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-40.1.0/forge-1.18.2-40.1.0-installer.jar

### Container definition

```
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: 6G
      VERSION: 1.18.2
      TYPE: CURSEFORGE
      CF_SERVER_MOD: create_flavored.zip
      USE_MODPACK_START_SCRIPT: "FALSE"
      DEBUG: "TRUE"
      GUI: "FALSE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /home/mc_server:/data

```

### Container logs

```
+ EXTRA_ARGS+=' nogui'
+ : 6G
+ : 6G
+ : 6G
+ expandedDOpts=
+ '[' -n '' ']'
+ isTrue ''
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 1
+ isTrue ''
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 1
+ isTrue ''
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 1
+ isTrue ''
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 1
+ isTrue ''
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 1
+ [[ -n 6G ]]
+ log 'Setting initial memory to 6G and max to 6G'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2022-07-13 07:36:09+00:00 Setting initial memory to 6G and max to 6G
+ [[ -n 6G ]]
+ JVM_OPTS='-Xms6G '
+ [[ -n 6G ]]
+ JVM_OPTS='-Xmx6G -Xms6G '
+ mcServerRunnerArgs=(--stop-duration "${STOP_DURATION:-60}s" --named-pipe "${CONSOLE_IN_NAMED_PIPE:-/tmp/minecraft-console-in}")
+ [[ -n '' ]]
+ [[ CURSEFORGE == \C\U\R\S\E\F\O\R\G\E ]]
+ [[ -n /data/FeedTheBeast/forge.jar ]]
+ copyFilesForCurseForge
+ '[' -f /data/ops.txt ']'
+ '[' -f /data/white-list.txt ']'
+ '[' '!' -e /data/FeedTheBeast/server-icon.png -a -e /data/server-icon.png ']'
+ cp -f /data/eula.txt /data/FeedTheBeast/
+ cd /data/FeedTheBeast
+ log 'Starting CurseForge server in /data/FeedTheBeast...'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2022-07-13 07:36:09+00:00 Starting CurseForge server in /data/FeedTheBeast...
+ isTrue
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 1
++ basename /data/FeedTheBeast/forge.jar
+ exec mc-server-runner --stop-duration 60s --named-pipe /tmp/minecraft-console-in java -Xmx6G -Xms6G -jar forge.jar nogui
JVM info: IcedTea - 1.8.0_212 - 25.212-b04
java.net.preferIPv4Stack=true
Found java version 1.8.0_212
Exception in thread "main"
java.lang.NullPointerException
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
        at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
        at sun.font.SunFontManager$2.run(SunFontManager.java:431)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:376)
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
        at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
        at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1107)
        at javax.swing.JComponent.getFontMetrics(JComponent.java:1617)
        at javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:276)
        at javax.swing.plaf.basic.BasicButtonUI.getPreferredSize(BasicButtonUI.java:376)
        at javax.swing.plaf.basic.BasicButtonUI.getMinimumSize(BasicButtonUI.java:366)
        at javax.swing.JComponent.getMinimumSize(JComponent.java:1735)
        at javax.swing.plaf.basic.BasicOptionPaneUI.addButtonComponents(BasicOptionPaneUI.java:693)
        at javax.swing.plaf.basic.BasicOptionPaneUI.createButtonArea(BasicOptionPaneUI.java:630)
        at javax.swing.plaf.basic.BasicOptionPaneUI.installComponents(BasicOptionPaneUI.java:178)
        at javax.swing.plaf.basic.BasicOptionPaneUI.installUI(BasicOptionPaneUI.java:141)
        at javax.swing.JComponent.setUI(JComponent.java:657)
        at javax.swing.JOptionPane.setUI(JOptionPane.java:1860)
        at javax.swing.JOptionPane.updateUI(JOptionPane.java:1882)
        at javax.swing.JOptionPane.<init>(JOptionPane.java:1845)
        at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:857)
        at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
        at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:177)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:147)
2022-07-13T07:36:10.135Z        WARN    mc-server-runner        Minecraft server process failed {"exitCode": 1}
2022-07-13T07:36:10.135Z        INFO    mc-server-runner        Done
```

**Comment by itzg** [comment]
By placing the installer jar there and naming it `forge.jar` it assumed it was the server jar and ran it as such. 

Start over fresh and try it as a `GENERIC_PACK` along with TYPE=FORGE etc.

**Comment by CursedDog19** [comment]
> By placing the installer jar there and naming it `forge.jar` it assumed it was the server jar and ran it as such.
> 
> Start over fresh and try it as a `GENERIC_PACK` along with TYPE=FORGE etc.

I updated my config. The server is still using the pack's buggy start script when USE_MODPACK_START_SCRIPT is set to false.
```
JVM_OPTS='-Xmx6G -Xms6G '
+ mcServerRunnerArgs=(--stop-duration "${STOP_DURATION:-60}s" --named-pipe "${CONSOLE_IN_NAMED_PIPE:-/tmp/minecraft-console-in}")
+ [[ -n '' ]]
+ [[ FORGE == \C\U\R\S\E\F\O\R\G\E ]]
+ [[ FORGE == \C\U\R\S\E\F\O\R\G\E ]]
+ [[ /data/run.sh =~ run.sh ]]
+ log 'Using Forge supplied run.sh script...'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2022-07-18 16:00:46+00:00 Using Forge supplied run.sh script...
+ echo -Xmx6G -Xms6G
+ isTrue false
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 1
+ exec mc-server-runner --stop-duration 60s --named-pipe /tmp/minecraft-console-in --shell bash /data/run.sh
Error: Could not find or load main class @user_jvm_args.txt
2022-07-18T16:00:46.791Z	WARN	mc-server-runner	Minecraft server process failed	{"exitCode": 1}
2022-07-18T16:00:46.791Z	INFO	mc-server-runner	Done
```
New config:
```
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: 6G
      VERSION: 1.18.2
      TYPE: FORGE
      FORGEVERSION: 40.1.0
      GENERIC_PACK: create_flavored.zip
      USE_MODPACK_START_SCRIPT: "FALSE"
      DEBUG: "TRUE"
      GUI: "FALSE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /home/mc_server:/data
```

**Comment by itzg** [comment]
You can't run 1.18+ with java8. Switch to the latest image to use Java 17.

**Comment by CursedDog19** [comment]
> You can't run 1.18+ with java8. Switch to the latest image to use Java 17.

Thank you for the help. The server is running with the following image/env:
```
 mc:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: 6G
      VERSION: 1.18.2
      TYPE: FORGE
      GENERIC_PACK: pack.zip
      USE_MODPACK_START_SCRIPT: "FALSE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /home/mc_server:/data
```
