### ISSUE TITLE
Failed to load datapacks with FTBA, FTB One pack 

### ISSUE THREAD

**Issue by GeoDerp** [itzg/docker-minecraft-server#1611]
### Describe the problem

When pulling the modpack via  `-e TYPE=FTBA` I get an `Failed to load datapacks` error.
Was wondering if anyone else had this issue occur when running an FTB modpack, if so, how did they get around the issue. (have attempted a few works around but nothing yet)

### Container definition

```
podman run -d -e ENABLE_AUTOPAUSE=TRUE -v ~/mc:/data:Z  -e TYPE=FTBA -p 57571:57571  -e EULA=TRUE   -e MEMORY="" -e JVM_XX_OPTS="-XX:MaxRAMPercentage=75" -m 8G -e JVM_DD_OPTS=disable.watchdog:true -e  FTB_MODPACK_ID=97 --name mc itzg/minecraft-server 
```

### Container logs

```java
...
[17Jul2022 15:08:53.548] [main/INFO] [KubeJS/]: Registered custom recipe handler for type minecraft:campfire_cooking
[17Jul2022 15:08:53.549] [main/INFO] [KubeJS/]: Registered custom recipe handler for type minecraft:smithing
[17Jul2022 15:08:53.563] [main/INFO] [KubeJS Server/]: Scanning recipes...
[17Jul2022 15:08:53.572] [main/WARN] [net.minecraft.server.Main/]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Unknown recipe type: kubejs:shaped
        at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:182) ~[server-1.19-20220607.102129-srg.jar%23237!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19-41.0.45.jar%2365!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%2353!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%2353!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%2353!/:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%2353!/:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%2353!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%2353!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%2353!/:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.1.jar:?]
Caused by: java.lang.NullPointerException: Unknown recipe type: kubejs:shaped
        at dev.latvian.mods.kubejs.recipe.RecipeEventJS.getRecipeFunction(RecipeEventJS.java:552) ~[kubejs-forge-1900.5.5-build.19.jar%23164!/:1900.5.5-build.19]
        at dev.latvian.mods.kubejs.recipe.RecipeEventJS.<init>(RecipeEventJS.java:118) ~[kubejs-forge-1900.5.5-build.19.jar%23164!/:1900.5.5-build.19]
        at dev.latvian.mods.kubejs.server.ServerScriptManager.wrapResourceManager(ServerScriptManager.java:140) ~[kubejs-forge-1900.5.5-build.19.jar%23164!/:1900.5.5-build.19]
        at net.minecraft.server.WorldLoader$PackConfig.redirect$zzk000$injectKubeJSPacks(WorldLoader.java:523) ~[server-1.19-20220607.102129-srg.jar%23237!/:?]
        at net.minecraft.server.WorldLoader$PackConfig.m_214399_(WorldLoader.java:61) ~[server-1.19-20220607.102129-srg.jar%23237!/:?]
        at net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:22) ~[server-1.19-20220607.102129-srg.jar%23237!/:?]
        at net.minecraft.server.WorldStem.m_214415_(WorldStem.java:18) ~[server-1.19-20220607.102129-srg.jar%23237!/:?]
        at net.minecraft.server.Main.lambda$main$3(Main.java:158) ~[server-1.19-20220607.102129-srg.jar%23237!/:?]
        at net.minecraft.Util.m_214652_(Util.java:768) ~[server-1.19-20220607.102129-srg.jar%23237!/:?]
        at net.minecraft.Util.m_214679_(Util.java:763) ~[server-1.19-20220607.102129-srg.jar%23237!/:?]
        at net.minecraft.server.Main.main(Main.java:157) ~[server-1.19-20220607.102129-srg.jar%23237!/:?]
        ... 13 more
```

**Comment by cylian914** [comment]
the an issue with datapack, if you have some datapack installed remove them if it don't fix try an other world and if it rly don't want to work remove  KubeJS but it can cause  some issue

**Comment by GeoDerp** [comment]
That would be understandable, however, running the modpack manually results no errors for the datapack (also same issues with pre-built works). My only understanding there would be that the error checking on the container is higher than just running it via script, or there is a patch of some kind in the start.sh that I ran manually that wasn't run by the container.

**Comment by itzg** [comment]
If you think there's something different about how the container runs it, then add `-e DEBUG=true`.

**Comment by GeoDerp** [comment]
Forgive my inaccessibility for the fix. I will close this issue and maybe reopen it later on the year if I experience the same issue.
