### ISSUE TITLE
Request for Java 18 Image

### ISSUE THREAD

**Issue by SleepyPxnda** [itzg/docker-minecraft-server#1621]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Is it possible to add an Java 18 tag ?

Eclipse-temurin provides an openjdk 18 image.

`FROM eclipse-temurin:18
CMD ["java", "--version"]`

Tested it with this basic Dockerfile which resulted in:

`openjdk 18.0.1 2022-04-19
OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode, sharing)`

**Comment by itzg** [comment]
Yep, should be very easy. Just curious if there's any specific reason other than being latest and greatest. (I use 18 now on my new projects)

**Comment by itzg** [comment]
FYI rather than add 5 more builds, I'd like to just stick with the JRE one like

https://github.com/itzg/docker-minecraft-server/blob/5cec41319d0f1bca0f57e401e9e4275e404395a3/.github/workflows/build-multiarch.yml#L27

**Comment by SleepyPxnda** [comment]
> Yep, should be very easy. Just curious if there's any specific reason other than being latest and greatest. (I use 18 now on my new projects)

I tried installing the modpack not2complicated but it always results in an error, according to the launch.sh it needs Java 1.8.

`echo "Checking java version..."
echo
java -version
echo
echo "The expected java version is 1.8. Not higher, not lower."
echo`

Error:
`[16:28:57] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 17.0.3 by Eclipse Adoptium
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x76e37707) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x76e37707
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:43)
2022-07-22T16:28:57.847Z        WARN    mc-server-runner        Minecraft server process failed {"exitCode": 1}
2022-07-22T16:28:57.847Z        INFO    mc-server-runner        Done`

Could be a different source of problems, but I think the matching java version could be a fix. And maybe some future modpacks also rely on java 18

**Comment by itzg** [comment]
Oh Java 1.8 is not Java 18. It's also known as just Java 8. Use the `java8` or `java8-multiarch` tags.

**Comment by SleepyPxnda** [comment]
Oh man ... I see it now aswell ... Im so sorry ....

**Comment by SleepyPxnda** [comment]
Dont know how i read java 18 the whole time 🤦‍♂️

**Comment by SleepyPxnda** [comment]
I guess this issue can be closed

**Comment by itzg** [comment]
No problem at all. Had all the right digits 😀
