### ISSUE TITLE
'get' command failed: launchermeta.mojang.com: Try again

### ISSUE THREAD

**Issue by Nakynum** [itzg/docker-minecraft-server#1625]
My Minecraft server worked with curseforge for up to 2 hours without any problems and suddenly my log only shows this error

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Jul 23 15:36 /data'
[mc-image-helper] 15:40:39.340 ERROR : 'get' command failed: launchermeta.mojang.com: Try again
[init] ERROR: version lookup failed: 
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Jul 23 15:36 /data'
[mc-image-helper] 15:42:20.499 ERROR : 'get' command failed: launchermeta.mojang.com: Try again
[init] ERROR: version lookup failed: 

hope someone can help me

**Comment by itzg** [comment]
I'm guessing it is some kind of network/DNS issue specific to your Docker system. Can you add `DEBUG_HELPER=true` to env vars and provide output with that?

**Comment by gamegine** [comment]
its DNS error I have the same due to a change on my network (openvpn setup on docker host server)
to confirm it add entrypoint to /bin/bash and try ping hostname and ip
````
bash-5.1# /start
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 60 Jul 30 14:22 /data'
[mc-image-helper] 14:35:10.573 ERROR : 'get' command failed: launchermeta.mojang.com: Try again
[init] ERROR: version lookup failed: 
bash-5.1# ping google.com
ping: google.com: Try again
bash-5.1# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=116 time=3.12 ms
^C
--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 3.123/3.182/3.242/0.059 ms
````

**Comment by Samega7Cattac** [comment]
I had the same issue.
But with the help of the TrueCharts discord peps seems the issue is with Vanilla only.
So changing to paper made it work.

**Comment by marauder13** [comment]
Hi. I have got the same issue as OP, and as recommended, I added the debug helper to the environment variables. Below is the generated output

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Aug  6 03:51 /data'
[mc-image-helper] 03:51:27.451 DEBUG : Getting uri=https://launchermeta.mojang.com/mc/game/version_manifest.json
[mc-image-helper] 03:51:27.458 DEBUG : Executing GET /mc/game/version_manifest.json with headers=[Accept: application/json]
[mc-image-helper] 03:51:27.467 DEBUG : Intercepting request uri=https://launchermeta.mojang.com/mc/game/version_manifest.json
[mc-image-helper] 03:51:47.507 ERROR : 'get' command failed: launchermeta.mojang.com: Temporary failure in name resolution
[mc-image-helper] 03:51:47.509 DEBUG : Details
java.net.UnknownHostException: launchermeta.mojang.com: Temporary failure in name resolution
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
        at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName(Unknown Source)
        at org.apache.hc.client5.http.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:43)
        at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at me.itzg.helpers.get.LatchingUrisInterceptor.execute(LatchingUrisInterceptor.java:27)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:200)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:143)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:117)
        at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:397)
        at me.itzg.helpers.get.GetCommand.call(GetCommand.java:175)
        at me.itzg.helpers.get.GetCommand.call(GetCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:70)
[init] ERROR: version lookup failed:

I hope that is useful.

**Comment by itzg** [comment]
@marauder13 Thanks. In your case at least you have a DNS issue with your docker or host system. It could be your firewall blocking DNS replies. 

```
java.net.UnknownHostException: launchermeta.mojang.com: Temporary failure in name resolution
```

**Comment by Nakynum** [comment]
> I'm guessing it is some kind of network/DNS issue specific to your Docker system. Can you add `DEBUG_HELPER=true` to env vars and provide output with that?

its was a dns error thanks for your help

**Comment by Pyrrha** [comment]
Hello @Nakynum @marauder13,
I'm encountering the same issue (and same logs as @marauder13 with `DEBUG_HELPER=true`).

Can I ask you how did you fix it?

Thanks

**Comment by Mistic92** [comment]
I have the same issue. I have my own DNS server and I don't see any request to it from container
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Feb 25 22:23 /data'
[init] ERROR: your Docker provider has an annoying flaw where it
[init]        tries to set PATH even though the container establishes
[init]        a very specific value.
[mc-image-helper] 22:24:29.668 DEBUG : Getting uri=https://launchermeta.mojang.com/mc/game/version_manifest.json
[mc-image-helper] 22:24:29.708 DEBUG : Executing GET /mc/game/version_manifest.json with headers=[Accept: application/json]
[mc-image-helper] 22:24:29.722 DEBUG : Intercepting request uri=https://launchermeta.mojang.com/mc/game/version_manifest.json
[mc-image-helper] 22:24:39.824 ERROR : 'get' command failed. Version is 1.24.23
java.net.UnknownHostException: launchermeta.mojang.com: Temporary failure in name resolution
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.hc.client5.http.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:43)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at me.itzg.helpers.http.LatchingUrisInterceptor.execute(LatchingUrisInterceptor.java:27)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
	at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:429)
	at me.itzg.helpers.get.GetCommand.call(GetCommand.java:186)
	at me.itzg.helpers.get.GetCommand.call(GetCommand.java:53)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:121)
[init] ERROR: version lookup failed: 
```

**Comment by MicahParks** [comment]
I was having the same issue, off and on, all weekend with a new server. This seems to be due to my hosting provider's DNS settings.

If you're using Docker Compose, there's an easy way to configure a different DNS server, see the example with `dns:` below.

```
version: "3"
services:
  minecraft:
    image: "itzg/minecraft-server"
    container_name: "minecraft"
    dns:
      - 8.8.8.8
    environment:
      EULA: "TRUE"
      DIFFICULTY: "hard"
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
 ```

**Comment by A3RNAV** [comment]
> > I'm guessing it is some kind of network/DNS issue specific to your Docker system. Can you add `DEBUG_HELPER=true` to env vars and provide output with that?
> 
> its was a dns error thanks for your help

@marauder13 @Nakynum Sorry, how did you manage to end up fixing this? What exactly was the issue with your DNS? I've had the same issue for the past 2 days and changing my DNS server, changing the DNS in the compose file, and adjusting my firewall have all failed.

Log:

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Apr  6 12:50 /data'
[mc-image-helper] 13:11:47.918 ERROR : 'get' command failed. Version is 1.26.2
java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.lambda$connectSocket$0(SSLConnectionSocketFactory.java:232)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:231)
        at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181)
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at me.itzg.helpers.http.LatchingUrisInterceptor.execute(LatchingUrisInterceptor.java:27)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
        at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:439)
        at me.itzg.helpers.get.GetCommand.call(GetCommand.java:187)
        at me.itzg.helpers.get.GetCommand.call(GetCommand.java:54)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:132)
[init] ERROR: version lookup failed:
```

Docker Compose File:

```
version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: 'TRUE'
      MEMORY: '4G'
    container_name: "minecraft"
    ports:
      - '25565:25565'
    dns:
    - 8.8.8.8
    volumes:
      - /minecraftdata:/data
    stdin_open: true
    tty: true
    restart: 'no'
volumes:
  minecraftdata:
    external: true
```

Linux Server 22.04


Thank you so much in advance!

**Comment by MicahParks** [comment]
@A3RNAV in YAML, spacing matters. In the case of your Docker Compose file, I noticed that two spaces are missing in front of `- 8.8.8.8`. I think this may be your issue. Try the below file
```yaml
version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: 'TRUE'
      MEMORY: '4G'
    container_name: "minecraft"
    ports:
      - '25565:25565'
    dns:
      - 8.8.8.8
    volumes:
      - /minecraftdata:/data
    stdin_open: true
    tty: true
    restart: 'no'
volumes:
  minecraftdata:
    external: true
```

**Comment by A3RNAV** [comment]
@MicahParks I think you've solved it. I've been given a different error about some issue with my file system but at least this is out of the way. I can't thank you enough!

```
/snap/docker/2746/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend
Removing minecraft
Recreating 0719b5327e73_minecraft ... error

ERROR: for 0719b5327e73_minecraft  Cannot start service minecraft: error while creating mount source path '/minecraftdata': mkdir /minecraftdata: read-only file system

ERROR: for minecraft  Cannot start service minecraft: error while creating mount source path '/minecraftdata': mkdir /minecraftdata: read-only file system
ERROR: Encountered errors while bringing up the project.
```

Should be alright though, I think I just need to sort out my drive.

**Comment by A3RNAV** [comment]
@MicahParks Sorry to drag you back into this. I've fixed the file system issue but now it runs for a little longer before crashing again with the "Temporary failure in name resolution" error. I think it _*is*_ a DNS issue. Nevertheless at least one thing has been sorted out.
