### ISSUE TITLE
Failed to run older version

### ISSUE THREAD

**Issue by KRUXLEX** [itzg/docker-minecraft-server#1634]
### Describe the problem

When I try run docker with swich -e VERSION= i get a error. It doesn't matter what version I will use. Error is the same.
When I don't use this switch server start properly 

### Container definition

```
docker run -d -e VERSION=1.9 -p 25565:25565 -v /var/minecraft:/data -e EULA=TRUE -e MEMORY=2G --name mc itzg/minecraft-server
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 7 1000 1000 4096 Jul 27 22:42 /data'
[init] Resolved version given 1.9 into 1.9 and major version 1.9
[init] Resolving type given VANILLA
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 2G and max to 2G
[init] Starting the Minecraft server...
[22:46:51] [Server thread/INFO]: Starting minecraft server version 1.9
[22:46:51] [Server thread/INFO]: Loading properties
[22:46:51] [Server thread/INFO]: Default game type: SURVIVAL
[22:46:51] [Server thread/INFO]: Generating keypair
[22:46:51] [Server thread/INFO]: Starting Minecraft server on *:25565
Jul 27, 2022 10:46:51 PM io.netty.util.internal.PlatformDependent <clinit>
INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
[22:46:51] [Server thread/INFO]: Using epoll channel type
[22:46:51] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[22:46:51] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[22:46:51] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[22:46:51] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[22:46:51] [Server thread/INFO]: Preparing level "world"
java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at java.base/java.io.DataInputStream.readUTF(Unknown Source)
        at dx.a(SourceFile:112)
        at dx.a(SourceFile:82)
        at dx.a(SourceFile:78)
        at azs.b(SourceFile:115)
        at azs.<init>(SourceFile:28)
        at lp.b(SourceFile:139)
        at net.minecraft.server.MinecraftServer.a(SourceFile:278)
        at la.j(SourceFile:226)
        at net.minecraft.server.MinecraftServer.run(SourceFile:427)
        at java.base/java.lang.Thread.run(Unknown Source)


[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 7 1000 1000 4096 Jul 27 22:42 /data'
[init] Resolved version given 1.9 into 1.9 and major version 1.9
[init] Resolving type given VANILLA
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 2G and max to 2G
[init] Starting the Minecraft server...
[22:58:36] [Server thread/INFO]: Starting minecraft server version 1.9
[22:58:36] [Server thread/INFO]: Loading properties
[22:58:36] [Server thread/INFO]: Default game type: SURVIVAL
[22:58:36] [Server thread/INFO]: Generating keypair
[22:58:37] [Server thread/INFO]: Starting Minecraft server on *:25565
[22:58:37] [Server thread/INFO]: Using epoll channel type
[22:58:37] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[22:58:37] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[22:58:37] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[22:58:37] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[22:58:37] [Server thread/INFO]: Preparing level "world"
[22:58:37] [Server thread/INFO]: Preparing start region for level 0
[22:58:37] [Server thread/ERROR]: Couldn't load chunk
java.lang.NullPointerException: Cannot invoke "eb.a(java.io.DataInput, int, dw)" because "☃" is null
        at dn.a(SourceFile:414) ~[minecraft_server.1.9.jar:?]
        at dn.a(SourceFile:71) ~[minecraft_server.1.9.jar:?]
        at dn.a(SourceFile:414) ~[minecraft_server.1.9.jar:?]
        at dn.a(SourceFile:71) ~[minecraft_server.1.9.jar:?]
        at dn.a(SourceFile:414) ~[minecraft_server.1.9.jar:?]
        at dn.a(SourceFile:71) ~[minecraft_server.1.9.jar:?]
        at dx.a(SourceFile:117) ~[minecraft_server.1.9.jar:?]
        at dx.a(SourceFile:82) ~[minecraft_server.1.9.jar:?]
        at dx.a(SourceFile:78) ~[minecraft_server.1.9.jar:?]
        at ass.a(SourceFile:64) ~[minecraft_server.1.9.jar:?]
        at lo.f(SourceFile:124) [minecraft_server.1.9.jar:?]
        at lo.c(SourceFile:76) [minecraft_server.1.9.jar:?]
        at lo.d(SourceFile:91) [minecraft_server.1.9.jar:?]
        at net.minecraft.server.MinecraftServer.l(SourceFile:325) [minecraft_server.1.9.jar:?]
        at net.minecraft.server.MinecraftServer.a(SourceFile:296) [minecraft_server.1.9.jar:?]
        at la.j(SourceFile:226) [minecraft_server.1.9.jar:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:427) [minecraft_server.1.9.jar:?]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
[22:58:37] [Server thread/ERROR]: Couldn't load chunk
java.lang.NullPointerException: Cannot invoke "eb.a(java.io.DataInput, int, dw)" because "☃" is null
        at dn.a(SourceFile:414) ~[minecraft_server.1.9.jar:?]
        at dn.a(SourceFile:71) ~[minecraft_server.1.9.jar:?]
        at dn.a(SourceFile:414) ~[minecraft_server.1.9.jar:?]
        at dn.a(SourceFile:71) ~[minecraft_server.1.9.jar:?]
        at dn.a(SourceFile:414) ~[minecraft_server.1.9.jar:?]
        at dn.a(SourceFile:71) ~[minecraft_server.1.9.jar:?]
        at dx.a(SourceFile:117) ~[minecraft_server.1.9.jar:?]
        at dx.a(SourceFile:82) ~[minecraft_server.1.9.jar:?]
        at dx.a(SourceFile:78) ~[minecraft_server.1.9.jar:?]
        at ass.a(SourceFile:64) ~[minecraft_server.1.9.jar:?]
        at lo.f(SourceFile:124) [minecraft_server.1.9.jar:?]
        at lo.d(SourceFile:95) [minecraft_server.1.9.jar:?]
        at net.minecraft.server.MinecraftServer.l(SourceFile:325) [minecraft_server.1.9.jar:?]
        at net.minecraft.server.MinecraftServer.a(SourceFile:296) [minecraft_server.1.9.jar:?]
        at la.j(SourceFile:226) [minecraft_server.1.9.jar:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:427) [minecraft_server.1.9.jar:?]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]


Jul 27, 2022 10:58:51 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer
        at io.netty.channel.epoll.Native.read(Native Method)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.base/java.lang.Thread.run(Unknown Source)

Jul 27, 2022 10:58:51 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer
        at io.netty.channel.epoll.Native.read(Native Method)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by itzg** [comment]
You need to be running Java 8 for older Minecraft versions. Use the image tag `java8` or `java8-multiarch`.
