### ISSUE TITLE
Minecraft: Spigot 1.8.8 server

### ISSUE THREAD

**Issue by kimhrac** [itzg/docker-minecraft-server#171]
I tried to setup a Spigot/Bukkit server for version 1.8.8 but I can't find out what is wrong. I try to run this command:

```
docker \
run \
-e EULA=TRUE \
-e TYPE=BUKKIT \
-e VERSION=1.8.8 \
-e DIFFICULTY=peaceful \
-e ENABLE_COMMAND_BLOCK=true \
-e FORCE_GAMEMODE=false \
-e GENERATE_STRUCTURES=true \
-e SPAWN_ANIMALS=true \
-e SPAWN_MONSTERS=true \
-e MODE=survival \
-e MAX_PLAYERS=20 \
-d \
-v /data/minecraft/servers/mc-bukkit:/data \
-p 25565:25565 \
--name mc-bukkit \
itzg/minecraft-server \
--noconsole
```

but when the server starts I see this and it exits:

```
usermod: no changes
Correcting writability of /data ...
Switching to user 'minecraft'
Checking version information.
Checking type information.
2017/07/12 22:06:07 Unable to find an element with the class 'jar-div'
ERROR: Version 1.8.8 is not supported for BUKKIT
Refer to https://mcadmin.net/ for supported versions
```

I also tried to change version to 1.8, 1.12 etc, but the same problem. Also the website that is referenced does not seem to be running?

**Comment by itzg** [comment]
The mcadmin.net site quickly runs out of capacity, so it seems to be rarely online. It takes longer to startup, but an "easy" solution is to add

```
-e BUILD_FROM_SOURCE=true
```

to your `docker run` command line.

**Comment by kimhrac** [comment]
Thanks, but if I add that line to the script and run it I get this from the log:

```
usermod: no changes
Switching to user 'minecraft'
Checking version information.
Checking type information.
Building Spigot 1.8.8 from source, might take a while, get some coffee
............done
mv: cannot stat ‘spigot-*.jar’: No such file or directory
mv: cannot stat ‘craftbukkit-*.jar’: No such file or directory
Cleaning up
Copying any Bukkit plugins over
Error: Unable to access jarfile craftbukkit_server.jar
```

**Comment by itzg** [comment]
@kimhrac unless you trimmed some of the ....'s before the done, your build seems to have error'ed out early. Can you post the last part of what should be the build log at `/data/minecraft/servers/mc-bukkit/spigot_build.log`?

**Comment by kimhrac** [comment]
I didn't trim out anything.
The content of spigot_build.log is:

```
Loading BuildTools version: git-BuildTools-7f7e531-60 (#60)
Git name not set, setting it to default value.
Exception in thread "main" java.io.IOException: Cannot run program "git" (in directory "."): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.spigotmc.builder.Builder.runProcess(Builder.java:552)
        at org.spigotmc.builder.Builder.main(Builder.java:162)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 2 more
```

**Comment by kimhrac** [comment]
I can see that I might need to add also the `-e SPIGOT_DOWNLOAD_URL` and change type to `-e TYPE=SPIGOT` so I tried the following:

```
docker \
        run \
        -e EULA=TRUE \
        -e TYPE=SPIGOT \
        -e VERSION=1.12 \
        -e BUILD_FROM_SOURCE=true \
        -e SPIGOT_DOWNLOAD_URL=https://cdn.getbukkit.org/spigot/spigot-1.12.jar \
        -e DIFFICULTY=peaceful \
        -e ENABLE_COMMAND_BLOCK=true \
        -e FORCE_GAMEMODE=false \
        -e GENERATE_STRUCTURES=true \
        -e SPAWN_ANIMALS=true \
        -e SPAWN_MONSTERS=true \
        -e MODE=survival \
        -e MAX_PLAYERS=20 \
        -d \
        -v /data/minecraft/servers/mc-bukkit:/data \
        -p 25566:25565 \
        --name mc-bukkit \
        itzg/minecraft-server \
        --noconsole
```

but this gives the following when I try to run it and use `docker logs <containerid>`:

```
usermod: no changes
Switching to user 'minecraft'
Checking version information.
Checking type information.
Building Spigot 1.12 from source, might take a while, get some coffee
............done
mv: cannot stat ‘spigot-*.jar’: No such file or directory
mv: cannot stat ‘craftbukkit-*.jar’: No such file or directory
Cleaning up
Copying any Bukkit plugins over
Error: Unable to access jarfile spigot_server.jar
```

Am I missing something? Is the download URL correct?

**Comment by itzg** [comment]
Sorry for the delay on responding. Yours is acting like `git` isn't present within the image, but I just double checked that I can see it.

This time can you do a fresh pull and see what it is reported about your image's git:

```bash
docker pull itzg/minecraft-server
docker run --rm --entrypoint /usr/bin/git itzg/minecraft-server version
```

**Comment by kimhrac** [comment]
Thanks for helping out. Output is like this:

```
# docker pull itzg/minecraft-server
Using default tag: latest
latest: Pulling from itzg/minecraft-server
88286f41530e: Pull complete
009f6e766a1b: Pull complete
132a112fc74a: Pull complete
12c2c69acadd: Pull complete
9c8d689deeae: Pull complete
8c748a120a0a: Pull complete
266bf930cd9c: Pull complete
8ddf30fbe82a: Pull complete
d7572c5a5bcc: Pull complete
b902fc97be92: Pull complete
e8a68354a689: Pull complete
2c0296b9754b: Pull complete
679cc2babd1a: Pull complete
Digest: sha256:b59b6979a160d167a4a520a80d84aabd7aad518504a03248cf113ce22eede876
Status: Downloaded newer image for itzg/minecraft-server:latest
# docker run --rm --entrypoint /usr/bin/git itzg/minecraft-server version
git version 2.13.0
```

This helped move beyond git problem. Now I get the following when trying to run the command above:

```
# docker logs 2c
Switching to user 'minecraft'
Checking version information.
Checking type information.
Building Spigot 1.12 from source, might take a while, get some coffee
.........................................................................................................................................done
Cleaning up
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.

Usage: mv [-fin] SOURCE DEST
or: mv [-fin] SOURCE... DIRECTORY

Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY

        -f      Don't prompt before overwriting
        -i      Interactive, prompt before overwrite
        -n      Don't overwrite an existing file
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.

Usage: mv [-fin] SOURCE DEST
or: mv [-fin] SOURCE... DIRECTORY

Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY

        -f      Don't prompt before overwriting
        -i      Interactive, prompt before overwrite
        -n      Don't overwrite an existing file
Copying any Bukkit plugins over
Setting initial memory to 1G and max to 1G
Error: Unable to access jarfile spigot_server.jar
```

**Comment by itzg** [comment]
Since there's a relatively small number of dots from the build step, I'm guessing it failed unexpectedly. Can you paste the last part of the file `/data/spigot_build.log` from the container? If you had `-v` attached a host directory to `/data`, it'll be easier to obtain from there.

**Comment by kimhrac** [comment]
Sure:

```
# more spigot_build.log
Loading BuildTools version: git-BuildTools-7f7e531-60 (#60)
Git name not set, setting it to default value.
Git email not set, setting it to default value.
Starting clone of https://hub.spigotmc.org/stash/scm/spigot/bukkit.git to Bukkit
Cloned git repository https://hub.spigotmc.org/stash/scm/spigot/bukkit.git to /data/temp/Bukkit. Current HEAD: 0ce77bc4b3825b1665b34f7dd6dc4b01a02e9443
Starting clone of https://hub.spigotmc.org/stash/scm/spigot/craftbukkit.git to CraftBukkit
Cloned git repository https://hub.spigotmc.org/stash/scm/spigot/craftbukkit.git to /data/temp/CraftBukkit. Current HEAD: 2c5c611d0c3c198c1ac904e8d64051a8437a8720
Starting clone of https://hub.spigotmc.org/stash/scm/spigot/spigot.git to Spigot
Cloned git repository https://hub.spigotmc.org/stash/scm/spigot/spigot.git to /data/temp/Spigot. Current HEAD: 596221bf2ffd4e694d008406f7940a8a041a71fb
Starting clone of https://hub.spigotmc.org/stash/scm/spigot/builddata.git to BuildData
Cloned git repository https://hub.spigotmc.org/stash/scm/spigot/builddata.git to /data/temp/BuildData. Current HEAD: ebd264edb506ff3e72e92dd16b1b68c46905972c
Maven does not exist, downloading. Please wait.
Starting download of https://static.spigotmc.org/maven/apache-maven-3.2.5-bin.zip
Downloaded file: mvn.zip with md5: e617600b75dff1f69b67e92d55f47c6a
Extracted: ./apache-maven-3.2.5/README.txt
Extracted: ./apache-maven-3.2.5/LICENSE
Extracted: ./apache-maven-3.2.5/NOTICE
Extracted: ./apache-maven-3.2.5/lib/aether-api.license
Extracted: ./apache-maven-3.2.5/lib/aether-connector-basic.license
Extracted: ./apache-maven-3.2.5/lib/aether-impl.license
Extracted: ./apache-maven-3.2.5/lib/aether-spi.license
Extracted: ./apache-maven-3.2.5/lib/aether-transport-wagon.license
Extracted: ./apache-maven-3.2.5/lib/aether-util.license
Extracted: ./apache-maven-3.2.5/lib/cdi-api.license
Extracted: ./apache-maven-3.2.5/lib/jsoup.license
Extracted: ./apache-maven-3.2.5/lib/jsr250-api.license
Extracted: ./apache-maven-3.2.5/lib/maven-aether-provider.license
Extracted: ./apache-maven-3.2.5/lib/maven-artifact.license
Extracted: ./apache-maven-3.2.5/lib/maven-compat.license
Extracted: ./apache-maven-3.2.5/lib/maven-core.license
Extracted: ./apache-maven-3.2.5/lib/maven-embedder.license
Extracted: ./apache-maven-3.2.5/lib/maven-model-builder.license
Extracted: ./apache-maven-3.2.5/lib/maven-model.license
Extracted: ./apache-maven-3.2.5/lib/maven-plugin-api.license
Extracted: ./apache-maven-3.2.5/lib/maven-repository-metadata.license
Extracted: ./apache-maven-3.2.5/lib/maven-settings-builder.license
Extracted: ./apache-maven-3.2.5/lib/maven-settings.license
Extracted: ./apache-maven-3.2.5/lib/org.eclipse.sisu.inject.license
Extracted: ./apache-maven-3.2.5/lib/org.eclipse.sisu.plexus.license
Extracted: ./apache-maven-3.2.5/lib/plexus-cipher.license
Extracted: ./apache-maven-3.2.5/lib/plexus-sec-dispatcher.license
Extracted: ./apache-maven-3.2.5/lib/slf4j-api.license
Extracted: ./apache-maven-3.2.5/lib/slf4j-simple.license
Extracted: ./apache-maven-3.2.5/lib/wagon-file.license
Extracted: ./apache-maven-3.2.5/lib/wagon-http-shared.license
Extracted: ./apache-maven-3.2.5/lib/wagon-http.license
Extracted: ./apache-maven-3.2.5/lib/wagon-provider-api.license
Extracted: ./apache-maven-3.2.5/bin/m2.conf
Extracted: ./apache-maven-3.2.5/bin/mvn.bat
Extracted: ./apache-maven-3.2.5/bin/mvnDebug.bat
Extracted: ./apache-maven-3.2.5/bin/mvn
Extracted: ./apache-maven-3.2.5/bin/mvnDebug
Extracted: ./apache-maven-3.2.5/bin/mvnyjp
Extracted: ./apache-maven-3.2.5/conf/logging/simplelogger.properties
Extracted: ./apache-maven-3.2.5/conf/settings.xml
Extracted: ./apache-maven-3.2.5/lib/ext/README.txt
Extracted: ./apache-maven-3.2.5/boot/plexus-classworlds-2.5.2.jar
Extracted: ./apache-maven-3.2.5/lib/maven-embedder-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/maven-settings-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/plexus-utils-3.0.20.jar
Extracted: ./apache-maven-3.2.5/lib/maven-core-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/maven-model-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/maven-settings-builder-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/plexus-interpolation-1.21.jar
Extracted: ./apache-maven-3.2.5/lib/plexus-component-annotations-1.5.5.jar
Extracted: ./apache-maven-3.2.5/lib/plexus-sec-dispatcher-1.3.jar
Extracted: ./apache-maven-3.2.5/lib/plexus-cipher-1.7.jar
Extracted: ./apache-maven-3.2.5/lib/maven-repository-metadata-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/maven-artifact-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/maven-plugin-api-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/org.eclipse.sisu.plexus-0.3.0.M1.jar
Extracted: ./apache-maven-3.2.5/lib/cdi-api-1.0.jar
Extracted: ./apache-maven-3.2.5/lib/jsr250-api-1.0.jar
Extracted: ./apache-maven-3.2.5/lib/javax.inject-1.jar
Extracted: ./apache-maven-3.2.5/lib/org.eclipse.sisu.inject-0.3.0.M1.jar
Extracted: ./apache-maven-3.2.5/lib/maven-model-builder-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/maven-aether-provider-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/aether-api-1.0.0.v20140518.jar
Extracted: ./apache-maven-3.2.5/lib/aether-spi-1.0.0.v20140518.jar
Extracted: ./apache-maven-3.2.5/lib/aether-util-1.0.0.v20140518.jar
Extracted: ./apache-maven-3.2.5/lib/aether-impl-1.0.0.v20140518.jar
Extracted: ./apache-maven-3.2.5/lib/sisu-guice-3.2.3-no_aop.jar
Extracted: ./apache-maven-3.2.5/lib/aopalliance-1.0.jar
Extracted: ./apache-maven-3.2.5/lib/guava-18.0.jar
Extracted: ./apache-maven-3.2.5/lib/maven-compat-3.2.5.jar
Extracted: ./apache-maven-3.2.5/lib/wagon-provider-api-2.8.jar
Extracted: ./apache-maven-3.2.5/lib/slf4j-api-1.7.5.jar
Extracted: ./apache-maven-3.2.5/lib/commons-cli-1.2.jar
Extracted: ./apache-maven-3.2.5/lib/wagon-http-2.8-shaded.jar
Extracted: ./apache-maven-3.2.5/lib/wagon-http-shared-2.8.jar
Extracted: ./apache-maven-3.2.5/lib/jsoup-1.7.2.jar
Extracted: ./apache-maven-3.2.5/lib/commons-lang-2.6.jar
Extracted: ./apache-maven-3.2.5/lib/commons-io-2.2.jar
Extracted: ./apache-maven-3.2.5/lib/wagon-file-2.8.jar
Extracted: ./apache-maven-3.2.5/lib/aether-connector-basic-1.0.0.v20140518.jar
Extracted: ./apache-maven-3.2.5/lib/aether-transport-wagon-1.0.0.v20140518.jar
Extracted: ./apache-maven-3.2.5/lib/slf4j-simple-1.7.5.jar
Attempting to build version: '1.12' use --rev <version> to override
Found version
{
        "name": "1366",
        "description": "Jenkins build 1366",
        "refs": {
                "BuildData": "ebd264edb506ff3e72e92dd16b1b68c46905972c",
                "Bukkit": "0ce77bc4b3825b1665b34f7dd6dc4b01a02e9443",
                "CraftBukkit": "2c5c611d0c3c198c1ac904e8d64051a8437a8720",
                "Spigot": "596221bf2ffd4e694d008406f7940a8a041a71fb"
        },
        "toolsVersion": 47
}

Pulling updates for /data/temp/BuildData/.git
Successfully fetched updates!
Checked out: ebd264edb506ff3e72e92dd16b1b68c46905972c
Pulling updates for /data/temp/Bukkit/.git
Successfully fetched updates!
Checked out: 0ce77bc4b3825b1665b34f7dd6dc4b01a02e9443
Pulling updates for /data/temp/CraftBukkit/.git
Successfully fetched updates!
Checked out: 2c5c611d0c3c198c1ac904e8d64051a8437a8720
Pulling updates for /data/temp/Spigot/.git
Successfully fetched updates!
Checked out: 596221bf2ffd4e694d008406f7940a8a041a71fb
Attempting to build Minecraft with details: VersionInfo(minecraftVersion=1.12, accessTransforms=bukkit-1.12.at, classMappings=bukkit-1.12-cl.csrg, memberMappings=bukkit-1.12-members.csrg, packageMappings=package.srg, minecraftHash=218513c2d5b0ec4b6db26801a3883ad1, decompileCommand=java -jar BuildData/bin/fernflower.jar -dgs=1 -hdc=0 -asc=1 -udv=0 {0} {1}, serverUrl=https://launc
her.mojang.com/mc/game/1.12/server/8494e844e911ea0d63878f64da9dcc21f53a3463/server.jar)
Starting download of https://launcher.mojang.com/mc/game/1.12/server/8494e844e911ea0d63878f64da9dcc21f53a3463/server.jar
Downloaded file: work/minecraft_server.1.12.jar with md5: 218513c2d5b0ec4b6db26801a3883ad1
Found good Minecraft hash (218513c2d5b0ec4b6db26801a3883ad1)
Final mapped jar: work/mapped.323675e4.jar does not exist, creating!
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e4c00000, 39845888, 0) failed; error='Out of memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 39845888 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /data/temp/hs_err_pid67.log
Exception in thread "main" java.lang.RuntimeException: Error running command, return status !=0: [java, -jar, BuildData/bin/SpecialSource-2.jar, map, -i, work/minecraft_server.1.12.jar, -m, BuildData/mappings/bukkit-1.12-cl.csrg, -o, work/mapped.323675e4.jar-cl]
        at org.spigotmc.builder.Builder.runProcess(Builder.java:561)
        at org.spigotmc.builder.Builder.main(Builder.java:319)
```

**Comment by itzg** [comment]
I'll have to ponder the error message some more if Maven ran out of memory or if the host where the container is running out of memory. I'm leaning towards the later.
