### ISSUE TITLE
Error installing Forge

### ISSUE THREAD

**Issue by DonRohan** [itzg/docker-minecraft-server#1724]
### Describe the problem

Forge cannot be installed using the latest verison of itzg/minecraft-server

### Container definition

version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:latest
    volumes:
    - ./data:/data
    - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      MEMORY: 6G
      TYPE: FORGE
      VERSION: 1.18.2
      FORGEVERSION: 40.1.79
      # Need to download Server-Files-0.4.13.zip and
      # put it in modpacks directory next to this compose file
      GENERIC_PACK: /modpacks/ATM7-0.4.30-server.zip
    ports:
      - "25565:25565"

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Sep  9 08:55 /data'
[init] Resolved version given 1.18.2 into 1.18.2 and major version 1.18
[init] Resolving type given FORGE
[mc-image-helper] 09:30:35.915 INFO  : Downloading Forge installer 40.1.79 for Minecraft 1.18.2
[mc-image-helper] 09:30:39.104 INFO  : Running Forge installer. This might take a while...
[mc-image-helper] 09:30:43.093 ERROR : 'install-forge' command failed: Forge installer failed with exit code 1
[init] ERROR failed to install forge

----

JVM info: Eclipse Adoptium - 17.0.4.1 - 17.0.4.1+1
java.net.preferIPv4Stack=true
Found java version 17.0.4.1
Target Directory: .
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.finishHandshake(Unknown Source)
	at java.base/sun.security.ssl.Finished$T13FinishedProducer.onProduceFinished(Unknown Source)
	at java.base/sun.security.ssl.Finished$T13FinishedProducer.produce(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.produce(Unknown Source)
	at java.base/sun.security.ssl.Finished$T13FinishedConsumer.onConsumeFinished(Unknown Source)
	at java.base/sun.security.ssl.Finished$T13FinishedConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at net.minecraftforge.installer.DownloadUtils.getConnection(DownloadUtils.java:243)
	at net.minecraftforge.installer.DownloadUtils.downloadMirrors(DownloadUtils.java:293)
	at net.minecraftforge.installer.json.Install.getMirror(Install.java:117)
	at net.minecraftforge.installer.actions.ServerInstall.run(ServerInstall.java:54)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:128)
Considering minecraft server jar
A problem installing was detected, install cannot continue

---

ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1029348
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 62987
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by itzg** [comment]
It looks like the docker host is very low on memory:

> java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

**Comment by DonRohan** [comment]
the docker-host has got min 6GB to spare

**Comment by DonRohan** [comment]
issue has been resolved
