### ISSUE TITLE
FEAURE REQUEST: Forge - Missing *.jar files after mounting a new /data folder - redownload / reinstall / restart issue ?

### ISSUE THREAD

**Issue by OhmegaStar** [itzg/docker-minecraft-server#176]
Hi

After changing the mounted docker volume /data to a new folder the container will not start, in stderr i find this error:

2017-08-08T09:19:14.133724954Z Error: Unable to access jarfile forge-1.12-14.21.0.2322-universal.jar
2017-08-08T09:20:06.292328199Z Error: Unable to access jarfile forge-1.12-14.21.0.2322-universal.jar
2017-08-08T09:21:49.782606695Z Error: Unable to access jarfile forge-1.12-14.21.0.2322-universal.jar

and that is correct the new folder has none of the minecraft jar's or forge jars downloaded. 
this is similar to when you start the container, but for some reason this container when started does not discover and redownload the missing resources, it just fails.

is there something i can do to fix this issue myself ?

Regards,

OhmegaStar

**Comment by itzg** [comment]
@OhmegaStar sorry for taking so long to respond. Since the majority of the container runs as UID `1000` my initial guess is that the new folder referenced by your -v mount may not be writable by that user. Double check that and concurrently I'll enhance the startup script to test if the `/data` mount is writable early in startup and output an appropriate message.

**Comment by OhmegaStar** [comment]
@itzg, thanks for responding. 
The access rights on the mounted folder has not been changed in the folder host, so I think it is unlikely that that caused the issue. (the access is for 1000:1000)

right now it shows a different kind of error:
2017-09-05T07:12:57.645069955Z Switching to user 'minecraft'
2017-09-05T07:12:57.648058901Z Checking version information.
2017-09-05T07:12:57.885038736Z Checking type information.
2017-09-05T07:12:57.885096737Z Checking Forge version information.
2017-09-05T07:12:58.503681620Z Setting initial memory to 1G and max to 1G
2017-09-05T07:13:03.309569912Z [07:13:03] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
2017-09-05T07:13:03.339468469Z [07:13:03] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
2017-09-05T07:13:03.340234181Z [07:13:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
2017-09-05T07:13:03.780779118Z 2017-09-05 07:13:03,777 main WARN Disabling terminal, you're running in an unsupported environment.
2017-09-05T07:13:03.819018103Z [07:13:03] [main/INFO] [FML]: Forge Mod Loader version 14.22.0.2449 for Minecraft 1.12.1 loading
2017-09-05T07:13:03.819798315Z [07:13:03] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_131, running on Linux:amd64:4.4.0-92-generic, installed at /usr/lib/jvm/java-1.8-openjdk/jre
2017-09-05T07:13:04.095111325Z [07:13:04] [main/ERROR] [LaunchWrapper]: Unable to launch
2017-09-05T07:13:04.095149926Z java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at /data/. for Forge Mod Loader
2017-09-05T07:13:04.095160126Z 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:104) ~[forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095169526Z 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:81) ~[forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095179026Z 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:43) ~[forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095187826Z 	at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62) ~[forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095197027Z 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
2017-09-05T07:13:04.095205427Z 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
2017-09-05T07:13:04.095213827Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
2017-09-05T07:13:04.095222727Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
2017-09-05T07:13:04.095231227Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
2017-09-05T07:13:04.095239627Z 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
2017-09-05T07:13:04.095247827Z 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095256528Z 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095265028Z Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/IOUtils
2017-09-05T07:13:04.095273328Z 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:405) ~[forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095299528Z 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255) ~[forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095308928Z 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:100) ~[forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095317528Z 	... 11 more
2017-09-05T07:13:04.095325129Z Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.IOUtils
2017-09-05T07:13:04.095332929Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
2017-09-05T07:13:04.095353229Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
2017-09-05T07:13:04.095361729Z 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_131]
2017-09-05T07:13:04.095369529Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
2017-09-05T07:13:04.095377129Z 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:405) ~[forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095385129Z 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255) ~[forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095393230Z 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:100) ~[forge-1.12.1-14.22.0.2449-universal.jar:?]
2017-09-05T07:13:04.095401230Z 	... 11 more
2017-09-05T07:13:04.104227365Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: java.lang.reflect.InvocationTargetException
2017-09-05T07:13:04.104258265Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-09-05T07:13:04.104274165Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-09-05T07:13:04.104283666Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-09-05T07:13:04.104967976Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at java.lang.reflect.Method.invoke(Method.java:498)
2017-09-05T07:13:04.105441283Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
2017-09-05T07:13:04.106183695Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
2017-09-05T07:13:04.107965322Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
2017-09-05T07:13:04.108573231Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
2017-09-05T07:13:04.109196041Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
2017-09-05T07:13:04.109795750Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Runtime.exit(Runtime.java:107)
2017-09-05T07:13:04.110342758Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.System.exit(System.java:971)
2017-09-05T07:13:04.110934567Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
2017-09-05T07:13:04.111586977Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
2017-09-05T07:13:04.112353189Z [07:13:04] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	... 6 more

and

2017-09-05T07:13:04.219234423Z A problem occurred running the Server launcher.
2017-09-05T07:13:04.614701968Z container_linux.go:247: starting container process caused "exec: \"/start\": stat /start: no such file or directory"

/OhmegaStar

**Comment by itzg** [comment]
Those are both strange. I'll investigate further.

**Comment by OhmegaStar** [comment]
@itzg Thanks - Ill appreciate that. Let me know if i should do anything to help troubleshooting.
