### ISSUE TITLE
Container run and down almost immediately

### ISSUE THREAD

**Issue by Juludu47** [itzg/docker-minecraft-server#1778]
### Describe the problem

I would like to run several instances of Minecraft servers, however, the container starts and stops almost immediately. 

configuration : 
Debian 11
Docker ce (latest)
4GB RAM
4* CPU on Vmware ESXI

Command used : 
docker run -d -it -p 25900:25565 -e EULA=TRUE --name mc-jnf itzg/minecraft-server -v /home/"user"/minecraft-data/jnf:/data

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Oct 12 15:14 /data'
,[init] Checking for JSON files.
,[init] Resolved version given LATEST into 1.19.2 and major version 1.19
,[init] Resolving type given VANILLA
,[init] Disabling whitelist functionality
,[init] Setting initial memory to 1G and max to 1G
,[init] Starting the Minecraft server...
,Starting net.minecraft.server.Main
,[15:24:26] [ServerMain/ERROR]: Failed to start the minecraft server
,joptsimple.UnrecognizedOptionException: v is not a recognized option
,	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[jopt-simple-5.0.4.jar:?]
,	at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:633) ~[jopt-simple-5.0.4.jar:?]
,	at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:528) ~[jopt-simple-5.0.4.jar:?]
,	at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:523) ~[jopt-simple-5.0.4.jar:?]
,	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:59) ~[jopt-simple-5.0.4.jar:?]
,	at joptsimple.OptionParser.parse(OptionParser.java:396) ~[jopt-simple-5.0.4.jar:?]
,	at net.minecraft.server.Main.main(SourceFile:84) ~[server-1.19.2.jar:?]
,	at net.minecraft.bundler.Main.lambda$run$0(Main.java:54) ~[?:?]
,	at java.lang.Thread.run(Unknown Source) [?:?]
,2022-10-12T15:24:26.513Z	INFO	mc-server-runner	Done

**Comment by DerEnderKeks** [comment]
Your docker command is slightly wrong. You put `-v /home/"user"/minecraft-data/jnf:/data` after the name of the image (`itzg/minecraft-server`), which means it's passed to the container (thus the `v is not a recognized option`) . Your command should look like this:

```shell
docker run -d -it -p 25900:25565 -v /home/"user"/minecraft-data/jnf:/data -e EULA=TRUE --name mc-jnf itzg/minecraft-server
```

(Btw.: `latest` is not really a helpful version number, since it could mismatch the actual `latest` within minutes)

**Comment by Juludu47** [comment]
Hi, sorry for the late and thanks for the help, it's work !!!
