### ISSUE TITLE
Build from source seems to not finish?

### ISSUE THREAD

**Issue by Kianda** [itzg/docker-minecraft-server#179]
Here is the last part of the log:

```
..........................................................done
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.

Usage: mv [-fin] SOURCE DEST
or: mv [-fin] SOURCE... DIRECTORY

Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY

	-f	Don't prompt before overwriting
	-i	Interactive, prompt before overwrite
	-n	Don't overwrite an existing file
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.

Usage: mv [-fin] SOURCE DEST
or: mv [-fin] SOURCE... DIRECTORY

Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY

	-f	Don't prompt before overwriting
	-i	Interactive, prompt before overwrite
	-n	Don't overwrite an existing file
Cleaning up
Copying any Bukkit plugins over
Setting initial memory to 512M and max to 512M
Error: Unable to access jarfile spigot_server.jar
```

Any idea? Thanks!

**Comment by itzg** [comment]
Hmm, I'll double check this too. Just to align scenarios can you provide the 'docker run' line you're using?

**Comment by Kianda** [comment]
> https://www.dropbox.com/s/1xuwvynuw9ujjtg/minecraft.zip?dl=0

Here is the template I'm using (under Ubuntu).
minecraft/server/docker/zzsh -> sh minecraft_start.sh

And this will run:
`docker run -d -i -v $(pwd)/../../data:/data -p 25565:25565 -e BUILD_FROM_SOURCE=true -e TYPE=SPIGOT -e VERSION=LATEST -e EULA=TRUE -e MEMORY=512M --name minecraft-server itzg/minecraft-server`

**Comment by Kianda** [comment]
Adding here also the spigot_build.log

```
Loading BuildTools version: git-BuildTools-582e680-63 (#63)
Git name not set, setting it to default value.
Git email not set, setting it to default value.
Starting clone of https://hub.spigotmc.org/stash/scm/spigot/bukkit.git to Bukkit
Cloned git repository https://hub.spigotmc.org/stash/scm/spigot/bukkit.git to /data/temp/Bukkit. Current HEAD: 4f16bdbabbad82b6130b19bcc0a4621dee83e86e
Starting clone of https://hub.spigotmc.org/stash/scm/spigot/craftbukkit.git to CraftBukkit
Cloned git repository https://hub.spigotmc.org/stash/scm/spigot/craftbukkit.git to /data/temp/CraftBukkit. Current HEAD: 94b098085269b86ae8f926fe64e06fa3fbe6a7ca
Starting clone of https://hub.spigotmc.org/stash/scm/spigot/spigot.git to Spigot
Cloned git repository https://hub.spigotmc.org/stash/scm/spigot/spigot.git to /data/temp/Spigot. Current HEAD: 775423189fea374bf4f1d0391c4cf242e741185f
Starting clone of https://hub.spigotmc.org/stash/scm/spigot/builddata.git to BuildData
Cloned git repository https://hub.spigotmc.org/stash/scm/spigot/builddata.git to /data/temp/BuildData. Current HEAD: a9c4523879abc011821f06283dd468c67c3b0097
Maven does not exist, downloading. Please wait.
Starting download of https://static.spigotmc.org/maven/apache-maven-3.5.0-bin.zip
Downloaded file: mvn.zip with md5: c062cb57ca81615cc16500af332b93bd
Extracted: ./apache-maven-3.5.0/README.txt
Extracted: ./apache-maven-3.5.0/lib/maven-compat.license
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-connector-basic.license
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-provider.license
Extracted: ./apache-maven-3.5.0/lib/plexus-cipher.license
Extracted: ./apache-maven-3.5.0/lib/wagon-provider-api.license
Extracted: ./apache-maven-3.5.0/bin/mvn.cmd
Extracted: ./apache-maven-3.5.0/lib/ext/README.txt
Extracted: ./apache-maven-3.5.0/lib/commons-lang3-3.5.jar
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-spi-1.0.3.jar
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-impl-1.0.3.jar
Extracted: ./apache-maven-3.5.0/lib/wagon-http-2.12-shaded.jar
Extracted: ./apache-maven-3.5.0/LICENSE
Extracted: ./apache-maven-3.5.0/lib/maven-embedder.license
Extracted: ./apache-maven-3.5.0/lib/plexus-sec-dispatcher.license
Extracted: ./apache-maven-3.5.0/lib/jansi-native/osx/libjansi.jnilib
Extracted: ./apache-maven-3.5.0/bin/mvnyjp
Extracted: ./apache-maven-3.5.0/lib/maven-settings-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/plexus-interpolation-1.24.jar
Extracted: ./apache-maven-3.5.0/lib/maven-repository-metadata-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/javax.inject-1.jar
Extracted: ./apache-maven-3.5.0/lib/org.eclipse.sisu.inject-0.3.3.jar
Extracted: ./apache-maven-3.5.0/lib/maven-compat-3.5.0.jar
Extracted: ./apache-maven-3.5.0/NOTICE
Extracted: ./apache-maven-3.5.0/lib/maven-artifact.license
Extracted: ./apache-maven-3.5.0/lib/maven-plugin-api.license
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-transport-wagon.license
Extracted: ./apache-maven-3.5.0/lib/wagon-file.license
Extracted: ./apache-maven-3.5.0/bin/m2.conf
Extracted: ./apache-maven-3.5.0/conf/toolchains.xml
Extracted: ./apache-maven-3.5.0/lib/maven-core-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/guice-4.0-no_aop.jar
Extracted: ./apache-maven-3.5.0/lib/cdi-api.license
Extracted: ./apache-maven-3.5.0/lib/maven-model-builder.license
Extracted: ./apache-maven-3.5.0/lib/org.eclipse.sisu.inject.license
Extracted: ./apache-maven-3.5.0/lib/org.eclipse.sisu.plexus.license
Extracted: ./apache-maven-3.5.0/lib/wagon-http.license
Extracted: ./apache-maven-3.5.0/bin/mvnDebug.cmd
Extracted: ./apache-maven-3.5.0/lib/jansi-native/README.txt
Extracted: ./apache-maven-3.5.0/lib/maven-settings-builder-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/plexus-sec-dispatcher-1.4.jar
Extracted: ./apache-maven-3.5.0/lib/jsr250-api-1.0.jar
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-provider-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/maven-shared-utils-3.1.0.jar
Extracted: ./apache-maven-3.5.0/lib/aopalliance-1.0.jar
Extracted: ./apache-maven-3.5.0/lib/slf4j-api-1.7.22.jar
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-connector-basic-1.0.3.jar
Extracted: ./apache-maven-3.5.0/lib/commons-cli.license
Extracted: ./apache-maven-3.5.0/lib/maven-core.license
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-impl.license
Extracted: ./apache-maven-3.5.0/lib/maven-slf4j-provider.license
Extracted: ./apache-maven-3.5.0/lib/slf4j-api.license
Extracted: ./apache-maven-3.5.0/lib/jansi-native/windows64/jansi.dll
Extracted: ./apache-maven-3.5.0/bin/mvnDebug
Extracted: ./apache-maven-3.5.0/boot/plexus-classworlds-2.5.2.jar
Extracted: ./apache-maven-3.5.0/lib/maven-builder-support-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/cdi-api-1.0.jar
Extracted: ./apache-maven-3.5.0/lib/guava-20.0.jar
Extracted: ./apache-maven-3.5.0/lib/commons-io.license
Extracted: ./apache-maven-3.5.0/lib/maven-builder-support.license
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-api.license
Extracted: ./apache-maven-3.5.0/lib/maven-settings-builder.license
Extracted: ./apache-maven-3.5.0/lib/maven-shared-utils.license
Extracted: ./apache-maven-3.5.0/lib/plexus-utils.license
Extracted: ./apache-maven-3.5.0/lib/jansi-native/windows32/jansi.dll
Extracted: ./apache-maven-3.5.0/bin/mvn
Extracted: ./apache-maven-3.5.0/lib/maven-embedder-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/plexus-component-annotations-1.7.1.jar
Extracted: ./apache-maven-3.5.0/lib/maven-artifact-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-api-1.0.3.jar
Extracted: ./apache-maven-3.5.0/lib/commons-cli-1.4.jar
Extracted: ./apache-maven-3.5.0/lib/jansi-1.13.jar
Extracted: ./apache-maven-3.5.0/lib/commons-lang3.license
Extracted: ./apache-maven-3.5.0/lib/maven-model.license
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-spi.license
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-util.license
Extracted: ./apache-maven-3.5.0/lib/plexus-component-annotations.license
Extracted: ./apache-maven-3.5.0/lib/jansi-native/linux32/libjansi.so
Extracted: ./apache-maven-3.5.0/conf/logging/simplelogger.properties
Extracted: ./apache-maven-3.5.0/lib/plexus-utils-3.0.24.jar
Extracted: ./apache-maven-3.5.0/lib/org.eclipse.sisu.plexus-0.3.3.jar
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-util-1.0.3.jar
Extracted: ./apache-maven-3.5.0/lib/wagon-provider-api-2.12.jar
Extracted: ./apache-maven-3.5.0/lib/maven-slf4j-provider-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/jcl-over-slf4j.license
Extracted: ./apache-maven-3.5.0/lib/jsr250-api.license
Extracted: ./apache-maven-3.5.0/lib/maven-repository-metadata.license
Extracted: ./apache-maven-3.5.0/lib/maven-settings.license
Extracted: ./apache-maven-3.5.0/lib/plexus-interpolation.license
Extracted: ./apache-maven-3.5.0/lib/jansi-native/linux64/libjansi.so
Extracted: ./apache-maven-3.5.0/conf/settings.xml
Extracted: ./apache-maven-3.5.0/lib/maven-model-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/plexus-cipher-1.7.jar
Extracted: ./apache-maven-3.5.0/lib/maven-plugin-api-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/maven-model-builder-3.5.0.jar
Extracted: ./apache-maven-3.5.0/lib/commons-io-2.5.jar
Extracted: ./apache-maven-3.5.0/lib/jcl-over-slf4j-1.7.22.jar
Extracted: ./apache-maven-3.5.0/lib/wagon-file-2.12.jar
Extracted: ./apache-maven-3.5.0/lib/maven-resolver-transport-wagon-1.0.3.jar
Attempting to build version: '1.12.2' use --rev <version> to override
Found version
{
	"name": "1404",
	"description": "Jenkins build 1404",
	"refs": {
		"BuildData": "a9c4523879abc011821f06283dd468c67c3b0097",
		"Bukkit": "4f16bdbabbad82b6130b19bcc0a4621dee83e86e",
		"CraftBukkit": "94b098085269b86ae8f926fe64e06fa3fbe6a7ca",
		"Spigot": "775423189fea374bf4f1d0391c4cf242e741185f"
	},
	"toolsVersion": 47
}

Pulling updates for /data/temp/BuildData/.git
Successfully fetched updates!
Checked out: a9c4523879abc011821f06283dd468c67c3b0097
Pulling updates for /data/temp/Bukkit/.git
Successfully fetched updates!
Checked out: 4f16bdbabbad82b6130b19bcc0a4621dee83e86e
Pulling updates for /data/temp/CraftBukkit/.git
Successfully fetched updates!
Checked out: 94b098085269b86ae8f926fe64e06fa3fbe6a7ca
Pulling updates for /data/temp/Spigot/.git
Successfully fetched updates!
Checked out: 775423189fea374bf4f1d0391c4cf242e741185f
Attempting to build Minecraft with details: VersionInfo(minecraftVersion=1.12.2, accessTransforms=bukkit-1.12.2.at, classMappings=bukkit-1.12.2-cl.csrg, memberMappings=bukkit-1.12.2-members.csrg, packageMappings=package.srg, minecraftHash=71728ed3fbd0acd1394bf3ade2649a5c, decompileCommand=java -jar BuildData/bin/fernflower.jar -dgs=1 -hdc=0 -asc=1 -udv=0 {0} {1}, serverUrl=https://launcher.mojang.com/mc/game/1.12.2/server/886945bfb2b978778c3a0288fd7fab09d315b25f/server.jar)
Starting download of https://launcher.mojang.com/mc/game/1.12.2/server/886945bfb2b978778c3a0288fd7fab09d315b25f/server.jar
Exception in thread "main" java.net.UnknownHostException: launcher.mojang.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
	at com.google.common.io.ByteSource.read(ByteSource.java:285)
	at com.google.common.io.Resources.toByteArray(Resources.java:98)
	at org.spigotmc.builder.Builder.download(Builder.java:663)
	at org.spigotmc.builder.Builder.main(Builder.java:272)
	at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:23)
```

**Comment by Kianda** [comment]
Update:

Working if I change TYPE=SPIGOT to TYPE=BUKKIT

**Comment by itzg** [comment]
Sorry, I forgot to post here, but I did recreate your issue, but apparently with a different symptom. In my case I saw some java compilation errors. Given that switching the type resolves it, my guess is that the latest Spigot code has some kind of issues. I haven't researched yet to see if they have any issues reported up stream.
