### ISSUE TITLE
ERROR failed to install forge

### ISSUE THREAD

**Issue by magicmener** [itzg/docker-minecraft-server#1814]
### Describe the problem

Cant install 1.7.10 Forge Version

### Container definition

EULA=TRUE
TYPE=FORGE
VERSION=1.7.10
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
JAVA_VERSION=jdk8u312-b07
JAVA_HOME=/opt/java/openjdk
UID=1000
GID=1000
RCON_PASSWORD=minecraft

### Container logs

ctions

      

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 6 1000 1000 4096 Nov  2 20:13 /data'

[init] Resolved version given 1.7.10 into 1.7.10 and major version 1.7

[init] Resolving type given FORGE

[mc-image-helper] 20:17:50.329 INFO  : Removing previously installed files due to version change from MC 1.12.2/Forge 14.23.5.2854 to MC 1.7.10/Forge 10.13.4.1614

[mc-image-helper] 20:17:50.337 INFO  : Downloading Forge installer 10.13.4.1614 for Minecraft 1.7.10

[mc-image-helper] 20:17:52.015 INFO  : Running Forge installer. This might take a while...

java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/minecraft_server.1.7.10.jar

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1947)

	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1942)

	at java.security.AccessController.doPrivileged(Native Method)

	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1941)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)

	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:368)

	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:356)

	at com.google.common.io.ByteStreams$6.openStream(ByteStreams.java:989)

	at com.google.common.io.ByteSource.copyTo(ByteSource.java:202)

	at com.google.common.io.Files.copy(Files.java:382)

	at net.minecraftforge.installer.DownloadUtils.downloadFileEtag(DownloadUtils.java:151)

	at net.minecraftforge.installer.ServerInstall.run(ServerInstall.java:75)

	at net.minecraftforge.installer.InstallerAction.run(InstallerAction.java:55)

	at net.minecraftforge.installer.SimpleInstaller.handleOptions(SimpleInstaller.java:93)

	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:68)

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/minecraft_server.1.7.10.jar

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1897)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)

	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3058)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:305)

	at net.minecraftforge.installer.DownloadUtils.downloadFileEtag(DownloadUtils.java:138)

	... 4 more

Downloading minecraft server failed, invalid e-tag checksum.

Try again, or manually place server jar to skip download.

There was an error during server installation

[mc-image-helper] 20:17:53.675 ERROR : 'install-forge' command failed: Forge installer failed with exit code 1

[init] ERROR failed to install forge

**Comment by itzg** [comment]
And if you had include the line above 

```
[mc-image-helper] 20:17:52.015 INFO : Running Forge installer. This might take a while...
```

you'll see that's the forge installer reporting that error. Please open an issue with Forge since I can't do anything to fix this.
