### ISSUE TITLE
Access Denied: Can't apply patches

### ISSUE THREAD

**Issue by ArikSquad** [itzg/docker-minecraft-server#1831]
### Describe the problem

I can't launch as it says Access Denied

### Container definition

```
Well I used portainer, but I added /data volume and some environments, but I am pretty sure they aren't the issue here
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 12 1000 1000 4096 Nov 18 21:36 /data'
[init] Resolved version given LATEST into 1.19.2 and major version 1.19
[init] Resolving type given PAPER
[init] Removing old PaperMC versions ...
[init] Downloading PaperMC 1.19.2 (build 271) ...
[init] Setting initial memory to 4G and max to 4G
[init] Starting the Minecraft server...
Applying patches
Failed to patch /META-INF/versions/1.19.2/server-1.19.2.jar
java.nio.file.AccessDeniedException: versions/1.19.2/paper-1.19.2.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
	at io.papermc.paperclip.PatchEntry.applyPatch(PatchEntry.java:132)
	at io.papermc.paperclip.Paperclip.applyPatches(Paperclip.java:238)
	at io.papermc.paperclip.Paperclip.extractAndApplyPatches(Paperclip.java:156)
	at io.papermc.paperclip.Paperclip.setupClasspath(Paperclip.java:72)
	at io.papermc.paperclip.Paperclip.main(Paperclip.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.papermc.paperclip.Main.main(Main.java:26)
2022-11-18T21:36:45.018+0200	WARN	mc-server-runner	Minecraft server process failed	{"exitCode": 1}
2022-11-18T21:36:45.019+0200	INFO	mc-server-runner	Done
```

**Comment by ArikSquad** [comment]
I changed all file permissions to 777
