### ISSUE TITLE
ConnectTimeoutException, cannot download the .jar at all

### ISSUE THREAD

**Issue by GodGMN** [itzg/docker-minecraft-server#1872]
### Describe the problem

Whenever I run `docker compose up` it gets stuck on the `[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Dec 22 09:10 /data'` line for several minutes. After that, this message (along with the stacktrace) appears:

```
minecraft  | [mc-image-helper] 16:51:35.089 ERROR : 'get' command failed
minecraft  | org.apache.hc.client5.http.ConnectTimeoutException: Connect to https://launchermeta.mojang.com:443 [launchermeta.mojang.com/13.107.237.43, launchermeta.mojang.com/13.107.238.43] failed: Connection timed out
``` 

After a bit of googling, I found [this issue](https://github.com/itzg/docker-minecraft-server/discussions/1343), but it doesn't seem to be my case, as I do have a properly set up connection, as I do have connectivity to the outside. However, I cannot load the launchermeta URL displayed on the error, I get this response:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. RequestId:98741a7e-101e-0017-7137-1661bf000000 Time:2022-12-22T18:59:38.6097164Z</Message>
</Error>
```

I am not sure if this issue comes from my network or if it's a missconfiguration. The parameters I used on my compose file are pretty standard and I have successfully deployed containers in the past with very similar compose files.

### Container definition

```
version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "false"
      RCON_PASSWORD: ""
      RCON_PORT: 25575
```

### Container logs

```
sergio@pve-001:~/docker/minecraft$ docker compose up
[+] Running 1/0
 ⠿ Container minecraft  Recreated                                                                                                                                                                             0.0s
Attaching to minecraft
minecraft  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Dec 22 09:10 /data'
minecraft  | [mc-image-helper] 16:51:35.089 ERROR : 'get' command failed
minecraft  | org.apache.hc.client5.http.ConnectTimeoutException: Connect to https://launchermeta.mojang.com:443 [launchermeta.mojang.com/13.107.237.43, launchermeta.mojang.com/13.107.238.43] failed: Connection timed out
minecraft  |    at org.apache.hc.client5.http.ConnectExceptionSupport.createConnectTimeoutException(ConnectExceptionSupport.java:52)
minecraft  |    at org.apache.hc.client5.http.ConnectExceptionSupport.enhance(ConnectExceptionSupport.java:74)
minecraft  |    at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
minecraft  |    at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
minecraft  |    at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
minecraft  |    at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
minecraft  |    at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
minecraft  |    at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
minecraft  |    at me.itzg.helpers.http.LatchingUrisInterceptor.execute(LatchingUrisInterceptor.java:28)
minecraft  |    at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
minecraft  |    at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
minecraft  |    at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
minecraft  |    at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:200)
minecraft  |    at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:143)
minecraft  |    at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:117)
minecraft  |    at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:424)
minecraft  |    at me.itzg.helpers.get.GetCommand.call(GetCommand.java:185)
minecraft  |    at me.itzg.helpers.get.GetCommand.call(GetCommand.java:52)
minecraft  |    at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
minecraft  |    at picocli.CommandLine.access$1300(CommandLine.java:145)
minecraft  |    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
minecraft  |    at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
minecraft  |    at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
minecraft  |    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
minecraft  |    at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
minecraft  |    at picocli.CommandLine.execute(CommandLine.java:2078)
minecraft  |    at me.itzg.helpers.McImageHelper.main(McImageHelper.java:100)
minecraft  | Caused by: java.net.ConnectException: Connection timed out
minecraft  |    at java.base/sun.nio.ch.Net.pollConnect(Native Method)
minecraft  |    at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
minecraft  |    at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
minecraft  |    at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
minecraft  |    at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
minecraft  |    at java.base/java.net.Socket.connect(Unknown Source)
minecraft  |    at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory$1.run(SSLConnectionSocketFactory.java:219)
minecraft  |    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
minecraft  |    at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:216)
minecraft  |    at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:148)
minecraft  |    ... 37 common frames omitted
minecraft  | [init] ERROR: version lookup failed:
minecraft exited with code 1
```

**Comment by itzg** [comment]
That discussion you linked is the same problem you have. (The DNS was one was not.)

As I mentioned there, it has to be something networking related within your docker environment. Perhaps post to that discussion to see if a solution was found. 

FYI the error output is misleading since it is only reporting low level network issue. It's trying to access https://launchermeta.mojang.com/mc/game/version_manifest.json

**Comment by GodGMN** [comment]
I just checked and you're right, it's a connectivity issue.

I ran a bash shell on the minecraft container and it has no connectivity to the outside, however, I checked with a freshly created Ubuntu container (`docker run -it ubuntu`) and that one did have connectivity so I'm not sure why is this happening.

Since this was happening only with your image, I thought it was a bug with some of its configuration.

However, I also tried on a different VM and it is actually working there (under the same network, subnetwork and DNS) so I am not fully sure what's the issue. I wish I knew so next time I can try to fix it.

Anyway seems like something in my docker installation is broken since I can't really think of any other reason. Both machines are running under the same hardware and using the same exact OS, installed within minutes from one another.

Thank you for taking time to respond!

**Comment by GodGMN** [comment]
An update on this for anyone potentially googling it (sorry if I'm using the github tracker improperly, I'm not used to posting there)

I booted up a brand new VM, latest Ubuntu Server, the usual installation. When I was prompted about installing extra stuff, I marked Docker, as usual. When I tried to run the container with the compose file listed on this thread, it failed. Same exact behaviour.

Then I tried yet another VM but this time I did not select Docker for the automatic installation, instead, I followed the standard procedure listed in the Docker documentation and... it worked! 

Seems like automatically installing Docker when installing Ubuntu Server does something weird with some configurations which make certain images (not sure which ones but it happens with this one) not able to connect to the internet no matter what.

**Comment by itzg** [comment]
Thanks for the update! FWIW, I always do the latter since I remember seeing the Docker docs say to uninstall the distro packages. 

I'll convert to a discussion so people can find this easier.
