### ISSUE TITLE
Minecraft Crash Report

### ISSUE THREAD

**Issue by AAlieZZ** [itzg/docker-minecraft-server#1881]
### Describe the problem

It crashes after about an hour or two of running.

### Container definition

```
docker run -d -it -p 25565:25565 -e EULA=TRUE -e GAMEMODE=creative -e ONLINE_MODE=FALSE itzg/minecraft-server
```

### Container logs

```
[21:25:17] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 9171ms or 183 ticks behind
Crash report:
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2022-12-31 21:24:12
Description: Watching Server

java.lang.Error: Watchdog
        at eat.getDouble(SourceFile:17)
        at eax.a(SourceFile:55)
        at eax.a(SourceFile:133)
        at eax$$Lambda$783/0x0000000800fa1d60.test(Unknown Source)
        at aoc.a(SourceFile:778)
        at eax.a(SourceFile:133)
        at eax.a(SourceFile:236)
        at eax.a(SourceFile:210)
        at eau.a(SourceFile:205)
        at bdr.a(SourceFile:1004)
        at bdr.a(SourceFile:990)
        at bdr.h(SourceFile:954)
        at bdr.a(SourceFile:648)
        at beg.a(SourceFile:2301)
        at beg.h(SourceFile:2246)
        at beg.b_(SourceFile:2703)
        at bei.b_(SourceFile:552)
        at beg.l(SourceFile:2404)
        at bei.l(SourceFile:352)
        at bpj.l(SourceFile:130)
        at ahm.a(SourceFile:728)
        at ahm$$Lambda$5063/0x000000080160ec60.accept(Unknown Source)
        at cjw.a(SourceFile:482)
        at ahm.a(SourceFile:374)
        at ahm$$Lambda$5039/0x00000008015de888.accept(Unknown Source)
        at dcp.a(SourceFile:54)
        at ahm.a(SourceFile:342)
        at net.minecraft.server.MinecraftServer.b(SourceFile:886)
        at agn.b(SourceFile:283)
        at net.minecraft.server.MinecraftServer.a(SourceFile:830)
        at net.minecraft.server.MinecraftServer.w(SourceFile:676)
        at net.minecraft.server.MinecraftServer.a(SourceFile:264)
        at net.minecraft.server.MinecraftServer$$Lambda$4349/0x0000000801451640.run(Unknown Source)
        at java.base@17.0.5/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
        at eat.getDouble(SourceFile:17)
        at eax.a(SourceFile:55)
        at eax.a(SourceFile:133)
        at eax$$Lambda$783/0x0000000800fa1d60.test(Unknown Source)
        at aoc.a(SourceFile:778)
        at eax.a(SourceFile:133)
        at eax.a(SourceFile:236)
        at eax.a(SourceFile:210)
        at eau.a(SourceFile:205)
        at bdr.a(SourceFile:1004)
        at bdr.a(SourceFile:990)
        at bdr.h(SourceFile:954)
        at bdr.a(SourceFile:648)
        at beg.a(SourceFile:2301)
        at beg.h(SourceFile:2246)
        at beg.b_(SourceFile:2703)
        at bei.b_(SourceFile:552)
        at beg.l(SourceFile:2404)
        at bei.l(SourceFile:352)
        at bpj.l(SourceFile:130)
        at ahm.a(SourceFile:728)
        at ahm$$Lambda$5063/0x000000080160ec60.accept(Unknown Source)
        at cjw.a(SourceFile:482)
        at ahm.a(SourceFile:374)
        at ahm$$Lambda$5039/0x00000008015de888.accept(Unknown Source)
        at dcp.a(SourceFile:54)
        at ahm.a(SourceFile:342)
        at net.minecraft.server.MinecraftServer.b(SourceFile:886)
        at agn.b(SourceFile:283)
        at net.minecraft.server.MinecraftServer.a(SourceFile:830)
        at net.minecraft.server.MinecraftServer.w(SourceFile:676)
        at net.minecraft.server.MinecraftServer.a(SourceFile:264)

-- Thread Dump --
Details:
        Threads: "Reference Handler" daemon prio=10 Id=2 RUNNABLE
        at java.base@17.0.5/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
        at java.base@17.0.5/java.lang.ref.Reference.processPendingReferences(Unknown Source)
        at java.base@17.0.5/java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)


"Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@52f6c1f6
        at java.base@17.0.5/java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@52f6c1f6
        at java.base@17.0.5/java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.base@17.0.5/java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.base@17.0.5/java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)


"Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE


"Notification Thread" daemon prio=9 Id=10 RUNNABLE


"Common-Cleaner" daemon prio=8 Id=11 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@960f441
        at java.base@17.0.5/java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@960f441
        at java.base@17.0.5/java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.base@17.0.5/jdk.internal.ref.CleanerImpl.run(Unknown Source)
        at java.base@17.0.5/java.lang.Thread.run(Unknown Source)
        at java.base@17.0.5/jdk.internal.misc.InnocuousThread.run(Unknown Source)


"DestroyJavaVM" prio=5 Id=13 RUNNABLE


"JNA Cleaner" daemon prio=5 Id=18 WAITING on java.lang.ref.ReferenceQueue$Lock@7fc321a6
        at java.base@17.0.5/java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@7fc321a6
        at java.base@17.0.5/java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.base@17.0.5/java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at com.sun.jna.internal.Cleaner$1.run(Cleaner.java:58)


"Timer hack thread" daemon prio=5 Id=19 TIMED_WAITING
        at java.base@17.0.5/java.lang.Thread.sleep(Native Method)
        at aa$9.run(SourceFile:841)


"Server thread" prio=5 Id=21 RUNNABLE
        at eat.getDouble(SourceFile:17)
        at eax.a(SourceFile:55)
        at eax.a(SourceFile:133)
        at eax$$Lambda$783/0x0000000800fa1d60.test(Unknown Source)
        at aoc.a(SourceFile:778)
        at eax.a(SourceFile:133)
        at eax.a(SourceFile:236)
        at eax.a(SourceFile:210)
        ...


"Server console handler" daemon prio=5 Id=23 RUNNABLE (in native)
        at java.base@17.0.5/java.io.FileInputStream.readBytes(Native Method)
        at java.base@17.0.5/java.io.FileInputStream.read(Unknown Source)
        at java.base@17.0.5/java.io.BufferedInputStream.read1(Unknown Source)
        at java.base@17.0.5/java.io.BufferedInputStream.read(Unknown Source)
        -  locked java.io.BufferedInputStream@1a284c6f
        at java.base@17.0.5/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at java.base@17.0.5/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at java.base@17.0.5/sun.nio.cs.StreamDecoder.read(Unknown Source)
        -  locked java.io.InputStreamReader@796d4936
        at java.base@17.0.5/java.io.InputStreamReader.read(Unknown Source)
        ...


"Netty Epoll Server IO #0" daemon prio=5 Id=24 RUNNABLE (in native)
        at io.netty.channel.epoll.Native.epollWait(Native Method)
        at io.netty.channel.epoll.Native.epollWait(Native.java:209)
        at io.netty.channel.epoll.Native.epollWait(Native.java:202)
        at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:306)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:363)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base@17.0.5/java.lang.Thread.run(Unknown Source)


"Netty Epoll Server IO #1" daemon prio=5 Id=25 RUNNABLE (in native)
        at io.netty.channel.epoll.Native.epollWait(Native Method)
        at io.netty.channel.epoll.Native.epollWait(Native.java:209)
        at io.netty.channel.epoll.Native.epollWait(Native.java:202)
        at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:306)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:363)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base@17.0.5/java.lang.Thread.run(Unknown Source)


"Netty Epoll Server IO #2" daemon prio=5 Id=26 RUNNABLE (in native)
        at io.netty.channel.epoll.Native.epollWait(Native Method)
        at io.netty.channel.epoll.Native.epollWait(Native.java:209)
        at io.netty.channel.epoll.Native.epollWait(Native.java:202)
        at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:306)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:363)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base@17.0.5/java.lang.Thread.run(Unknown Source)


"Netty Epoll Server IO #3" daemon prio=5 Id=31 RUNNABLE
        at io.netty.channel.epoll.Native.epollWait0(Native Method)
        at io.netty.channel.epoll.Native.epollWait(Native.java:182)
        at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:302)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:366)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base@17.0.5/java.lang.Thread.run(Unknown Source)


"RCON Listener #1" prio=5 Id=36 RUNNABLE
        at java.base@17.0.5/sun.nio.ch.Net.poll(Native Method)
        at java.base@17.0.5/sun.nio.ch.NioSocketImpl.park(Unknown Source)
        at java.base@17.0.5/sun.nio.ch.NioSocketImpl.timedAccept(Unknown Source)
        at java.base@17.0.5/sun.nio.ch.NioSocketImpl.accept(Unknown Source)
        at java.base@17.0.5/java.net.ServerSocket.implAccept(Unknown Source)
        at java.base@17.0.5/java.net.ServerSocket.platformImplAccept(Unknown Source)
        at java.base@17.0.5/java.net.ServerSocket.implAccept(Unknown Source)
        at java.base@17.0.5/java.net.ServerSocket.implAccept(Unknown Source)
        ...

        Number of locked synchronizers = 1
        - java.util.concurrent.locks.ReentrantLock$NonfairSync@77a178a6


"Server Watchdog" daemon prio=5 Id=37 RUNNABLE
        at java.management@17.0.5/sun.management.ThreadImpl.dumpThreads0(Native Method)
        at java.management@17.0.5/sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
        at java.management@17.0.5/sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
        at agq.run(SourceFile:47)
        at java.base@17.0.5/java.lang.Thread.run(Unknown Source)


"Worker-Main-56" daemon prio=5 Id=84 TIMED_WAITING on java.util.concurrent.ForkJoinPool@1109a9e5
        at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.ForkJoinPool@1109a9e5
        at java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkUntil(Unknown Source)
        at java.base@17.0.5/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
        at java.base@17.0.5/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base@17.0.5/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)


"Worker-Main-58" daemon prio=5 Id=86 TIMED_WAITING on java.util.concurrent.ForkJoinPool@1109a9e5
        at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.ForkJoinPool@1109a9e5
        at java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkUntil(Unknown Source)
        at java.base@17.0.5/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
        at java.base@17.0.5/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base@17.0.5/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)



Stacktrace:
        at agq.run(SourceFile:63)
        at java.base/java.lang.Thread.run(Unknown Source)

-- Performance stats --
Details:
        Random tick rate: 3
        Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 0, entities: 189,189,132,529,529,0,0 [minecraft:chest_minecart:32,minecraft:skeleton:23,minecraft:creeper:23,minecraft:zombie:16,minecraft:bat:16], block_entities: 64 [minecraft:mob_spawner:60,<null>:3,minecraft:furnace:1], block_ticks: 262, fluid_ticks: 5256, chunk_source: Chunks[S] W: 2209 E: 189,189,132,529,529,0,0,
ResourceKey[minecraft:dimension / minecraft:the_end]: players: 0, entities: 0,0,0,0,0,0,0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: Chunks[S] W: 0 E: 0,0,0,0,0,0,0,
ResourceKey[minecraft:dimension / minecraft:the_nether]: players: 0, entities: 0,0,0,0,0,0,0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: Chunks[S] W: 0 E: 0,0,0,0,0,0,0

-- System Details --
Details:
        Minecraft Version: 1.19.3
        Minecraft Version ID: 1.19.3
        Operating System: Linux (amd64) version 5.10.0-19-amd64
        Java Version: 17.0.5, Eclipse Adoptium
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
        Memory: 369889928 bytes (352 MiB) / 1037959168 bytes (989 MiB) up to 1037959168 bytes (989 MiB)
        CPUs: 2
        Processor Vendor: GenuineIntel
        Processor Name: Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
        Identifier: Intel64 Family 6 Model 85 Stepping 7
        Microarchitecture: Cascade Lake
        Frequency (GHz): 2.50
        Number of physical packages: 1
        Number of physical CPUs: 1
        Number of logical CPUs: 2
        Graphics card #0 name: unknown
        Graphics card #0 vendor: unknown
        Graphics card #0 VRAM (MB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: unknown
        Virtual memory max (MB): 859.57
        Virtual memory used (MB): 1702.44
        Swap memory total (MB): 0.00
        Swap memory used (MB): 0.00
        JVM Flags: 2 total; -Xmx1G -Xms1G
        Server Running: true
        Player Count: 0 / 20; []
        Data Packs: vanilla
        Enabled Feature Flags: minecraft:vanilla
        World Generation: Stable
        Is Modded: Probably not. Server jar signature and brand is untouched
        Type: Dedicated Server (map_server.txt)
[21:30:24] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 292363ms or 5847 ticks behind
[21:30:48] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2016ms or 40 ticks behind
[21:31:07] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2778ms or 55 ticks behind
[21:31:26] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2443ms or 48 ticks behind
[21:31:48] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2822ms or 56 ticks behind
[21:32:06] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2684ms or 53 ticks behind
[21:32:16] [Server Watchdog/ERROR]: This crash report has been saved to: /data/./crash-reports/crash-2022-12-31_21.26.52-server.txt
[21:32:25] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2523ms or 50 ticks behind
[21:34:12] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 92217ms or 1844 ticks behind
[21:35:20] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2572ms or 51 ticks behind
[21:36:31] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 56405ms or 1128 ticks behind
[21:37:04] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 17419ms or 348 ticks behind
2022-12-31T21:37:50.327Z        WARN    mc-server-runner        Minecraft server process failed       {"exitCode": 1}
2022-12-31T21:37:50.577Z        INFO    mc-server-runner        Done
```

**Comment by itzg** [comment]
Crash reports need to be addressed by Mojang. This image only automates the startup of the server and has no involvement in ongoing execution.
