### ISSUE TITLE
Type of "AUTO_CURSEFORGE" fails to start 'All of Fabric 6' CurseForge server pack

### ISSUE THREAD

**Issue by Ogloppi** [itzg/docker-minecraft-server#1891]
### Describe the problem

_All of Fabric 6_ offers separate server pack downloads, thus I used the provided server pack download: https://www.curseforge.com/minecraft/modpacks/all-of-fabric-6/files/4325309
As seen from the logs, the Docker image can't find `manifest.json` it requires.

However, the server pack in question does not include any `manifest.json` file in its CurseForge download.
You can find a file called `server-setup-config.yaml` inside the downloaded server pack, and further inside this file it includes a link to the actual server modpack: `modpackUrl: https://media.forgecdn.net/files/4325/308/All-of-Fabric-6-1.2.2.zip`

Is the `server-setup-config.yaml --> modpackUrl` the actual link that I'm supposed to provide for `CF_PAGE_URL`?

### Container definition

In `docker-compose.yml`:

```
version: "2.1"
  services:
    minecraft_aof6:
      image: itzg/minecraft-server:java17
      container_name: minecraft_aof6
      volumes:
        - ./Minecraft/AoF6/data:/data
      networks:
        - minecraft
      environment:
        - TYPE=AUTO_CURSEFORGE
        - CF_BASE_DIR=/data
        - CF_PAGE_URL=https://www.curseforge.com/minecraft/modpacks/all-of-fabric-6/files/4325309
        - INIT_MEMORY="3G"
        - MAX_MEMORY="6G"
        - EULA=true
      ports:
        - "12345:25565"
      restart: unless-stopped
```

Start container with `docker-compose up -d minecraft_aof6`

### Container logs

```
[init] 2023-01-10 18:01:30+02:00 Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 17 1000 1000 4096 Jan 10 18:00 /data'
[init] 2023-01-10 18:01:31+02:00 Resolved version given LATEST into 1.19.3 and major version 1.19
[init] 2023-01-10 18:01:31+02:00 Starting RCON commands
[init] 2023-01-10 18:01:31+02:00 Rcon cmds functionality enabled
[init] 2023-01-10 18:01:31+02:00 Resolving type given AUTO_CURSEFORGE
[mc-image-helper] 18:01:32.478 INFO  : Processing modpack All of Fabric 6 Server - 1.2.2 @ 695890:4325309
[mc-image-helper] 18:01:32.991 ERROR : 'install-curseforge' command failed
me.itzg.helpers.errors.GenericException: Modpack is missing manifest.json
        at me.itzg.helpers.curseforge.CurseForgeInstaller.extractModpackManifest(CurseForgeInstaller.java:285)
        at me.itzg.helpers.curseforge.CurseForgeInstaller.processModpackFile(CurseForgeInstaller.java:166)
        at me.itzg.helpers.curseforge.CurseForgeInstaller.processMod(CurseForgeInstaller.java:104)
        at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:70)
        at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:68)
        at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:104)
[init] 2023-01-10 18:01:33+02:00 ERROR failed to auto-install CurseForge modpack
```

**Comment by itzg** [comment]
I need to add better detection for this scenario, but with `AUTO_CURSEFORGE` you actually should **not** reference the server files. Instead, reference the non-server file https://www.curseforge.com/minecraft/modpacks/all-of-fabric-6/files/4325308 .

**Comment by tmkempster** [comment]
@itzg I have tried referencing the ATM pack per the docs for ATM8 1.0.8 referencing by both the CF_FILE_ID=4322138 and also using CF_FILENAME_MATCHER=1.0.8 - it appears that it grabs all the mods from the manifest which also include client side mods (specifically oculus) which results in errors. Commenting on here because it seems related.

Stacktrace below:


Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.3-universal.jar%23764!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.2.3-universal.jar%23764!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23759!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.3.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.2.3.jar%2367!/:1.0] {}
-- MOD oculus --
Details:
	Mod File: /data/mods/oculus-mc1.19.2-1.2.8a.jar
	Failure message: Oculus (oculus) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
	Mod Version: 1.2.8a
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.2.3.jar%2367!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:?] {re:mixin}
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:?] {re:mixin}
	at java.lang.Class.getDeclaredConstructor(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.3.jar%23761!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.3.jar%23760!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

**Comment by itzg** [comment]
Thanks for the update. I'll fix that also.

**Comment by itzg** [comment]
@tmkempster please open a new issue. I just noticed yours is different pack and different symptom than the original.

**Comment by itzg** [comment]
The latest image should now resolve this.

**Comment by Ogloppi** [comment]
Thanks for taking a look at this problem.
I tested this with the following workflow:

- Created a new fresh _All of Fabric 6_ version v1.2.2 server with the same `docker-compose.yml` as in [my first message](https://github.com/itzg/docker-minecraft-server/issues/1891#issue-1527732612), except without `CF_PAGE_URL` and with the following variables:
`TYPE=AUTO_CURSEFORGE` `CF_SLUG=all-of-fabric-6` `CF_FILE_ID=4325308`
  - Do note that `CF_FILE_ID=4325308` references the client files and _**not**_ the server files that _All of Fabric 6_ provides on their CurseForge page. This was done as suggested by @itzg.
- Start up the server with `docker-compose up -d minecraft_aof6`
- Install _All of Fabric 6_ v1.2.2 modpack to `PolyMC` and start it up.
- Connect to server. No issues and Minecraft client does not report any mod mismatch between client and server.
- Shutdown client and Docker-server.
- Modify `CF_FILE_ID=4325308` to `CF_FILE_ID=4338947` (this references All of Fabric 6 - v1.3.0 client files) in `docker-compose.yml`.
- Start server again with `docker-compose up -d minecraft_aof6`
- Install _All of Fabric 6_ v1.3.0 modpack to `PolyMC` and start it up.
- Connect to server. No issues and Minecraft client does not report any mod mismatch between client and server.
  - World data etc. seems to be fine and preserved.

In my opinion, `TYPE=AUTO_CURSEFORGE` seems to work.
I read through Docker log files and `itzg/mc-image-helper` seems to handle deleting/updating/preserving of server files automatically between updates. Neat!

**Comment by itzg** [comment]
Thanks for the thorough testing @Ogloppi !

> I read through Docker log files and itzg/mc-image-helper seems to handle deleting/updating/preserving of server files automatically between updates. Neat!

Thanks. I was really proud of getting that capability in there.

**Comment by Ogloppi** [comment]
Oh right, I'll close this issue.
