### ISSUE TITLE
Forge 1.7.10 Failed to Istall

### ISSUE THREAD

**Issue by Waschke1994** [itzg/docker-minecraft-server#1908]
### Describe the problem

Hello, i try to start container with docker-compose but the "instalation" fails every time. Anyone got the same problem or has anyone found a solution.

### Container definition

```
version: "3"
networks:
  minecraft:
services:
  minecraft-forge:
    networks:
      - minecraft
    image: itzg/minecraft-server:java8-openj9
    container_name: minecraft-lotr
    environment:
      EULA: "TRUE"
      # V---- WICHTIG ANPASSEN Installer muss manuell in das Verzeichnis kopiert werden !!!!!
      TYPE: FORGE
      VERSION: 1.7.10
      FORGE_INSTALLER: forge-1.7.10-10.13.4.1614-installer.jar
      CF_BASE_DIR: /data
      # V---- WICHTIG ANPASSEN !!!!!
      LANG: en_US.UTF-8
      LANGUAGE: eb_US:en
      LC_ALL: en_US.UTF-8
      # V---- WICHTIG ANPASSEN !!!!!
      UID: 1006
      # V---- WICHTIG ANPASSEN !!!!!
      GID: 2000
      RCON_PASSWORD: minecraft
      PATH: /opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      JAVA_HOME: /opt/java/openjdk
      TZ: Europe/Berlin
      # V---- WICHTIG ANPASSEN !!!!!
      MEMORY: 8G
    ports:
      # V---- WICHTIG ANPASSEN !!!!!
      - "25765:25765"
    volumes:
      # V---- WICHTIG ANPASSEN !!!!!
      - /docker/LordOfTheRingsMP:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

```

### Container logs

```
[init] Changing uid of minecraft to 1006
[init] Changing gid of minecraft to 2000
[init] Running as uid=1006 gid=2000 with /data as 'drwxrwsr-x+ 5 1006 2000 4096 Jan 15 19:51 /data'
[init] Resolved version given 1.7.10 into 1.7.10 and major version 1.7
[init] Resolving type given FORGE
[mc-image-helper] 19:52:16.801 INFO  : Running Forge installer. This might take a while...
[mc-image-helper] 19:52:18.093 ERROR : 'install-forge' command failed
java.lang.NullPointerException: null
	at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:226)
	at me.itzg.helpers.forge.ForgeInstaller.installUsingExisting(ForgeInstaller.java:147)
	at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:103)
	at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:65)
	at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:14)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:104)
[init] ERROR failed to install Forge given installer forge-1.7.10-10.13.4.1614-installer.jar
```

**Comment by itzg** [comment]
Thanks for reporting this. I'll look into it since it was broken with something I did yesterday.

**Comment by itzg** [comment]
This build should include the fix, but let me know if it doesn't help

https://github.com/itzg/docker-minecraft-server/actions/runs/3925265985

**Comment by Waschke1994** [comment]
Yes, it works, deleted persistent images and pulled new. :) thank you
