### ISSUE TITLE
Failed to install Forge

### ISSUE THREAD

**Issue by AndrewTevebaugh** [itzg/docker-minecraft-server#1916]
### Describe the problem

Starting up a new modpack so I am using this image again, but when I try to launch, container gets stuck trying to install the forge installer. I may be doing this incorrectly, but right now I have my docker-compose file linked to a directory that already has all the server files. There does not seem to be an issue with the backups, just kept it in there for the sake of not leaving anything out.

### Container definition

version: "3.8"

services:
  NewHorizons:
    hostname: NewHorizons
    image: itzg/minecraft-server:${IMAGE_TAG:-java8}
    ports:
      - 25566:25566
    environment:
      SERVER_PORT: 25566
      RCON_PORT: 25576
      MEMORY: 6G
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: 1.7.10
      MOTD: Greg
      ENABLE_RCON: "true"
      RCON_PASSWORD: <mypassword>
      TZ: "America/New_York"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /mnt/NewHorizons/NewHorizons:/data
  NewHorizonsBackups:
    hostname: NewHorizonsBackups
    image: itzg/mc-backup
    environment:
      SERVER_PORT: 25566
      RCON_HOST: NewHorizons
      RCON_PORT: 25576
      RCON_PASSWORD: <mypassword>
      BACKUP_INTERVAL: "4h"
      TZ: "America/New_York"
      PAUSE_IF_NO_PLAYERS: true
      BACKUP_METHOD: restic
      RESTIC_PASSWORD: password
      RESTIC_REPOSITORY: /backups
      PRUNE_RESTIC_RETENTION: "--keep-hourly 1 --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75"
    volumes:
      - /mnt/NewHorizons/NewHorizons:/data:ro
      - /mnt/NewHorizons/NewHorizons-Backups:/backups
        #network_mode: "service:NewHorizons"
    restart: unless-stopped
                           

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 8 1000 1000 4096 Jan 19 23:58 /data'

[init] Resolved version given 1.7.10 into 1.7.10 and major version 1.7

[init] Resolving type given FORGE

[mc-image-helper] 00:01:44.544 INFO  : Downloading Forge installer 10.13.4.1614 for Minecraft 1.7.10

[mc-image-helper] 00:01:44.683 ERROR : 'install-forge' command failed. Version is 1.24.12

me.itzg.helpers.errors.GenericException: Unexpected content type in response

        at me.itzg.helpers.http.SpecificFileFetchBuilder.lambda$assemble$5(SpecificFileFetchBuilder.java:123)

        at reactor.netty.http.client.HttpClientFinalizer.lambda$responseSingle$6(HttpClientFinalizer.java:121)

        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)

        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)

        at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)

        at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:172)

        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:431)

        at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:710)

        at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:195)

        at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:456)

        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:647)

        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)

        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)

        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)

        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)

        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)

        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)

        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)

        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)

        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)

        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)

        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)

        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)

        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)

        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)

        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)

        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)

        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)

        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)

        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)

        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)

        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

        at java.lang.Thread.run(Thread.java:748)

        Suppressed: java.lang.Exception: #block terminated with an error

                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)

                at reactor.core.publisher.Mono.block(Mono.java:1710)

                at me.itzg.helpers.http.SpecificFileFetchBuilder.execute(SpecificFileFetchBuilder.java:65)

                at me.itzg.helpers.forge.ForgeInstaller.downloadInstaller(ForgeInstaller.java:293)

                at me.itzg.helpers.forge.ForgeInstaller.downloadAndInstall(ForgeInstaller.java:167)

                at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:100)

                at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:65)

                at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:14)

                at picocli.CommandLine.executeUserObject(CommandLine.java:2041)

                at picocli.CommandLine.access$1500(CommandLine.java:148)

                at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)

                at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)

                at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)

                at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)

                at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)

                at picocli.CommandLine.execute(CommandLine.java:2170)

                at me.itzg.helpers.McImageHelper.main(McImageHelper.java:104)

[init] ERROR failed to install Forge

**Comment by AndrewTevebaugh** [comment]
I'm not sure why it formatted the logs like that

**Comment by itzg** [comment]
Thanks for reporting this. It fails for me too -- something about the URL it tries is not correct.

**Comment by AndrewTevebaugh** [comment]
Is there a way I can circumvent the container installing forge itself? When I downloaded the server files it seems to already have a forge jar file and ready to run.

**Comment by itzg** [comment]
You could use `TYPE=CUSTOM` and set the `SERVER` to the existing one.

Also, I should have the fix up in 15 minutes or so.
