### ISSUE TITLE
ERROR failed to auto-install CurseForge modpack

### ISSUE THREAD

**Issue by FabMaster2000** [itzg/docker-minecraft-server#1986]
### Describe the problem

I want to create a SkyFactory 4 Server with the following command:

docker run -d -it -p 25565:25565 --name SkyFactory -e EULA=TRUE  -e MEMORY=2G -e VIEW_DISTANCE=10 -e TYPE=AUTO_CURSEFORGE -e CF_PAGE_URL=https://www.curseforge.com/minecraft/modpacks/skyfactory-4/files/3565683 -e VERSION=1.12.2 itzg/minecraft-server

After some modpacks are successful downloaded the following error message occure:

[mc-image-helper] 14:10:58.887 WARN  : [a13ebe68, L:/172.17.0.2:51750 - R:api.curse.tools/188.114.97.3:443] The connection observed an error
io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
        at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2115)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
[mc-image-helper] 14:10:58.896 ERROR : 'install-curseforge' command failed. Version is 1.24.19
reactor.core.Exceptions$ReactiveException: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
        at reactor.core.Exceptions.propagate(Exceptions.java:408)
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
        at reactor.core.publisher.Mono.block(Mono.java:1710)
        at me.itzg.helpers.curseforge.CurseForgeInstaller.processModpackZip(CurseForgeInstaller.java:319)
        at me.itzg.helpers.curseforge.CurseForgeInstaller.downloadAndProcessModpackZip(CurseForgeInstaller.java:271)
        at me.itzg.helpers.curseforge.CurseForgeInstaller.processModPack(CurseForgeInstaller.java:185)
        at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:124)
        at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:137)
        at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:121)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                ... 16 common frames omitted
Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
        at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2115)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
[init] ERROR failed to auto-install CurseForge modpack

**Comment by itzg** [comment]
...and if it persists, you can set `FETCH_TLS_HANDSHAKE_TIMEOUT` to a longer duration like "PT40S"

**Comment by FabMaster2000** [comment]
> ...and if it persists, you can set FETCH_TLS_HANDSHAKE_TIMEOUT to a longer duration like "PT40S"


so I could have the following command?:

docker run -d -it -p 25565:25565 --name SkyFactory -e EULA=TRUE -e MEMORY=2G -e VIEW_DISTANCE=10 -e FETCH_TLS_HANDSHAKE_TIMEOUT="PT40S" -e TYPE=AUTO_CURSEFORGE -e CF_PAGE_URL=https://www.curseforge.com/minecraft/modpacks/skyfactory-4/files/3565683 -e VERSION=1.12.2 itzg/minecraft-server

**Comment by itzg** [comment]
You can also set `FETCH_RESPONSE_TIMEOUT` to something longer than the default PT20S. Your network seems to be suboptimal, so I would recommend also looking into that unless you are already aware of it.

**Comment by RazeLighter777** [comment]
Hey this is an MTU issue. I fixed this by setting my docker MTU lower. I set mine to 800.

**Comment by RazeLighter777** [comment]
For docker compose I added the following options
```
networks:
  minecraft:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 800
```

And added

```
    networks:
      - minecraft
```
To the container

**Comment by FabMaster2000** [comment]
> For docker compose I added the following options
> 
> ```
> 
> networks:
> 
>   minecraft:
> 
>     driver: bridge
> 
>     driver_opts:
> 
>       com.docker.network.driver.mtu: 800
> 
> ```
> 
> 
> 
> And added
> 
> 
> 
> ```
> 
>     networks:
> 
>       - minecraft
> 
> ```
> 
> To the container



Thanks a lot. I will try it in a few days :)

**Comment by FabMaster2000** [comment]
After adding the line which is explained by the following lines:
https://github.com/itzg/docker-minecraft-server#fixing-unable-to-launch-forgemodloader


The modpacks were installed. But at starting the server after that, the following error occured:

```
[mc-image-helper] 11:04:10.688 INFO  : Downloaded mod file mods/rftoolspower-1.12-1.2.0.jar
[mc-image-helper] 11:04:11.399 INFO  : Downloading Forge installer 14.23.5.2860 for Minecraft 1.12.2
[mc-image-helper] 11:04:13.951 INFO  : Running Forge installer. This might take a while...
[init] Creating server properties in /data/server.properties
[init] Disabling whitelist functionality
[init] Setting initial memory to 2G and max to 2G
[init] Starting the Minecraft server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
```

**Comment by itzg** [comment]
You're using the wrong Java version. Refer to 

https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version

**Comment by FabMaster2000** [comment]
> You're using the wrong Java version. Refer to
> 
> https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version

Oh, doesn't mentioned that. I will try it with java8 / java8-multiarch

**Comment by itzg** [comment]
Ah, I actually am missing a check and warning for non-Java 8 with TYPE=AUTO_CURSEFORGE. I'll fix that. 

Otherwise, yes, I do wish the Minecraft software would fail more gracefully with a version mismatch.

**Comment by itzg** [comment]
Sure. There's always the old CurseForge mechanism and can fallback to generic pack if the server mod pack is "broken" like most.

**Comment by matthip04** [comment]
Hi, sorry for "reopening" the old case. I have the same issue, but this Link: 
https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version 
is just refering to the startpage of the itzg Minecraft Server. It can be that i am dumb, but i dont know where i should land.

**Comment by itzg** [comment]
@Louis5487 I know stack traces all look like piles of noise, but you don't have the same  problem. There is something not working with your DNS

```
DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'mediafilez.forgecdn.net' [A(1)] and search domain query for configured domains failed as well: [voo.be]
```
