### ISSUE TITLE
Mod download circular redirect

### ISSUE THREAD

**Issue by yurisasc** [itzg/docker-minecraft-server#2001]
### Describe the problem

I downloaded a mod from CurseForge and reuploaded it to my dropbox because I was not sure how to get the direct download URL from there. The link for the mod is https://www.dropbox.com/s/aeeudyxlm9q7hxo/villagernames-1.19.3-4.5.1.jar?dl=1. I got an error, as provided in the log.

### Container definition

```
docker run -d -it -p 25565:25565 \
-e EULA=TRUE \
-e TYPE=FABRIC \
-e MODS="https://www.dropbox.com/s/aeeudyxlm9q7hxo/villagernames-1.19.3-4.5.1.jar?dl=1" \
itzg/minecraft-server
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Mar  4 15:46 /data'
[init] Resolved version given LATEST into 1.19.3 and major version 1.19
[init] Resolving type given FABRIC
[mc-image-helper] 23:45:28.062 INFO  : Installing Fabric Versions(game=1.19.3, loader=0.14.17, installer=0.11.2)
[init] Downloading mod/plugin https://www.dropbox.com/s/aeeudyxlm9q7hxo/villagernames-1.19.3-4.5.1.jar?dl=1 ...
[mc-image-helper] 23:45:30.473 INFO  : Recoverable I/O exception (org.apache.hc.core5.http.MessageConstraintException) caught when processing request to {s}->https://www.dropbox.com:443
[mc-image-helper] 23:45:30.954 ERROR : 'get' command failed. Version is 1.25.11
org.apache.hc.client5.http.ClientProtocolException: Circular redirect to 'https://www.dropbox.com/s/dl/aeeudyxlm9q7hxo/villagernames-1.19.3-4.5.1.jar'
at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:173)
at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
at me.itzg.helpers.get.GetCommand.needsDownload(GetCommand.java:333)
at me.itzg.helpers.get.GetCommand.processUrisForDirectory(GetCommand.java:301)
at me.itzg.helpers.get.GetCommand.call(GetCommand.java:196)
at me.itzg.helpers.get.GetCommand.call(GetCommand.java:53)
at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
at picocli.CommandLine.execute(CommandLine.java:2170)
at me.itzg.helpers.McImageHelper.main(McImageHelper.java:123)
Caused by: org.apache.hc.client5.http.CircularRedirectException: Circular redirect to 'https://www.dropbox.com/s/dl/aeeudyxlm9q7hxo/villagernames-1.19.3-4.5.1.jar'
at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:143)
at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at me.itzg.helpers.http.LatchingUrisInterceptor.execute(LatchingUrisInterceptor.java:27)
at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
... 16 common frames omitted
[init] ERROR: failed to download from https://www.dropbox.com/s/aeeudyxlm9q7hxo/villagernames-1.19.3-4.5.1.jar?dl=1 into /data/mods
```

**Comment by yurisasc** [comment]
I did a quick google search on how to do a direct download from CurseForge. Using this download URL instead seems to get around that error:
https://media.forgecdn.net/files/4426/546/villagernames-1.19.3-4.5.1.jar
