### ISSUE TITLE
ERROR : 'install-forge' command failed when specifying FORGE_INSTALLER

### ISSUE THREAD

**Issue by qibao07** [itzg/docker-minecraft-server#2011]
### Describe the problem

Everything used to work fine until the new image was pulled.

When I execute "docker pull itzg/minecraft-server:java8-multiarch", and then restart, the problem occurs.

It is normal to use old image by imageID.

### Container definition

```
  docker run -d -it \
    --name $SERVER_NAME \
    -v $(pwd)/data:/data \
    -e TZ=Asia/Shanghai \
    -e TYPE=FORGE \
    -e VERSION=1.12.2 \
    -e FORGE_INSTALLER=forge-1.12.2-14.23.5.2855-installer.jar \
    -e EULA=TRUE \
    -e ONLINE_MODE=FALSE \
    -e MEMORY=4G \
    -p $MC_PORT:25565 \
    itzg/minecraft-server:java8-multiarch
```

### Container logs

```
+ mc-image-helper install-forge --output-directory=/data --results-file=/data/.run-forge.env --minecraft-version=1.12.2 --forge-installer=forge-1.12.2-14.23.5.2855-installer.jar --force-reinstall=false
[mc-image-helper] 21:19:31.427 DEBUG : JSON FETCH: uri=https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json headers=DefaultHttpHeaders[user-agent: mc-image-helper/1.25.12 (cmd=forge), x-fetch-session: 6a9778d4-7e93-4aa1-b9bd-5641357652a2, accept: application/json, host: files.minecraftforge.net]
[mc-image-helper] 21:19:34.542 DEBUG : JSON FETCH: uri=https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json headers=DefaultHttpHeaders[user-agent: mc-image-helper/1.25.12 (cmd=forge), x-fetch-session: 6a9778d4-7e93-4aa1-b9bd-5641357652a2, accept: application/json, host: files.minecraftforge.net]
[mc-image-helper] 21:19:35.055 INFO  : Running Forge installer. This might take a while...
[mc-image-helper] 21:19:39.073 DEBUG : Deleting Forge installer log at /data/forge-1.12.2-14.23.5.2855-installer.jar.log
[mc-image-helper] 21:19:39.075 ERROR : 'install-forge' command failed. Version is 1.25.12
me.itzg.helpers.errors.GenericException: Unable to locate forge server jar
        at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:264)
        at me.itzg.helpers.forge.ForgeInstaller.installUsingExisting(ForgeInstaller.java:157)
        at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:113)
        at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:84)
        at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:16)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:132)
+ log 'ERROR failed to install Forge given installer forge-1.12.2-14.23.5.2855-installer.jar'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2023-03-16 21:19:39+08:00 ERROR failed to install Forge given installer forge-1.12.2-14.23.5.2855-installer.jar
+ exit 1
```

**Comment by qibao07** [comment]
@itzg 
As you said, the problem is gone. Thanks! 🙏
