### ISSUE TITLE
ERROR failed to auto-install CurseForge modpack.... No mods found with slug

### ISSUE THREAD

**Issue by doctorangu** [itzg/docker-minecraft-server#2037]
Hi together,

We try to run a docker container with a self-made and approved modpack that can be seen in the Curseforge modpack library, but we get an error message. Trying it with a different modpack, and it works.

Here's our command that we use:
docker run -d -v /home/thomas/minecraft/data:/data -v /home/thomas/minecraft/modpack:/modpacks \
    -e TYPE=AUTO_CURSEFORGE \
    -e MEMORY=6G \
    -e CF_SLUG=tandb-just-some-adds \
    -p 25565:25565 -e EULA=TRUE --name mc_TandB itzg/minecraft-server

Here's the error message:
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-- 19 1000 1000 4096 Mar 27 07:41 /data'
[init] Resolved version given LATEST into 1.19.4 and major version 1.19
[init] Resolving type given AUTO_CURSEFORGE
[mc-image-helper] 09:46:28.144 ERROR : 'install-curseforge' command failed. Version is 1.25.16
me.itzg.helpers.errors.GenericException: No mods found with slug={}tandb-just-some-adds
    at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:126)
    at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:145)
    at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:23)
    at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
    at picocli.CommandLine.access$1500(CommandLine.java:148)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
    at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
    at picocli.CommandLine.execute(CommandLine.java:2170)
    at me.itzg.helpers.McImageHelper.main(McImageHelper.java:132)
[init] ERROR failed to auto-install CurseForge modpack

Any clues?

Thanks, Best regards

**Comment by itzg** [comment]
The API provider seems to be caching too aggressively since

https://api.curse.tools/v1/cf/mods/search?gameId=432&slug=tandb-just-some-adds&classId=4471

is reporting an empty list. I'll have to add a "cache buster" query parameter to this one like I needed to for file listings.

**Comment by thomas41587** [comment]
@itzg what does this mean for now? Is there a possibility to manually refresh the cache? Or does the cache automatically refresh every night?

**Comment by itzg** [comment]
I'm sorry, I should have clarified: it means we're stuck until I can adjust the mc-image-helper code to call their API with a query parameter that forces it to not cache.

I'm actually not sure what their caching lifetime seems to be, but from similar scenarios it seems to be quite long or "forever".

**Comment by doctorangu** [comment]
thank you ! that was quick!
