### ISSUE TITLE
If failure to auto-install CurseForge modpack, should continue if existing modpack already installed.

### ISSUE THREAD

**Issue by camalot** [itzg/docker-minecraft-server#2041]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Server should try to use existing mod-packs installed if attempts to install mod-pack on startup fails (maybe with environment flag?)

Use case:
Curse API (via cloudflare) is returning a 502 Bad Gateway after restarting the server and now server will not start up.

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 21 1000 1000 4096 Mar 28 16:55 /data'
[init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
[init] Resolving type given AUTO_CURSEFORGE
[mc-image-helper] 08:36:28.772 ERROR : 'install-curseforge' command failed. Version is 1.25.19
me.itzg.helpers.http.FailedRequestException: HTTP request of https://api.curse.tools/v1/cf/mods/search?gameId=432&slug=all-the-mods-8&classId=4471&latest=5600323 failed with 502 Bad Gateway: Fetching object content
	at me.itzg.helpers.http.FetchBuilderBase.lambda$failedRequestMono$1(FetchBuilderBase.java:151)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:128)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:193)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:431)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:485)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:712)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1382)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1245)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1294)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1710)
		at me.itzg.helpers.http.ObjectFetchBuilder.execute(ObjectFetchBuilder.java:34)
		at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:128)
		at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:145)
		at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:23)
		at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
		at picocli.CommandLine.access$1500(CommandLine.java:148)
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
		at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
		at picocli.CommandLine.execute(CommandLine.java:2170)
		at me.itzg.helpers.McImageHelper.main(McImageHelper.java:132)
[init] ERROR failed to auto-install CurseForge modpack

```

**Comment by Rayvhiz** [comment]
I have the same prolem.

**Comment by camalot** [comment]
I just looked at `curse.tools`, that claims to be a "drop in replacement" for the CurseForge API, so my initial thought was: easy, I will just add a CNAME entry in my DNS... except their API url adds `/cf` after the `/v1`. So, while I could probably put in an nginx proxy to just handle the `api.curse.tools` requests, and send them off to the actual CF api, that seems like more work than what I want to do just because the `curse.tools` is having service issues. But it did aggravate me that they call it a "drop in replacement", and it is not.

**Comment by camalot** [comment]
Fallback to the curseforge api sounds like a possibility to fix the currently experienced issue, since curse.tools is down.

Maybe a config value to specify what endpoint to use. 

UNSET uses default configured.
"CURSEFORGE"
"CURSE_TOOLS"

**Comment by itzg** [comment]
> An alternative solution might be to fall back to the real CurseForge API instead of curse.tools ?

That is non-trivial since CurseForge requires an API key. If everyone doesn't mind allocating their own key, then that kind of switch gets easier.

> But it did aggravate me that they call it a "drop in replacement", and it is not.

It is a drop-in replacement -- it just didn't conform to your definition.

A longer term solution will be to stand up my own proxy with my own API key and run the risk of getting flagged by CurseForge.

**Comment by camalot** [comment]
I did not realize that curse.tools removes the need for needing an API key. That does make things more difficult.

**Comment by camalot** [comment]
Is there a short term solution? is there a way to bypass having it trying to install the modpack, since one is already installed?

**Comment by xicrow** [comment]
Is the CurseForge API free (just need to register) or how does that work ?

One solution could be an option to force using CurseForge API, but then also have to provide an API key.

But I'm also voting for the solution Camelot suggested, to either have a config to bypass the check, or simply not checking for updates if API can't be reached.

I'm not sure what's better or easier to implement ?

**Comment by itzg** [comment]
As far as easier, it would be easier to switch https://github.com/itzg/mc-image-helper/blob/master/src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java over to using CurseForge API directly and requiring an API key from each user.

The API keys are free, just an extra/annoying step that would be needed for each user.

**Comment by itzg** [comment]
...at the same time, if both the project slug and exact file ID are provided, then I'm thinking this lookup

https://github.com/itzg/mc-image-helper/blob/cea415c1902cd8c423f67e6ea09cba44fd70f1cb/src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java#L120-L128

could possibly be skipped, but I'm not totally sure since I must have put it that early for some reason.

**Comment by camalot** [comment]
https://github.com/itzg/docker-minecraft-server/issues/1576

"however, the code changes should allow for easily switching back if that proxy service goes away." 😄 at least you knew it would be a problem eventually 🤣

**Comment by Goten87** [comment]
why is it checking on startup to the api if the pack is fully installed i think this needs to be skipped exept if we want to check it
maby for now a skip-check argument in the docker file will be nice so that people who still have the pack can still run it

**Comment by camalot** [comment]
I get why it checks, because it updates the modpack if it is set to do that by just using a slug and such. but, if that check fails, it should fail gracefully, and just continue, logging that it failed to hit the api and is loading the existing modpack.

**Comment by itzg** [comment]
Right. In general it's 
- performing an up to date check, if a file ID/matcher was not provided
- resolving identifiers so that it can compare with the manifest file to see if that is already what is installed

So, sounds like there's these pieces to the near term fix:
- use CurseForge API directly, requiring API key
- if no API key is provided, but any kind of manifest is present, then log a warning and continue anyway

**Comment by camalot** [comment]
For informational purposes:

If you want to get an API Key from CurseForge, here is their [Support Documentation](https://support.curseforge.com/en/support/solutions/articles/9000208346-about-the-curseforge-api-and-how-to-apply-for-a-key) on doing so.

Specifically the **How to Apply for an API Key** is the important part of the documentation on obtaining an API key.

**Comment by AerikAwesome** [comment]
Is there a quick/easy way to switch from an existing AUTO_CURSEFORGE container, with all the mods etc already downloaded and installed, to a type that doesn't do this check? Or am I better off just waiting for this to be fixed?

**Comment by itzg** [comment]
Good question @AerikAwesome . I think it'll work to set TYPE to "FORGE" along with VERSION and FORGE_VERSION to match what was auto installed.

**Comment by camalot** [comment]
Confirmed Temporary Workaround ✅

Set the following to the versions you need. In this case I have ATM8 1.0.15, Minecraft version 1.19.2, and Forge version 43.2.6

```yaml
  environment:
      TYPE: FORGE
      VERSION: 1.19.2
      FORGEVERSION: 43.2.6
```

After setting that in my docker compose, the server started up and I was able to login to the server.

Make sure you have the correct versions here, or the server will likely crash due to version requirements.

**Comment by itzg** [comment]
The current image build includes the aspects discussed. Let me know if any new issues pop out from that.

**Comment by camalot** [comment]
Just got a chance to update. With `CF_API_KEY` set to my api key i get a 403 error:

```shell
init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 21 1000 1000 4096 Mar 29 16:18 /data'
[init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
[init] Resolving type given AUTO_CURSEFORGE
[mc-image-helper] 09:08:42.479 ERROR : 'install-curseforge' command failed. Version is 1.25.21
me.itzg.helpers.http.FailedRequestException: HTTP request of https://api.curseforge.com/v1/categories?gameId=432&classesOnly=true failed with 403 Forbidden: Fetching object content
	at me.itzg.helpers.http.FetchBuilderBase.lambda$failedRequestMono$1(FetchBuilderBase.java:151)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:134)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:222)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:210)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:431)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:485)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:712)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1382)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1245)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1294)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1710)
		at me.itzg.helpers.curseforge.CurseForgeInstaller.loadCategoryInfo(CurseForgeInstaller.java:826)
		at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:142)
		at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:161)
		at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:23)
		at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
		at picocli.CommandLine.access$1500(CommandLine.java:148)
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
		at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
		at picocli.CommandLine.execute(CommandLine.java:2170)
		at me.itzg.helpers.McImageHelper.main(McImageHelper.java:132)
[init] ERROR failed to auto-install CurseForge modpack
```

```yaml
environment:
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: '*****************************************************'
      CF_SLUG: all-the-mods-8
      VERSION: 1.19.2
      FORGEVERSION: 43.2.6
```

**Comment by camalot** [comment]
@itzg looks like curse.tools is back. not sure when they came back, just happened to check today.

**Comment by itzg** [comment]
Thanks for checking. I think I'll just have it stick with official CF endpoint. The API key step is annoying for people, but really it's more correct rather than sharing a credential via a proxy. Besides, it became quite clear there was no way to find out how to contact them.
