### ISSUE TITLE
ERROR : 'install-curseforge' command failed. Version is 1.25.20. Failed with 403 Forbidden

### ISSUE THREAD

**Issue by IamMatheusLira** [itzg/docker-minecraft-server#2047]
### Describe the problem

I was get error 403 when I try to install all the mods 8 modpack
maybe there is a mod that has an invalid url

Is there any version that I can make this modpack run or any tips to make the server run?

### Container definition

docker run -e TYPE=AUTO_CURSEFORGE -e CF_SLUG=all-the-mods-8 -e MEMORY=8G -e CF_API_KEY={key} -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Mar 22 01:22 /data'
[init] Resolved version given LATEST into 1.19.4 and major version 1.19
[init] Resolving type given AUTO_CURSEFORGE
[mc-image-helper] 13:15:09.769 ERROR : 'install-curseforge' command failed. Version is 1.25.20
me.itzg.helpers.http.FailedRequestException: HTTP request of https://api.curseforge.com/v1/categories?gameId=432&classesOnly=true failed with 403 Forbidden: Fetching object content
        at me.itzg.helpers.http.FetchBuilderBase.lambda$failedRequestMono$1(FetchBuilderBase.java:151)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
        at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
        at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:134)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:222)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:210)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
        at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
        at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:431)
        at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:485)
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:712)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1382)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1245)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1294)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Mono.block(Mono.java:1710)
                at me.itzg.helpers.curseforge.CurseForgeInstaller.loadCategoryInfo(CurseForgeInstaller.java:824)
                at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:142)
                at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:161)
                at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:23)
                at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
                at picocli.CommandLine.access$1500(CommandLine.java:148)
                at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
                at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
                at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
                at picocli.CommandLine.execute(CommandLine.java:2170)
                at me.itzg.helpers.McImageHelper.main(McImageHelper.java:132)
[init] ERROR failed to auto-install CurseForge modpack

**Comment by itzg** [comment]
The URL https://api.curseforge.com/v1/categories?gameId=432&classesOnly=true works fine for me. Double check your API key.

**Comment by IamMatheusLira** [comment]
I accessed the website
https://console.curseforge.com/#/api-keys
I regenerated the API key and replaced it in the command I sent you and got the same 403 error

**Comment by RemusRichter** [comment]
Don´t know if thats related, but I am having similar problems since yesterday evening with atm8 although it beeing completely auto_curseforge and without api key. 

Checking the presented link https://api.curse.tools/v1/cf/mods/520914/files?latest=1680119190476 yields 502 bad gateway and cloudflare.com claims the following:
![502](https://user-images.githubusercontent.com/75588771/228859711-b97aa618-d1c6-4667-b567-d8f847168ed1.PNG)

**Comment by IamMatheusLira** [comment]
maybe some maintenance is being done, before opening the issue I managed to access this url in the browser, but now I can't access it anymore

![image](https://user-images.githubusercontent.com/61715822/228861347-56e72370-2720-425e-ba58-12a4c768fa60.png)

**Comment by camalot** [comment]
@IamMatheusLira if your API KEY has `$` in it and its in the `environment -> CF_API_KEY`, you have to escape the `$` with another `$`. 

```yaml
environment:
  CF_API_KEY: '$12$13$1449483nf832n20fmn94n95r4n4595t4nsn4903'
```

would be 

```yaml
environment:
  CF_API_KEY: '$$12$$13$$1449483nf832n20fmn94n95r4n4595t4nsn4903'
```

**Comment by itzg** [comment]
Interesting finding @camalot . I'm surprised the single quotes aren't enough to escape them.

**Comment by camalot** [comment]
> > Interesting finding @camalot . I'm surprised the single quotes aren't enough to escape them.
> 
> It also seems like you need to escape the $ with a \ when you use docker run instead of compose on Linux. $ are reserved for environment variables.

Yeah, I should have mentioned that too. sorry.

**Comment by camalot** [comment]
submitted a PR (#2050) to add info about escaping the `$` characters

**Comment by camalot** [comment]
> Interesting finding @camalot . I'm surprised the single quotes aren't enough to escape them.

What I also found odd about that, part of the key was there in my container. it was when the 3rd `$` appeared in the key that the value stopped in the environment variable.

my key was `$11$22$33aaaaaaaaaaaaaaaaaaaaaaaaaaaa`
my container had `CF_API_KEY: $11$22`

**Comment by IceEcold1** [comment]
Currently experiencing this 
`HTTP request of https://api.curse.tools/v1/cf/mods/520914/files/4453236 failed with 502 Bad Gateway` when downloading ATM8.  Anyone else having issues?

My docker compose looks like:
```version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: '$$2a$$10restofthekey'
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-8/files/4453236
      EULA: "true"
      MOTD: "MC server"
      DIFFICULTY: "normal"
      MEMORY: "12G"
      RCON_PASSWORD: "myrconpassword"
      SEED: "7809404675354188026"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    restart: unless-stopped
