### ISSUE TITLE
MAGMA jar file download fails

### ISSUE THREAD

**Issue by NemockZans** [itzg/docker-minecraft-server#2154]
### Describe the problem

When starting up with docker-compose, the download of the magma jar file fails with the exception pasted in below

I checked the path `https://git.magmafoundation.org/api/v4/projects/103/packages/maven/org/magmafoundation/Magma/1.19.3-44.1.23-80dd3a91/Magma-1.19.3-44.1.23-80dd3a91-server.jar` and everything seems to download just fine.
Downloading the jar manually and adding it to the folder lets the server run fine.

### Container definition

```
version: '3.4'

services:
  topsim:
    image: itzg/minecraft-server:java17
    container_name: mc-test
    environment:
      EULA: "TRUE"
      OPS: "<username>"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "2G"
      TYPE: MAGMA
      VERSION: 1.19.3
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      SERVER_NAME: "mc-test"
    volumes:
      - ./data:/data
  router:
    image: ${MC_ROUTER_IMAGE:-itzg/mc-router}
    environment:
      # enable API
      API_BINDING: ":25564"
    ports:
      - 25666:25565
      # bind the API port to only loopback to avoid external exposure
      - 127.0.0.1:25464:25564
    command: --mapping=<subdomain>=mc-test:25666
```

### Container logs

```
mc-test   | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 8 1000 1000 4096 May 28 19:02 /data'
router_1  | time="2023-05-28T19:02:24Z" level=info msg="Listening for Minecraft client connections" listenAddress=":25565"
router_1  | time="2023-05-28T19:02:24Z" level=info msg="Serving API requests" binding=":25564"
mc-test   | [init] Resolved version given 1.19.3 into 1.19.3 and major version 1.19
mc-test   | [init] Resolving type given MAGMA
mc-test   | [init] Updating ops
mc-test   | [init] NemockZans already present in ops.json, skipping
mc-test   | [init] Setting initial memory to 2G and max to 2G
mc-test   | [init] Starting the Minecraft server...
mc-test   |     __  ___                           
mc-test   |    /  |/  /___ _____ _____ ___  ____ _
mc-test   |   / /|_/ / __ `/ __ `/ __ `__ \/ __ `/
mc-test   |  / /  / / /_/ / /_/ / / / / / / /_/ / 
mc-test   | /_/  /_/\__,_/\__, /_/ /_/ /_/\__,_/  
mc-test   |              /____/                   
mc-test   | Copyright (c) 2023 MagmaFoundation.
mc-test   | --------------------------------------
mc-test   | Running on Java 17.0.7 (Eclipse Adoptium)
mc-test   | Magma version   1.19.3-80dd3a91
mc-test   | Bukkit version  v1_19_R2
mc-test   | Forge version   44.1.23
mc-test   | --------------------------------------
mc-test   | If the server crashes while installing, try removing the libraries folder and launching the server again.
Loading libraries... 100% [========================] 96/96 (0:00:03 / 0:00:00) 
Patching server... 100% [============================] 8/8 (0:00:17 / 0:00:00) 
mc-test   | 2023-05-28 19:02:59,211 main WARN Advanced terminal features are not available in this environment
mc-test   | [19:02:59] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 44.1.23, --fml.mcVersion, 1.19.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20221207.122022]
mc-test   | [19:02:59] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.7 by Eclipse Adoptium; OS Linux arch amd64 version 4.15.0-91-generic
mc-test   | [19:02:59] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/data/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
mc-test   | [19:02:59] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/libraries/net/minecraftforge/fmlcore/1.19.3-44.1.23/fmlcore-1.19.3-44.1.23.jar is missing mods.toml file
mc-test   | [19:02:59] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/libraries/net/minecraftforge/javafmllanguage/1.19.3-44.1.23/javafmllanguage-1.19.3-44.1.23.jar is missing mods.toml file
mc-test   | [19:02:59] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/libraries/net/minecraftforge/lowcodelanguage/1.19.3-44.1.23/lowcodelanguage-1.19.3-44.1.23.jar is missing mods.toml file
mc-test   | [19:02:59] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/libraries/net/minecraftforge/mclanguage/1.19.3-44.1.23/mclanguage-1.19.3-44.1.23.jar is missing mods.toml file
mc-test   | [19:02:59] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
mc-test   | [19:03:00] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
mc-test   | [19:03:01] [main/INFO] [or.ma.ma.pr.InjectProtect/]: Booting up InjectProtect
mc-test   | [19:03:05] [main/INFO] [minecraft/DataFixers]: Building unoptimized datafixer
mc-test   | [19:03:06] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 44.1.23, for MC 1.19.3 with MCP 20221207.122022
mc-test   | [19:03:06] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v44.1.23 Initialized
mc-test   | [19:03:07] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [backpacked] Starting version check at https://mrcrayfish.com/modupdatejson?id=backpacked
mc-test   | [19:03:07] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [backpacked] Found status: BETA Current: 2.1.12 Target: 2.1.12
mc-test   | [19:03:07] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
mc-test   | [19:03:08] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: AHEAD Current: 44.1.23 Target: null
mc-test   | [19:03:08] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
mc-test   | [19:03:08] [main/WARN] [ne.mi.co.ForgeHooks/WP]: The following mods have version differences that were not resolved:
mc-test   | forge (version 44.1.0 -> 44.1.23)
mc-test   | Things may not work well.
mc-test   | [19:03:09] [main/WARN] [minecraft/VanillaPackResourcesBuilder]: Assets URL 'union:/data/libraries/net/minecraft/server/1.19.3-20221207.122022/server-1.19.3-20221207.122022-srg.jar%2366!/assets/.mcassetsroot' uses unexpected schema
mc-test   | [19:03:09] [main/WARN] [minecraft/VanillaPackResourcesBuilder]: Assets URL 'union:/data/libraries/net/minecraft/server/1.19.3-20221207.122022/server-1.19.3-20221207.122022-srg.jar%2366!/data/.mcassetsroot' uses unexpected schema
mc-test   | [19:03:09] [main/ERROR] [mixin/]: Critical injection failure: LVT in net/minecraft/server/level/ServerPlayerGameMode::m_9280_(Lnet/minecraft/core/BlockPos;)Z has incompatible changes at opcode 137 in callback backpacked.mixins.json:common.PlayerInteractionManagerMixin->@Inject::afterBreakBlock(Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/level/block/state/BlockState;I)V.
mc-test   |  Expected: [Lnet/minecraft/world/level/block/state/BlockState;, I]
mc-test   |     Found: [Lnet/minecraft/world/level/block/state/BlockState;, Lnet/minecraft/world/level/block/entity/BlockEntity;]
mc-test   | Available: [Lnet/minecraft/world/level/block/state/BlockState;, Lnet/minecraft/world/level/block/entity/BlockEntity;, Lnet/minecraft/world/level/block/Block;]
mc-test   | Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
mc-test   | 	at org.magmafoundation.magma.utils.BootstrapLauncher.startServer(BootstrapLauncher.java:96)
mc-test   | 	at org.magmafoundation.magma.MagmaStart.main(MagmaStart.java:106)
mc-test   | Caused by: java.lang.reflect.InvocationTargetException
mc-test   | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mc-test   | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
mc-test   | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
mc-test   | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
mc-test   | 	at MC-BOOTSTRAP/fmlloader@1.19.3-44.1.23/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
mc-test   | 	... 8 more
mc-test   | Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
mc-test   | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
mc-test   | 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
mc-test   | 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
mc-test   | 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
mc-test   | 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
mc-test   | 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
mc-test   | 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
mc-test   | 	at TRANSFORMER/minecraft@1.19.3/net.minecraft.server.WorldLoader$PackConfig.m_214399_(WorldLoader.java:74)
mc-test   | 	at TRANSFORMER/minecraft@1.19.3/net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:28)
mc-test   | 	at TRANSFORMER/minecraft@1.19.3/net.minecraft.server.Main.lambda$main$2(Main.java:257)
mc-test   | 	at TRANSFORMER/minecraft@1.19.3/net.minecraft.Util.m_214652_(Util.java:768)
mc-test   | 	at TRANSFORMER/minecraft@1.19.3/net.minecraft.Util.m_214679_(Util.java:763)
mc-test   | 	at TRANSFORMER/minecraft@1.19.3/net.minecraft.server.Main.main(Main.java:256)
mc-test   | 	... 14 more
mc-test   | Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/server/level/ServerPlayerGameMode::m_9280_(Lnet/minecraft/core/BlockPos;)Z has incompatible changes at opcode 137 in callback backpacked.mixins.json:common.PlayerInteractionManagerMixin->@Inject::afterBreakBlock(Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/level/block/state/BlockState;I)V.
mc-test   |  Expected: [Lnet/minecraft/world/level/block/state/BlockState;, I]
mc-test   |     Found: [Lnet/minecraft/world/level/block/state/BlockState;, Lnet/minecraft/world/level/block/entity/BlockEntity;]
mc-test   | Available: [Lnet/minecraft/world/level/block/state/BlockState;, Lnet/minecraft/world/level/block/entity/BlockEntity;, Lnet/minecraft/world/level/block/Block;]
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1355)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
mc-test   | 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
mc-test   | 	... 33 more
```

**Comment by itzg** [comment]
That is failing after the container has handed off to the magma jar, so it seems to be beyond my control. If you think the wrong installer was downloaded by the container, then please set `DEBUG` variable to "true" and provide those logs.

**Comment by NemockZans** [comment]
So I should forward this to the magma team I guess.
Thanks for the fast response, I will close this now
