### ISSUE TITLE
Unable to start server with the 1.12.2 pack.

### ISSUE THREAD

**Issue by D217696** [itzg/docker-minecraft-server#2171]
### Describe the problem

I'm trying to run a modpack server for the 1.12.2 modpack, but each time I try to launch it I get a duplicate mods error code.

I've tried running it on 3 different versions of the package
- Latest, gave me an error that had to do with the java version
- Both java8-jdk and java8-multiarch gave me the below error

I ran the compose file with: 
```sudo docker-compose up -d --force-recreate``` 

### Container definition

```
version: "3.1"

services: 
  minecraft:
    image: itzg/minecraft-server:java8-multiarch
    volumes: 
      - minecraftdata2:/data
      - /home/lab/minecraft2/plugins:/plugins
    ports: 
      - 25564:25565
    environment: 
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      OPS: "MyTotallyLegitUsername"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      CF_API_KEY: 'get your own key'
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/the-1122-pack
      MEMORY: 4g
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  minecraftdata2: 
    external: true
```

### Container logs

```
[11:12:33] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.DuplicateModsFoundException: 
Duplicate Mods:
	voxelmap : /data/./mods/forgemod_VoxelMap-1.9.28_for_1.12.2.jar
	voxelmap : /data/./mods/forgemod_VoxelMap-1.9.28_for_1.12.2.jar


	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:466) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:428) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

**Comment by itzg** [comment]
My response from Discord:

> oh...I thought you meant that exception was getting thrown during the container initialization / mod downloading. Now it makes sense why that exception didn't sound familiar. You might need to apply exclusions, but then it's error is showing the exact same file as the "duplicate mod". Maybe that needs to be an issue for that mod author or the modpack?

Sorry for getting you to create this issue prematurely. I'll convert to a discussion.
