### ISSUE TITLE
404 error when paper looks for update

### ISSUE THREAD

**Issue by Brtrnd** [itzg/docker-minecraft-server#2207]
### Describe the problem

Hi
I updated my minecraft server and I get the following error repeating over and over.
I checked and there's no 1.20.1 paper version; only 1.20

```
[init] ERROR: failed to lookup build number for PaperMC version=1.20.1
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 1000 678 Jun 12 19:54 /data'
[init] Resolved version given LATEST into 1.20.1 and major version 1.20
[init] Resolving type given PAPER
[mc-image-helper] 19:55:42.794 ERROR : 'get' command failed. Version is 1.29.2
java.net.UnknownHostException: papermc.io: Temporary failure in name resolution
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
        at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
...
```

I manually updated the paper to 1.20-13.jar but that gives me the same error.
This configuration has worked for a few months; updates were never an issue

### Container definition

```
version: '3.8'
services:
  minecraft:
    image: "itzg/minecraft-server"
    container_name: "minecraft"
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "19132:19132/udp"
      - "19132:19132"
    environment:
      TZ: "Etc/GMT+1"
      EULA: "true"
      TYPE: "PAPER"
      MEMORY: "3G"
      VERSION: "latest"
    tty: true
    stdin_open: true
    volumes:
      - /volume1/docker/minecraft/data:/data:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock #https://github.com/ualex73/monitor_docker

networks:
    default:
        external:
            name: alexandria
```

### Container logs

```
user@host:/volume1/docker/minecraft# docker logs minecraft
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 1000 678 Jun 12 19:54 /data'
[init] Resolved version given LATEST into 1.20.1 and major version 1.20
[init] Resolving type given PAPER
[mc-image-helper] 19:54:54.225 ERROR : 'get' command failed. Version is 1.29.2
me.itzg.helpers.get.RequestFailedException: Failed to download https://papermc.io/api/v2/projects/paper/versions/1.20.1: status code: 404, reason phrase: Not Found
        at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:442)
        at me.itzg.helpers.get.GetCommand.call(GetCommand.java:188)
        at me.itzg.helpers.get.GetCommand.call(GetCommand.java:55)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:143)
Caused by: org.apache.hc.client5.http.HttpResponseException: status code: 404, reason phrase: Not Found
        at org.apache.hc.client5.http.impl.classic.AbstractHttpClientResponseHandler.handleResponse(AbstractHttpClientResponseHandler.java:68)
        at me.itzg.helpers.http.LoggingResponseHandler.handleResponse(LoggingResponseHandler.java:20)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
        at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:440)
        ... 11 common frames omitted
[init] ERROR: failed to lookup build number for PaperMC version=1.20.1
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 1000 678 Jun 12 19:54 /data'
[init] Resolved version given LATEST into 1.20.1 and major version 1.20
[init] Resolving type given PAPER
[mc-image-helper] 19:55:06.541 ERROR : 'get' command failed. Version is 1.29.2
me.itzg.helpers.get.RequestFailedException: Failed to download https://papermc.io/api/v2/projects/paper/versions/1.20.1: status code: 404, reason phrase: Not Found

```

**Comment by itzg** [comment]
As of this moment they haven't released 1.20.1 yet. Perhaps I need to have it intercept the 404 and clarify that?

![image](https://github.com/itzg/docker-minecraft-server/assets/988985/7021a060-19f4-459d-b364-4c958b8446ba)

**Comment by Brtrnd** [comment]
I'm not sure why the updater looks for the newer version?  
I would assume that the updater first looks at https://[papermc.io/api/v2/projects/paper/](https://papermc.io/api/v2/projects/paper/) before looking for versions?
I also don't see an option in the documentation not to look for paper updates? there's one for the java version and minecraft version, but not to block looking at paper.

(ps, thank you for the quick reply)

**Comment by GarretSidzaka** [comment]
ive got this too.  thank you itzg for your help here

**Comment by itzg** [comment]
I'm almost finished with a complete overhaul of the Paper download logic. I'm hoping to have that pushed sometime today.

**Comment by HueGo7258** [comment]
same error for purpur version too

**Comment by now-start** [comment]
I solved the error by setting the version environment variable to 1.20. 
Please keep that in mind. 
Thank you.

**Comment by itzg** [comment]
Latest image now resolves this.

**Comment by GarretSidzaka** [comment]
the image downloaded, server back up thank you!

**Comment by Brtrnd** [comment]
it works here too; I'm very grateful.
