### ISSUE TITLE
Minecraft Purpur version download 404 error

### ISSUE THREAD

**Issue by HueGo7258** [itzg/docker-minecraft-server#2213]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Hi, the Purpur version is giving the following error when downloading

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Jun 13 19:02 /data'
[init] Resolved version given LATEST into 1.20.1 and major version 1.20
[init] Resolving type given PURPUR
[mc-image-helper] 20:24:00.596 ERROR : 'get' command failed. Version is 1.30.1
me.itzg.helpers.get.RequestFailedException: Failed to download https://api.purpurmc.org/v2/purpur/1.20.1: status code: 404, reason phrase: Not Found
	at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:442)
	at me.itzg.helpers.get.GetCommand.call(GetCommand.java:188)
	at me.itzg.helpers.get.GetCommand.call(GetCommand.java:55)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:145)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:145)
Caused by: org.apache.hc.client5.http.HttpResponseException: status code: 404, reason phrase: Not Found
	at org.apache.hc.client5.http.impl.classic.AbstractHttpClientResponseHandler.handleResponse(AbstractHttpClientResponseHandler.java:68)
	at me.itzg.helpers.http.LoggingResponseHandler.handleResponse(LoggingResponseHandler.java:20)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
	at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:440)
	... 11 common frames omitted
[init] ERROR: Failed to locate a Purpur build for 1.20.1.
[init]        Please check if a download is available at https://purpur.pl3x.net/downloads/
```

My docker compose file:

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: "minecraftJS"
    ports:
      - 25565:25565
    environment:
      USE_AIKAR_FLAGS: true
      EULA: "TRUE"
      VERSION: LATEST
      TYPE: PURPUR
      ONLINE_MODE: false
      MEMORY: 2G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
```

**Comment by itzg** [comment]
Not surprisingly, Purpur is running a little behind on their versions. They seem to have 1.20 out, but not yet 1.20.1.  For now you can set `VERSION: "1.20"`.

I'll work on rewriting the download logic like I just did for Paper. In fact, it looks like Purpur's download API is compatible with PaperMC.

**Comment by HueGo7258** [comment]
Thank you, setting the environment variable worked!
