### ISSUE TITLE
Magma jar download with java8 image failed

### ISSUE THREAD

**Issue by Kaktus14** [itzg/docker-minecraft-server#2275]
### Describe the problem

Magma jar download with java8 image failed.

### Container definition

```
docker run -d -it -p 25565:25565 --name magma -v /var/magma:/data -e EULA=TRUE -e VERSION=1.12.2 -e TYPE=magma itzg/minecraft-server:java8
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 1000 152 Jul  7 16:04 /data'
[init] Resolving type given magma
[init] Resolved version given 1.12.2 into 1.12.2
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/cxf/attachment/Rfc5987Util has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at me.itzg.helpers.http.FilenameExtractor.filenameFromContentDisposition(FilenameExtractor.java:46)
	at me.itzg.helpers.http.FilenameExtractor.extract(FilenameExtractor.java:81)
	at me.itzg.helpers.http.DeriveFilenameHandler.handleResponse(DeriveFilenameHandler.java:21)
	at me.itzg.helpers.http.DeriveFilenameHandler.handleResponse(DeriveFilenameHandler.java:10)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
	at me.itzg.helpers.get.GetCommand.resolveExpectedFilename(GetCommand.java:356)
	at me.itzg.helpers.get.GetCommand.needsDownload(GetCommand.java:329)
	at me.itzg.helpers.get.GetCommand.processUrisForDirectory(GetCommand.java:303)
	at me.itzg.helpers.get.GetCommand.call(GetCommand.java:198)
	at me.itzg.helpers.get.GetCommand.call(GetCommand.java:55)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:149)
[init] ERROR: failed to download Magma server jar from https://git.magmafoundation.org/api/v4/projects/7/packages/maven/org/magmafoundation/Magma/1.12.2-15ea32c3/Magma-1.12.2-15ea32c3.jar
```

**Comment by itzg** [comment]
Thanks for reporting this. I am working on fixing that.
