### ISSUE TITLE
MTU mismatch causing server jar download to fail

### ISSUE THREAD

**Issue by usbpc** [itzg/docker-minecraft-server#2276]
### Describe the problem

I just pulled the most recent version of this image and changed the server version to 1.20.1 and now the server is not starting anymore, but instead crashing because of the ssl timeout for some reason. I've included all the logs below.

### Container definition

```
version: '2.3'
services:
        minecraft:
                image: itzg/minecraft-server
                environment:
                        MEMORY: '8G'
                        EULA: 'TRUE'
                        VERSION: '1.20.1'
                volumes:
                        - ./usbcraft:/data
                ports:
                        - 25565:25565
                restart: always
```

### Container logs

```
Starting minecraft_minecraft_1 ... done
Attaching to minecraft_minecraft_1
minecraft_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 12 1000 1000 4096 Jul  7 20:43 /data'
minecraft_1  | [init] Resolving type given VANILLA
minecraft_1  | [mc-image-helper] 20:47:31.137 ERROR : 'resolve-minecraft-version' command failed. Version is 1.32.5
minecraft_1  | reactor.core.Exceptions$ReactiveException: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 30000ms
minecraft_1  |  at reactor.core.Exceptions.propagate(Exceptions.java:408)
minecraft_1  |  at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:100)
minecraft_1  |  at reactor.core.publisher.Mono.block(Mono.java:1712)
minecraft_1  |  at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:26)
minecraft_1  |  at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:12)
minecraft_1  |  at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
minecraft_1  |  at picocli.CommandLine.access$1500(CommandLine.java:148)
minecraft_1  |  at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
minecraft_1  |  at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
minecraft_1  |  at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
minecraft_1  |  at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
minecraft_1  |  at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
minecraft_1  |  at picocli.CommandLine.execute(CommandLine.java:2170)
minecraft_1  |  at me.itzg.helpers.McImageHelper.main(McImageHelper.java:149)
minecraft_1  |  Suppressed: java.lang.Exception: #block terminated with an error
minecraft_1  |          at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:102)
minecraft_1  |          ... 12 common frames omitted
minecraft_1  | Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 30000ms
minecraft_1  |  at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2125)
minecraft_1  |  at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
minecraft_1  |  at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
minecraft_1  |  at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
minecraft_1  |  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
minecraft_1  |  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
minecraft_1  |  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
minecraft_1  |  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
minecraft_1  |  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
minecraft_1  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
minecraft_1  |  at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by itzg** [comment]
I'm guessing it's a temporary networking issue. Hopefully it'll work when you try again later unless it's something you need to fix on your network and/or docker host.

**Comment by usbpc** [comment]
I've let the container try again and again since I opened this issue and no luck yet. I've also restarted the system just in case that would fix it but no luck.

Other containers on the same host are working without a problem. I guess I'll have to do some more debugging to do.

If I followd the ./start script correctly and understand the debug message it it is failing https://github.com/itzg/docker-minecraft-server/blob/8fabf17c215b5fa9cad5f5dd133ad6b6866626b2/scripts/start-utils#L328 in that line, which actually starts the mc-image-helper tool from another of your repositories here https://github.com/itzg/mc-image-helper/tree/master.

The command 'resolve-minecraft-version' seems to be definded here: https://github.com/itzg/mc-image-helper/blob/e8add4cdb893f360035ff13b51d44c1b3693597e/src/main/java/me/itzg/helpers/versions/ResolveMinecraftVersionCommand.java#L12

And if I understand that code and the error correctly it fails when trying to connect to `https://launchermeta.mojang.com/mc/game/version_manifest_v2.json` because the SSL handshake times out. The URL defined here: https://github.com/itzg/mc-image-helper/blob/e8add4cdb893f360035ff13b51d44c1b3693597e/src/main/java/me/itzg/helpers/versions/MinecraftVersionsApi.java#L15C43-L15C107

I'll go and test if network connections to there are working or not from within docker containers.

**Comment by usbpc** [comment]
The results are very weird and unexpected for me.

I've used `curl --connect-timeout 10 https://launchermeta.mojang.com/mc/game/version_manifest_v2.json` to check the connection to the mojang server. On the host itself it works, but from within the container it fails:

```
# curl -vv --connect-timeout 10 https://launchermeta.mojang.com/mc/game/version_manifest_v2.json
*   Trying 13.107.246.45:443...
* Connected to launchermeta.mojang.com (13.107.246.45) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
```

So the apperently the connection to the server is established... just the SSL session dosen't get started and gets stuck waiting for a response from the server. But with for example google.com it works:

```
# curl -vv --connect-timeout 10 https://google.com
*   Trying 74.125.133.138:443...
* Connected to google.com (74.125.133.138) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.google.com
*  start date: Jun 19 08:16:09 2023 GMT
*  expire date: Sep 11 08:16:08 2023 GMT
*  subjectAltName: host "google.com" matched cert's "google.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x556b2f74f2c0)
> GET / HTTP/2
> Host: google.com
> user-agent: curl/7.74.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 301
< location: https://www.google.com/
< content-type: text/html; charset=UTF-8
< content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-j_2CcGlAdUQc1ACrQOICBg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
< date: Sat, 08 Jul 2023 11:48:08 GMT
< expires: Sat, 08 Jul 2023 11:48:08 GMT
< cache-control: private, max-age=2592000
< server: gws
< content-length: 220
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< set-cookie: CONSENT=PENDING+540; expires=Mon, 07-Jul-2025 11:48:08 GMT; path=/; domain=.google.com; Secure
< p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
<
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host google.com left intact
```

Very weird and confusing.

**Comment by itzg** [comment]
Thank you for investigating further and correctly identifying the test with curl inside the container. 

Just to be sure, re-pull the image just in case you're running an old copy with some kind of SSL and/or CA cert quirk.

**Comment by usbpc** [comment]
I did that yesterday and just to be sure a moment ago. It updated and I'm now running a newer version... but it didn't fix the problem. 

Here is the log from when I just started up the container:

```
minecraft_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 12 1000 1000 4096 Jul  7 20:43 /data'
minecraft_1  | [init] Resolving type given VANILLA
minecraft_1  | [mc-image-helper] 16:58:52.553 ERROR : 'resolve-minecraft-version' command failed. Version is 1.32.6
minecraft_1  | reactor.core.Exceptions$ReactiveException: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 30000ms
minecraft_1  |  at reactor.core.Exceptions.propagate(Exceptions.java:408)
minecraft_1  |  at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:100)
minecraft_1  |  at reactor.core.publisher.Mono.block(Mono.java:1712)
minecraft_1  |  at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:26)
minecraft_1  |  at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:12)
minecraft_1  |  at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
minecraft_1  |  at picocli.CommandLine.access$1500(CommandLine.java:148)
minecraft_1  |  at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
minecraft_1  |  at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
minecraft_1  |  at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
minecraft_1  |  at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
minecraft_1  |  at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
minecraft_1  |  at picocli.CommandLine.execute(CommandLine.java:2170)
minecraft_1  |  at me.itzg.helpers.McImageHelper.main(McImageHelper.java:149)
minecraft_1  |  Suppressed: java.lang.Exception: #block terminated with an error
minecraft_1  |          at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:102)
minecraft_1  |          ... 12 common frames omitted
minecraft_1  | Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 30000ms
minecraft_1  |  at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2125)
minecraft_1  |  at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
minecraft_1  |  at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
minecraft_1  |  at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
minecraft_1  |  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
minecraft_1  |  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
minecraft_1  |  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
minecraft_1  |  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
minecraft_1  |  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
minecraft_1  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
minecraft_1  |  at java.base/java.lang.Thread.run(Unknown Source)
minecraft_1  | [mc-image-helper] 16:58:52.557 WARN  : [9ee5b41b, L:/172.20.0.2:57378 - R:launchermeta.mojang.com/13.107.246.45:443] The connection observed an error
minecraft_1  | io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 30000ms
minecraft_1  |  at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2125)
minecraft_1  |  at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
minecraft_1  |  at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
minecraft_1  |  at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
minecraft_1  |  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
minecraft_1  |  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
minecraft_1  |  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
minecraft_1  |  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
minecraft_1  |  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
minecraft_1  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
minecraft_1  |  at java.base/java.lang.Thread.run(Unknown Source)
```

And here my attempt at connecting from within the container to the same url at the same time:

```
# curl -vv --connect-timeout 10 https://launchermeta.mojang.com/mc/game/version_manifest_v2.json
*   Trying 13.107.246.45:443...
* TCP_NODELAY set
* Connected to launchermeta.mojang.com (13.107.246.45) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* Operation timed out after 10001 milliseconds with 0 out of 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10001 milliseconds with 0 out of 0 bytes received

# curl -vv --connect-timeout 10 https://google.com
*   Trying 66.102.1.102:443...
* TCP_NODELAY set
* Connected to google.com (66.102.1.102) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.google.com
*  start date: Jun 19 08:16:09 2023 GMT
*  expire date: Sep 11 08:16:08 2023 GMT
*  subjectAltName: host "google.com" matched cert's "google.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5571ddf69300)
> GET / HTTP/2
> Host: google.com
> user-agent: curl/7.68.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 301
< location: https://www.google.com/
< content-type: text/html; charset=UTF-8
< content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-gxlTceSv0HSTBfBA9Y6WqQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
< date: Sat, 08 Jul 2023 17:04:10 GMT
< expires: Sat, 08 Jul 2023 17:04:10 GMT
< cache-control: private, max-age=2592000
< server: gws
< content-length: 220
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< set-cookie: CONSENT=PENDING+725; expires=Mon, 07-Jul-2025 17:04:10 GMT; path=/; domain=.google.com; Secure
< p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
<
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host google.com left intact
```

I'm not sure how to best procceed maybe I'll start some packet captures to see if I can learn anything from them.

Also since it has something to do with my setup and not a widespread issue with this image I have to thank you for taking the time and looking at this issue!

**Comment by itzg** [comment]
I used exactly your file and mine started up fine. I'm running out of ideas. Perhaps make sure you host has the latest kernel for your distro.

**Comment by usbpc** [comment]
Thanks for checking. One other test I did is try plain http without encryption and that also fails to the mojang server:

```
# curl -vv --max-time 10 http://launchermeta.mojang.com/mc/game/version_manifest_v2.json
*   Trying 13.107.246.67:80...
* TCP_NODELAY set
* Connected to launchermeta.mojang.com (13.107.246.67) port 80 (#0)
> GET /mc/game/version_manifest_v2.json HTTP/1.1
> Host: launchermeta.mojang.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* Operation timed out after 10001 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10001 milliseconds with 0 bytes received
```

So it is not the SSL that is the problem. But I will need to investigate it further.  I'll keep this issue to write down my own investigation so maybe someone in the future can benefit from it!

**Comment by usbpc** [comment]
Looking at a packet capture unfortunatly only confuses me more. It is still working perfectly outside the container, but not inside the container. As docker uses NAT there should be no way for any of the network devices to distinguish between a request from within docker and from outside docker.

The packet capture shows that from inside the container the TCP connection with SYN / ACK to the server works and even that the HTTP request TCP packet is acknowledged:

![image](https://github.com/itzg/docker-minecraft-server/assets/3638901/69f2d9fd-17e2-43e2-b373-02e653e7088d)

It is just that no response ever gets to the server beyong the ACK for the HTTP request TCP packet. I performed the caputure on the docker host so it could see all network traffic happening.

**Comment by usbpc** [comment]
I've also tested with other docker images and they also have the same problem and can't get a http response from `http://launchermeta.mojang.com/mc/game/version_manifest_v2.json` either.

And then something that confuses me even more is that I tried curl to just get `http://launchermeta.mojang.com` from within a container and that works:

```
root@749b637b47cd:/data# curl -vv --max-time 10 http://launchermeta.mojang.com
*   Trying 13.107.246.45:80...
* TCP_NODELAY set
* Connected to launchermeta.mojang.com (13.107.246.45) port 80 (#0)
> GET / HTTP/1.1
> Host: launchermeta.mojang.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 The specified resource does not exist.
< Date: Sun, 09 Jul 2023 14:39:21 GMT
< Content-Type: application/xml
< Content-Length: 223
< Connection: keep-alive
< x-ms-request-id: adee566c-801e-006e-2873-b2e0ac000000
< x-ms-version: 2014-02-14
< x-azure-ref: 20230709T143921Z-6byexnud2t19zfr5bumk9r70h40000000ad000000001pwpg
< X-Cache: TCP_MISS
< Access-Control-Allow-Origin: *
<
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:adee566c-801e-006e-2873-b2e0ac000000
* Connection #0 to host launchermeta.mojang.com left intact
Time:2023-07-09T14:39:21.3786445Z</Message></Error>root@749b637b47cd:/data# curl -vv --max-time 10 http://launchermeta.mojang.com/mc/game/version_manifest_v2.json
*   Trying 13.107.246.67:80...
* TCP_NODELAY set
* Connected to launchermeta.mojang.com (13.107.246.67) port 80 (#0)
> GET /mc/game/version_manifest_v2.json HTTP/1.1
> Host: launchermeta.mojang.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* Operation timed out after 10001 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10001 milliseconds with 0 bytes received
```

**Comment by itzg** [comment]
For posterity, can you post what host OS distro, kernel version, and Docker version you're running?

**Comment by usbpc** [comment]
SOLVED!

It was a MTU problem, my network setup is not straight forward as I have all my docker containers connected to the internet through a wiregard VPN so I can use the static IP from a small VSP I rent:

```
$ ip a show dev wg1
27: wg1: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 10.102.0.3/24 scope global wg1
       valid_lft forever preferred_lft forever
```

So the MTU is not the default 1500 as it is in most networks but 1400 as you can see from the output above. Docker dosen't automatically configure continers the same way, but just uses the normal 1500:

```
# ip a show dev eth0
75: eth0@if76: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

I've been using this setup for as long as I've used this docker image, so I have no idea why it stopped working just now. To solve this I changed my `docker-compose.yml` to:

```
version: '2.3'
services:
        minecraft:
                image: itzg/minecraft-server
                environment:
                        MEMORY: '8G'
                        EULA: 'TRUE'
                        VERSION: '1.20.1'
                volumes:
                        - ./usbcraft:/data
                ports:
                        - 25565:25565
                restart: always
                networks:
                        - mc_net

networks:
        mc_net:
                driver: bridge
                driver_opts:
                        com.docker.network.driver.mtu: 1400
```

Now even inside the container the MTU is set to 1400 and everything works nicely.

Even tho I don't think my specific OS, kernel or Docker have something to do with this problem this is what I'm running:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
$ docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2
$ uname -r
5.15.0-76-generic
```

**Comment by itzg** [comment]
I'm so glad you found the cause and thanks for posting your research here. This will be great help for anyone else that runs into this.

**Comment by funkel1989** [comment]
@usbpc @itzg How did you determine the MTU was supposed to be 1400. I'm running into the same problem deploying the chart into a k3s cluster which worked 2 days ago but i made a config change from vanilla to paper and am now getting the same error as you. I made a cilum edit to make my MTU 1400 (affecting the entire cluster) and that didn't seem to fix it for me.

**Comment by usbpc** [comment]
@funkel1989 

I know my network and what connection was the one with the lowest MTU then I could check the interface for that connection using the `ip a` command and that printed out the MTU that that connection was using.

Also since you are not using docker-compose directly but a k3s cluster make sure that the settings you think you applied are actually used. You could either look at the network traffic with wireshark and inspect the packets that way or run `ip a` in a container to see what MTU the network interface has.

**Comment by omblivion** [comment]
Thanks, you all! I had the same issue for days and now it works again! If it helps for the ones having the same problem my setup is to run this docker container in a Proxmox VM which gets internet from a Tailscale network.
