### ISSUE TITLE
Forge installer exception: java.util.zip.ZipException: zip END header not found

### ISSUE THREAD

**Issue by Merlin8000** [itzg/docker-minecraft-server#2283]
### Describe the problem

When instantiating a new pod for Forge without mods (any version it seems), I get the output below and the container fails to start.  I've tried multiple versions of Forge and minecraft all with the same result.  I switched the type to PAPER with latest as version and startup was successful.

```
java.util.zip.ZipException: zip END header not found
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.zerror(Unknown Source)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(Unknown Source)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(Unknown Source)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(Unknown Source)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(Unknown Source)
        at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source)
        at net.minecraftforge.installertools.BundlerExtract.process(BundlerExtract.java:73)
        at net.minecraftforge.installertools.ConsoleTool.main(ConsoleTool.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.installer.actions.PostProcessors.process(PostProcessors.java:226)
        at net.minecraftforge.installer.actions.ServerInstall.run(ServerInstall.java:118)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:128)
Failed to run processor: java.util.zip.ZipException:zip END header not found
See log for more details.
There was an error during installation
[mc-image-helper] 02:29:34.317 ERROR : 'install-forge' command failed. Version is 1.32.6
me.itzg.helpers.errors.GenericException: Forge installer failed with exit code 1
        at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:334)
        at me.itzg.helpers.forge.ForgeInstaller.downloadAndInstall(ForgeInstaller.java:268)
        at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:136)
        at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:84)
        at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:16)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:149)
[init] ERROR failed to install Forge
```

### Container definition

```
podman run -e TYPE=FORGE -e VERSION=1.19.2 -e FORGE_VERSION=43.2.3 -e EULA=TRUE -e MEMORY=4G -e SNOOPER_ENABLED=false -e UID=1001 -e GID=1001 -v /home/minecraft/placeholder-II/data:/data:z -p 25567:25565 -p 25577:25575 -l io.containers.autoupdate=registry --replace --name minecraft-placeholder-II -d docker.io/itzg/minecraft-server:latest
```

### Container logs

```
[init] Changing uid of minecraft to 1001
[init] Changing gid of minecraft to 1001
[init] Running as uid=1001 gid=1001 with /data as 'drwxrwxr-x. 4 1001 1001 4096 Jul 10 02:29 /data'
[init] Resolving type given FORGE
[mc-image-helper] 02:29:28.900 INFO  : Downloading Forge installer 43.2.3 for Minecraft 1.19.2
[mc-image-helper] 02:29:32.989 INFO  : Running Forge installer. This might take a while...
JVM info: AdoptOpenJDK - 11.0.11 - 11.0.11+9
java.net.preferIPv4Stack=true
Found java version 11.0.11
Target Directory: .
Data kindly mirrored by CreeperHost at https://www.creeperhost.net/
Considering minecraft server jar
Downloading libraries
Found 0 additional library directories
Considering library cpw.mods:securejarhandler:2.1.4
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-util:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:9.3
  File exists: Checksum validated.
Considering library net.minecraftforge:accesstransformers:8.0.4
  File exists: Checksum validated.
Considering library org.antlr:antlr4-runtime:4.9.1
  File exists: Checksum validated.
Considering library net.minecraftforge:eventbus:6.0.3
  File exists: Checksum validated.
Considering library net.minecraftforge:forgespi:6.0.0
  File exists: Checksum validated.
Considering library net.minecraftforge:coremods:5.0.1
  File exists: Checksum validated.
Considering library cpw.mods:modlauncher:10.0.8
  File exists: Checksum validated.
Considering library net.minecraftforge:unsafe:0.2.0
  File exists: Checksum validated.
Considering library com.electronwill.night-config:core:3.6.4
  File exists: Checksum validated.
Considering library com.electronwill.night-config:toml:3.6.4
  File exists: Checksum validated.
Considering library org.apache.maven:maven-artifact:3.8.5
  File exists: Checksum validated.
Considering library net.jodah:typetools:0.8.3
  File exists: Checksum validated.
Considering library net.minecrell:terminalconsoleappender:1.2.0
  File exists: Checksum validated.
Considering library org.jline:jline-reader:3.12.1
  File exists: Checksum validated.
Considering library org.jline:jline-terminal:3.12.1
  File exists: Checksum validated.
Considering library org.spongepowered:mixin:0.8.5
  File exists: Checksum validated.
Considering library org.openjdk.nashorn:nashorn-core:15.3
  File exists: Checksum validated.
Considering library net.minecraftforge:JarJarSelector:0.3.16
  File exists: Checksum validated.
Considering library net.minecraftforge:JarJarMetadata:0.3.16
  File exists: Checksum validated.
Considering library cpw.mods:bootstraplauncher:1.1.2
  File exists: Checksum validated.
Considering library net.minecraftforge:JarJarFileSystems:0.3.16
  File exists: Checksum validated.
Considering library net.minecraftforge:fmlloader:1.19.2-43.2.3
  File exists: Checksum validated.
Considering library com.github.jponge:lzma-java:1.3
  File exists: Checksum validated.
Considering library com.google.code.findbugs:jsr305:3.0.2
  File exists: Checksum validated.
Considering library com.google.code.gson:gson:2.8.7
  File exists: Checksum validated.
Considering library com.google.errorprone:error_prone_annotations:2.1.3
  File exists: Checksum validated.
Considering library com.google.guava:guava:20.0
  File exists: Checksum validated.
Considering library com.google.guava:guava:25.1-jre
  File exists: Checksum validated.
Considering library com.google.j2objc:j2objc-annotations:1.1
  File exists: Checksum validated.
Considering library com.nothome:javaxdelta:2.0.1
  File exists: Checksum validated.
Considering library com.opencsv:opencsv:4.4
  File exists: Checksum validated.
Considering library commons-beanutils:commons-beanutils:1.9.3
  File exists: Checksum validated.
Considering library commons-collections:commons-collections:3.2.2
  File exists: Checksum validated.
Considering library commons-io:commons-io:2.4
  File exists: Checksum validated.
Considering library commons-logging:commons-logging:1.2
  File exists: Checksum validated.
Considering library de.oceanlabs.mcp:mcp_config:1.19.2-20220805.130853@zip
  File exists: Checksum validated.
Considering library de.siegmar:fastcsv:2.0.0
  File exists: Checksum validated.
Considering library net.md-5:SpecialSource:1.11.0
  File exists: Checksum validated.
Considering library net.minecraftforge:ForgeAutoRenamingTool:0.1.22:all
  File exists: Checksum validated.
Considering library net.minecraftforge:binarypatcher:1.1.1
  File exists: Checksum validated.
Considering library net.minecraftforge:fmlcore:1.19.2-43.2.3
  File exists: Checksum validated.
Considering library net.minecraftforge:fmlloader:1.19.2-43.2.3
  File exists: Checksum validated.
Considering library net.minecraftforge:forge:1.19.2-43.2.3:universal
  File exists: Checksum validated.
Considering library net.minecraftforge:installertools:1.3.0
  File exists: Checksum validated.
Considering library net.minecraftforge:jarsplitter:1.1.4
  File exists: Checksum validated.
Considering library net.minecraftforge:javafmllanguage:1.19.2-43.2.3
  File exists: Checksum validated.
Considering library net.minecraftforge:lowcodelanguage:1.19.2-43.2.3
  File exists: Checksum validated.
Considering library net.minecraftforge:mclanguage:1.19.2-43.2.3
  File exists: Checksum validated.
Considering library net.minecraftforge:srgutils:0.4.11
  File exists: Checksum validated.
Considering library net.minecraftforge:srgutils:0.4.3
  File exists: Checksum validated.
Considering library net.minecraftforge:srgutils:0.4.9
  File exists: Checksum validated.
Considering library net.sf.jopt-simple:jopt-simple:5.0.4
  File exists: Checksum validated.
Considering library net.sf.jopt-simple:jopt-simple:6.0-alpha-3
  File exists: Checksum validated.
Considering library org.apache.commons:commons-collections4:4.2
  File exists: Checksum validated.
Considering library org.apache.commons:commons-lang3:3.8.1
  File exists: Checksum validated.
Considering library org.apache.commons:commons-text:1.3
  File exists: Checksum validated.
Considering library org.checkerframework:checker-qual:2.0.0
  File exists: Checksum validated.
Considering library org.codehaus.mojo:animal-sniffer-annotations:1.14
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:9.2
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:9.2
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:9.2
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:9.2
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:9.3
  File exists: Checksum validated.
Considering library trove:trove:1.0.2
  File exists: Checksum validated.
Created Temporary Directory: /tmp/forge_installer6566398125876401687
  Extracting: /data/server.lzma
Building Processors
===============================================================================
  MainClass: net.minecraftforge.installertools.ConsoleTool
  Classpath:
    /data/./libraries/net/minecraftforge/installertools/1.3.0/installertools-1.3.0.jar
    /data/./libraries/net/md-5/SpecialSource/1.11.0/SpecialSource-1.11.0.jar
    /data/./libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
    /data/./libraries/com/google/code/gson/gson/2.8.7/gson-2.8.7.jar
    /data/./libraries/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar
    /data/./libraries/net/minecraftforge/srgutils/0.4.11/srgutils-0.4.11.jar
    /data/./libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
    /data/./libraries/com/google/guava/guava/20.0/guava-20.0.jar
    /data/./libraries/com/opencsv/opencsv/4.4/opencsv-4.4.jar
    /data/./libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
    /data/./libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
    /data/./libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
    /data/./libraries/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
    /data/./libraries/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
    /data/./libraries/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
    /data/./libraries/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar
    /data/./libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
    /data/./libraries/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
  Args: --task, EXTRACT_FILES, --archive, /data/forge-installer-1.19.2-43.2.3.jar, --from, data/run.sh, --to, /data/./run.sh, --exec, /data/./run.sh, --from, data/run.bat, --to, /data/./run.bat, --from, data/user_jvm_args.txt, --to, /data/./user_jvm_args.txt, --optional, /data/./user_jvm_args.txt, --from, data/win_args.txt, --to, /data/./libraries/net/minecraftforge/forge/1.19.2-43.2.3/win_args.txt, --from, data/unix_args.txt, --to, /data/./libraries/net/minecraftforge/forge/1.19.2-43.2.3/unix_args.txt
Task: EXTRACT_FILES
Archive: /data/forge-installer-1.19.2-43.2.3.jar
Extract: data/run.sh
         /data/./run.sh
Extract: data/run.bat
         /data/./run.bat
Extract: data/user_jvm_args.txt
         /data/./user_jvm_args.txt
Extract: data/win_args.txt
         /data/./libraries/net/minecraftforge/forge/1.19.2-43.2.3/win_args.txt
Extract: data/unix_args.txt
         /data/./libraries/net/minecraftforge/forge/1.19.2-43.2.3/unix_args.txt
Exec:    /data/./run.sh
===============================================================================
  MainClass: net.minecraftforge.installertools.ConsoleTool
  Classpath:
    /data/./libraries/net/minecraftforge/installertools/1.3.0/installertools-1.3.0.jar
    /data/./libraries/net/md-5/SpecialSource/1.11.0/SpecialSource-1.11.0.jar
    /data/./libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
    /data/./libraries/com/google/code/gson/gson/2.8.7/gson-2.8.7.jar
    /data/./libraries/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar
    /data/./libraries/net/minecraftforge/srgutils/0.4.11/srgutils-0.4.11.jar
    /data/./libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
    /data/./libraries/com/google/guava/guava/20.0/guava-20.0.jar
    /data/./libraries/com/opencsv/opencsv/4.4/opencsv-4.4.jar
    /data/./libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
    /data/./libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
    /data/./libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
    /data/./libraries/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
    /data/./libraries/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
    /data/./libraries/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
    /data/./libraries/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar
    /data/./libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
    /data/./libraries/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
  Args: --task, BUNDLER_EXTRACT, --input, /data/./libraries/net/minecraft/server/1.19.2/server-1.19.2.jar, --output, /data/./libraries/, --libraries
Task: BUNDLER_EXTRACT
Input:   /data/./libraries/net/minecraft/server/1.19.2/server-1.19.2.jar
Output:  /data/./libraries
All:     false
JarOnly: false
Libs:    true
java.util.zip.ZipException: zip END header not found
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.zerror(Unknown Source)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(Unknown Source)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(Unknown Source)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(Unknown Source)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(Unknown Source)
        at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source)
        at net.minecraftforge.installertools.BundlerExtract.process(BundlerExtract.java:73)
        at net.minecraftforge.installertools.ConsoleTool.main(ConsoleTool.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.installer.actions.PostProcessors.process(PostProcessors.java:226)
        at net.minecraftforge.installer.actions.ServerInstall.run(ServerInstall.java:118)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:128)
Failed to run processor: java.util.zip.ZipException:zip END header not found
See log for more details.
There was an error during installation
[mc-image-helper] 02:29:34.317 ERROR : 'install-forge' command failed. Version is 1.32.6
me.itzg.helpers.errors.GenericException: Forge installer failed with exit code 1
        at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:334)
        at me.itzg.helpers.forge.ForgeInstaller.downloadAndInstall(ForgeInstaller.java:268)
        at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:136)
        at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:84)
        at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:16)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:149)
[init] ERROR failed to install Forge
```

**Comment by itzg** [comment]
I can't recreate the problem and besides, that's the forge installer failing. I'm not sure how I can address that. Also, you seem to have a very old image if running latest reports

```
JVM info: AdoptOpenJDK - 11.0.11 - 11.0.11+9
```

Should be reporting Java 17.0.7:
```
> docker run --rm --entrypoint=java docker.io/itzg/minecraft-server:latest -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)
```

**Comment by Merlin8000** [comment]
Sorry, I had been trying various versions of the image as a troubleshooting measure, the result is the same with all image versions.

```
podman run --rm --entrypoint=java docker.io/itzg/minecraft-server:latest -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)
```

[forge-installer-1.19.2-43.2.3.jar.log](https://github.com/itzg/docker-minecraft-server/files/12001401/forge-installer-1.19.2-43.2.3.jar.log)

**Comment by itzg** [comment]
That error means there's a corrupted zip/jar file. Again, it's failing during the forge installer and I can't recreate the issue. Try a fresh system or report an issue with forge.

**Comment by Merlin8000** [comment]
For whatever reason, server-<version>.jar was never downloading completely.  I checked and the version downloaded automatically was roughly 8MB.  Downloading the file myself and replacing it with the full 45MB file fixed the problem.

I wish I knew what the root problem was since there's presumably no meaningful difference between our environments, we should be downloading from the same place and I was working with an empty /data directory.

For my purposes the issue is resolved with a work-around of manually replacing the corrupted jar file.

**Comment by ocontant** [comment]
Just reporting, i'm facing the same error today with ATM9 deployment. Fail at the same spot.
I also had issue with the PT20S timeout, adding the variable suggested in another thread to my docker-compose didn't have impact on the timeout, it still timed out at 120000ms. 


Thanks for this thread by the way, that was the only clue I could find about this problem.

**Comment by BrewedCoffee** [comment]
How did you find what .jar file was corrupted? Also running into this issue.

**Comment by juaps** [comment]
Im having the same exact problem described here, using Mac, and fresh minecraft copies, tried differents javas, no luck

**Comment by itzg** [comment]
Set env var `FORGE_FORCE_REINSTALL` to "true"

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/server-types/forge/

**Comment by psoloviov** [comment]
Well, I can say that with default env config for forge:

```yaml
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      FORGE_VERSION: "43.5.0"
```

Something goes wrong, and installing forge via script fails.
When I switch to direct installation from source:
```yaml
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      FORGE_VERSION: "43.5.0"
      FORGE_INSTALLER_URL: "https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.5.0/forge-1.19.2-43.5.0-installer.jar"
```

Everything starts working.
I guess that problem inside forge-install script, they download bad-file and can't process installation.

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/server-types/forge/#cleanroom

In my case, the problem was NOT with bad *.jar/zip files (I mean mods that I download), but with forge and his installing process via env configuration.
