### ISSUE TITLE
Forge doesn't work in 1.12.2

### ISSUE THREAD

**Issue by KillsT3aler69** [itzg/docker-minecraft-server#2318]
### Describe the problem

The image crashes when you try to run forge in 1.12.2.

### Container definition

docker run -it \
    -p 25565:25565 \
    -e EULA=TRUE \
    -e TYPE=FORGE \
    -e VERSION=1.12.2 \
    itzg/minecraft-server

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Aug  3 18:19 /data'
[init] Resolving type given FORGE
[mc-image-helper] 14:26:31.979 INFO  : Downloading Forge installer 14.23.5.2859 for Minecraft 1.12.2
[mc-image-helper] 14:26:33.257 INFO  : Running Forge installer. This might take a while...
[init] Creating server properties in /data/server.properties
[init] Disabling whitelist functionality
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
2023-08-05T14:26:45.332Z        WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.        {"exitCode": 1}
2023-08-05T14:26:45.332Z        INFO    mc-server-runner        Done

**Comment by palivtom** [comment]
What Java version are you running? (Java 8 could be required)

**Comment by itzg** [comment]
Java 8 is indeed required. Refer to https://docker-minecraft-server.readthedocs.io/en/latest/versions/java/#running-minecraft-server-on-different-java-version

**Comment by KillsT3aler69** [comment]
This did indeed fix the issue, thanks!
