### ISSUE TITLE
Error Downloading Paper

### ISSUE THREAD

**Issue by brussom** [itzg/docker-minecraft-server#2336]
### Describe the problem

Cannot download PaperDocker logs trying to download Paper using the latest image

### Container definition

version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: papermcserver
    ports:
      - 25565:25565
    stdin_open: true
    tty: true
    volumes:
      - ./minecraft-data/w2:/data
      - ./plugins:/plugins
      
      
    environment:
     
      EULA: TRUE
      TYPE: PAPER
      
      MAX_MEMORY: "4G"
    
    restart: unless-stopped

### Container logs

2023-08-12 22:21:32 [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 1 1000 1000 512 Aug 13 00:54 /data'
2023-08-12 22:21:32 [init] Resolving type given PAPER
2023-08-12 22:21:37 [mc-image-helper] 05:21:37.105 ERROR : 'install-paper' command failed. Version is 1.33.5
2023-08-12 22:21:37 reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: null: api.papermc.io/104.26.12.138:443
2023-08-12 22:21:37     at reactor.core.Exceptions.propagate(Exceptions.java:408)
2023-08-12 22:21:37     at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
2023-08-12 22:21:37     at reactor.core.publisher.Mono.block(Mono.java:1712)
2023-08-12 22:21:37     at me.itzg.helpers.paper.InstallPaperCommand.useCoordinates(InstallPaperCommand.java:152)
2023-08-12 22:21:37     at me.itzg.helpers.paper.InstallPaperCommand.call(InstallPaperCommand.java:109)
2023-08-12 22:21:37     at me.itzg.helpers.paper.InstallPaperCommand.call(InstallPaperCommand.java:35)
2023-08-12 22:21:37     at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
2023-08-12 22:21:37     at picocli.CommandLine.access$1500(CommandLine.java:148)
2023-08-12 22:21:37     at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
2023-08-12 22:21:37     at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
2023-08-12 22:21:37     at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
2023-08-12 22:21:37     at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
2023-08-12 22:21:37     at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
2023-08-12 22:21:37     at picocli.CommandLine.execute(CommandLine.java:2170)
2023-08-12 22:21:37     at me.itzg.helpers.McImageHelper.main(McImageHelper.java:151)
2023-08-12 22:21:37     Suppressed: java.lang.Exception: #block terminated with an error
2023-08-12 22:21:37             at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
2023-08-12 22:21:37             ... 13 common frames omitted
2023-08-12 22:21:37 Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: null: api.papermc.io/104.26.12.138:443
2023-08-12 22:21:37 Caused by: java.net.NoRouteToHostException: null
2023-08-12 22:21:37     at io.netty.channel.unix.Errors.newConnectException0(Errors.java:158)
2023-08-12 22:21:37     at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
2023-08-12 22:21:37     at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
2023-08-12 22:21:37     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
2023-08-12 22:21:37     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
2023-08-12 22:21:37     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
2023-08-12 22:21:37     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489)
2023-08-12 22:21:37     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
2023-08-12 22:21:37     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-08-12 22:21:37     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-08-12 22:21:37     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-08-12 22:21:37     at java.base/java.lang.Thread.run(Unknown Source)
2023-08-12 22:21:37 [init] ERROR: failed to download paper
2023-08-12 22:22:37 [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 1 1000 1000 512 Aug 13 00:54 /data'
2023-08-12 22:22:37 [init] Resolving type given PAPER
2023-08-12 22:22:41 [mc-image-helper] 05:22:41.985 ERROR : 'install-paper' command failed. Version is 1.33.5
2023-08-12 22:22:41 reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: null: api.papermc.io/104.26.12.138:443
2023-08-12 22:22:41     at reactor.core.Exceptions.propagate(Exceptions.java:408)
2023-08-12 22:22:41     at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
2023-08-12 22:22:41     at reactor.core.publisher.Mono.block(Mono.java:1712)
2023-08-12 22:22:41     at me.itzg.helpers.paper.InstallPaperCommand.useCoordinates(InstallPaperCommand.java:152)
2023-08-12 22:22:41     at me.itzg.helpers.paper.InstallPaperCommand.call(InstallPaperCommand.java:109)
2023-08-12 22:22:41     at me.itzg.helpers.paper.InstallPaperCommand.call(InstallPaperCommand.java:35)
2023-08-12 22:22:41     at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
2023-08-12 22:22:41     at picocli.CommandLine.access$1500(CommandLine.java:148)
2023-08-12 22:22:41     at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
2023-08-12 22:22:41     at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
2023-08-12 22:22:41     at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
2023-08-12 22:22:41     at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
2023-08-12 22:22:41     at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
2023-08-12 22:22:41     at picocli.CommandLine.execute(CommandLine.java:2170)
2023-08-12 22:22:41     at me.itzg.helpers.McImageHelper.main(McImageHelper.java:151)
2023-08-12 22:22:41     Suppressed: java.lang.Exception: #block terminated with an error
2023-08-12 22:22:41             at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
2023-08-12 22:22:41             ... 13 common frames omitted
2023-08-12 22:22:41 Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: null: api.papermc.io/104.26.12.138:443
2023-08-12 22:22:41 Caused by: java.net.NoRouteToHostException: null
2023-08-12 22:22:41     at io.netty.channel.unix.Errors.newConnectException0(Errors.java:158)
2023-08-12 22:22:41     at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
2023-08-12 22:22:41     at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
2023-08-12 22:22:41     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
2023-08-12 22:22:41     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
2023-08-12 22:22:41     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
2023-08-12 22:22:41     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489)
2023-08-12 22:22:41     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
2023-08-12 22:22:41     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-08-12 22:22:41     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-08-12 22:22:41     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-08-12 22:22:41     at java.base/java.lang.Thread.run(Unknown Source)

**Comment by itzg** [comment]
There is something at fault with your particular network/docker system

```
AnnotatedNoRouteToHostException: null: api.papermc.io/104.26.12.138:443
```

**Comment by brussom** [comment]
confirmed. Reinstalled docker desktop and problem resolved.

**Comment by Plugner** [comment]
I'm with this same issue. Was running at VMWare ESXi at the time, but now switched to Proxmox. Trying with a Debian 12 VM.
