### ISSUE TITLE
support offline installation

### ISSUE THREAD

**Issue by willzhang** [itzg/docker-minecraft-server#2340]
### Enhancement Type

A completely new feature

### Describe the enhancement

i want to install minecraft server in offline environment with docker and helm, any way?

I tried to download the server.jar in advance and copy it to the /data directory, but it didn't work.

```
mkdir -p /data/mc/vanilla/data
cp server.jar /data/mc/vanilla/data/minecraft_server.1.20.1.jar
```

```
docker run -d --name vanilla --restart always \
  -e DEBUG=true \
  -e EULA=TRUE \
  -e VERSION=1.20.1 \
  -v /data/mc/vanilla/data:/data \
  -e OPS=willminec \
  -e ONLINE_MODE=FALSE \
  -p 25565:25565 \
  itzg/minecraft-server
```
error logs
```
root@ubuntu:/data/mc/vanilla/data# docker logs -f vanilla 
+ export HOME=/data
+ HOME=/data
++ id -u
++ id -g
++ ls -lnd /data
+ log 'Running as uid=1000 gid=1000 with /data as '\''drwxrwxr-x 2 1000 1000 41 Aug 16 03:43 /data'\'''
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2023-08-16 03:43:39+00:00 Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 41 Aug 16 03:43 /data'
+ '[' '!' -e /data/eula.txt ']'
+ isTrue TRUE
+ case "${1,,}" in
+ return 0
+ writeEula
++ date
+ echo '# Generated via Docker
# Wed 16 Aug 2023 03:43:39 AM UTC
eula=true
'
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ echo password=ef6e354391248c80bcb19aa4
+ fixJavaPath
+ which java
+ cd /data
+ export ORIGINAL_TYPE=VANILLA
+ ORIGINAL_TYPE=VANILLA
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ : ''
+ case "${TYPE^^}" in
+ [[ -n '' ]]
+ log 'Resolving type given VANILLA'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2023-08-16 03:43:39+00:00 Resolving type given VANILLA
+ case "${TYPE^^}" in
+ exec /start-deployVanilla
+ set -o pipefail
+ resolveVersion
+ givenVersion=1.20.1
++ mc-image-helper resolve-minecraft-version 1.20.1
[mc-image-helper] 03:43:46.131 ERROR : 'resolve-minecraft-version' command failed. Version is 1.33.5
reactor.core.Exceptions$ReactiveException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'launchermeta.mojang.com' [A(1)] and search domain query for configured domains failed as well: [.]
        at reactor.core.Exceptions.propagate(Exceptions.java:408)
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
        at reactor.core.publisher.Mono.block(Mono.java:1712)
        at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:26)
        at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:151)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
                ... 12 common frames omitted
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'launchermeta.mojang.com' [A(1)] and search domain query for configured domains failed as well: [.]
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1097)
        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1044)
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:432)
        at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:66)
        at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:500)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
        at io.netty.resolver.dns.DnsQueryContext.finishFailure(DnsQueryContext.java:348)
        at io.netty.resolver.dns.DnsQueryContext$5.run(DnsQueryContext.java:290)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [50214: /192.168.72.16:53] DefaultDnsQuestion(launchermeta.mojang.com. IN A) query '50214' via UDP timed out after 5000 milliseconds (no stack trace available)
+ VERSION=
+ exit 2
```

maybe it still connnect internet to `resolveVersion`  when minecraft_server.1.20.1.jar already exsits

[resolveVersion](https://github.com/itzg/docker-minecraft-server/blob/316b79bf72ee75535117ec20fc314ed9121431ea/scripts/start-deployVanilla#L8C1-L8C15)

**Comment by itzg** [comment]
Have you tried the custom server type? 

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/server-types/others/#custom

**Comment by willzhang** [comment]
thanks, it work
```
docker run -d --name vanilla --restart always \
  -e TYPE=CUSTOM \
  -e CUSTOM_SERVER=/data/minecraft_server.1.20.1.jar \
  -e DEBUG=true \
  -e EULA=TRUE \
  -v /data/mc/vanilla/data:/data \
  -e ONLINE_MODE=default \
  -p 25565:25565 \
  itzg/minecraft-server
```
