### ISSUE TITLE
Modrinth auto installer doesn't work on java8

### ISSUE THREAD

**Issue by Jefemy** [itzg/docker-minecraft-server#2344]
### Describe the problem

When using the java8 container the install-modrinth-modpack command fails. Can be worked around by using the latest tag to run the installer and then changing the `TYPE` from `MODRINTH` to the proper API after it installs the first time.

### Container definition

Original broken container
```
  losteratest:
    image: itzg/minecraft-server:java8
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "p87Jiw2q"
      MODRINTH_VERSION: "1.6.1"

      MOTD: "lostera server"
      MAX_TICK_TIME: -1
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 16
      WORLD_TYPE: "BIOMESOP"

      DIFFICULTY: "easy"

      OVERRIDE_SERVER_PROPERTIES: "true"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"
      SYNC_CHUNK_WRITES: "false"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: 300
      AUTOPAUSE_TIMEOUT_INIT: 30
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
        - /losteratest:/data
```

This container works perfectly fine for initial install
```
  losteratest:
    image: itzg/minecraft-server:latest
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "p87Jiw2q"
      MODRINTH_VERSION: "1.6.1"

      MOTD: "lostera server"
      MAX_TICK_TIME: -1
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 16
      WORLD_TYPE: "BIOMESOP"

      DIFFICULTY: "easy"

      OVERRIDE_SERVER_PROPERTIES: "true"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"
      SYNC_CHUNK_WRITES: "false"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: 300
      AUTOPAUSE_TIMEOUT_INIT: 30
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
        - /losteratest:/data
```

After running above container this works fine. Cant use TYPE: MODRINTH as it still runs the autoinstaller after the files are already there.
```
  lostera:
    image: itzg/minecraft-server:java8
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.7.10"
      #MODRINTH_MODPACK: "p87Jiw2q"
      #MODRINTH_VERSION: "1.6.1"

      MOTD: "lostera server"
      MAX_TICK_TIME: -1
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 16
      WORLD_TYPE: "BIOMESOP"

      DIFFICULTY: "easy"

      OVERRIDE_SERVER_PROPERTIES: "true"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"
      SYNC_CHUNK_WRITES: "false"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: 300
      AUTOPAUSE_TIMEOUT_INIT: 30
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
        - /losteratest:/data
```

### Container logs

```
[mc-image-helper] 19:51:04.802 ERROR : 'install-modrinth-modpack' command failed. Version is 1.34.0
java.lang.NullPointerException: null
        at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.buildModpackFetcher(InstallModrinthModpackCommand.java:119)
        at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.call(InstallModrinthModpackCommand.java:82)
        at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.call(InstallModrinthModpackCommand.java:16)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:153)
[init] ERROR failed to install Modrinth modpack
```

**Comment by itzg** [comment]
Thanks. I'll look into this.

**Comment by Jefemy** [comment]
I updated my container and it now does appear to be working on the first run of the installer however it then errors with this every time after that

```
[mc-image-helper] 03:25:10.085 ERROR : 'install-modrinth-modpack' command failed. Version is 1.34.2
java.lang.NullPointerException: null
        at me.itzg.helpers.modrinth.ModrinthApiPackFetcher.needsInstall(ModrinthApiPackFetcher.java:64)
        at me.itzg.helpers.modrinth.ModrinthApiPackFetcher.lambda$fetchModpack$0(ModrinthApiPackFetcher.java:39)
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:104)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
        at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
                at reactor.core.publisher.Mono.block(Mono.java:1712)
                at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.call(InstallModrinthModpackCommand.java:105)
                at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.call(InstallModrinthModpackCommand.java:16)
                at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
                at picocli.CommandLine.access$1500(CommandLine.java:148)
                at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
                at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
                at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
                at picocli.CommandLine.execute(CommandLine.java:2170)
                at me.itzg.helpers.McImageHelper.main(McImageHelper.java:153)
                ```
                
Here is my container
```
  losteratest:
    image: itzg/minecraft-server:java8
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "p87Jiw2q"
      MODRINTH_VERSION: "1.6.1"

      MOTD: "lostera server"
      MAX_TICK_TIME: -1
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 16
      WORLD_TYPE: "BIOMESOP"

      DIFFICULTY: "easy"

      OVERRIDE_SERVER_PROPERTIES: "true"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"
      SYNC_CHUNK_WRITES: "false"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: 300
      AUTOPAUSE_TIMEOUT_INIT: 30
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /losteratest:/data
```

**Comment by Jefemy** [comment]
Looks like this issue is for all of the versions as one of my containers running `latest` is now showing this error after a restart
```
[mc-image-helper] 21:51:11.925 ERROR : 'install-modrinth-modpack' command failed. Version is 1.34.2
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "me.itzg.helpers.modrinth.ModrinthModpackManifest.getVersionId()" is null
        at me.itzg.helpers.modrinth.ModrinthApiPackFetcher.needsInstall(ModrinthApiPackFetcher.java:64)
        at me.itzg.helpers.modrinth.ModrinthApiPackFetcher.lambda$fetchModpack$0(ModrinthApiPackFetcher.java:39)
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:104)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
        at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
                at reactor.core.publisher.Mono.block(Mono.java:1712)
                at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.call(InstallModrinthModpackCommand.java:105)
                at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.call(InstallModrinthModpackCommand.java:16)
                at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
                at picocli.CommandLine.access$1500(CommandLine.java:148)
                at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
                at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
                at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
                at picocli.CommandLine.execute(CommandLine.java:2170)
                at me.itzg.helpers.McImageHelper.main(McImageHelper.java:153)
```

**Comment by itzg** [comment]
Capturing findings [from Discord](https://discord.com/channels/660567679458869252/1142247804513812582/1142260838057652274)

> i think i found the issue with mcinstance
it removes a file after first install but then the modrinth installer adds it back
config/mcinstanceloader/pack.mcinstance
it only does the install+restart process when that exists so its just an issue with how the mod works

**Comment by itzg** [comment]
Added a new option to ignore files like that https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/modrinth-modpacks/#ignore-missing-files
