### ISSUE TITLE
Bad packet 254

### ISSUE THREAD

**Issue by Octelly** [itzg/docker-minecraft-server#2359]
### Describe the problem

Trying to host a Better than Adventure server, log keeps getting spammed. Doesn't happen outside on host (outside Docker). I'm assuming it's the included healthcheck script, which has always worked flawlessly for any release version I've tried. Is there perhaps an undocumented ENV variable for disabling it or something?

### Container definition

```yml
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      VERSION: "1.0"

      MEMORY: "6G"
      USE_AIKAR_FLAGS: "true"

      TYPE: "CUSTOM"
      CUSTOM_SERVER: "https://github.com/Better-than-Adventure/bta-download-repo/releases/download/v1.7.7.0_01/better-than-adventure-1.7.7.0_01-server.jar"
    restart: unless-stopped
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
```

### Container logs

```
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:55:15 INFO  Minecraft - /127.0.0.1:54506 lost connection
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:55:20 INFO  Minecraft - /127.0.0.1:59354 lost connection
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:55:25 INFO  Minecraft - /127.0.0.1:59364 lost connection
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:55:30 INFO  Minecraft - /127.0.0.1:54022 lost connection
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:55:36 INFO  Minecraft - /127.0.0.1:37490 lost connection
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:55:41 INFO  Minecraft - /127.0.0.1:37498 lost connection
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:55:46 INFO  Minecraft - /127.0.0.1:58850 lost connection
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:55:51 INFO  Minecraft - /127.0.0.1:58862 lost connection
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:55:56 INFO  Minecraft - /127.0.0.1:38022 lost connection
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:56:01 INFO  Minecraft - /127.0.0.1:38038 lost connection
bta-docker-mc-1  | java.io.IOException: Bad packet id 254
bta-docker-mc-1  | 	at net.minecraft.core.net.packet.Packet.readPacket(Packet.java:86)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readPacket(NetworkManager.java:136)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkManager.readNetworkPacket(NetworkManager.java:257)
bta-docker-mc-1  | 	at net.minecraft.core.net.NetworkReaderThread.run(NetworkReaderThread.java:31)
bta-docker-mc-1  | 2023-08-24 17:56:06 INFO  Minecraft - /127.0.0.1:40746 lost connection
```

**Comment by itzg** [comment]
Via VERSION you're telling it you're running a 1.0 server and it's using an old server ping protocol. Either set VERSION properly or as you were wondering, disable health check https://docker-minecraft-server.readthedocs.io/en/latest/misc/healthcheck/#healthcheck

**Comment by Octelly** [comment]
You're correct. I didn't find any documentation on how to specify beta or earlier versions. I tried ``B1.7.3`` and that didn't do anything.
And I missed the last paragraph in the healtcheck docs, sorry for that.

**Comment by lightlike** [comment]
It looks like Minecraft Server only impelemented a ping method from Beta 1.8 on.
At least that is the earliest I could find. (See: https://wiki.vg/Server_List_Ping#Beta_1.8_to_1.3)

It seems that we need to disable healthcheck for any older Servers or ask the BtA Developers for something.

**Comment by itzg** [comment]
Thanks @lightlike . I knew < 1.7 was a breakpoint for using the older server list ping (SLP) but hadn't noticed the < 1.3 caveat. Agreed, it should just disable health check (by setting that env var) for those versions.

**Comment by itzg** [comment]
If either of you want to PR that, the relevant code is around here

https://github.com/itzg/docker-minecraft-server/blob/8fd149579526532c120d173f9864918bf645abb6/scripts/start-finalExec#L224-L232

**Comment by lightlike** [comment]
Just some questions so I understand this correctly (Rx.x for Release, Bx.x for Beta Versions):

So the current docker only supports the R1.7+ ping and the ping from Version R1.6 with the argument `--use-server-list-ping`.
The older versions should still be compatible with these R1.6 Ping as they should just ignore every Byte after their relevant data. (If that assumption is correct, I will probably test that with a simple server when I have time later)
So the earliest version that is supported should be B1.8.

If that is the case how would beta versions be differentiated from Release Versions in `start-finalExec`?
Does the version comparison work with something like `Bx.x`?

**Comment by lightlike** [comment]
I found the version comparison. I'll try to implement that using the `bx.x`-Format.

**Comment by itzg** [comment]
> I found the version comparison. I'll try to implement that using the `bx.x`-Format.

Yes, "release" versions don't have a prefix. Beta versions have the "b" prefix.
