### ISSUE TITLE
cant define OPS

### ISSUE THREAD

**Issue by shoham-elad** [itzg/docker-minecraft-server#2378]
### Describe the problem

When adding OPS to and env var, its is not respected.
Also, ops.json is always overridden to an empty list (`[]`) even if manually edited.

seems like I am unable to add an OPS in any way

I am running on casaos

### Container definition

```
docker run -d \
-p 25564:25565 \
-v /DATA/AppData/mc-data/:/data \
-e EULA=TRUE \
-e OPS="USER" \
--name minecraft \
itzg/minecraft-server
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 7 1000 1000 4096 Sep 10 16:33 /data'
[init] Resolving type given VANILLA
[init] Resolved version given LATEST into 1.20.1
[mc-image-helper] 16:34:05.530 INFO  : The file ./ops.json already exists, so no changes will be made
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 7 1000 1000 4096 Sep 10 16:33 /data'
[init] Resolving type given VANILLA
[init] Resolved version given LATEST into 1.20.1
[mc-image-helper] 16:35:49.570 INFO  : The file ./ops.json already exists, so no changes will be made
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
Starting net.minecraft.server.Main
[16:36:54] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:37:03] [ServerMain/INFO]: Loaded 7 recipes
[16:37:04] [ServerMain/INFO]: Loaded 1271 advancements
[16:37:07] [Server thread/INFO]: Starting minecraft server version 1.20.1
[16:37:07] [Server thread/INFO]: Loading properties
[16:37:07] [Server thread/INFO]: Default game type: SURVIVAL
[16:37:07] [Server thread/INFO]: Generating keypair
[16:37:07] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:37:08] [Server thread/INFO]: Using epoll channel type
[16:37:08] [Server thread/WARN]: Failed to load operators list: 
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive; at path $
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1010) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1062) ~[gson-2.10.jar:?]
	at alp.f(SourceFile:118) ~[server-1.20.1.jar:?]
	at ahd.A(SourceFile:93) ~[server-1.20.1.jar:?]
	at ahd.<init>(SourceFile:28) ~[server-1.20.1.jar:?]
	at ahe.e(SourceFile:161) ~[server-1.20.1.jar:?]
	at net.minecraft.server.MinecraftServer.w(SourceFile:646) ~[server-1.20.1.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:265) ~[server-1.20.1.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[16:37:08] [Server thread/INFO]: Preparing level "world"
[16:37:30] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:37:31] [Server thread/INFO]: Preparing spawn area: 0%
.....
[16:38:14] [Worker-Main-2/INFO]: Preparing spawn area: 98%
[16:38:14] [User Authenticator #1/INFO]: UUID of player USER is 00000000-0000-0000-0000-000000000000
[16:38:14] [Worker-Main-2/INFO]: Preparing spawn area: 98%
[16:38:14] [Worker-Main-2/INFO]: Preparing spawn area: 99%
[16:38:15] [Server thread/INFO]: Time elapsed: 44125 ms
[16:38:15] [Server thread/INFO]: Done (66.231s)! For help, type "help"
[16:38:15] [Server thread/INFO]: Starting remote control listener
[16:38:15] [Server thread/INFO]: Thread RCON Listener started
[16:38:15] [Server thread/INFO]: RCON running on 0.0.0.0:25575
[16:38:15] [Server thread/INFO]: USER[/x.x.x.x:54142] logged in with entity id 1 at (52.49468668786936, 63.0625, 21.50220777891973)
[16:38:15] [Server thread/INFO]: USER joined the game

```

**Comment by itzg** [comment]
This is way too vague. The issue template requests container configs and logs. Provide those to receive any further assistance.

**Comment by shoham-elad** [comment]
edited. thanks. if you need any more info please let me know

**Comment by itzg** [comment]
Thanks. The relevant log line is

```
[mc-image-helper] 16:35:49.570 INFO  : The file ./ops.json already exists, so no changes will be made
```

Set `EXISTING_OPS_FILE` according to https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#opadministrator-players

I'm now thinking I should have it mention that variable in the log.

**Comment by shoham-elad** [comment]
thank you
