### ISSUE TITLE
Forge with MC 1.12.2 and docker compose not working

### ISSUE THREAD

**Issue by TimoWL** [itzg/docker-minecraft-server#2410]
### Describe the problem

Hello,

using the following docker compose leads to the following error. How can I fix this?

### Container definition

version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      DEBUG: "true"
      VERSION: 1.12.2
      FORGE_VERSION: 14.23.5.2860
    tty: true
    stdin_open: true
    restart: "no"
    volumes:
      - XXXXX Mine works. :)

### Container logs

+ exec mc-server-runner --stop-duration 60s --named-pipe /tmp/minecraft-console-in java -Xmx1G -Xms1G -javaagent:/image/Log4jPatcher.jar -Dlog4j2.formatMsgNoLookups=true -jar forge-1.12.2-14.23.5.2860.jar
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
2023-10-05T18:58:57.318Z        WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.     {"exitCode": 1}
2023-10-05T18:58:57.318Z        INFO    mc-server-runner        Done

**Comment by itzg** [comment]
You need to be using a Java 8 image for 1.12

https://docker-minecraft-server.readthedocs.io/en/latest/versions/java/

**Comment by TimoWL** [comment]
It worked, thank you. Attached is my docker compose for future people with that question.

version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      DEBUG: "true"
      VERSION: 1.12.2
      FORGE_VERSION: 14.23.5.2860
    tty: true
    stdin_open: true
    restart: "no"
    volumes:
      - your volume
