### ISSUE TITLE
Container not starting, 'install-curseforge' command failed

### ISSUE THREAD

**Issue by spookyX01** [itzg/docker-minecraft-server#2442]
### Describe the problem

I'm not sure if I am missing something but whenever I would run this docker compose it would fail to install curseforge. I tried looking at other issues and fixing it myself but I am not sure what the problem is. 

### Container definition

version: "3.9"

networks:
  mc0:
    name: mc0
    enable_ipv6: false
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
    driver_opts:
      com.docker.network.bridge.name: mc0

services:

  atm8:
    container_name: atm8
    hostname: atm8
    image: itzg/minecraft-server:java19
    volumes:
    - /opt/atm8/modpacks:/modpacks:ro
    - /opt/atm8/data:/data
    - /mnt:/mnt
    environment:
    - EULA=TRUE
    - TYPE=AUTO_CURSEFORGE
    - VERSION=1.19.2
    - CF_PAGE=https://www.curseforge.com/minecraft/modpacks/all-the-mods-8
    - CF_SLUG=all-the-mods-8
    - CF_FILE_ID=4787465
    - CF_API_KEY=$$2a$$10$$
    - TZ=EST
    - MEMORY=16G
    - ENABLE_RCON=true
    - RCON_PASSWORD=$PASSWORD
    - RCON_PORT=25575
    ports:
      - 25565:25565
      - 25575:25575
    restart: unless-stopped
    networks:
      mc0:
        ipv4_address: 192.168.90.10

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Oct 17 04:25 /data'
[init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
[init] Resolving type given AUTO_CURSEFORGE
[mc-image-helper] 21:03:19.985 INFO  : Processing modpack 'All the Mods 8-1.0.28' (all-the-mods-8) @ 520914:4787465
[mc-image-helper] 21:03:20.173 ERROR : 'install-curseforge' command failed. Version is 1.29.1
me.itzg.helpers.errors.GenericException: Failed to parse response body into class me.itzg.helpers.curseforge.model.ModsSearchResponse: Cannot deserialize value of type `me.itzg.helpers.curseforge.model.ModLoaderType` from String "6": not one of the values accepted for Enum class: [0, 1, 2, 3, 4, 5]
 at [Source: (reactor.netty.ByteBufMono$ReleasingInputStream); line: 1, column: 3339] (through reference chain: me.itzg.helpers.curseforge.model.ModsSearchResponse["data"]->java.util.ArrayList[0]->me.itzg.helpers.curseforge.model.CurseForgeMod["latestFilesIndexes"]->java.util.ArrayList[1]->me.itzg.helpers.curseforge.model.FileIndex["modLoader"])
        at me.itzg.helpers.http.ObjectFetchBuilder.lambda$handleResponse$1(ObjectFetchBuilder.java:89)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
        at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Mono.block(Mono.java:1710)
                at me.itzg.helpers.curseforge.CurseForgeInstaller.resolveExcludeIncludes(CurseForgeInstaller.java:546)
                at me.itzg.helpers.curseforge.CurseForgeInstaller.processModpack(CurseForgeInstaller.java:463)
                at me.itzg.helpers.curseforge.CurseForgeInstaller.resolveModpackFileAndProcess(CurseForgeInstaller.java:327)
                at me.itzg.helpers.curseforge.CurseForgeInstaller.installByRetrievingModpackZip(CurseForgeInstaller.java:201)
                at me.itzg.helpers.curseforge.CurseForgeInstaller.lambda$install$4(CurseForgeInstaller.java:135)
                at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:170)
                at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:134)
                at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:189)
                at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:24)
                at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
                at picocli.CommandLine.access$1500(CommandLine.java:148)
                at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
                at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
                at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
                at picocli.CommandLine.execute(CommandLine.java:2170)
                at me.itzg.helpers.McImageHelper.main(McImageHelper.java:139)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `me.itzg.helpers.curseforge.model.ModLoaderType` from String "6": not one of the values accepted for Enum class: [0, 1, 2, 3, 4, 5]
 at [Source: (reactor.netty.ByteBufMono$ReleasingInputStream); line: 1, column: 3339] (through reference chain: me.itzg.helpers.curseforge.model.ModsSearchResponse["data"]->java.util.ArrayList[0]->me.itzg.helpers.curseforge.model.CurseForgeMod["latestFilesIndexes"]->java.util.ArrayList[1]->me.itzg.helpers.curseforge.model.FileIndex["modLoader"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002)
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:415)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._fromString(EnumDeserializer.java:279)
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:258)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
        at me.itzg.helpers.http.ObjectFetchBuilder.lambda$handleResponse$1(ObjectFetchBuilder.java:85)
        ... 9 common frames omitted
[init] ERROR failed to auto-install CurseForge modpack
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Oct 17 04:25 /data'
[init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
[init] Resolving type given AUTO_CURSEFORGE

**Comment by itzg** [comment]
This has already been fixed. You need to re-pull the latest image.

**Comment by spookyX01** [comment]
I re-pulled the image. Still got the same error, so I deleted the and re-pulled then restarted. Still got the same issue. You just have to run 'docker pull itzg/minecraft-server' right?

**Comment by spookyX01** [comment]
Nevermind! Sorry please ignore my last message I was confused

**Comment by itzg** [comment]
Two things

- You need to pull the actual image you're using. Calling `docker compose pull` solves that 
- The java19 image tag is deprecated. Use one of the active image tags, such as `latest` or `java20`

**Comment by KairunHanjun** [comment]
Same here, i am using docker compose with server zip
mc-1  | [mc-image-helper] 11:37:05.507 ERROR : 'install-curseforge' command failed. Version is 1.61.0
mc-1  | java.lang.NullPointerException: Cannot invoke "me.itzg.helpers.curseforge.model.MinecraftModpackManifest.getOverrides()" because "modpackManifest" is null
mc-1  |         at me.itzg.helpers.curseforge.CurseForgeInstaller.resolveModpackFileAndProcess(CurseForgeInstaller.java:421)
mc-1  |         at me.itzg.helpers.curseforge.CurseForgeInstaller.installByRetrievingModpackZip(CurseForgeInstaller.java:278)
mc-1  |         at me.itzg.helpers.curseforge.CurseForgeInstaller.lambda$install$3(CurseForgeInstaller.java:200)
mc-1  |         at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:246)
mc-1  |         at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:199)
mc-1  |         at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:265)
mc-1  |         at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:33)
mc-1  |         at picocli.CommandLine.executeUserObject(CommandLine.java:2031)
mc-1  |         at picocli.CommandLine.access$1500(CommandLine.java:148)
mc-1  |         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2469)
mc-1  |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2461)
mc-1  |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2423)
mc-1  |         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
mc-1  |         at picocli.CommandLine$RunLast.execute(CommandLine.java:2425)
mc-1  |         at picocli.CommandLine.execute(CommandLine.java:2174)
mc-1  |         at me.itzg.helpers.McImageHelper.main(McImageHelper.java:182)
mc-1  | [init] [ERROR] Failed to auto-install CurseForge modpack
