### ISSUE TITLE
On start mc-image-helper fails with timeout

### ISSUE THREAD

**Issue by johannes-wolf** [itzg/docker-minecraft-server#2463]
### Describe the problem

When starting the container, the `mc-image-helper` fails with the following message:
```
[mc-image-helper] 15:22:09.641 ERROR : 'resolve-minecraft-version' command failed. Version is 1.36.5
mc_1  | reactor.core.Exceptions$ReactiveException: io.netty.channel.ConnectTimeoutException: connection timed out: launchermeta.mojang.com/13.107.246.45:443
```

### Container definition

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      VERSION: "1.20.2"
      WHITELIST_FILE: "/data/whitelist"
      OPS_FILE: "/data/admins"
    volumes:
      - ./data:/data
```

### Container logs

```
mc_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 3 1000 1000 4096 Nov  3 15:07 /data'
mc_1  | [init] Resolving type given VANILLA
mc_1  | [mc-image-helper] 15:22:09.641 ERROR : 'resolve-minecraft-version' command failed. Version is 1.36.5
mc_1  | reactor.core.Exceptions$ReactiveException: io.netty.channel.ConnectTimeoutException: connection timed out: launchermeta.mojang.com/13.107.246.45:443
mc_1  |         at reactor.core.Exceptions.propagate(Exceptions.java:408)
mc_1  |         at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
mc_1  |         at reactor.core.publisher.Mono.block(Mono.java:1712)
mc_1  |         at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:26)
mc_1  |         at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:12)
mc_1  |         at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
mc_1  |         at picocli.CommandLine.access$1500(CommandLine.java:148)
mc_1  |         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
mc_1  |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
mc_1  |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
mc_1  |         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
mc_1  |         at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
mc_1  |         at picocli.CommandLine.execute(CommandLine.java:2170)
mc_1  |         at me.itzg.helpers.McImageHelper.main(McImageHelper.java:157)
mc_1  |         Suppressed: java.lang.Exception: #block terminated with an error
mc_1  |                 at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
mc_1  |                 ... 12 common frames omitted
mc_1  | Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: launchermeta.mojang.com/13.107.246.45:443
mc_1  |         at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
mc_1  |         at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
mc_1  |         at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
mc_1  |         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
mc_1  |         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
mc_1  |         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
mc_1  |         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
mc_1  |         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
mc_1  |         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
mc_1  |         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
mc_1  |         at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by dlabreu** [comment]
+1 here same issue.

**Comment by johannes-wolf** [comment]
Maybe it is a routing issue on my side?

**Comment by itzg** [comment]
Let's not reopen an issue I can't fix...but I will convert to a discussion so it's more visible.
