### ISSUE TITLE
failed to ping localhost:25565 : read tcp 127.0.0.1:56970->127.0.0.1:25565: read: connection reset by peer

### ISSUE THREAD

**Issue by Colon101** [itzg/docker-minecraft-server#2469]
### Describe the problem

I just repeatedly get this error

```

Nov 06, 2023 9:56:05 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught

WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.lang.RuntimeException: Unable to access address of buffer

	at io.netty.channel.epoll.Native.read(Native Method)

	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678)

	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714)

	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755)

	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)

	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)

	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)

	at java.base/java.lang.Thread.run(Unknown Source)



```

### Container definition

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"

      VERSION: "1.8.8"

    volumes:
      - /root/storage/minecraft/testv3:/data
```

### Container logs

[_minecraft-mc-1_logs.txt](https://github.com/itzg/docker-minecraft-server/files/13272984/_minecraft-mc-1_logs.txt)

**Comment by Colon101** [comment]
my bad for not thinking before sending this turns out i just needed to add the java8-jdk tag and everything got fixed 🤦‍♂️

**Comment by duxt3r** [comment]
Hey @Colon101 
I get the same error but don't understand how you fixed it. Would you mind explaining where you added the "java8-jdk tag" and what code is involved? Cheers
