### ISSUE TITLE
java.lang.illegalAccessError when trying to startup FORGE server

### ISSUE THREAD

**Issue by KinoKiru** [itzg/docker-minecraft-server#2475]
### Describe the problem

As defined in my container definition i want to setup a server using minecraft forge 1.16.5 for some reason this version and the version below 1.16.4 are giving the same error is there something wrong with my definition or is it just forge?

### Container definition

```
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: TRUE
      TYPE: FORGE
      VERSION: 1.16.5
      REMOVE_OLD_MODS: true
      MEMORY: 4g
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./modpack:/mods:ro
    restart: unless-stopped

volumes:
  data:

```

### Container logs

```
[+] Building 0.0s (0/0)                                                                                                                        docker:default
[+] Running 1/0
 ✔ Container minecraft-server-mc-1  Recreated                                                                                                            0.1s 
Attaching to minecraft-server-mc-1
minecraft-server-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 9 1000 1000 4096 Nov  9 18:34 /data'
minecraft-server-mc-1  | [init] Resolving type given FORGE
minecraft-server-mc-1  | [mc-image-helper] 18:37:15.515 INFO  : Re-installing Forge due to version change from MC 1.16.5/Forge 36.2.34 to MC 1.16.4/Forge 35.1.4
minecraft-server-mc-1  | [mc-image-helper] 18:37:15.516 INFO  : Downloading Forge installer 35.1.4 for Minecraft 1.16.4
minecraft-server-mc-1  | [mc-image-helper] 18:37:16.693 INFO  : Running Forge installer. This might take a while...
minecraft-server-mc-1  | [init] Removing old mods including:*.jar,*-version.json excluding:
minecraft-server-mc-1  | [mc-image-helper] 18:37:35.391 INFO  : Created/updated 1 property in /data/server.properties
minecraft-server-mc-1  | [init] Setting initial memory to 4g and max to 4g
minecraft-server-mc-1  | [init] Starting the Minecraft server...
minecraft-server-mc-1  | [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
minecraft-server-mc-1  | [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
minecraft-server-mc-1  | 2023-11-09 18:37:39,244 main WARN Advanced terminal features are not available in this environment
minecraft-server-mc-1  | [18:37:39] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 35.1.4, --fml.mcpVersion, 20201102.104115, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge]
minecraft-server-mc-1  | [18:37:39] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 17.0.9 by Eclipse Adoptium
minecraft-server-mc-1  | Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x4c873330) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x4c873330
minecraft-server-mc-1  |        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
minecraft-server-mc-1  |        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
minecraft-server-mc-1  |        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
minecraft-server-mc-1  |        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
minecraft-server-mc-1  |        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
minecraft-server-mc-1  |        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
minecraft-server-mc-1  |        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
minecraft-server-mc-1  |        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
minecraft-server-mc-1  |        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
minecraft-server-mc-1  |        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
minecraft-server-mc-1  |        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
minecraft-server-mc-1  |        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
minecraft-server-mc-1  |        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
minecraft-server-mc-1  | 2023-11-09T18:37:39.374Z       WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.      {"exitCode": 1}
minecraft-server-mc-1  | 2023-11-09T18:37:39.374Z       INFO    mc-server-runner        Done
minecraft-server-mc-1 exited with code 0
```

**Comment by KinoKiru** [comment]
changed the java version and it worked nvm me

**Comment by Soon5** [comment]
@KinoKiru 
Do you mind describing how you fixed it? I am running in the same issue...

**Comment by Soon5** [comment]
Ok, I figured it out:
For everyone else: use "image: itzg/minecraft-server:java8" in the compose file (or any other java8 Version)
