### ISSUE TITLE
World Download Integer Overflow

### ISSUE THREAD

**Issue by jay-lane** [itzg/docker-minecraft-server#2491]
I've been using the charts for a long time without any issues, they have worked perfectly.  I recently migrated my long time server from cloud to home lab.  The total server backup is >2GB.  When I try to download the world with the helm chart, it causes an Integer overflow check to fail.  I've never seen this before, but is this something I missed in configuration?  Is it a JVM limitation?
```

2023-11-13 07:26:04.218 | [init] Downloading world from https://cloudobjectstorage/world-20231016-125154.tgz |  
-- | -- | --
  |   | 2023-11-13 07:26:30.146 | [mc-image-helper] 12:26:30.142 ERROR : 'get' command failed. Version is 1.36.7 |  
  **|   | 2023-11-13 07:26:30.146 | java.lang.IllegalArgumentException: Can't increase by 4096 as capacity(2147479552) would overflow 2147483647 |**  
  |   | 2023-11-13 07:26:30.146 | at io.netty.buffer.CompositeByteBuf.checkForOverflow(CompositeByteBuf.java:272) |  
  |   | 2023-11-13 07:26:30.146 | at io.netty.buffer.CompositeByteBuf.addComponent0(CompositeByteBuf.java:292) |  
  |   | 2023-11-13 07:26:30.147 | at io.netty.buffer.CompositeByteBuf.addComponents(CompositeByteBuf.java:550) |  
  |   | 2023-11-13 07:26:30.147 | at io.netty.buffer.CompositeByteBuf.addComponents(CompositeByteBuf.java:251) |  
  |   | 2023-11-13 07:26:30.147 | at reactor.netty.ByteBufFlux.lambda$aggregate$7(ByteBufFlux.java:283) |  
  |   | 2023-11-13 07:26:30.147 | at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:179) |  
  |   | 2023-11-13 07:26:30.147 | at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) |  
  |   | 2023-11-13 07:26:30.148 | at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071) |  
  |   | 2023-11-13 07:26:30.149 | at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) |  
  |   | 2023-11-13 07:26:30.149 | at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) |  
  |   | 2023-11-13 07:26:30.149 | at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) |  
  |   | 2023-11-13 07:26:30.149 | at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:413) |  
  |   | 2023-11-13 07:26:30.149 | at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:444) |  
  |   | 2023-11-13 07:26:30.150 | at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:498) |  
  |   | 2023-11-13 07:26:30.150 | at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:753) |  
  |   | 2023-11-13 07:26:30.150 | at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) |  
  |   | 2023-11-13 07:26:30.150 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) |  
  |   | 2023-11-13 07:26:30.150 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) |  
  |   | 2023-11-13 07:26:30.151 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) |  
  |   | 2023-11-13 07:26:30.151 | at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) |  
  |   | 2023-11-13 07:26:30.151 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) |  
  |   | 2023-11-13 07:26:30.151 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) |  
  |   | 2023-11-13 07:26:30.152 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) |  
  |   | 2023-11-13 07:26:30.152 | at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) |  
  |   | 2023-11-13 07:26:30.152 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) |  
  |   | 2023-11-13 07:26:30.152 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) |  
  |   | 2023-11-13 07:26:30.152 | at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) |  
  |   | 2023-11-13 07:26:30.153 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) |  
  |   | 2023-11-13 07:26:30.153 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) |  
  |   | 2023-11-13 07:26:30.153 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) |  
  |   | 2023-11-13 07:26:30.153 | at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1471) |  
  |   | 2023-11-13 07:26:30.153 | at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1334) |  
  |   | 2023-11-13 07:26:30.154 | at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1383) |  
  |   | 2023-11-13 07:26:30.154 | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) |  
  |   | 2023-11-13 07:26:30.154 | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) |  
  |   | 2023-11-13 07:26:30.154 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) |  
  |   | 2023-11-13 07:26:30.154 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) |  
  |   | 2023-11-13 07:26:30.155 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) |  
  |   | 2023-11-13 07:26:30.155 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) |  
  |   | 2023-11-13 07:26:30.155 | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) |  
  |   | 2023-11-13 07:26:30.155 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) |  
  |   | 2023-11-13 07:26:30.155 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) |  
  |   | 2023-11-13 07:26:30.156 | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) |  
  |   | 2023-11-13 07:26:30.156 | at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) |  
  |   | 2023-11-13 07:26:30.156 | at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) |  
  |   | 2023-11-13 07:26:30.156 | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) |  
  |   | 2023-11-13 07:26:30.157 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) |  
  |   | 2023-11-13 07:26:30.157 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) |  
  |   | 2023-11-13 07:26:30.157 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) |  
  |   | 2023-11-13 07:26:30.157 | at java.base/java.lang.Thread.run(Unknown Source) |  
  |   | 2023-11-13 07:26:30.157 | Suppressed: java.lang.Exception: #block terminated with an error |  
  |   | 2023-11-13 07:26:30.158 | at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103) |  
  |   | 2023-11-13 07:26:30.158 | at reactor.core.publisher.Mono.block(Mono.java:1712) |  
  |   | 2023-11-13 07:26:30.158 | at me.itzg.helpers.http.SpecificFileFetchBuilder.execute(SpecificFileFetchBuilder.java:53) |  
  |   | 2023-11-13 07:26:30.158 | at me.itzg.helpers.get.GetCommand.call(GetCommand.java:221) |  
  |   | 2023-11-13 07:26:30.159 | at me.itzg.helpers.get.GetCommand.call(GetCommand.java:55) |  
  |   | 2023-11-13 07:26:30.159 | at picocli.CommandLine.executeUserObject(CommandLine.java:2041) |  
  |   | 2023-11-13 07:26:30.159 | at picocli.CommandLine.access$1500(CommandLine.java:148) |  
  |   | 2023-11-13 07:26:30.160 | at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) |  
  |   | 2023-11-13 07:26:30.160 | at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) |  
  |   | 2023-11-13 07:26:30.160 | at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) |  
  |   | 2023-11-13 07:26:30.160 | at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) |  
  |   | 2023-11-13 07:26:30.161 | at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) |  
  |   | 2023-11-13 07:26:30.161 | at picocli.CommandLine.execute(CommandLine.java:2170) |  
  |   | 2023-11-13 07:26:30.161 | at me.itzg.helpers.McImageHelper.main(McImageHelper.java:157) |  
  |   | 2023-11-13 07:26:30.652 | [init] ERROR: failed to download world from https://cloudobjectstorage/world-20231016-125154.tgz

```

**Comment by itzg** [comment]
@jay-lane ,  after [this build](https://github.com/itzg/docker-minecraft-server/actions/runs/6868071123) finishes, can you re-pull the latest image (with imagePullPolicy: Always) and see if that resolves your world download?

**Comment by jay-lane** [comment]
@itzg this looks like it worked perfectly.  No issues downloading and extracting the world, and I was able to login fine.  Thank you!
