### ISSUE TITLE
"Cannot invoke "net.minecraft.server.level.ServerLevel.m_6857_()" because "serverlevel2" is null"

### ISSUE THREAD

**Issue by mattiasghodsian** [itzg/docker-minecraft-server#2514]
### Describe the problem

Im trying to get forge server to run but i keep getting ``Cannot invoke "net.minecraft.server.level.ServerLevel.m_6857_()" because "serverlevel2" is null``. Any ideas ? 

### Container definition

```
version: "3"
services:
    minecraft-java-server:
        image: itzg/minecraft-server
        container_name: mc
        environment:
            - EULA=TRUE
            - MOTD="test" 
            - TYPE=FORGE 
            - DIFFICULTY=normal
            - MEMORY=5G 
        volumes:
            - ./data:/data
        ports:
          - 25565:25565
        restart: unless-stopped 
```

### Container logs

```
mc | [23:03:23] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
mc | [23:03:24] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forge_server' with arguments []
mc | [23:03:30] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 48.0.40, for MC 1.20.2 with MCP 20230921.100330
mc | [23:03:30] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v48.0.40 Initialized
mc | [23:03:30] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
mc | [23:03:31] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: BETA Current: 48.0.40 Target: 48.0.40
mc | [23:03:32] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
mc | [23:03:32] [main/WARN] [minecraft/VanillaPackResourcesBuilder]: Assets URL 'union:/data/libraries/net/minecraft/server/1.20.2-20230921.100330/server-1.20.2-20230921.100330-srg.jar%2395!/assets/.mcassetsroot' uses unexpected schema
mc | [23:03:32] [main/WARN] [minecraft/VanillaPackResourcesBuilder]: Assets URL 'union:/data/libraries/net/minecraft/server/1.20.2-20230921.100330/server-1.20.2-20230921.100330-srg.jar%2395!/data/.mcassetsroot' uses unexpected schema
mc | [23:03:34] [main/INFO] [minecraft/RecipeManager]: Loaded 7 recipes
mc | [23:03:34] [main/INFO] [minecraft/AdvancementTree]: Loaded 1271 advancements
mc | [23:03:35] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.20.2
mc | [23:03:35] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
mc | [23:03:35] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
mc | [23:03:35] [Server thread/INFO] [minecraft/MinecraftServer]: Generating keypair
mc | [23:03:35] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:25565
mc | [23:03:35] [Server thread/INFO] [minecraft/ServerConnectionListener]: Using epoll channel type
mc | [23:03:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
mc | java.lang.RuntimeException: Couldn't watch config file
mc |      at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:54) ~[fmlcore-1.20.2-48.0.40.jar%2396!/:?] {}
mc |      at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.20.2-48.0.40.jar%2396!/:?] {}
mc |      at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.20.2-48.0.40.jar%2396!/:?] {}
mc |      at java.lang.Iterable.forEach(Unknown Source) ~[?:?] {}
mc |      at java.util.Collections$SynchronizedCollection.forEach(Unknown Source) ~[?:?] {}
mc |      at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.20.2-48.0.40.jar%2396!/:?] {}
mc |      at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:98) ~[forge-1.20.2-48.0.40-universal.jar%23100!/:?] {re:classloading}
mc |      at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:162) ~[server-1.20.2-20230921.100330-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
mc |      at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:629) ~[server-1.20.2-20230921.100330-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
mc |      at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:249) ~[server-1.20.2-20230921.100330-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
mc |      at java.lang.Thread.run(Unknown Source) ~[?:?] {}
mc | Caused by: java.io.IOException: User limit of inotify watches reached
mc |      at sun.nio.fs.LinuxWatchService$Poller.implRegister(Unknown Source) ~[?:?] {}
mc |      at sun.nio.fs.AbstractPoller.processRequests(Unknown Source) ~[?:?] {}
mc |      at sun.nio.fs.LinuxWatchService$Poller.run(Unknown Source) ~[?:?] {}
mc |      ... 1 more
mc | [23:03:35] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID bd453fd9-5bd5-4962-bdac-dce19dde969d
mc | [23:03:35] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /data/./crash-reports/crash-2023-11-26_23.03.35-server.txt
mc | [23:03:35] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
mc | [23:03:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
mc | [23:03:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
mc | [23:03:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
mc | java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.m_6857_()" because "serverlevel2" is null
mc |      at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:511) ~[server-1.20.2-20230921.100330-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
mc |      at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:579) ~[server-1.20.2-20230921.100330-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
mc |      at net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:514) ~[server-1.20.2-20230921.100330-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
mc |      at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:684) ~[server-1.20.2-20230921.100330-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
mc |      at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:249) ~[server-1.20.2-20230921.100330-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
mc |      at java.lang.Thread.run(Unknown Source) ~[?:?] {}
mc | 2023-11-26T23:03:35.776Z     INFO    mc-server-runner        Done 
```

**Comment by itzg** [comment]
This is the error you want to address

```
Caused by: java.io.IOException: User limit of inotify watches reached
```

**Comment by mattiasghodsian** [comment]
> This is the error you want to address
> 
> ```
> Caused by: java.io.IOException: User limit of inotify watches reached
> ```

Thank you, i change the max_user_watches with 
```bash
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
and now it starts up.

**Comment by Mecoolnotcool** [comment]
Hello, I also have a Minecraft server with this same issue but I don't really know much about java or Minecraft servers so it would be really helpful If someone were to have helped me but I'm not sure if this is the right but just please do help me with this if you can. Here is the crash report.  [crash-2024-08-08_08.28.15-server.txt](https://github.com/user-attachments/files/16548795/crash-2024-08-08_08.28.15-server.txt)

**Comment by itzg** [comment]
Do not post crash reports here. Please contact Mojang (or the modloader provider) for support of their software.

**Comment by Mecoolnotcool** [comment]
Ok my bad I thought I could get help here since the problem I had was similar.
