### ISSUE TITLE
My MC docker container keeps restarting.

### ISSUE THREAD

**Issue by szewczuko** [itzg/docker-minecraft-server#2544]
### Describe the problem

My container in docker keeps rebooting. Before restarting, it displays messages in docker container logs.

### Container definition

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: "SPIGOT"
      SPAWN_PROTECTION: 0
    restart: unless-stopped
    volumes:
      - ./data:/home/xyz/mc
```

### Container logs

```
[14:43:21] [ServerMain/ERROR]: Failed to start the minecraft server

java.nio.file.AccessDeniedException: ./world/session.lock

	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]

	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]

	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]

	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source) ~[?:?]

	at java.nio.channels.FileChannel.open(Unknown Source) ~[?:?]

	at java.nio.channels.FileChannel.open(Unknown Source) ~[?:?]

	at net.minecraft.util.SessionLock.a(SourceFile:34) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]

	at net.minecraft.world.level.storage.Convertable$ConversionSession.<init>(Convertable.java:517) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]

	at net.minecraft.world.level.storage.Convertable.validateAndCreateAccess(Convertable.java:430) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]

	at net.minecraft.server.Main.main(Main.java:174) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]

	at org.bukkit.craftbukkit.Main.main(Main.java:225) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]

	at org.bukkit.craftbukkit.bootstrap.Main.lambda$1(Main.java:60) ~[spigot_server-1.20.1.jar:?]
```

**Comment by itzg** [comment]
```
java.nio.file.AccessDeniedException: ./world/session.lock
```

Sounds like there is a mismatch between the file/directory ownership of the directories under your `./data`. Make sure the files are owned and/or writable by UID 1000, which is what the container runs as by default.

**Comment by szewczuko** [comment]
It worked! Thanks a lot
