### ISSUE TITLE
Stuck to Start My Container

### ISSUE THREAD

**Issue by meltymon** [itzg/docker-minecraft-server#2626]
I get an Error about to Start the Container:
2024-02-03T06:24:47.879259175Z me.itzg.helpers.errors.InvalidParameterException: Access to https://api.curseforge.com is forbidden or rate-limit has been exceeded. Ensure CF_API_KEY is set to a valid API key from https://console.curseforge.com/ or allow rate-limit to reset.

[Full Log](https://pastebin.com/cyg768my)

The API Key is Valid

What I Can do?

**Comment by meltymon** [comment]
2024-02-03T06:24:47.879670759Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-02-03T06:24:47.879677029Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2024-02-03T06:24:47.879683282Z 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
2024-02-03T06:24:47.879689585Z 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
2024-02-03T06:24:47.879695824Z 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
2024-02-03T06:24:47.879703187Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2024-02-03T06:24:47.879709813Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-02-03T06:24:47.879716352Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-02-03T06:24:47.879722856Z 	at java.base/java.lang.Thread.run(Unknown Source)
2024-02-03T06:24:47.879729233Z 	Suppressed: java.lang.Exception: #block terminated with an error
2024-02-03T06:24:47.879735622Z 		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
2024-02-03T06:24:47.879742334Z 		at reactor.core.publisher.Mono.block(Mono.java:1712)
2024-02-03T06:24:47.879749019Z 		at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:198)
2024-02-03T06:24:47.879756016Z 		at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:163)
2024-02-03T06:24:47.879762709Z 		at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:214)
2024-02-03T06:24:47.879769500Z 		at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:29)
2024-02-03T06:24:47.879776239Z 		at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
2024-02-03T06:24:47.879782705Z 		at picocli.CommandLine.access$1500(CommandLine.java:148)
2024-02-03T06:24:47.879789013Z 		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
2024-02-03T06:24:47.879795545Z 		at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
2024-02-03T06:24:47.879801874Z 		at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
2024-02-03T06:24:47.879808240Z 		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
2024-02-03T06:24:47.879814704Z 		at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
2024-02-03T06:24:47.879821069Z 		at picocli.CommandLine.execute(CommandLine.java:2170)
2024-02-03T06:24:47.879827436Z 		at me.itzg.helpers.McImageHelper.main(McImageHelper.java:157)
2024-02-03T06:24:48.219766181Z + log 'ERROR failed to auto-install CurseForge modpack'
2024-02-03T06:24:48.219806579Z + local oldState
2024-02-03T06:24:48.220316457Z ++ shopt -po xtrace
2024-02-03T06:24:48.220495712Z + oldState='set -o xtrace'
2024-02-03T06:24:48.220510694Z + shopt -u -o xtrace
2024-02-03T06:24:48.222023942Z [init] 2024-02-03 06:24:48+00:00 ERROR failed to auto-install CurseForge modpack
2024-02-03T06:24:48.222049503Z + exit 1

**Comment by dustojnikhummer** [comment]
I'm seconding this issue.

```
[init] Changing uid of minecraft to 1001

[init] Changing gid of minecraft to 1001

[init] Running as uid=1001 gid=1001 with /data as 'drwxr-xr-x 2 1001 1001 4096 Feb  3 11:32 /data'

[mc-image-helper] 11:48:11.172 ERROR : Invalid parameter provided for 'install-curseforge' command: Access to https://api.curseforge.com is forbidden or rate-limit has been exceeded. Ensure CF_API_KEY is set to a valid API key from https://console.curseforge.com/ or allow rate-limit to reset.

[init] ERROR failed to auto-install CurseForge modpack

```

**Comment by rhullah** [comment]
Have you [properly escaped](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#api-key) your API key?

**Comment by dustojnikhummer** [comment]
> Have you [properly escaped](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#api-key) your API key?
```
environment:
      - CF_API_KEY=${CF_API_KEY} 
```

and .env

```
CF_API_KEY=$2a$10$uppo[redacted]QR9lP8xWW
```

**Comment by rhullah** [comment]
That's not correct, the docs go into detail what you need to do with escaping the $s.

**Comment by dustojnikhummer** [comment]
> That's not correct, the docs go into detail what you need to do with escaping the $s.

Yeah, realized. Now it works, my bad

**Comment by meltymon** [comment]
I only use the container privately from my home network and the server is not publicly accessible.
I am not an expert in encryption or similar topics, and I simply integrated the API key as described in the documentation.

**Comment by itzg** [comment]
@meltymon home network/public or not doesn't make a difference. 

Please read (or re-read) this section and make sure you have doubled up **all three** dollar signs in the API key value

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#api-key

**Comment by meltymon** [comment]
I added the 3 $ in the API but I get the same error.

**Comment by itzg** [comment]
Must be the CueseForge imposed rate limit then.

**Comment by meltymon** [comment]
I have now generated a new API token, but that did not solve the problem.

Can the fixed rate limit be changed?

**Comment by itzg** [comment]
> I have now generated a new API token, but that did not solve the problem.

Are you totally sure you have escaped the dollar signs correctly? Your `CF_API_KEY` should start out with something like:

```
$$2a$$10$$[and remainder will be here]
```

> Can the fixed rate limit be changed?

That is in CurseForge's control, but make sure your container is not set with a restart policy. If it is, the container will continually restart and quickly exhaust all of the allowed API calls from your IP address. If this has been happening, then stop the container and wait at least an hour to start it again.

**Comment by dustojnikhummer** [comment]
> > I have now generated a new API token, but that did not solve the problem.
> 
> Are you totally sure you have escaped the dollar signs correctly? Your `CF_API_KEY` should start out with something like:
> 
> ```
> $$2a$$10$$[and remainder will be here]
> ```
> 
> > Can the fixed rate limit be changed?
> 
> That is in CurseForge's control, but make sure your container is not set with a restart policy. If it is, the container will continually restart and quickly exhaust all of the allowed API calls from your IP address. If this has been happening, then stop the container and wait at least an hour to start it again.

Speaking of the API limit, does it eat up an API call with every container restart?

**Comment by itzg** [comment]
> Speaking of the API limit, does it eat up an API call with every container restart?

Yes. Even with the modpack already installed it has to make at least one or two calls to ensure it is still valid. Those calls are fine normally, but if the container is crash looping and still trying to install mods then CurseForge's limit will be reached pretty quickly. 

How many and for what duration, I have no idea. It would be great if somebody asked CurseForge.

**Comment by dustojnikhummer** [comment]
> > Speaking of the API limit, does it eat up an API call with every container restart?
> 
> Yes. Even with the modpack already installed it has to make at least one or two calls to ensure it is still valid. Those calls are fine normally, but if the container is crash looping and still trying to install mods then CurseForge's limit will be reached pretty quickly.
> 
> How many and for what duration, I have no idea. It would be great if somebody asked CurseForge.

Alright thanks, I will make sure to change my compose to not restart automatically. Any clue what the daily limit is? There is no "x of x API calls remaining" counter.

**Comment by meltymon** [comment]
okay the restart policy was on never until stop :D 
this is right now 
https://pastebin.com/AUk4gGUr

**Comment by meltymon** [comment]
other question , have you an public server ?
i have hosted my docker-server on a intel-xeon cluster with 32* E5-2699V3 with 768GB DDR4 Ram for Each Cpu.
not only used about Minecraft container lol

**Comment by itzg** [comment]
> Alright thanks, I will make sure to change my compose to not restart automatically. 

To clarify what I was trying to say: restart policy is fine once the container setup is stable. 

> Any clue what the daily limit is? There is no "x of x API calls remaining" counter.

Like I said, no, I don't know the limit. Ask CurseForge. No, they provide absolutely no indication of remaining usage and their API doesn't even say the rate limit was reached. It just fails with a generic authorization failed status. Please share your complaints with CurseForge.

**Comment by meltymon** [comment]
> okay the restart policy was on never until stop :D this is right now https://pastebin.com/AUk4gGUr

can you see in the log file any solve ?

**Comment by rhullah** [comment]
The log file states what's wrong and action needed. There's 3 mods you have to manually download and provide to the server. It's listed in the table at the end.

**Comment by meltymon** [comment]
how I do that for a container is not running?
with 
docker exec -it Minecraft-server /bin/bash 
not works

**Comment by rhullah** [comment]
[Manual Downloads](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#manual-downloads)

Look at the example. Though if your using `docker run` you'll need to use the `-v` option to mount `/downloads`.

**Comment by meltymon** [comment]
another problem with my docker-compose script
I get an error , how I can solve it?
There is an error in the yaml syntax: YAMLSyntaxError: Invalid escape sequence \:

https://pastebin.com/FwBe3pGq

**Comment by meltymon** [comment]
> [Manual Downloads](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#manual-downloads)
> 
> Look at the example. Though if your using `docker run` you'll need to use the `-v` option to mount `/downloads`.

thanks I solved that

**Comment by rhullah** [comment]
You can't use the raw server.properties in the environment section. Please check the documentation on how to set each item.

**Comment by meltymon** [comment]
> You can't use the raw server.properties in the environment section. Please check the documentation on how to set each item.

I Solved it but now I have the problem the jvm only use 1g of ram , I tried to change that but it don't work:
JAVA_OPTS: "-Xms16G -Xmx64G"
deploy:
      resources:
        limits:
          memory: 128G
2024-02-05T00:05:20.064767305Z java.lang.OutOfMemoryError: Java heap space

**Comment by rhullah** [comment]
Look at the memory setting of the image.

**Comment by rhullah** [comment]
[Memory Limit](https://docker-minecraft-server.readthedocs.io/en/latest/configuration/jvm-options/#memory-limit)

By the way, the docs have a search option that's super helpful to find what your looking for.

**Comment by meltymon** [comment]
sorry my English isn't the best to search in the docs.
can I add environment values to the container like?
-e MEMORY="128G" 
-e JVM_XX_OPTS="-XX:MaxRAMPercentage=75" -m 128G

**Comment by itzg** [comment]
I'd say keep it simple and use specific limits rather than percentage based. Since I assume you're initially using a compose file, replace

```
  JAVA_OPTS: "-Xms16G -Xmx64G"
```

with

```
  INIT_MEMORY: 16G
  MAX_MEMORY: 64G
```

**Comment by meltymon** [comment]
> I'd say keep it simple and use specific limits rather than percentage based. Since I assume you're initially using a compose file, replace
> 
> ```
>   JAVA_OPTS: "-Xms16G -Xmx64G"
> ```
> 
> with
> 
> ```
>   INIT_MEMORY: 16G
>   MAX_MEMORY: 64G
> ```
> 
> and remove the `JVM_XX_OPTS`.

Yes you Are Right 

This is my Docker-Compose File

`version: "3.8"

services:
  minecraft-server:
    container_name: minecraft-server  # Set the container name
    image: itzg/minecraft-server
    ports:
      - "25565:25565"  # Expose Minecraft server port

    environment:
      EULA: "TRUE"
      DEBUG: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"  # Enable custom properties
      MEMORY: "128G"
      CF_API_KEY: "secure"  
      CF_SLUG: "all-the-mods-9"
       TYPE: "AUTO_CURSEFORGE"  

    volumes:
      - /minecraft-server:/data  # Mount /minecraft-server on the host to /data in the container
      - /minecraft-server/mods:/mods  # Mount /minecraft-server/mods on the host to /mods in the container

    networks:
      local:  # Set the network name
        ipv4_address: 192.168.2.180  # Assign a specific IP address to the container

    

networks:
  local:  # Define the network
    external: true  # Join the existing network named "minecraft-server-network"
`

"I have tried a lot, and I finally have the auto-download of mod packages from CurseForge up and running, but I keep encountering errors. Now, I have received a crash dump. When I disable the mods, the server works. Here is the crash dump: [link] (https://pastebin.com/skxr7FUK)."
