### ISSUE TITLE
Install error.  TrueNAS-SCALE-22.12.4.2

### ISSUE THREAD

**Issue by frumeladka** [itzg/docker-minecraft-server#2668]
### Describe the problem

When I try to install docker from truecharts it gives me the error. I have last OS version
![image](https://github.com/itzg/docker-minecraft-server/assets/152558602/9ad4ed5f-b15f-4cdf-be14-5ba02253cbbd)
![image](https://github.com/itzg/docker-minecraft-server/assets/152558602/4325c215-2f54-4c2b-8872-1e0b31eea5de)

### Container definition

truechats

### Container logs

 Ошибка: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 427, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 465, in __run_body
    rv = await self.method(*([self] + args))
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1247, in nf
    res = await f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1379, in nf
    return await func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 486, in do_create
    await self.middleware.call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1368, in call
    return await self._call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1328, in _call
    return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1231, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/helm.py", line 44, in helm_action
    raise CallError(f'Failed to {tn_action} chart release: {stderr.decode()}')
middlewared.service_exception.CallError: [EFAULT] Failed to install chart release: Error: INSTALLATION FAILED: execution error at (minecraft-java/templates/common.yaml:2:4): Expected helm version [>=3.12], but found [v3.9.4]. Upgrade TrueNAS SCALE OS

**Comment by itzg** [comment]
I don't maintain the Truechart definition. You need to contact the author of that.

**Comment by thomabsk** [comment]
You most likely still doesn't have the latest version. You may have to manually update your Truenas SCALE. Is your version by chance 22 and not 23?

**Comment by frumeladka** [comment]
> You most likely still don't have the latest version. You may have to manually update your Truenas SCALE. The latest version is 23 not 22.

Thanks!
