### ISSUE TITLE
ERROR failed to install Forge

### ISSUE THREAD

**Issue by Andision** [itzg/docker-minecraft-server#2673]
### Describe the problem

```
Starting mc ... done
Attaching to mc
mc    | [init] Changing ownership of /data to 1000 ...
mc    | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Feb 19 05:53 /data'
mc    | [init] Resolving type given FORGE
mc    | [mc-image-helper] 05:53:27.975 INFO  : Downloading Forge installer 49.0.30 for Minecraft 1.20.4
mc    | [mc-image-helper] 05:53:30.985 INFO  : Running Forge 49.0.30 installer for Minecraft 1.20.4. This might take a while...
mc    | JVM info: Eclipse Adoptium - 17.0.10 - 17.0.10+7
mc    | java.net.preferIPv4Stack=true
mc    | Current Time: 19/02/2024 05:53:31
mc    | Host: files.minecraftforge.net [51.79.83.165]
mc    | Host: maven.minecraftforge.net [51.79.83.165]
mc    | Host: libraries.minecraft.net [13.107.213.74, 13.107.246.74]
mc    | Host: launchermeta.mojang.com [13.107.213.74, 13.107.246.74]
mc    | Host: piston-meta.mojang.com [13.107.246.74, 13.107.213.74]
mc    | Host: authserver.mojang.com [52.84.229.51, 52.84.229.76, 52.84.229.114, 52.84.229.67]
mc    | Target Directory: .
mc    | Data kindly mirrored by CreeperHost at https://www.creeperhost.net/
mc    | Extracting main jar:
mc    |   Extracted successfully
mc    | Considering minecraft server jar
mc    | java.net.SocketTimeoutException: Connect timed out
mc    |         at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
mc    |         at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
mc    |         at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
mc    |         at java.base/java.net.Socket.connect(Unknown Source)
mc    |         at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
mc    |         at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
mc    |         at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
mc    |         at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
mc    |         at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
mc    |         at net.minecraftforge.installer.DownloadUtils.getConnection(DownloadUtils.java:244)
mc    |         at net.minecraftforge.installer.DownloadUtils.downloadManifest(DownloadUtils.java:338)
mc    |         at net.minecraftforge.installer.json.Util.getVanillaVersion(Util.java:59)
mc    |         at net.minecraftforge.installer.actions.ServerInstall.run(ServerInstall.java:70)
mc    |         at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:148)
mc    | Failed to download version manifest, can not find server jar URL.
mc    | There was an error during installation
mc    | [mc-image-helper] 05:55:48.892 ERROR : 'install-forge' command failed. Version is 1.38.3
mc    | me.itzg.helpers.errors.GenericException: Forge installer failed with exit code 1
mc    |         at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:211)
mc    |         at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:99)
mc    |         at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:103)
mc    |         at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:19)
mc    |         at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
mc    |         at picocli.CommandLine.access$1500(CommandLine.java:148)
mc    |         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
mc    |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
mc    |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
mc    |         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
mc    |         at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
mc    |         at picocli.CommandLine.execute(CommandLine.java:2170)
mc    |         at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
mc    | [init] ERROR failed to install Forge
mc exited with code 1
```

### Container definition

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: mc
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.4"
      TYPE: FORGE
      FORGE_VERSION: "49.0.30"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /data/Minecraft/data:/data


```

### Container logs

```
Starting mc ... done
Attaching to mc
mc    | [init] Changing ownership of /data to 1000 ...
mc    | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Feb 19 05:53 /data'
mc    | [init] Resolving type given FORGE
mc    | [mc-image-helper] 05:53:27.975 INFO  : Downloading Forge installer 49.0.30 for Minecraft 1.20.4
mc    | [mc-image-helper] 05:53:30.985 INFO  : Running Forge 49.0.30 installer for Minecraft 1.20.4. This might take a while...
mc    | JVM info: Eclipse Adoptium - 17.0.10 - 17.0.10+7
mc    | java.net.preferIPv4Stack=true
mc    | Current Time: 19/02/2024 05:53:31
mc    | Host: files.minecraftforge.net [51.79.83.165]
mc    | Host: maven.minecraftforge.net [51.79.83.165]
mc    | Host: libraries.minecraft.net [13.107.213.74, 13.107.246.74]
mc    | Host: launchermeta.mojang.com [13.107.213.74, 13.107.246.74]
mc    | Host: piston-meta.mojang.com [13.107.246.74, 13.107.213.74]
mc    | Host: authserver.mojang.com [52.84.229.51, 52.84.229.76, 52.84.229.114, 52.84.229.67]
mc    | Target Directory: .
mc    | Data kindly mirrored by CreeperHost at https://www.creeperhost.net/
mc    | Extracting main jar:
mc    |   Extracted successfully
mc    | Considering minecraft server jar
mc    | java.net.SocketTimeoutException: Connect timed out
mc    |         at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
mc    |         at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
mc    |         at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
mc    |         at java.base/java.net.Socket.connect(Unknown Source)
mc    |         at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
mc    |         at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
mc    |         at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
mc    |         at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
mc    |         at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
mc    |         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
mc    |         at net.minecraftforge.installer.DownloadUtils.getConnection(DownloadUtils.java:244)
mc    |         at net.minecraftforge.installer.DownloadUtils.downloadManifest(DownloadUtils.java:338)
mc    |         at net.minecraftforge.installer.json.Util.getVanillaVersion(Util.java:59)
mc    |         at net.minecraftforge.installer.actions.ServerInstall.run(ServerInstall.java:70)
mc    |         at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:148)
mc    | Failed to download version manifest, can not find server jar URL.
mc    | There was an error during installation
mc    | [mc-image-helper] 05:55:48.892 ERROR : 'install-forge' command failed. Version is 1.38.3
mc    | me.itzg.helpers.errors.GenericException: Forge installer failed with exit code 1
mc    |         at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:211)
mc    |         at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:99)
mc    |         at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:103)
mc    |         at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:19)
mc    |         at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
mc    |         at picocli.CommandLine.access$1500(CommandLine.java:148)
mc    |         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
mc    |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
mc    |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
mc    |         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
mc    |         at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
mc    |         at picocli.CommandLine.execute(CommandLine.java:2170)
mc    |         at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
mc    | [init] ERROR failed to install Forge
mc exited with code 1

```

**Comment by itzg** [comment]
The Forge installer failed, so it's beyond my control. It looks like a networking issue about might be temporary.

**Comment by KhawanC** [comment]
Same here
