### ISSUE TITLE
ERROR failed to auto-install CurseForge modpack

### ISSUE THREAD

**Issue by minermartijn** [itzg/docker-minecraft-server#2696]
### Describe the problem

I think it cant find the zip file. but im a bit of a noob with this.
The following error inside the logs are below.
Just incase i used the wrong folder, modpacks with the zip file are both in data and in the linked volume.

### Container definition

```
version: "3.8"

services:
  mc-oneblock:
    image: itzg/minecraft-server
    container_name: mc_oneblock
    ports:
      - "25566:25565"
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: one-block-modded
      CF_MODPACK_ZIP: /modpacks/Modded+OneBlock.zip
      CF_SET_LEVEL_FROM: OVERRIDES
      DEBUG: "false"
      MEMORY: 4G
    volumes: 
      - /home/administrator/Scripts/NewMinecraftDocker/OneBlock:/data
      - /home/administrator/Scripts/NewMinecraftDocker/modpacks:/modpacks:ro
```

### Container logs

```
Creating network "newminecraftdocker_default" with the default driver
Creating mc_oneblock ... done
Attaching to mc_oneblock
mc_oneblock    | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Mar  5 10:39 /data'
mc_oneblock    | [mc-image-helper] 10:47:37.711 ERROR : 'install-curseforge' command failed. Version is 1.38.5
mc_oneblock    | java.nio.file.NoSuchFileException: /modpacks/Modded+OneBlock.zip
mc_oneblock    |        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
mc_oneblock    |        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
mc_oneblock    |        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
mc_oneblock    |        at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source)
mc_oneblock    |        at java.base/java.nio.channels.FileChannel.open(Unknown Source)
mc_oneblock    |        at java.base/java.nio.channels.FileChannel.open(Unknown Source)
mc_oneblock    |        at org.apache.commons.compress.archivers.zip.ZipFile.openZipChannel(ZipFile.java:500)
mc_oneblock    |        at org.apache.commons.compress.archivers.zip.ZipFile.access$000(ZipFile.java:89)
mc_oneblock    |        at org.apache.commons.compress.archivers.zip.ZipFile$Builder.get(ZipFile.java:160)
mc_oneblock    |        at me.itzg.helpers.curseforge.CurseForgeInstaller.extractModpackManifest(CurseForgeInstaller.java:929)
mc_oneblock    |        at me.itzg.helpers.curseforge.CurseForgeInstaller.lambda$installFromModpackZip$0(CurseForgeInstaller.java:130)
mc_oneblock    |        at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:213)
mc_oneblock    |        at me.itzg.helpers.curseforge.CurseForgeInstaller.installFromModpackZip(CurseForgeInstaller.java:129)
mc_oneblock    |        at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:222)
mc_oneblock    |        at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:30)
mc_oneblock    |        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
mc_oneblock    |        at picocli.CommandLine.access$1500(CommandLine.java:148)
mc_oneblock    |        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
mc_oneblock    |        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
mc_oneblock    |        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
mc_oneblock    |        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
mc_oneblock    |        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
mc_oneblock    |        at picocli.CommandLine.execute(CommandLine.java:2170)
mc_oneblock    |        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
mc_oneblock    | [init] ERROR failed to auto-install CurseForge modpack
mc_oneblock exited with code 1
```

**Comment by itzg** [comment]
Yep it can't find the zip file. 

```
java.nio.file.NoSuchFileException: /modpacks/Modded+OneBlock.zip
```

Your mount looks right but you must not have the file there or with the right name.

**Comment by minermartijn** [comment]
I also renamed it to a filename without spaces, and changed the file name inside the docker-compose.yml file and it still didnt find it.

**Comment by itzg** [comment]
Provide your latest compose file and a listing of the directory /home/administrator/Scripts/NewMinecraftDocker/modpacks

**Comment by minermartijn** [comment]
I seem to have fixed it, but moving the zip file to the data folder. (I think it was a permission error somewhere on my part)

**Comment by UntaintedIo** [comment]
So I'm kind of having the same issue a little bit. Can't say I'm new but I'm kind of new but I'm getting the [init] ERROR failed to auto-install CurseForge modpack

Docker-Compose:
`version: "3.8"

services:
  cfmar:
    image: itzg/minecraft-server
    container_name: "cfmar"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: "$$2a$$10$$3QfryeZ0.MDfq4VUkquMYeL5LsxzkU3XbFWjpiJSbuVDUY78yK5Fq"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/ciscos-fantasy-medieval-adventure-rpg/download/5143656"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./curseforge/cfmar:/data`
