### ISSUE TITLE
Some mods are not excluded using MODRINTH_EXCLUDE_FILES

### ISSUE THREAD

**Issue by backstromjoel** [itzg/docker-minecraft-server#2700]
### Describe the problem

I'm trying to set up a BMC4 server from Modrinth (tried CurseForge without any luck).

I ran into some issues with it trying to load client side mods so i excluded them in the MODRINTH_EXCLUDE_FILES env variable. This fixed the issue for most of the mods, however, there are still 2 mods that are not excluded whatever i try.

### Container definition

```
docker run -d -e TYPE=MODRINTH -e MODRINTH_LOADER=forge -e MOTD='Minecraft Server' -e MODE=survival -e MEMORY=6G -e VERSION=LATEST -e EULA=true -e MODRINTH_MODPACK=better-mc-forge-bmc4 -e MODRINTH_FORCE_SYNCHRONIZE=true -e MODRINTH_EXCLUDE_FILES='citresewn,oculus,yungsmenutweaks,neko,notenoughanimations,ryoamiclights,euphoriapatcher,entity_model_features,entity_texture_features,3dskinlayers' -p '25565:25565' itzg/minecraft-server:latest
```

### Container logs

```
2024-03-08 11:24:44     Crash Report UUID: f88c054f-8cc3-46ec-9680-c81fd054e7d6
2024-03-08 11:24:44     FML: 47.2
2024-03-08 11:24:44     Forge: net.minecraftforge:47.2.17[10:24:44] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
2024-03-08 11:24:44 net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
2024-03-08 11:24:44     Neko's Enchanted Books (nebs) has failed to load correctly
2024-03-08 11:24:44 §7java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER,
2024-03-08 11:24:44     CIT Resewn (citresewn) has failed to load correctly
2024-03-08 11:24:44 §7java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/atlas/SpriteSource
2024-03-08 11:24:44 ]
2024-03-08 11:24:44     at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:246) ~[fmlcore-1.20.1-47.2.17.jar%23576!/:?] {}
2024-03-08 11:24:44     at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.2.17.jar%23576!/:?] {}
2024-03-08 11:24:44     at java.util.Optional.ifPresent(Unknown Source) ~[?:?] {re:mixin}
2024-03-08 11:24:44     at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.2.17.jar%23576!/:?] {}
2024-03-08 11:24:44     at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.17.jar%23576!/:?] {}
2024-03-08 11:24:44     at java.lang.Iterable.forEach(Unknown Source) ~[?:?] {re:mixin}
2024-03-08 11:24:44     at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.17.jar%23576!/:?] {}
2024-03-08 11:24:44     at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.2.17-universal.jar%23580!/:?] {re:classloading}
2024-03-08 11:24:44     at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23575!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}
2024-03-08 11:24:44     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
2024-03-08 11:24:44     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
2024-03-08 11:24:44     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
2024-03-08 11:24:44     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
2024-03-08 11:24:44     at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar%2369!/:?] {}
2024-03-08 11:24:44     at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.17.jar%2369!/:?] {}
2024-03-08 11:24:44     at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.17.jar%2369!/:?] {}
2024-03-08 11:24:44     at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
2024-03-08 11:24:44     at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
2024-03-08 11:24:44     at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
2024-03-08 11:24:44     at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
2024-03-08 11:24:44     at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
2024-03-08 11:24:44     at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
2024-03-08 11:24:44     at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
2024-03-08 11:24:44     at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```

**Comment by itzg** [comment]
Can you point out which two are not getting excluded? The underscores don't seem to be what naming convention they would use for file IDs. It'll probably have dashes instead in the URL field for those.

**Comment by backstromjoel** [comment]
citresewn and neko is not getting excluded, i've tried with a ton of variations of the names.

I've fixed this by just downloading the zip and running a regular FORGE server for now.
`docker run -d  -p 25565:25565 -v /modpacks:/modpacks -v /data:/data -e VERSION='1.20.1' -e TYPE='FORGE' -e FORGE_VERSION='47.2.6' -e MEMORY=6G -e GENERIC_PACK='/modpacks/BMC4_FORGE_1.20.1_Server_Pack_v26.zip' -e EULA=TRUE itzg/minecraft-server`

**Comment by itzg** [comment]
I haven't checked the other, but NekosEnchangedBooks is coming in via overrides

<img width="515" alt="image" src="https://github.com/itzg/docker-minecraft-server/assets/988985/1dd12844-8e02-4bc1-b1ed-2e6bdb505d0a">

I'll need to add an option [like this](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#excluding-overrides-files) for Modrinth.

**Comment by itzg** [comment]
I also need to add debug logs for files being copied from overrides.

**Comment by itzg** [comment]
New option is documented here:

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/modrinth-modpacks/#excluding-overrides-files

**Comment by backstromjoel** [comment]
Thanks for the quick help! You're doing great stuff here man, greatly appreciate it!
