### ISSUE TITLE
Crashes with 2024.4.0 after some time

### ISSUE THREAD

**Issue by Madaraxa** [itzg/docker-minecraft-server#2765]
### Describe the problem

I just repulled the image on my docker (Portainer) and the server keeps crashing after some time. Even if no one is "on it".
I had 10+ crashes since the repull (5th april) and not a single one before the crash.
I didnt change anything about the config but added an icon to my server (but commented out it still crashes).
I added the last crash log. If you need a can add 6 more :)
EDIT: I thought it had to do with a virscan in Background, but when i use SSH and type "top" it shows, that my 2 minecraft server (without ppl logged in) use 35-45% of the CPU (so its 70-90% in total). That causes the crash.
I never had the problem with the version pre 2024.4.0.

### Container definition

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    environment:
      EULA: "true"
      TZ: "Europe/Berlin"
      MOTD: "myMOTD"
      DIFFICULTY: "peaceful"
      WHITE-LIST: "true"
      OP-PERMISSION-LEVEL: "0"
      SERVER_NAME: "myname"
      ALLOW_CHEATS: "true"
      SEED: "-2882832953968269043"
      ICON: "/data/tnt.png"
      OPS: |
        myops
      WHITELIST: |
        mywhitelistnames
      LEVEL: "mylevel"
      DEFAULT-PLAYER-PERMISSION-LEVEL: "operator"
    ports:
      - "25565:25565"

    volumes:
      - /share/containerdata/config/minecraft-data:/data
    restart: always
```

### Container logs

```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2024-04-08 18:56:26
Description: Watching Server

java.lang.Error: Watchdog
	at anb.a(SourceFile:147)
	at ctp.a(SourceFile:207)
	at ctp.c(SourceFile:668)
	at cst.a(SourceFile:62)
	at cst.computeNext(SourceFile:81)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:474)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:870)
	at blv.a(SourceFile:1064)
	at blv.a(SourceFile:1035)
	at blv.a(SourceFile:707)
	at bml.a(SourceFile:2339)
	at bml.a(SourceFile:2259)
	at bml.d_(SourceFile:2743)
	at bmn.d_(SourceFile:556)
	at blq.d_(SourceFile:128)
	at bxy.d_(SourceFile:58)
	at byu.d_(SourceFile:142)
	at bml.l(SourceFile:2446)
	at bmn.l(SourceFile:357)
	at and.a(SourceFile:761)
	at and$$Lambda/0x00007fcf00be3688.accept(Unknown Source)
	at ctp.a(SourceFile:492)
	at and.a(SourceFile:399)
	at and$$Lambda/0x00007fcf00be5560.accept(Unknown Source)
	at dne.a(SourceFile:54)
	at and.a(SourceFile:363)
	at net.minecraft.server.MinecraftServer.b(SourceFile:948)
	at ama.b(SourceFile:283)
	at net.minecraft.server.MinecraftServer.a(SourceFile:845)
	at net.minecraft.server.MinecraftServer.w(SourceFile:683)
	at net.minecraft.server.MinecraftServer.a(SourceFile:270)
	at net.minecraft.server.MinecraftServer$$Lambda/0x00007fcf00a0d560.run(Unknown Source)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	at java.base@21.0.2/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at anb.a(SourceFile:147)
	at ctp.a(SourceFile:207)
	at ctp.c(SourceFile:668)
	at cst.a(SourceFile:62)
	at cst.computeNext(SourceFile:81)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:474)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:870)
	at blv.a(SourceFile:1064)
	at blv.a(SourceFile:1035)
	at blv.a(SourceFile:707)
	at bml.a(SourceFile:2339)
	at bml.a(SourceFile:2259)
	at bml.d_(SourceFile:2743)
	at bmn.d_(SourceFile:556)
	at blq.d_(SourceFile:128)
	at bxy.d_(SourceFile:58)
	at byu.d_(SourceFile:142)
	at bml.l(SourceFile:2446)
	at bmn.l(SourceFile:357)
	at and.a(SourceFile:761)
	at and$$Lambda/0x00007fcf00be3688.accept(Unknown Source)
	at ctp.a(SourceFile:492)
	at and.a(SourceFile:399)
	at and$$Lambda/0x00007fcf00be5560.accept(Unknown Source)
	at dne.a(SourceFile:54)
	at and.a(SourceFile:363)
	at net.minecraft.server.MinecraftServer.b(SourceFile:948)
	at ama.b(SourceFile:283)
	at net.minecraft.server.MinecraftServer.a(SourceFile:845)
	at net.minecraft.server.MinecraftServer.w(SourceFile:683)
	at net.minecraft.server.MinecraftServer.a(SourceFile:270)
	at net.minecraft.server.MinecraftServer$$Lambda/0x00007fcf00a0d560.run(Unknown Source)

-- Thread Dump --
Details:
	Threads: "Reference Handler" daemon prio=10 Id=9 RUNNABLE
	at java.base@21.0.2/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
	at java.base@21.0.2/java.lang.ref.Reference.processPendingReferences(Unknown Source)
	at java.base@21.0.2/java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)


"Finalizer" daemon prio=8 Id=10 WAITING on java.lang.ref.NativeReferenceQueue$Lock@7108e812
	at java.base@21.0.2/java.lang.Object.wait0(Native Method)
	-  waiting on java.lang.ref.NativeReferenceQueue$Lock@7108e812
	at java.base@21.0.2/java.lang.Object.wait(Unknown Source)
	at java.base@21.0.2/java.lang.Object.wait(Unknown Source)
	at java.base@21.0.2/java.lang.ref.NativeReferenceQueue.await(Unknown Source)
	at java.base@21.0.2/java.lang.ref.ReferenceQueue.remove0(Unknown Source)
	at java.base@21.0.2/java.lang.ref.NativeReferenceQueue.remove(Unknown Source)
	at java.base@21.0.2/java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)


"Signal Dispatcher" daemon prio=9 Id=11 RUNNABLE


"Notification Thread" daemon prio=9 Id=17 RUNNABLE


"Common-Cleaner" daemon prio=8 Id=18 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@37169175
	at java.base@21.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@37169175
	at java.base@21.0.2/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at java.base@21.0.2/java.lang.ref.ReferenceQueue.await(Unknown Source)
	at java.base@21.0.2/java.lang.ref.ReferenceQueue.remove0(Unknown Source)
	at java.base@21.0.2/java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.base@21.0.2/jdk.internal.ref.CleanerImpl.run(Unknown Source)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	...


"DestroyJavaVM" prio=5 Id=20 RUNNABLE


"JNA Cleaner" daemon prio=5 Id=28 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@96214d0
	at java.base@21.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@96214d0
	at java.base@21.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at java.base@21.0.2/java.lang.ref.ReferenceQueue.await(Unknown Source)
	at java.base@21.0.2/java.lang.ref.ReferenceQueue.remove0(Unknown Source)
	...


"Timer hack thread" daemon prio=5 Id=29 TIMED_WAITING
	at java.base@21.0.2/java.lang.Thread.sleep0(Native Method)
	at java.base@21.0.2/java.lang.Thread.sleep(Unknown Source)
	at ac$9.run(SourceFile:833)


"Yggdrasil Key Fetcher" daemon prio=5 Id=30 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6b963b5b
	at java.base@21.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6b963b5b
	at java.base@21.0.2/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"Server thread" prio=5 Id=36 RUNNABLE
	at anb.a(SourceFile:147)
	at ctp.a(SourceFile:207)
	at ctp.c(SourceFile:668)
	at cst.a(SourceFile:62)
	at cst.computeNext(SourceFile:81)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:474)
	...


"Server console handler" daemon prio=5 Id=38 RUNNABLE (in native)
	at java.base@21.0.2/java.io.FileInputStream.readBytes(Native Method)
	at java.base@21.0.2/java.io.FileInputStream.read(Unknown Source)
	at java.base@21.0.2/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base@21.0.2/java.io.BufferedInputStream.implRead(Unknown Source)
	at java.base@21.0.2/java.io.BufferedInputStream.read(Unknown Source)
	at java.base@21.0.2/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at java.base@21.0.2/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at java.base@21.0.2/sun.nio.cs.StreamDecoder.lockedRead(Unknown Source)
	...

	Number of locked synchronizers = 3
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@5a93d74b
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@590d6855
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@40502330


"Netty Epoll Server IO #0" daemon prio=5 Id=39 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:209)
	at io.netty.channel.epoll.Native.epollWait(Native.java:202)
	at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:316)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	...


"Netty Epoll Server IO #1" daemon prio=5 Id=40 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:209)
	at io.netty.channel.epoll.Native.epollWait(Native.java:202)
	at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:316)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	...


"Netty Epoll Server IO #2" daemon prio=5 Id=41 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:209)
	at io.netty.channel.epoll.Native.epollWait(Native.java:202)
	at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:316)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	...


"Netty Epoll Server IO #3" daemon prio=5 Id=42 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:209)
	at io.netty.channel.epoll.Native.epollWait(Native.java:202)
	at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:316)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	...


"Netty Epoll Server IO #4" daemon prio=5 Id=47 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:209)
	at io.netty.channel.epoll.Native.epollWait(Native.java:202)
	at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:316)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	...


"Netty Epoll Server IO #5" daemon prio=5 Id=48 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:209)
	at io.netty.channel.epoll.Native.epollWait(Native.java:202)
	at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:316)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	...


"Netty Epoll Server IO #6" daemon prio=5 Id=53 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:209)
	at io.netty.channel.epoll.Native.epollWait(Native.java:202)
	at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:316)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	...


"Netty Epoll Server IO #7" daemon prio=5 Id=54 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:209)
	at io.netty.channel.epoll.Native.epollWait(Native.java:202)
	at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:316)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	...


"RCON Listener #1" prio=5 Id=56 RUNNABLE
	at java.base@21.0.2/sun.nio.ch.Net.poll(Native Method)
	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.park(Unknown Source)
	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedAccept(Unknown Source)
	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.accept(Unknown Source)
	at java.base@21.0.2/java.net.ServerSocket.implAccept(Unknown Source)
	at java.base@21.0.2/java.net.ServerSocket.platformImplAccept(Unknown Source)
	at java.base@21.0.2/java.net.ServerSocket.implAccept(Unknown Source)
	at java.base@21.0.2/java.net.ServerSocket.implAccept(Unknown Source)
	...

	Number of locked synchronizers = 1
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@1ac68482


"Server Watchdog" daemon prio=5 Id=57 RUNNABLE
	at java.management@21.0.2/sun.management.ThreadImpl.dumpThreads0(Native Method)
	at java.management@21.0.2/sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
	at java.management@21.0.2/sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
	at amd.run(SourceFile:48)
	at java.base@21.0.2/java.lang.Thread.runWith(Unknown Source)
	at java.base@21.0.2/java.lang.Thread.run(Unknown Source)


"Java2D Disposer" daemon prio=10 Id=58 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5eab311e
	at java.base@21.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5eab311e
	at java.base@21.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at java.base@21.0.2/java.lang.ref.ReferenceQueue.await(Unknown Source)
	at java.base@21.0.2/java.lang.ref.ReferenceQueue.remove0(Unknown Source)
	...


"Worker-Main-20" daemon prio=5 Id=515 TIMED_WAITING on java.util.concurrent.ForkJoinPool@6c56a55e
	at java.base@21.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@6c56a55e
	at java.base@21.0.2/java.util.concurrent.locks.LockSupport.parkUntil(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)


"Worker-Main-21" daemon prio=5 Id=516 WAITING on java.util.concurrent.ForkJoinPool@6c56a55e
	at java.base@21.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@6c56a55e
	at java.base@21.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base@21.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)



Stacktrace:
	at amd.run(SourceFile:64)
	at java.base/java.lang.Thread.run(Unknown Source)

-- Performance stats --
Details:
	Random tick rate: 1
	Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 1, entities: 475,475,101,735,735,140,0 [minecraft:chicken:115,minecraft:cow:95,minecraft:sheep:71,minecraft:pig:60,minecraft:item:55], block_entities: 934 [minecraft:sculk_sensor:599,minecraft:sculk_catalyst:113,minecraft:mob_spawner:61,minecraft:sign:60,minecraft:sculk_shrieker:50], block_ticks: 16, fluid_ticks: 51, chunk_source: Chunks[S] W: 3734 E: 475,475,101,735,735,140,0,
ResourceKey[minecraft:dimension / minecraft:the_end]: players: 0, entities: 0,0,0,0,0,0,0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: Chunks[S] W: 0 E: 0,0,0,0,0,0,0,
ResourceKey[minecraft:dimension / minecraft:the_nether]: players: 0, entities: 32,32,28,625,625,0,0 [minecraft:strider:28,minecraft:item:4], block_entities: 4 [minecraft:sign:3,minecraft:mob_spawner:1], block_ticks: 0, fluid_ticks: 329, chunk_source: Chunks[S] W: 2401 E: 32,32,28,625,625,0,0

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 5.10.60-qnap
	Java Version: 21.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 530333712 bytes (505 MiB) / 1073741824 bytes (1024 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
	Identifier: Intel64 Family 6 Model 92 Stepping 9
	Microarchitecture: Goldmont
	Frequency (GHz): 1.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 31375.64
	Virtual memory used (MB): 13274.52
	Swap memory total (MB): 23447.24
	Swap memory used (MB): 322.22
	JVM Flags: 2 total; -Xmx1G -Xms1G
	Server Running: true
	Player Count: 1 / 20; [ane['myname'/15058, l='ServerLevel[mylevel]', x=144.61, y=71.00, z=120.50]]
	Data Packs: vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Probably not. Server jar signature and brand is untouched
	Type: Dedicated Server (map_server.txt)
```

**Comment by Madaraxa** [comment]
It seems it had to do with too much "work" on the NAS (Virscan / Backup in background). I played for 2 hours now without a crash.
Sorry to have bothered you all

**Comment by itzg** [comment]
I'm not able to provide support for crash logs. With that said, maybe it was due to bumping the default Java version

https://docker-minecraft-server.readthedocs.io/en/latest/versions/java/#java-21

So you may want to try the java17 image tag instead.

**Comment by itzg** [comment]
Correct. I hope that fixes it.

**Comment by Madaraxa** [comment]
It seems it does. 
"top" shows around 5-15% cpu usage now (from 35-45%).  Need to check if its stable like this.
Could you - or any other - explain why java17 is "better" than java 21?  I dont use any mods (as you see in the compose)

**Comment by itzg** [comment]
That's good but I agree that it is unexpected it actually helped for a vanilla server type. I had originally missed that aspect of your container setup.

**Comment by itzg** [comment]
BTW, the env vars with dashes actually need to be using underscores. For example instead of `OP-PERMISSION-LEVEL` it should be `OP_PERMISSION_LEVEL`. It's certainly confusing since the final property has dashes.

**Comment by Madaraxa** [comment]
One day gone and no more crashes... It seems that (java17) has fixed it :) Thanks a lot
