### ISSUE TITLE
Problem with starting server

### ISSUE THREAD

**Issue by Tim2653** [itzg/docker-minecraft-server#2773]
I have seen many very similiar problems, but no exact copy. When I try to launch container, i see this error message:

[14:00:16]` [ServerMain/ERROR]: Failed to start the minecraft server
joptsimple.UnrecognizedOptionException: t is not a recognized option
        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[jopt-simple-5.0.4.jar:?]
        at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:633) ~[jopt-simple-5.0.4.jar:?]
        at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:528) ~[jopt-simple-5.0.4.jar:?]
        at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:523) ~[jopt-simple-5.0.4.jar:?]
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:59) ~[jopt-simple-5.0.4.jar:?]
        at joptsimple.OptionParser.parse(OptionParser.java:396) ~[jopt-simple-5.0.4.jar:?]
        at net.minecraft.server.Main.main(SourceFile:87) ~[server-1.20.4.jar:?]
        at net.minecraft.bundler.Main.lambda$run$0(Main.java:54) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

Does anyone have an idea what might be the issue?

**Comment by Tim2653** [comment]
I am supprised with such quick response. What info do you need?  I`ve been trying to run with this command:

docker run -e EULA=TRUE -d -it -p 25565:25565 -v C:Minecraft_Java:/data itzg/minecraft-server

Now I`m gonna remove all the "t" and check if it works.

**Comment by itzg** [comment]
Specifying Windows absolute paths is always a little tricky. Make sure to use backslashes like shown in this answer 

https://stackoverflow.com/a/72578357/121324

Better yet, I recommend switching to using a compose file to declare your container and then you can use simple, relative paths

https://docker-minecraft-server.readthedocs.io/en/latest/#using-docker-compose

**Comment by Tim2653** [comment]
What does -t have to do with paths? I`m confused.

**Comment by itzg** [comment]
Something about the command line parsing is not liking your command. The colon from the Windows path without a backslash is likely the culprit.

**Comment by Tim2653** [comment]
It seems that, when played on docker desktop everything works fine, but when I try to launch it on qnas it doesn`t work.( Says Eula is not set to true, and when I manually add this file I get agan error message about -t not being recognized)

**Comment by itzg** [comment]
No, it's Docker either way. What is the latest command you're trying on QNAP?
