### ISSUE TITLE
container fails to launch, complains about Error: LinkageError occurred while loading main class net.minecraft.bundler.Main

### ISSUE THREAD

**Issue by xamindar** [itzg/docker-minecraft-server#2805]
### Describe the problem

Restarted my container to pull the latest version of minecraft 1.20.5 and this version fails to launch. Logs are below. This is run on k8s. There also appears to be a bug in it that adds a user "For" to the ops list.

Previous version 1.20.4 was running just fine.

### Container definition

```
helm upgrade --install minecraft-k3s -f minecraft-k3s-values.yaml minecraft-server-charts/minecraft -n minecraft
```

### Container logs

```
chmod: changing permissions of '/data': Operation not permitted
[init] Running as uid=1000 gid=3000 with /data as 'drwxrwsr-x 9 0 2000 4096 Apr 28 22:39 /data'
[init] Resolved version given LATEST into 1.20.5 and major version 1.20
[init] Resolving type given VANILLA
[init] server.properties already created, skipping
[init] Updating ops
[picocli WARN] Unbalanced quotes in [Solve] for field java.util.List<java.net.URI> me.itzg.helpers.get.GetCommand.uris (value=https://playerdb.co/api/player/minecraft/"Solve)
[picocli WARN] Unable to respect quotes while splitting value https://playerdb.co/api/player/minecraft/"Solve for field java.util.List<java.net.URI> me.itzg.helpers.get.GetCommand.uris (unprocessed remainder: [Solve])
[picocli WARN] Unbalanced quotes in [Solve] for field java.util.List<java.net.URI> me.itzg.helpers.get.GetCommand.uris (value=https://playerdb.co/api/player/minecraft/"Solve)
[picocli WARN] Unable to respect quotes while splitting value https://playerdb.co/api/player/minecraft/"Solve for field java.util.List<java.net.URI> me.itzg.helpers.get.GetCommand.uris (unprocessed remainder: [Solve])
[mc-image-helper] 22:43:46.766 ERROR : 'get' command failed: Failed to download https://playerdb.co/api/player/minecraft/%22Solve: status code: 400, reason phrase: Bad Request
[init] For already present in ops.json, skipping
[mc-image-helper] 22:43:50.793 ERROR : 'get' command failed: Failed to download https://playerdb.co/api/player/minecraft/M%22: status code: 400, reason phrase: Bad Request
[init] Checking for JSON files.
[init] Setting initial memory to 1024M and max to 1024M
[init] Starting the Minecraft server...
Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
        java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
2024-04-28T22:44:01.779Z        WARN    mc-server-runner        Minecraft server process failed {"exitCode": 1}
2024-04-28T22:44:01.780Z        INFO    mc-server-runner        Done

```

**Comment by itzg** [comment]
Use the `java17` image tag

https://docker-minecraft-server.readthedocs.io/en/latest/versions/java/

**Comment by xamindar** [comment]
Now it produces the following with the following tags set "itzg/mc-backup:java17,itzg/minecraft-server:java17":

`[init] Running as uid=1000 gid=3000 with /data as 'drwxrwsr-x 3 0 2000 4096 Apr 29 00:37 /data'
[init] Resolving type given VANILLA
[init] Resolved version given LATEST into 1.20.5
[init] server.properties already created and managed manually
[mc-image-helper] 00:37:40.605 ERROR : 'manage-users' command failed. Version is 1.38.14
me.itzg.helpers.http.FailedRequestException: HTTP request of https://playerdb.co/api/player/minecraft/%22Solve+For+M%22 failed with 500 Internal Server Error: Fetching object content
        at me.itzg.helpers.http.FetchBuilderBase.lambda$failedRequestMono$2(FetchBuilderBase.java:195)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
        at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:194)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
        at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
        at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:446)
        at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:500)
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:793)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
                at reactor.core.publisher.Mono.block(Mono.java:1712)
                at me.itzg.helpers.users.PlayerdbUserApi.resolveUser(PlayerdbUserApi.java:51)
                at me.itzg.helpers.users.ManageUsersCommand.lambda$resolveJavaUserId$1(ManageUsersCommand.java:254)
                at java.base/java.util.Optional.orElseGet(Unknown Source)
                at me.itzg.helpers.users.ManageUsersCommand.resolveJavaUserId(ManageUsersCommand.java:218)
                at me.itzg.helpers.users.ManageUsersCommand.reconcile(ManageUsersCommand.java:165)
                at me.itzg.helpers.users.ManageUsersCommand.processJavaUserIdList(ManageUsersCommand.java:138)
                at me.itzg.helpers.users.ManageUsersCommand.call(ManageUsersCommand.java:101)
                at me.itzg.helpers.users.ManageUsersCommand.call(ManageUsersCommand.java:35)
                at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
                at picocli.CommandLine.access$1500(CommandLine.java:148)
                at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
                at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
                at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
                at picocli.CommandLine.execute(CommandLine.java:2170)
                at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
`

What was it before the latest update? Was working fine before. I'll try some of the other tags.

**Comment by itzg** [comment]
I'm sorry, I told you the wrong way around. 1.20.5 need Java 21 so use image tag java21 or re-pull "latest" since that is now Java 21.

**Comment by xamindar** [comment]
Got it, tag java21 did finally work, but only on an amd64 node. When it was on an arm64 node it just kept failing to start. Thanks though, that at least gets it up and working for now.
