### ISSUE TITLE
Help PLEASE (Minecraft Server 1.13.2) Server Crash 

### ISSUE THREAD

**Issue by accfdude** [itzg/docker-minecraft-server#282]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 1/15/19 7:34 PM
Description: Exception in server tick loop

com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
	at xj.a(SourceFile:511)
	at xj.a(SourceFile:527)
	at vt.g(SourceFile:146)
	at sn.A(SourceFile:91)
	at sn.<init>(SourceFile:27)
	at so.d(SourceFile:203)
	at net.minecraft.server.MinecraftServer.run(SourceFile:566)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:74)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at xj.a(SourceFile:509)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1664419344 bytes (1587 MB) / 2058354688 bytes (1963 MB) up to 2058354688 bytes (1963 MB)
	JVM Flags: 2 total; -Xmx2048M -Xms2048M
	Profiler Position: N/A (disabled)
	Data Packs: 
	Is Modded: Unknown (can't tell)
	Type: Dedicated Server (map_server.txt)

I really have no clue what went wrong, Any help would be appreciated

**Comment by itzg** [comment]
I'm guessing it's failing on one the json-data files like `ops.json`. It's acting like it's an empty json file, but there's some startup logic to fix up files like that. Can you provide the container startup logs prior to the Minecraft crash dump? Also can you double check you have pulled the latest image?
