### ISSUE TITLE
Having a difficult time figuring why server is not deploying (DawnCraft Modpack)

### ISSUE THREAD

**Issue by D3NZ3N** [itzg/docker-minecraft-server#2833]
### Describe the problem

Im currently trying to run the DawnCraft modpack so my friends and I can enjoy it, but even after reading the whole documentation and trying every single fix, Im still not able to deploy the server. The only error messages I get are the zip END header not found, otherwise everything seems to working fine

### Container definition

version: "3.9"
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY:  <API Key>
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/dawn-craft/files/4900467
      EULA: "TRUE"
      MEMORY: "12G"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - C:\mcserver:/data

### Container logs

2024-05-19 15:31:07 Exception in thread "main" cpw.mods.niofs.union.UnionFileSystem$UncheckedIOException: java.util.zip.ZipException: zip END header not found
2024-05-19 15:31:07 Caused by: java.util.zip.ZipException: zip END header not found
2024-05-19 15:31:08 2024-05-19T13:31:08.082Z    WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.        {"exitCode": 1}
2024-05-19 15:31:08 2024-05-19T13:31:08.082Z    INFO    mc-server-runner        Done

**Comment by itzg** [comment]
That type of error usually indicates a corrupted file and/or download that redirected to an html page. 

If you can identify what files might be doing that, try manually deleting them and letting the startup redownload.

**Comment by D3NZ3N** [comment]
after replacing those files, I now happen to get an error that one mod is not loading, 
-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.2.9.jar%2318!/:1.0] {}
-- MOD compasscoords --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
even tho i let excluded this mod in the enviroment in my docker compose with the Profiled ID of the mod.
CF_EXCLUDE_MODS: "368398"

**Comment by D3NZ3N** [comment]
no clue but its working now, ty for this awesome container !XD

**Comment by districtjackson** [comment]
I was having a similar issue, and what fixed it for me was also deleting the mods folder to force Forge to redownload them, but this time not including compass-coords.
