### ISSUE TITLE
Crash on libXtst.so.6 not found

### ISSUE THREAD

**Issue by moyamejiasr** [itzg/docker-minecraft-server#2862]
### Describe the problem

So I'm trying to start the server but it keeps failing because Fabric keeps trying to load a GUI library nor present on the container. It never happened to me before, and I tried removing mods from the mods folder and restarting the container but nothing stops that message from appearing.

### Container definition

```
version: "3.8"

services:
  minecraft2:
    image: itzg/minecraft-server
    container_name: minecraft2
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25049:25049"
    volumes:
      - /root/minecraft2:/data
    environment:
      UID: "0"
      GID: "0"
      MEMORY: "6G"
      ENABLE_ROLLING_LOGS: "true"
      USE_AIKAR_FLAGS: "true"
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      MODE: "survival"
      DIFFICULTY: "normal"
      MOTD: "Test"
      # LEVEL_TYPE: "terraforged:terraforged"
      # GENERATOR_SETTINGS: "Big_Fancy_Mountains"
      MAX_PLAYERS: "4"
      VIEW_DISTANCE: "10"
      ENABLE_WHITELIST: "true"
      OVERRIDE_WHITELIST: "true"
      WHITELIST: "Me"
      ENFORCE_SECURE_PROFILE: "false"
      # FABRIC_LAUNCHER_VERSION: "0.10.2"
      FABRIC_LOADER_VERSION: "0.15.11"
```

### Container logs

```
[17:57:56] [main/INFO]: Applied 2548 biome modifications to 64 of 64 new biomes in 98.57 ms
[17:57:56] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.UnsatisfiedLinkError: /opt/java/openjdk/lib/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.UnsatisfiedLinkError: /opt/java/openjdk/lib/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.loadLibrary0(Unknown Source) ~[?:?]
	at java.lang.System.loadLibrary(Unknown Source) ~[?:?]
	at java.awt.Toolkit$2.run(Unknown Source) ~[?:?]
	at java.awt.Toolkit$2.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at java.awt.Toolkit.loadLibraries(Unknown Source) ~[?:?]
	at java.awt.Toolkit.initStatic(Unknown Source) ~[?:?]
	at java.awt.Toolkit.<clinit>(Unknown Source) ~[?:?]
	at java.awt.Component.<clinit>(Unknown Source) ~[?:?]
	at net.minecraft.class_3176.method_13948(class_3176.java:345) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_29734(Main.java:234) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:224) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
```

**Comment by moyamejiasr** [comment]
So yeah... for some reason my server is trying to open the GUI. I added the missing lib and now the issue is that it cannot contact the x11 server.

**Comment by itzg** [comment]
You need to remove/exclude what must be a client side mod. Too many mods incorrectly implement their registration logic to skip server side loading.

**Comment by moyamejiasr** [comment]
I see. I suspected something like this. I gave up because it continued failing after removing a bunch of them. But will try a bit more and close the issue.
Thank you very much!
