### ISSUE TITLE
IPv6-only isnt working

### ISSUE THREAD

**Issue by Chem0908** [itzg/docker-minecraft-server#2897]
### Discussed in https://github.com/itzg/docker-minecraft-server/discussions/2889

<div type='discussions-op-text'>

<sup>Originally posted by **Chem0908** June 10, 2024</sup>
i configure the container via Dockge and have trouble to run this with IPv6 only.
Docker seems to work with IPv6 becouse i can reach the WebInteface of Dockge.

I think the problem is the configuration inside the image. An plain alpine container can ping to purpurmc.com
confurations:

> **deamon.js**

```json
{
  "ipv6": true,
  "fixed-cidr-v6": "fd00::/80"
}
```

> **compose.yml**

```yml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "[::]:25566:25566"
    environment:
      EULA: "TRUE"
      TYPE: PURPUR
      VERSION: 1.20.5
      JVM_DD_OPTS: java.net.preferIPv6Addresses=true
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
networks:
  dockge_default:
    enable_ipv6: true
    external: true
```

> Error Message
```batch
minecraft-server-mc-1  | [init] ERROR: failed to download Purpur
minecraft-server-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 5 Jun 10 16:39 /data'
minecraft-server-mc-1  | [init] Resolving type given PURPUR
minecraft-server-mc-1  | [mc-image-helper] 18:13:11.075 ERROR : 'install-purpur' command failed. Version is 1.38.16
minecraft-server-mc-1  | reactor.core.Exceptions$ReactiveException: java.net.UnknownHostException: Failed to resolve 'api.purpurmc.org' [A(1)]
minecraft-server-mc-1  |        at reactor.core.Exceptions.propagate(Exceptions.java:408)
minecraft-server-mc-1  |        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
minecraft-server-mc-1  |        at reactor.core.publisher.Mono.block(Mono.java:1712)
minecraft-server-mc-1  |        at me.itzg.helpers.purpur.InstallPurpurCommand.useCoordinates(InstallPurpurCommand.java:147)
minecraft-server-mc-1  |        at me.itzg.helpers.purpur.InstallPurpurCommand.call(InstallPurpurCommand.java:104)
minecraft-server-mc-1  |        at me.itzg.helpers.purpur.InstallPurpurCommand.call(InstallPurpurCommand.java:35)
minecraft-server-mc-1  |        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
minecraft-server-mc-1  |        at picocli.CommandLine.access$1500(CommandLine.java:148)
minecraft-server-mc-1  |        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
minecraft-server-mc-1  |        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
minecraft-server-mc-1  |        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
minecraft-server-mc-1  |        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
minecraft-server-mc-1  |        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
minecraft-server-mc-1  |        at picocli.CommandLine.execute(CommandLine.java:2174)
minecraft-server-mc-1  |        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
minecraft-server-mc-1  |        Suppressed: java.lang.Exception: #block terminated with an error
minecraft-server-mc-1  |                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
minecraft-server-mc-1  |                ... 13 common frames omitted
minecraft-server-mc-1  | Caused by: java.net.UnknownHostException: Failed to resolve 'api.purpurmc.org' [A(1)]
minecraft-server-mc-1  |        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1151)
minecraft-server-mc-1  |        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1098)
minecraft-server-mc-1  |        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:457)
minecraft-server-mc-1  |        at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:69)
minecraft-server-mc-1  |        at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:526)
minecraft-server-mc-1  |        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
minecraft-server-mc-1  |        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
minecraft-server-mc-1  |        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
minecraft-server-mc-1  |        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
minecraft-server-mc-1  |        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
minecraft-server-mc-1  |        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
minecraft-server-mc-1  |        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
minecraft-server-mc-1  |        at io.netty.resolver.dns.DnsQueryContext.finishFailure(DnsQueryContext.java:380)
minecraft-server-mc-1  |        at io.netty.resolver.dns.DnsQueryContext$5.run(DnsQueryContext.java:315)
minecraft-server-mc-1  |        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
minecraft-server-mc-1  |        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
minecraft-server-mc-1  |        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
minecraft-server-mc-1  |        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
minecraft-server-mc-1  |        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
minecraft-server-mc-1  |        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:408)
minecraft-server-mc-1  |        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
minecraft-server-mc-1  |        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
minecraft-server-mc-1  |        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
minecraft-server-mc-1  |        at java.base/java.lang.Thread.run(Unknown Source)
minecraft-server-mc-1  | Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [15068: /127.0.0.11:53] DefaultDnsQuestion(api.purpurmc.org. IN A) query '15068' via UDP timed out after 5000 milliseconds (no stack trace available)
minecraft-server-mc-1  | [init] ERROR: failed to download Purpur
minecraft-server-mc-1 exited with code 1
```</div>

**Comment by itzg** [comment]
Let's stick with the discussion rather than creating a duplicate issue.
