### ISSUE TITLE
ERROR : 'install-fabric-loader' command failed. Version is 1.39.0 me.itzg.helpers.errors.GenericException: Unable to find requested version

### ISSUE THREAD

**Issue by davralin** [itzg/docker-minecraft-server#2914]
```
[init] Running as uid=1000 gid=3000 with /data as 'drwxrwsr-x 13 0 2000 4096 Jun 18 14:12 /data'
[init] Resolving type given FABRIC
[mc-image-helper] 14:12:55.965 ERROR : 'install-fabric-loader' command failed. Version is 1.39.0
me.itzg.helpers.errors.GenericException: Unable to find requested version
	at me.itzg.helpers.fabric.FabricMetaClient.lambda$resolveMinecraftVersion$4(FabricMetaClient.java:48)
	at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4496)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
		at reactor.core.publisher.Mono.block(Mono.java:1712)
		at me.itzg.helpers.fabric.FabricLauncherInstaller.installUsingVersions(FabricLauncherInstaller.java:70)
		at me.itzg.helpers.fabric.InstallFabricLoaderCommand.call(InstallFabricLoaderCommand.java:93)
		at me.itzg.helpers.fabric.InstallFabricLoaderCommand.call(InstallFabricLoaderCommand.java:15)
		at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
		at picocli.CommandLine.access$1500(CommandLine.java:148)
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
		at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
		at picocli.CommandLine.execute(CommandLine.java:2174)
		at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
[init] ERROR failed to install Fabric launcher given 1.21.0, LATEST, LATEST
```

I'm not really sure if this is the correct repo to submit this bug to, but I see the same people here, as in the other alternatives - so I'm giving it a go!

The relevant parts of the values.yaml-file:
```
  valuesFrom:
    - targetPath: minecraftServer.whitelist
      kind: Secret
      name: minecraft-secrets
      valuesKey: whitelist
    - targetPath: minecraftServer.ops
      kind: Secret
      name: minecraft-secrets
      valuesKey: ops
    - targetPath: mcbackup.resticEnvs.RESTIC_PASSWORD
      kind: Secret
      name: minecraft-secrets
      valuesKey: restic_password
  values:
    extraVolumes:
      - volumeMounts:
          - name: fabric-mods
            mountPath: /mods
            readOnly: false
      - volumes:
         - name: fabric-mods
           persistentVolumeClaim:
             claimName: fabric-mods
    minecraftServer:
      tz: "${TIMEZONE}"
      eula: true
      type: FABRIC
      version: "1.21.0"
      difficulty: "easy"
      maxPlayers: 5
      levelSeed: 421112feedmekittens
      maxTickTime: -1
      mode: creative
      memory: 3G
      motd: "A Creative Minecraft Server"
      overrideServerProperties: true
      rcon:
        enabled: true
    resources:
      requests:
        memory: 3G
    extraEnv:
      ENABLE_AUTOPAUSE: "FALSE"
      USE_AIKAR_FLAGS: true
      ENFORCE_WHITELIST: "TRUE"
      REMOVE_OLD_MODS: "TRUE"
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: "creative.${SECRET_DEFAULT_DOMAIN}"
    podAnnotations:
      reloader.stakater.com/auto: "true"
    persistence:
      dataDir:
        enabled: true
        existingClaim: creative
    mcbackup:
      enabled: true
      pauseIfNoPlayers: true
      backupMethod: restic
      resticRepository: /backups
      pruneBackupsDays: 3
      persistence:
        backupDir:
          enabled: true
          existingClaim: creative-backup
```

When I revert minecraftServer.version to `1.20.6` everything just works, but is obviously the wrong version.

I also cleared all the mods/addons from /mods.

**Comment by Henrique-DeSousa** [comment]
> The error says it all. You requested a version of Fabric that doesn't exist. You probably meant "1.21" not "1.21.0". You'll have to ask Mojang why they drop the third part on the "zero" releases 😀

I have it using vanilla though

**Comment by itzg** [comment]
@Henrique-DeSousa you don't have the same issue then. Please note the mention of **fabric** in the issue title and the use of `type` set to "FABRIC".

Your issue is

```
ConnectTimeoutException: connection timed out after 30000 ms: launchermeta.mojang.com/13.107.246.42:443
```

That is a networking issue on your system somewhere.

**Comment by Henrique-DeSousa** [comment]
> @Henrique-DeSousa you don't have the same issue then. Please note the mention of **fabric** in the issue title and the use of `type` set to "FABRIC".
> 
> Your issue is
> 
> ```
> ConnectTimeoutException: connection timed out after 30000 ms: launchermeta.mojang.com/13.107.246.42:443
> ```
> 
> That is a networking issue on your system somewhere.

Oh `[mc-image-helper] 16:40:54.043 ERROR : 'resolve-minecraft-version' command failed. Version is 1.39.0`. My mistake then

**Comment by davralin** [comment]
> The error says it all. You requested a version of Fabric that doesn't exist. You probably meant "1.21" not "1.21.0". You'll have to ask Mojang why they drop the third part on the "zero" releases 😀

... I don't have anything to say to this.

Everything is good when I use 1.21.

**Comment by Henrique-DeSousa** [comment]
I have no idea how to fix my network issue, my VM has access to the internet and I can connect to my portainer via my web browser but the mc refuses to connect to the network?
