### ISSUE TITLE
Auto CurseForge

### ISSUE THREAD

**Issue by Amatsuka-Mao** [itzg/docker-minecraft-server#2945]
### Describe the problem

11/5000
The github connection refused

### Container definition

```
Paste run command or compose file here
```
docker run -d -v /path/on/host:/data -e TYPE=AUTO_CURSEFORGE \
    -e CF_PAGE_URL=https://www.curseforge.com/minecraft/modpacks/more-animals-fabric \
    -e  CF_SLUG=more-animals-fabric \
    -e	 CF_FILE_ID=5477742	\
    -e CF_API_KEY='$2a$10$CUrZHKdBV2Va/bPP7GzdU.0PpbPTjG7gmQijovq9q68l.L2Za/RDG' \
    -e http_proxy=http://127.0.0.1:7890/ \
    -e https_proxy=https://127.0.0.1:7890 \
    -p 25566:25566 -e EULA=TRUE --name mc2 [ghcr.io/itzg/minecraft-server:java21-graalvm](http://ghcr.io/itzg/minecraft-server:java21-graalvm)

### Container logs

```
Paste logs here
```
[mc-image-helper] 07:16:21.356 ERROR : 'install-curseforge' command failed. Version is 1.39.0
reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: raw.githubusercontent.com/0.0.0.0:443
	at reactor.core.Exceptions.propagate(Exceptions.java:408)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
	at reactor.core.publisher.Mono.block(Mono.java:1712)
	at me.itzg.helpers.http.ObjectFetchBuilder.execute(ObjectFetchBuilder.java:44)
	at me.itzg.helpers.curseforge.InstallCurseForgeCommand.loadExcludeIncludesFile(InstallCurseForgeCommand.java:323)
	at me.itzg.helpers.curseforge.InstallCurseForgeCommand.loadExcludeIncludes(InstallCurseForgeCommand.java:266)
	at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:185)
	at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
		... 15 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: raw.githubusercontent.com/0.0.0.0:443
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:166)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:715)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:692)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:491)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[init] ERROR failed to auto-install CurseForge modpack

**Comment by Amatsuka-Mao** [comment]
It doesn't matter if I join the agency

**Comment by itzg** [comment]
Something is wrong with your networking including DNS. Looking at

```
Connection refused: raw.githubusercontent.com/0.0.0.0:443
```

The IP address 0.0.0.0 is not a valid remote address. 

I will convert this to a discussion since there is nothing I can fix in the image for this.
