### ISSUE TITLE
Container is failing to download "paper"

### ISSUE THREAD

**Issue by adnieman** [itzg/docker-minecraft-server#2992]
### Describe the problem

I did a pull after successfully running 1.21, and now its exiting without being able to download paper

### Container definition

```
services:
  minecraft-existence:
    container_name: minecraft-existence
    user: 1000:1000
    image: itzg/minecraft-server
    ports:
      - 127.0.0.1:25575:25575/tcp # RCON port (localhost)
      - 25565:25565/udp           # Query port
      - 25565:25565/tcp           # Game port
    environment:
      CREATE_CONSOLE_IN_PIPE: true
      MEMORY: 10G
      USE_AIKAR_FLAGS: true
      JVM_OPTS:
        -Dlog4j.configurationFile=log4j2.xml
        -Dpaper.playerconnection.keepalive=60
        -Ddisable.watchdog=true
      TYPE: PAPER
      VERSION: 1.21
      OVERRIDE_SERVER_PROPERTIES: true
      EULA: true
      ENABLE_RCON: true
      RCON_PORT: 25575
      ENABLE_AUTOPAUSE: true
      AUTOPAUSE_TIMEOUT_INIT: 120
      AUTOPAUSE_TIMEOUT_EST: 90
      AUTOPAUSE_TIMEOUT_KN: 90
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /[REDACTED]/minecraft-existence:/data
```

### Container logs

```
[mc-image-helper] 10:27:38.936 DEBUG : Retrieving latest build for project=paper, version=1.21
[mc-image-helper] 10:27:39.780 DEBUG : JSON FETCH: uri=https://api.papermc.io/v2/projects/paper/versions/1.21/builds headers=[user-agent: itzg/mc-image-helper/1.39.6 (cmd=install-paper), x-fetch-session: b06250cf-daf4-48e2-bfb1-bf3e22818151, accept: application/json, host: api.papermc.io]
[mc-image-helper] 10:27:40.541 ERROR : Invalid parameter provided for 'install-paper' command: No build found for version 1.21 with channel default
[mc-image-helper] 10:27:40.541 DEBUG : Invalid parameter details
me.itzg.helpers.errors.InvalidParameterException: No build found for version 1.21 with channel default
	at me.itzg.helpers.paper.InstallPaperCommand.lambda$downloadUsingCoordinates$6(InstallPaperCommand.java:253)
	at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4496)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:155)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
		at reactor.core.publisher.Mono.block(Mono.java:1712)
		at me.itzg.helpers.paper.InstallPaperCommand.call(InstallPaperCommand.java:132)
		at me.itzg.helpers.paper.InstallPaperCommand.call(InstallPaperCommand.java:39)
		at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
		at picocli.CommandLine.access$1500(CommandLine.java:148)
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
		at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
		at picocli.CommandLine.execute(CommandLine.java:2174)
		at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
+ log 'ERROR: failed to download paper'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2024-07-14 10:27:40-04:00 ERROR: failed to download paper
+ exit 1
```

**Comment by itzg** [comment]
```
No build found for version 1.21 with channel default
```

![image](https://github.com/user-attachments/assets/763107ad-3530-4d56-945d-725e38931aad)

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/server-types/paper/#:~:text=to%20allow%20for%20the%20selection%20of%20experimental%20builds%2C%20set%20paper_channel%20to%20%22experimental%22 "To allow for the selection of experimental builds, set PAPER_CHANNEL to "experimental""

**Comment by adnieman** [comment]
It worked a treat. Thank you.  I used to live by RTFM, but I've been out of the industry for a long time.  Next time I'll take the time to RTFM first instead of filing a bug report.

**Comment by itzg** [comment]
Hmm, to help the search algo, I should probably include the error phrase on that page...

**Comment by adnieman** [comment]
I think you might just be correct, sir. If I was having this issue, it stands to reason that others are or will.
