### ISSUE TITLE
1.20.1 AUTO_CURSEFORGE failing to load modpacks?

### ISSUE THREAD

**Issue by joeyfigaro** [itzg/docker-minecraft-server#3018]
### Describe the problem

I can't get any modpacks to work properly in a 1.20.1 server. I've tried dozens.

### Container definition

```yml
services:
  mc:
    container_name: meowcraft-1.20
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: TRUE
      SEED: 2725214931529352700
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: $$2a$10$$...
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/valhelsia-6"
      CF_SLUG: valhelsia-6
      # CF_FILE_ID: "5529449" # server modpack
      CF_FILE_ID: "5529180" # client modpack
      VERSION: 1.20.1
      MAX_MEMORY: 8G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
      - ./mods.txt:/extras/mods.txt:ro
volumes:
  data:
```

starting it up with:
`sudo docker compose up`

### Container logs

```shell
meowcraft-1.20  | [init] Using Forge supplied run.sh script...
meowcraft-1.20  | 2024-07-28 13:37:37,616 main WARN Advanced terminal features are not available in this environment
meowcraft-1.20  | [13:37:37] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.3.5, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
meowcraft-1.20  | [13:37:37] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8.1 by Eclipse Adoptium; OS Linux arch amd64 version 6.2.0-39-generic
meowcraft-1.20  | [13:37:41] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
meowcraft-1.20  | [13:37:41] [main/INFO] [gg.es.lo.st.EssentialLoaderBase/]: Updating Essential Loader (stage2) version 1.4.1 (4b3b87be87d34916028dffa85460d085) from union:/data/mods/essential_1-3-1-1_forge_1-20-1.jar%23412!/stage2_1-4-1_forge_1-17-1.jar
meowcraft-1.20  | [13:37:41] [main/FATAL] [cp.mo.mo.TransformationServicesHandler/MODLAUNCHER]: Encountered serious error loading transformation service, expect problems
meowcraft-1.20  | java.util.ServiceConfigurationError: cpw.mods.modlauncher.api.ITransformationService: Provider gg.essential.container.loader.stage0.EssentialTransformationService could not be instantiated
meowcraft-1.20  | 	at java.util.ServiceLoader.fail(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.ServiceLoader$ProviderImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.ServiceLoader$ProviderImpl.get(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.util.ServiceLoaderUtils.lambda$streamWithErrorHandling$0(ServiceLoaderUtils.java:39) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.ServiceLoader$ProviderSpliterator.tryAdvance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.Spliterator.forEachRemaining(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:133) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:87) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
meowcraft-1.20  | Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.loadStage1OrThrow(EssentialTransformationServiceBase.java:27) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.lambda$new$0(EssentialTransformationServiceBase.java:20) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.util.DelegatingTransformationServiceBase.<init>(DelegatingTransformationServiceBase.java:13) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.<init>(EssentialTransformationServiceBase.java:20) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationService.<init>(EssentialTransformationService.java:7) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	... 17 more
meowcraft-1.20  | Caused by: java.lang.reflect.InvocationTargetException
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.loadStage1(EssentialTransformationServiceBase.java:47) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.loadStage1OrThrow(EssentialTransformationServiceBase.java:25) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.lambda$new$0(EssentialTransformationServiceBase.java:20) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.util.DelegatingTransformationServiceBase.<init>(DelegatingTransformationServiceBase.java:13) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.<init>(EssentialTransformationServiceBase.java:20) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationService.<init>(EssentialTransformationService.java:7) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	... 17 more
meowcraft-1.20  | Caused by: java.lang.NoClassDefFoundError: org/apache/commons/codec/digest/DigestUtils
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialLoaderBase.getChecksum(EssentialLoaderBase.java:356) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialLoaderBase.downloadFile(EssentialLoaderBase.java:473) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialLoaderBase.doDownload(EssentialLoaderBase.java:326) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:176) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialTransformationServiceBase.<init>(EssentialTransformationServiceBase.java:46) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialTransformationService.<init>(EssentialTransformationService.java:29) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.loadStage1(EssentialTransformationServiceBase.java:47) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.loadStage1OrThrow(EssentialTransformationServiceBase.java:25) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.lambda$new$0(EssentialTransformationServiceBase.java:20) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.util.DelegatingTransformationServiceBase.<init>(DelegatingTransformationServiceBase.java:13) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.<init>(EssentialTransformationServiceBase.java:20) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationService.<init>(EssentialTransformationService.java:7) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	... 17 more
meowcraft-1.20  | Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.digest.DigestUtils
meowcraft-1.20  | 	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialLoaderBase.getChecksum(EssentialLoaderBase.java:356) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialLoaderBase.downloadFile(EssentialLoaderBase.java:473) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialLoaderBase.doDownload(EssentialLoaderBase.java:326) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:176) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialTransformationServiceBase.<init>(EssentialTransformationServiceBase.java:46) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.loader.stage1.EssentialTransformationService.<init>(EssentialTransformationService.java:29) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.loadStage1(EssentialTransformationServiceBase.java:47) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.loadStage1OrThrow(EssentialTransformationServiceBase.java:25) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.lambda$new$0(EssentialTransformationServiceBase.java:20) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.util.DelegatingTransformationServiceBase.<init>(DelegatingTransformationServiceBase.java:13) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationServiceBase.<init>(EssentialTransformationServiceBase.java:20) ~[?:?] {}
meowcraft-1.20  | 	at gg.essential.container.loader.stage0.EssentialTransformationService.<init>(EssentialTransformationService.java:7) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	... 17 more
meowcraft-1.20  | [13:37:42] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/data/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
meowcraft-1.20  | [13:37:43] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/libraries/net/minecraftforge/fmlcore/1.20.1-47.3.5/fmlcore-1.20.1-47.3.5.jar is missing mods.toml file
meowcraft-1.20  | [13:37:43] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.3.5/javafmllanguage-1.20.1-47.3.5.jar is missing mods.toml file
meowcraft-1.20  | [13:37:43] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.3.5/lowcodelanguage-1.20.1-47.3.5.jar is missing mods.toml file
meowcraft-1.20  | [13:37:43] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/libraries/net/minecraftforge/mclanguage/1.20.1-47.3.5/mclanguage-1.20.1-47.3.5.jar is missing mods.toml file
meowcraft-1.20  | [13:37:43] [main/ERROR] [ne.mi.fm.lo.UniqueModListBuilder/LOADING]: Found duplicate mods:
meowcraft-1.20  | 	Mod ID: 'jei' from mod files: jei-1.20.1-forge-15.3.0.8.jar, REIPluginCompatibilities-forge-12.0.93.jar
meowcraft-1.20  | [13:37:43] [main/ERROR] [ne.mi.fm.lo.mo.ModDiscoverer/SCAN]: Failed to build unique mod list after mod discovery.
meowcraft-1.20  | net.minecraftforge.fml.loading.EarlyLoadingException: Duplicate mods found
meowcraft-1.20  | 	at net.minecraftforge.fml.loading.UniqueModListBuilder.buildUniqueList(UniqueModListBuilder.java:87) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:1.0] {}
meowcraft-1.20  | 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:106) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
meowcraft-1.20  | 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:1.0] {}
meowcraft-1.20  | 	at net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:1.0] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
meowcraft-1.20  | 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
meowcraft-1.20  | [13:37:43] [main/ERROR] [ne.mi.fm.lo.mo.ModDiscoverer/SCAN]: Mod Discovery failed. Skipping dependency discovery.
meowcraft-1.20  | Exception in thread "main" java.lang.IllegalStateException: Failed to find system mod: minecraft
meowcraft-1.20  | 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.ModSorter.detectSystemMods(ModSorter.java:181)
meowcraft-1.20  | 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.ModSorter.buildUniqueList(ModSorter.java:145)
meowcraft-1.20  | 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.ModSorter.sort(ModSorter.java:53)
meowcraft-1.20  | 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.moddiscovery.ModValidator.stage2Validation(ModValidator.java:120)
meowcraft-1.20  | 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.FMLLoader.completeScan(FMLLoader.java:172)
meowcraft-1.20  | 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.FMLServiceProvider.completeScan(FMLServiceProvider.java:91)
meowcraft-1.20  | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServiceDecorator.onCompleteScan(TransformationServiceDecorator.java:174)
meowcraft-1.20  | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$triggerScanCompletion$24(TransformationServicesHandler.java:145)
meowcraft-1.20  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
meowcraft-1.20  | 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
meowcraft-1.20  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
meowcraft-1.20  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
meowcraft-1.20  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
meowcraft-1.20  | 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
meowcraft-1.20  | 	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
meowcraft-1.20  | 	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
meowcraft-1.20  | 	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
meowcraft-1.20  | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.triggerScanCompletion(TransformationServicesHandler.java:147)
meowcraft-1.20  | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:95)
meowcraft-1.20  | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
meowcraft-1.20  | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
meowcraft-1.20  | 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
meowcraft-1.20  | 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
meowcraft-1.20  | 2024-07-28T13:37:44.035Z	WARN	mc-server-runner	Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.	{"exitCode": 1}
meowcraft-1.20  | 2024-07-28T13:37:44.037Z	INFO	mc-server-runner	Done
meowcraft-1.20 exited with code 0
```

I've tried two file IDs: one for the server modpack and one for (what I assume is) the client modpack. If I use the server modpack's file id, I get an error saying there's no manifest.json and to make sure I'm using a client modpack. If I use the client modpack, I get the error pasted above. I've also tried specifying the java version as part of the image to no avail. 

I see issues with mod duplication–is that the core issue here? 

edit: forgot to remove CF api key. Regenerated and redacted here.

**Comment by itzg** [comment]
Since there are several in the examples directory that work, there might be something that got out of sync in your data directory. You could try wiping the directory. Also, re-pull the image to make sure you have the latest. 

Given the root cause is

```
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/codec/digest/DigestUtils
```

Maybe forcing Forge to be re-installed would help with setting CF_FORCE_REINSTALL_MODLOADER to "true".
