### ISSUE TITLE
Minecraft Server Failed

### ISSUE THREAD

**Issue by Schmukas** [itzg/docker-minecraft-server#3041]
### Describe the problem

ive tried to setup a all the mods 9 server using auto curseforge but with little succes, everytime i start the container get the "WARN	mc-server-runner	Minecraft server failed." error

### Container definition

Im using Portainer on top of Docker

### Container logs

[init] Using Forge supplied run.sh script...

[mc-image-helper] 15:11:32.034 INFO  : Requested CurseForge modpack All the Mods 9-0.3.0 is already installed for All the Mods 9 - ATM9

[init] Running as uid=1000 gid=1000 with /data as 'drwxr-x--- 14 1000 1000 4096 Aug 12 13:49 /data'

[mc-image-helper] 15:11:33.303 INFO  : Forge version 47.2.20 for minecraft version 1.20.1 is already installed

[init] Setting mode

[mc-image-helper] 15:11:36.192 INFO  : Created/updated 1 property in /data/server.properties

[init] Setting initial memory to 16G and max to 16G

[15:11:39] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.20, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]

[15:11:39] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.4 by Eclipse Adoptium; OS Linux arch amd64 version 6.8.8-3-pve

Exception in thread "main" cpw.mods.niofs.union.UnionFileSystem$UncheckedIOException: java.util.zip.ZipException: zip END header not found

Caused by: java.util.zip.ZipException: zip END header not found

	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)

	at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source)

	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(Unknown Source)

	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(Unknown Source)

	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(Unknown Source)

	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(Unknown Source)

	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(Unknown Source)

	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.openFileSystem(UnionFileSystem.java:136)

	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)

	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:131)

	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)

	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)

	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)

	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66)

	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)

	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)

	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)

	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:76)

	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)

	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)

	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)

	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)

	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)

	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)

	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:65)

	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:48)

	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:38)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:125)

	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127)

	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)

	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

2024-08-12T15:11:40.030+0200	WARN	mc-server-runner	Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.	{"exitCode": 1}

2024-08-12T15:11:40.031+0200	INFO	mc-server-runner	Done

**Comment by itzg** [comment]
Sounds like a corrupted jar file perhaps within the modloader. Try temporarily setting `CF_FORCE_REINSTALL_MODLOADER` to "true" 

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#extra-options

**Comment by Schmukas** [comment]
Still the same issue
Logs:

[init] Running as uid=1000 gid=1000 with /data as 'drwxr-x--- 14 1000 1000 4096 Aug 12 13:49 /data'

[mc-image-helper] 18:09:42.575 INFO  : Requested CurseForge modpack All the Mods 9-0.3.0 is already installed for All the Mods 9 - ATM9

[mc-image-helper] 18:09:43.835 INFO  : Downloading Forge installer 47.2.20 for Minecraft 1.20.1

[mc-image-helper] 18:09:55.692 INFO  : Running Forge 47.2.20 installer for Minecraft 1.20.1. This might take a while...

[init] Setting mode

[mc-image-helper] 18:10:22.402 INFO  : Created/updated 1 property in /data/server.properties

[init] Setting initial memory to 16G and max to 16G

[init] Using Forge supplied run.sh script...

[18:10:26] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.20, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]

[18:10:26] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.4 by Eclipse Adoptium; OS Linux arch amd64 version 6.8.8-3-pve

Exception in thread "main" cpw.mods.niofs.union.UnionFileSystem$UncheckedIOException: java.util.zip.ZipException: zip END header not found

Caused by: java.util.zip.ZipException: zip END header not found

	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(Unknown Source)

	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(Unknown Source)

	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(Unknown Source)

	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(Unknown Source)

	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(Unknown Source)

	at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source)

	at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source)

	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.openFileSystem(UnionFileSystem.java:136)

	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)

	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)

	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)

	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:131)

	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)

	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)

	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)

	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)

	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66)

	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)

	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)

	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:76)

	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)

	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)

	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)

	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)

	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)

	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:65)

	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:48)

	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:38)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:125)

	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)

	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)

	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

2024-08-12T18:10:26.828+0200	WARN	mc-server-runner	Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.	{"exitCode": 1}

2024-08-12T18:10:26.828+0200	INFO	mc-server-runner	Done

**Comment by itzg** [comment]
I would now suggest deleting everything in your data directory except the world data.

**Comment by Schmukas** [comment]
Well i fixed it, issue was that i originally installed the server on 1.21.1 instead of 1.20.1 and didnt delete the world after switching versions which caused the server to fail at boot, and i also had to manually delete the old server.jar (which was and at 1.21.) and inserted the 1.20.1 server.jar
