### ISSUE TITLE
Minecraft Server: 1.5.2 didn't work

### ISSUE THREAD

**Issue by helmerdavila** [itzg/docker-minecraft-server#306]
I tried with 1.7.10. Server works perfectly. Then I tried with 1.5.2 and I see this message

Error: Could not find or load main class net.minecraft.server.MinecraftServer

**Comment by itzg** [comment]
Other than `VERSION` and `EULA`, were there any other variable you had set?

With a fresh container I am able to startup with 1.5.2:

```
> docker run -it --rm -e EULA=TRUE -e VERSION=1.5.2 itzg/minecraft-server
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Apr 22 01:41 /data'
Checking version information.
Checking type information.
Downloading minecraft_server.1.5.2.jar ...
Creating server.properties in /data/server.properties
Setting server-name to 'Dedicated Server' in /data/server.properties
Setting server-port to '25565' in /data/server.properties
Setting motd to 'A Vanilla Minecraft Server powered by Docker' in /data/server.properties
Skip setting allow-nether
Skip setting announce-player-achievements
Skip setting enable-command-block
Skip setting spawn-animals
Skip setting spawn-monsters
Skip setting spawn-npcs
Skip setting generate-structures
Skip setting view-distance
Skip setting hardcore
Skip setting snooper-enabled
Skip setting max-build-height
Skip setting force-gamemode
Skip setting max-tick-time
Skip setting enable-query
Skip setting query.port
Setting enable-rcon to 'true' in /data/server.properties
Setting rcon.password to 'minecraft' in /data/server.properties
Setting rcon.port to '25575' in /data/server.properties
Skip setting max-players
Skip setting max-world-size
Setting level-name to 'world' in /data/server.properties
Skip setting level-seed
Setting pvp to 'true' in /data/server.properties
Skip setting generator-settings
Setting online-mode to 'true' in /data/server.properties
Skip setting allow-flight
Setting level-type to 'DEFAULT' in /data/server.properties
Setting difficulty to '1' in /data/server.properties
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 1G
229 recipes
27 achievements
2019-04-22 01:41:59 [INFO] Starting minecraft server version 1.5.2
2019-04-22 01:41:59 [INFO] Loading properties
2019-04-22 01:41:59 [INFO] Default game type: SURVIVAL
2019-04-22 01:41:59 [INFO] Generating keypair
2019-04-22 01:42:00 [INFO] Starting Minecraft server on *:25565
2019-04-22 01:42:00 [WARNING] Failed to load operators list: java.io.FileNotFoundException: ./ops.txt (No such file or directory)
2019-04-22 01:42:00 [WARNING] Failed to load white-list: java.io.FileNotFoundException: ./white-list.txt (No such file or directory)
2019-04-22 01:42:00 [INFO] Preparing level "world"
2019-04-22 01:42:00 [INFO] Preparing start region for level 0
2019-04-22 01:42:01 [INFO] Preparing spawn area: 9%
2019-04-22 01:42:02 [INFO] Preparing spawn area: 22%
2019-04-22 01:42:03 [INFO] Preparing spawn area: 36%
2019-04-22 01:42:04 [INFO] Preparing spawn area: 50%
2019-04-22 01:42:05 [INFO] Preparing spawn area: 65%
2019-04-22 01:42:06 [INFO] Preparing spawn area: 76%
2019-04-22 01:42:07 [INFO] Preparing spawn area: 89%
2019-04-22 01:42:08 [INFO] Preparing spawn area: 98%
2019-04-22 01:42:09 [INFO] Done (9.033s)! For help, type "help" or "?"
2019-04-22 01:42:09 [INFO] Starting remote control listener
2019-04-22 01:42:09 [INFO] RCON running on 0.0.0.0:25575
```

**Comment by helmerdavila** [comment]
I'm using Forge. Here my complete docker-compose file

```yml
version: '3'

services:
  minecraft-server:
    ports:
      - "25565:25565"
    volumes:
      - .:/data
    environment:
      EULA: "TRUE"
      VERSION: 1.5.2
      SERVER_NAME: "OneMinecraftServer"
      TYPE: FORGE
      ONLINE_MODE: 0
      DIFFICULTY: "normal"  
    image: itzg/minecraft-server
    container_name: minecraft-server
    tty: true
    stdin_open: true
    restart: always
```

**Comment by itzg** [comment]
Ah, Forge specifically has this issue. This seems to be a known problem when running with Java 8

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2206446-forge-1-6-4-1-7-2-java-8-compatibility-patch

I don't see a patched file for 1.5, so I'm not sure if this is easily fixable.

**Comment by itzg** [comment]
Just as a note, switching the image to use Java 7 resulted in a different error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: ab
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Caused by: java.lang.ClassNotFoundException: ab
	at java.net.URLClassLoader$1.run(URLClassLoader.java:360)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	... 13 more
```

**Comment by kolaente** [comment]
I have a very similar issue:

```
Minecraft_1  | Saving optional modlist to: ./mods/mod_list.json
Minecraft_1  | java.io.FileNotFoundException: ./mods/mod_list.json (No such file or directory)
Minecraft_1  | 	at java.io.FileOutputStream.open0(Native Method)
Minecraft_1  | 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
Minecraft_1  | 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
Minecraft_1  | 	at com.google.common.io.Files$FileByteSink.openStream(Files.java:223)
Minecraft_1  | 	at com.google.common.io.Files$FileByteSink.openStream(Files.java:211)
Minecraft_1  | 	at com.google.common.io.ByteSink$AsCharSink.openStream(ByteSink.java:136)
Minecraft_1  | 	at com.google.common.io.CharSink.write(CharSink.java:86)
Minecraft_1  | 	at com.google.common.io.Files.write(Files.java:467)
Minecraft_1  | 	at net.minecraftforge.installer.OptionalLibrary.saveModListJson(OptionalLibrary.java:102)
Minecraft_1  | 	at net.minecraftforge.installer.ServerInstall.run(ServerInstall.java:97)
Minecraft_1  | 	at net.minecraftforge.installer.InstallerAction.run(InstallerAction.java:43)
Minecraft_1  | 	at net.minecraftforge.installer.SimpleInstaller.handleOptions(SimpleInstaller.java:72)
Minecraft_1  | 	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:47)
Minecraft_1  | There was an error during server installation
Minecraft_1  | Forge failed to install after several tries.
```

Here is my compose file:
```yaml
version: '2'
services:
  Minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - MODE=survival
      - DIFFICULTY=normal
      - EULA=true
      - PVP=false
      - MOTD=A Minecraft server powered by Docker
      - OPS=kolaente
      - VERSION=1.10.2
      - FORGEVERSION=12.18.3.2511
      - TYPE=FORGE
      - LEVEL_TYPE=DEFAULT
      - LEVEL=world
      - ENABLE_RCON=true
      - RCON_PORT=25575
      - RCON_PASSWORD=minecraft
      - SERVER_PORT=25565
      - ONLINE_MODE=TRUE
      - MEMORY=3G
    ports:
      - 25555:25565
      - 127.0.0.1:25575:25575
    volumes:
      - /path/to/data:/data
```

**Comment by Syndesi** [comment]
Hi,

I was able to start FTB Monster (MC 1.6.4) with Java 7.

```
# docker-compose.yml
version: '2'

services:
  mc-164:
#    image: itzg/minecraft-server
    build: ./docker-minecraft-server
    container_name: mc-164
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - /srv/docker/mc_164/data:/data
    environment:
      - EULA=true
      - VERSION=1.6.4
      - TYPE=FORGE
      - FORGEVERSION=9.11.1.965
      - SERVER_NAME=Monster
      - DIFFICULTY=normal
      - MAX_PLAYERS=10
      - ENABLE_COMMAND_BLOCK=true
      - SNOOPER_ENABLED=false
      - MODE=survival
      - PVP=true
      - LEVEL_TYPE=default
      - MEMORY=4G
      - SEED=-2149260122861391698
    ports:
      - "25565:25565"
```

And I cloned this repo into `/srv/docker/mc_164/docker-minecraft-server` and replaced the first line of the Dockerfile with the following:
`FROM openjdk:7u211-jre-alpine`

I only got errors regarding client-mods. I totally forgot that these still existed in 1.6.4 ^^

**Comment by itzg** [comment]
@TTR-maniac it looks like I forgot to document that there's a java7 image tag now. Can you try that?

**Comment by gatoborrachon** [comment]
@itzg i get the same issue of this comment using Java 7 and MC 1.5.2 
(Exception in thread "main" java.lang.NoClassDefFoundError: ab)
https://github.com/itzg/docker-minecraft-server/issues/306#issuecomment-486495620

was you able to fix it?

well, i'm not using the software of this repo, but if you know the fix, well, i kindly ask for it, maybe using a specific version of java 7?

**Comment by itzg** [comment]
> @itzg i get the same issue of [this comment](https://github.com/itzg/docker-minecraft-server/issues/306#issuecomment-486495620
> 
> ) using Java 7 and MC 1.5.2 with forge
> 
> (Exception in thread "main" java.lang.NoClassDefFoundError: ab)
> 
> 
> 
> was you able to fix it?

Unfortunately no, I didn't find a solution for that particular one. A class called "ab" seems likes coming from the obfuscated Minecraft code itself. So maybe there's a mod that should be added in there somehow.

**Comment by gatoborrachon** [comment]
wow, well, i just found the fix, from [this comment:](https://forums.minecraftforge.net/topic/10338-can-forge-as-a-jar-run-minecraft-server-152/?tab=comments#comment-54022)

+rename the file called "minecraft_server.1.5.2.jar" to "minecraft_server.jar"

it works pretty fine, i hope this helps anyone who require it

**Comment by itzg** [comment]
Very interesting. I could have the setup script handle that actually. I wonder what version that constraint was relaxed?

**Comment by itzg** [comment]
The latest images now adjust the server jar name to be `minecraft_server.jar` for versions before 1.6
