### ISSUE TITLE
Mod 'Prominent' (prominent) 3.0.0 requires any version of luna, which is missing!

### ISSUE THREAD

**Issue by Katze719** [itzg/docker-minecraft-server#3082]
### Describe the problem

trying to install the modpack https://www.curseforge.com/minecraft/modpacks/prominence-2-rpg

`Mod 'Prominent' (prominent) 3.0.0 requires any version of luna, which is missing!` how can i force install mods? 

```yml
CF_FORCE_INCLUDE_MODS: |
        luna
```

is not working for me

### Container definition

```yml
services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: 'hmmmmmmm'
      CF_SLUG: "prominence-2-rpg"
      DEBUG: true
      MEMORY: "15G"
      CF_FORCE_SYNCHRONIZE: true
      CF_FORCE_INCLUDE_MODS: |
        luna
    volumes:
      - "./minecraft_data:/data"
```

### Container logs

```
minecraft  | + isTrue ''
minecraft  | + case "${1,,}" in
minecraft  | + return 1
minecraft  | + [[ FABRIC == \C\U\R\S\E\F\O\R\G\E ]]
minecraft  | + [[ FABRIC == \C\U\R\S\E\F\O\R\G\E ]]
minecraft  | + [[ ./fabric-server-mc.1.20.1-loader.0.15.11-launcher.1.0.1.jar =~ run.sh ]]
minecraft  | + '[' -f /data/bootstrap.txt ']'
minecraft  | + log 'Starting the Minecraft server...'
minecraft  | + local oldState
minecraft  | ++ shopt -po xtrace
minecraft  | + oldState='set -o xtrace'
minecraft  | + shopt -u -o xtrace
minecraft  | [init] 2024-09-27 16:14:35+00:00 Starting the Minecraft server...
minecraft  | + finalArgs=($JVM_XX_OPTS $JVM_OPTS $expandedDOpts)
minecraft  | + [[ -n '' ]]
minecraft  | + finalArgs+=(-jar "$SERVER")
minecraft  | + finalArgs+=("$@" $EXTRA_ARGS)
minecraft  | + isTrue false
minecraft  | + case "${1,,}" in
minecraft  | + return 1
minecraft  | + isTrue false
minecraft  | + case "${1,,}" in
minecraft  | + return 1
minecraft  | + isTrue false
minecraft  | + case "${1,,}" in
minecraft  | + return 1
minecraft  | + exec mc-server-runner --stop-duration 60s java -Xmx15G -Xms15G -jar ./fabric-server-mc.1.20.1-loader.0.15.11-launcher.1.0.1.jar
minecraft  | Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
minecraft  | [16:14:36] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
minecraft  | [16:14:36] [ForkJoinPool-1-worker-5/WARN]: Mod death_knights uses the version 0.3.1beta which isn't compatible with Loader's extended semantic version format (Could not parse version number component '1beta'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:36] [ForkJoinPool-1-worker-7/WARN]: Mod oceansdelight uses the version fdrf-fabric-1.0.2-1.20 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fdrf'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:36] [ForkJoinPool-1-worker-6/WARN]: Mod wither_spawn_fix uses the version MC1.20.1-1.0.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'MC1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:36] [ForkJoinPool-1-worker-8/WARN]: Mod geophilic uses the version v2.1.0-mc1.20u1.20.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v2'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:36] [ForkJoinPool-1-worker-7/WARN]: Mod explorify uses the version v1.3.0-mc1.20 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:36] [ForkJoinPool-1-worker-4/WARN]: The mod "necronomicon" contains invalid entries in its mod json:
minecraft  | - Unsupported root entry "credits" at line 10 column 14
minecraft  | [16:14:36] [ForkJoinPool-1-worker-8/WARN]: The mod "openblocks" contains invalid entries in its mod json:
minecraft  | - Unsupported root entry "client" at line 24 column 11
minecraft  | [16:14:36] [ForkJoinPool-1-worker-8/WARN]: Mod magna uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:36] [ForkJoinPool-1-worker-3/WARN]: Mod ends_delight uses the version refabricated-1.20.1-alpha-1.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'refabricated'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:36] [ForkJoinPool-1-worker-2/WARN]: The mod "dungeons_arise" contains invalid entries in its mod json:
minecraft  | - Unsupported root entry "credits" at line 12 column 12
minecraft  | [16:14:37] [ForkJoinPool-1-worker-5/WARN]: Mod netherdepthsupgrade uses the version fabric-3.1.1-1.20 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:37] [ForkJoinPool-1-worker-4/WARN]: Mod travelersbackpack uses the version fabric-1.20.1-9.1.15 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:37] [ForkJoinPool-1-worker-8/WARN]: Mod io_netty_netty-codec-socks uses the version 4.1.82.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:37] [ForkJoinPool-1-worker-8/WARN]: Mod io_netty_netty-handler-proxy uses the version 4.1.82.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:37] [ForkJoinPool-1-worker-8/WARN]: Mod io_netty_netty-codec-http uses the version 4.1.82.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
minecraft  | [16:14:37] [main/INFO]: Dependencies overridden for smoothgui, create_questing, estrogen, thermoo, bettertrims, frostiful, chatanimation, copycats
minecraft  | [16:14:37] [main/WARN]: Mod resolution failed
minecraft  | [16:14:37] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE prominent 3.0.0 {depends luna @ [*]}, ROOT_FORCELOAD_SINGLE prominent 3.0.0]
minecraft  | [16:14:37] [main/INFO]: Reason: [HARD_DEP prominent 3.0.0 {depends luna @ [*]}]
minecraft  | [16:14:37] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, fastipping, auudio, modmenu, sodium-extra, animation_overhaul, fabric-screen-api-v1, fabric-renderer-indigo, mindfuldarkness, reeses-sodium-options, bobby, flywheel, citresewn, fabric-rendering-v0, fabric-sound-api-v1, fallingleaves, fabric-rendering-v1, fabric-key-binding-api-v1, spruceui, fabric-model-loading-api-v1, amecs, emitrades, resourcepackoverrides, indium, fabric-client-tags-api-v1, seasonhud, visuality, emiffect, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, chat_heads, languagereload, fabric-models-v0, zoomify, sdrp, loadmyresources, noindium]
minecraft  | [16:14:37] [main/INFO]: Fix: add [add:luna 1 ([(-∞,∞)])], remove [], replace []
minecraft  | [16:14:37] [main/ERROR]: Incompatible mods found!
minecraft  | net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
minecraft  | A potential solution has been determined, this may resolve your problem:
minecraft  | 	 - Install luna, any version.
minecraft  | More details:
minecraft  | 	 - Mod 'Prominent' (prominent) 3.0.0 requires any version of luna, which is missing!
minecraft  | 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
minecraft  | 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
minecraft  | 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
minecraft  | 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.11.jar:?]
minecraft  | 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
minecraft  | 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
minecraft  | 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
minecraft  | 2024-09-27T16:14:37.787Z	WARN	mc-server-runner	Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.	{"exitCode": 1}
minecraft  | 2024-09-27T16:14:37.788Z	INFO	mc-server-runner	Done
```

**Comment by EmilyxFox** [comment]
When you ran it the first time did it tell you that you needed to manually install any of the mods?

**Comment by Katze719** [comment]
got it working by manually mounting the mod

**Comment by Katze719** [comment]
but the server seems not to be very stable, exceptions on boot and server crashed after crafting wood planks

**Comment by itzg** [comment]
> but the server seems not to be very stable, exceptions on boot and server crashed after crafting wood planks 
> 
> 
> 
> ```
> 
> minecraft  | [16:40:51] [Netty Epoll Server IO #4/ERROR]: Exception occurred in netty pipeline
> 
> minecraft  | io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
> 
> ```

You'll need to contact the modpack author about that. The docker image just exec's the respective modloader in the end, so it's hands off after the server is up and running. And...docker containers are just regular Linux processes ultimately. (Giving info in case the author blames docker)

**Comment by Katze719** [comment]
> got it working by manually mounting the mod

closing this issue
