### ISSUE TITLE
Cant connect to Server ATM10

### ISSUE THREAD

**Issue by Schmukas** [itzg/docker-minecraft-server#3090]
### Describe the problem

Server appears to be online but u cant connect to it

### Container definition

docker container setup using portainer

### Container logs
[12:30:49] [Worker-Main-6/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 51%
[12:30:49] [Worker-Main-7/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 51%
[12:30:50] [Worker-Main-6/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 51%
[12:30:50] [Worker-Main-7/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 53%
[12:30:51] [Server thread/INFO] [minecraft/LoggerChunkProgressListener]: Time elapsed: 20889 ms
[12:30:51] [Server thread/INFO] [minecraft/DedicatedServer]: Done (41.514s)! For help, type "help"
[12:30:51] [Server thread/INFO] [minecraft/DedicatedServer]: Starting remote control listener
[12:30:51] [Server thread/INFO] [minecraft/GenericThread]: Thread RCON Listener started
[12:30:51] [Server thread/INFO] [minecraft/RconThread]: RCON running on 0.0.0.0:25575
[12:30:51] [LanServerPinger #1/WARN] [minecraft/LanServerPinger]: LanServerPinger: Network is unreachable
[12:30:51] [Server thread/INFO] [ne.ne.ne.se.pe.PermissionAPI/]: Successfully initialized permission handler neoforge:default_handler
[12:30:51] [Server thread/INFO] [journeymap/]: Loaded null for service interface journeymap.api.services.WebMapService
[12:30:51] [Server thread/INFO] [journeymap/]: Loaded journeymap.common.helpers.NeoForgeClientHooks@20a662a for service interface journeymap.api.services.ClientPlatformService
[12:30:51] [Server thread/INFO] [journeymap/]: Loaded journeymap.common.helpers.NeoForgeHooks@2202c36d for service interface journeymap.api.services.CommonPlatformService
[12:30:51] [Server thread/INFO] [journeymap/]: global (FirstLoaded) Setting config file to version "6.0.0-beta.27": journeymap.server.global.config
[12:30:51] [Server thread/INFO] [journeymap/]: global (Valid) Creating config file: journeymap/server/6.0/journeymap.server.global.config
[12:30:51] [Server thread/INFO] [journeymap/]: default (FirstLoaded) Setting config file to version "6.0.0-beta.27": journeymap.server.default.config
[12:30:51] [Server thread/INFO] [journeymap/]: default (Valid) Creating config file: journeymap/server/6.0/journeymap.server.default.config
[12:30:51] [Server thread/INFO] [journeymap/]: minecraft~overworld (Valid) Creating config file: journeymap/server/6.0/journeymap.server.minecraft~overworld.config
[12:30:51] [Server thread/INFO] [journeymap/]: undergarden~undergarden (Valid) Creating config file: journeymap/server/6.0/journeymap.server.undergarden~undergarden.config
[12:30:51] [Server thread/INFO] [journeymap/]: allthemodium~the_beyond (Valid) Creating config file: journeymap/server/6.0/journeymap.server.allthemodium~the_beyond.config
[12:30:51] [Server thread/INFO] [journeymap/]: minecraft~the_end (Valid) Creating config file: journeymap/server/6.0/journeymap.server.minecraft~the_end.config
[12:30:51] [Server thread/INFO] [journeymap/]: allthemodium~the_other (Valid) Creating config file: journeymap/server/6.0/journeymap.server.allthemodium~the_other.config
[12:30:51] [Server thread/INFO] [journeymap/]: minecraft~the_nether (Valid) Creating config file: journeymap/server/6.0/journeymap.server.minecraft~the_nether.config
[12:30:51] [Server thread/INFO] [journeymap/]: allthemodium~mining (Valid) Creating config file: journeymap/server/6.0/journeymap.server.allthemodium~mining.config
[12:30:51] [Server thread/INFO] [journeymap/]: mahoutsukai~reality_marble (Valid) Creating config file: journeymap/server/6.0/journeymap.server.mahoutsukai~reality_marble.config
[12:30:51] [Server thread/INFO] [journeymap/]: deeperdarker~otherside (Valid) Creating config file: journeymap/server/6.0/journeymap.server.deeperdarker~otherside.config
[12:30:51] [Server thread/INFO] [journeymap/]: the_bumblezone~the_bumblezone (Valid) Creating config file: journeymap/server/6.0/journeymap.server.the_bumblezone~the_bumblezone.config
[12:30:51] [Server thread/INFO] [journeymap/]: eternal_starlight~starlight (Valid) Creating config file: journeymap/server/6.0/journeymap.server.eternal_starlight~starlight.config
[12:30:51] [Server thread/INFO] [journeymap/]: ae2~spatial_storage (Valid) Creating config file: journeymap/server/6.0/journeymap.server.ae2~spatial_storage.config
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.InscriberTestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.ItemP2PTestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.SubnetPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.QnbTestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.InterfaceTestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.MemoryCardTestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.InvalidPatternTestPlot for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.GuidebookPlot for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.AnnihilationPlaneTests for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.TestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.SpatialTestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.SpawnExtraGridTestTools for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.CrystalResonanceGeneratorTestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.P2PTestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.ExternalEnergyTestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.PatternProviderPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.PatternProviderLockModePlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class appeng.server.testplots.AutoCraftingTestPlots for plots
[12:30:51] [Server thread/INFO] [AE2:S/]: Scanning class de.mari_023.ae2wtlib.AE2wtlibTestPlots for plots
[12:30:51] [Server thread/INFO] [Observable/]: Registered thread Server thread
[12:30:51] [Server thread/INFO] [FTB Quests/]: Loading quests from /data/config/ftbquests/quests
[12:30:51] [Server thread/INFO] [FTB Quests/]: loaded translation tables for 6 language(s)
[12:30:51] [Server thread/INFO] [FTB Quests/]: Loaded 9 chapter groups, 34 chapters, 2218 quests, 36 reward tables
[12:30:51] [Server thread/INFO] [FTB Ranks/]: Loaded 3 ranks
[12:30:51] [Server thread/INFO] [evilcraft/]: Loading infobook /data/evilcraft/info/book.xml
[12:30:51] [Server thread/WARN] [evilcraft/]: Invalid appendix info_book.evilcraft.second_age.tools.broom from mod evilcraft in an infobook: The broom modifier evilcraft:witherer has no valid items
[12:30:51] [Server thread/WARN] [evilcraft/]: Invalid appendix info_book.evilcraft.second_age.tools.broom from mod evilcraft in an infobook: The broom modifier evilcraft:hungerer has no valid items
[12:30:51] [Server thread/WARN] [evilcraft/]: Invalid appendix info_book.evilcraft.second_age.tools.broom from mod evilcraft in an infobook: The broom modifier evilcraft:kamikaze has no valid items
[12:30:51] [Server thread/WARN] [evilcraft/]: Invalid appendix info_book.evilcraft.second_age.tools.broom from mod evilcraft in an infobook: The broom modifier evilcraft:withershield has no valid items
[12:30:54] [Server thread/INFO] [cyclopscore/]: Loading infobook /data/cyclopscore/info/test.xml
[12:30:54] [Server thread/INFO] [integrateddynamics/]: Loading infobook /data/integrateddynamics/info/on_the_dynamics_of_integration.xml
[12:30:55] [Server thread/INFO] [ne.ne.co.Co.apothic_enchanting/COREMODLOG]: Replaced 1 calls to Enchantment#getMaxLevel() in net/minecraft/world/item/enchantment/EnchantmentHelper
[12:30:57] [Server thread/WARN] [zerocore/service_loader]: Invalid service definition for it.zerono.mods.zerocore.lib.compat.patchouli.IPatchouliService. Using fallback implementation.
[12:30:59] [Server thread/INFO] [patchouli/]: Sending reload packet to clients
[12:30:59] [Server thread/WARN] [ModernFix/]: Dedicated server took 133.444 seconds to load
[12:30:59] [Server thread/WARN] [minecolonies/]: Starting Compat Discovery
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering Ores 227 166
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering saplings 300
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering plantables 19
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering food 636 717
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering fuel 7000
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering flowers 174
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering items 33472
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering lucky oreBlocks 6
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering recruitment costs
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering diseases
[12:31:00] [Server thread/INFO] [minecolonies/]: Finished discovering compostables 2113
[12:31:00] [Server thread/ERROR] [minecolonies/]: Couldnt analyze animal
java.lang.IllegalArgumentException: Duplicate id value for 17!
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.syncher.SynchedEntityData$Builder.define(SynchedEntityData.java:155) ~[server-1.21.1-20240808.144430-srg.jar%23401!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/ars_elemental@1.21.0-0.7.0.5/alexthw.ars_elemental.common.entity.familiars.FirenandoFamiliar.defineSynchedData(FirenandoFamiliar.java:100) ~[ars_elemental-1.21.0-0.7.0.5.jar%23432!/:1.21.0-0.7.0.5] {re:classloading}


**Comment by itzg** [comment]
From the logs, it looks like it's still starting up. Modpacks greatly increase the time before the server can accept connections. 

Otherwise, you need to provide your actual container config; environment variables, port mappings, any manual changes to server.properties, etc

**Comment by Schmukas** [comment]
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
JAVA_HOME=/opt/java/openjdk
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
JAVA_VERSION=jdk-21.0.4+7
TYPE=AUTO_CURSEFORGE
VERSION=1.21.1
EULA=true
UID=1000
GID=1000
CF_API_KEY=$2a$10$jEPucatNjxVXkKsGMGTVF.W6mdreEkllKwo9NKQUjAIUpmN0D111q
CF_SLUG=all-the-mods-10
MEMORY=42G
DIFFICULTY=normal
VIEW_DISTANCE=14
SPAWN_PROTECTION=0
ONLINE_MODE=false
LEVEL_TYPE=amplified
SERVER_NAME=uh
SERVER_PORT=22506
CF_FORCE_REINSTALL_MODLOADER=false
FETCH_TLS_HANDSHAKE_TIMEOUT=PT20S
CF_EXCLUDE_MODS=986380, 520110, 394468, 447673

other than this i didnt change anything

**Comment by Schmukas** [comment]
im just stupid i forgot to do the port mapping

**Comment by rhullah** [comment]
You should now reset your Curseforge API key since you exposed it here.
