### ISSUE TITLE
Vanilla 1.14 | UnrecognizedOptionException noconsole

### ISSUE THREAD

**Issue by Wiamor** [itzg/docker-minecraft-server#319]
Hey,
I wanted to upgrade a server from 1.13.2 to 1.14 and starting n a new map, using docker-compose.
So i went into the server Properties and changed the level name, pulled the new docker and did a `docker-compose restart` 

now i get the following error when starting the server:

`Checking version information.
Checking type information.
Downloading minecraft_server.1.14.jar ...
DEBUG: Finding version manifest for 1.14
DEBUG: Found version manifest at https://launchermeta.mojang.com/v1/packages/3aa13ae273eb9f05c2b1fcee1aff6c9254492941/1.14.json
DEBUG: Downloading server from https://launcher.mojang.com/v1/objects/f1a0073671057f01aa843443fef34330281333ce/server.jar
`
...
So Downlaoding 1.14 worked
Then the start of the new server begins
...
`server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 8G
[07:33:55] [main/FATAL]: Failed to start the minecraft server
joptsimple.UnrecognizedOptionException: noconsole is not a recognized option
at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[minecraft_server.1.14.jar:?]
at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510) ~[minecraft_server.1.14.jar:?]
at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56) ~[minecraft_server.1.14.jar:?]
at joptsimple.OptionParser.parse(OptionParser.java:396) ~[minecraft_server.1.14.jar:?]
at net.minecraft.server.MinecraftServer.main(SourceFile:879) [minecraft_server.1.14.jar:?]
2019/05/11 07:33:56 Done
`

i have already tryed removing the console option from the composer file or setting it to true, but neither seamed to have worked.

Any further ideas?

Thx for your time

**Comment by Wiamor** [comment]
I found a solution myself.

Removing the containers and restarting then helped apparently.
so:
`docker-compose stop`
`docker-compose rm`
`docker-compose up`

**Comment by itzg** [comment]
Glad you resolved it, but strange that was the solution.

**Comment by lorenzschmid** [comment]
Having `minecraft_server.1.14.1.jar` but other than that I get exact the same error message. Docker container constantely tries to restart. Removing the container and recreating it as you suggested didn't help.

**Comment by Wiamor** [comment]
I also got a very simmular error, when having a older docker Image, have you tryied pulling a fresh one, if you havent just started with the newest Version?

**Comment by lorenzschmid** [comment]
> I also got a very simmular error, when having a older docker Image, have you tryied pulling a fresh one, if you havent just started with the newest Version?

I just started and should use the latest image

**Comment by itzg** [comment]
@lorenzschmid I believe what @Wiamor meant was to do a `docker pull itzg/minecraft-server` to double check you're running the latest image.

**Comment by lorenzschmid** [comment]
Thanks for answering. I just tried a new pull but everything is up-to-date.

**Comment by itzg** [comment]
@lorenzschmid can you post some more details about how you’re launching the se

**Comment by lorenzschmid** [comment]
I used more or less the example given for docker compose combined with your `itzg/rcon`:

```yaml
version: '3'
services:

  ...

  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
      UID: 1031
      GID: 100
      EULA: "TRUE"
      CONSOLE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "password"
      RCON_PORT: 28016
      SERVER_NAME: minecraft-server
    ports:
     - "25565:25565"
    volumes:
      - "/volume1/minecraft/data/:/data/"
    restart: unless-stopped

  minecraft-rcon:
    image: itzg/rcon
    container_name: minecraft-rcon
    ports:
     - "8701:4326"
     - "8702:4327"
    volumes:
      - "/volume1/minecraft/rcon/:/opt/rcon-web-admin/db"
    depends_on:
      - minecraft
    restart: unless-stopped

**Comment by lorenzschmid** [comment]
And concerning my docker logs the might be handy as well:

```
Running as uid=1031 gid=100 with /data as 'drwxrwxr-x    1 1031     100            146 May 26 16:33 /data'
Checking version information.
Checking type information.
server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
[16:35:47] [main/FATAL]: Failed to start the minecraft server
joptsimple.UnrecognizedOptionException: noconsole is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParser.parse(OptionParser.java:396) ~[minecraft_server.1.14.1.jar:?]
	at net.minecraft.server.MinecraftServer.main(SourceFile:879) [minecraft_server.1.14.1.jar:?]
2019/05/26 16:35:47 Done
usermod: no changes
Running as uid=1031 gid=100 with /data as 'drwxrwxr-x    1 1031     100            146 May 26 16:35 /data'
Checking version information.
Checking type information.
server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
[16:36:35] [main/FATAL]: Failed to start the minecraft server
joptsimple.UnrecognizedOptionException: noconsole is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParser.parse(OptionParser.java:396) ~[minecraft_server.1.14.1.jar:?]
	at net.minecraft.server.MinecraftServer.main(SourceFile:879) [minecraft_server.1.14.1.jar:?]
2019/05/26 16:36:35 Done
```

**Comment by itzg** [comment]
@lorenzschmid yeah, you're compose looks fine. If you could `docker pull itzg/minecraft-server` I have just added an env option `DEBUG_EXEC` to debug the java invocation. After pulling you can add this to your `environment`:

```
   DEBUG_EXEC: "true"
```

**Comment by lorenzschmid** [comment]
Thanks a lot for your help, @itzg . Just pulled the new image and added the environment variable. here you go with the new logs:

```
Running as uid=1031 gid=100 with /data as 'drwxrwxr-x    1 1031     100            146 May 26 16:39 /data'
Checking version information.
Checking type information.
server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
+ exec mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms1G -Xmx1G -jar minecraft_server.1.14.1.jar --noconsole
[17:11:41] [main/FATAL]: Failed to start the minecraft server
joptsimple.UnrecognizedOptionException: noconsole is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParser.parse(OptionParser.java:396) ~[minecraft_server.1.14.1.jar:?]
	at net.minecraft.server.MinecraftServer.main(SourceFile:879) [minecraft_server.1.14.1.jar:?]
2019/05/26 17:11:41 Done
usermod: no changes
Running as uid=1031 gid=100 with /data as 'drwxrwxr-x    1 1031     100            146 May 26 17:11 /data'
Checking version information.
Checking type information.
server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
+ exec mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms1G -Xmx1G -jar minecraft_server.1.14.1.jar --noconsole
[17:11:53] [main/FATAL]: Failed to start the minecraft server
joptsimple.UnrecognizedOptionException: noconsole is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56) ~[minecraft_server.1.14.1.jar:?]
	at joptsimple.OptionParser.parse(OptionParser.java:396) ~[minecraft_server.1.14.1.jar:?]
	at net.minecraft.server.MinecraftServer.main(SourceFile:879) [minecraft_server.1.14.1.jar:?]
2019/05/26 17:11:53 Done
```

**Comment by itzg** [comment]
Aha @lorenzschmid , it took seeing the debug output to realize that normally I don't use the `CONSOLE=false` option, which is why I didn't run into this.

Apparently this is an issue in the upstream server itself as of 1.14

https://bugs.mojang.com/browse/MC-151445

Easy solution for now is to remove the
```
   CONSOLE: "false"
```

**Comment by lorenzschmid** [comment]
That did the trick indeed! Thank you very much!
