### ISSUE TITLE
Please make sure you are using the server version of the FTB modpack!

### ISSUE THREAD

**Issue by Frenzoid** [itzg/docker-minecraft-server#358]
Hello!

I've searched on issues, and i've seen that some people had this issue before but they were fixed.

This is my launch: http://prntscr.com/ol5nxp
(I also tried via portainer, but i get the same output "Please make sure you are using the server version of the FTB modpack!").

I've tried the next combinations:
for FORGEVERSION
- not placing anything.
- FORGEVERSION=10.13.4.1558 (as shown on the dockerhub info).
- FORGEVERSION=1.7.10 (as shown on the package's manifest).

for VERSION
- not placing anything.
- VERSION=1.14.3 (Current version of a server which is running the modpack).
- VERSION=1.7.10 (as shown on the package's manifest).
- VERSION=1.14.4
- VERSION=LATEST

And i still get this error, i dont know if i did something wrong or theres something missing, or if it could be because the name of the file has a "+" on it.

For now i'll try and run just a TYPE=FORGE server, using FORGEVERSION=10.13.4.1558 and VERSION=1.7.10, and manually install the modpack.

Any help would be greatly appreciated!

**Comment by itzg** [comment]
It looks like only 1.2.5 of that modpack provides a server pack :(

![image](https://user-images.githubusercontent.com/988985/62011979-95776380-b145-11e9-87d2-057165a96d31.png)

So, a `CF_SERVER_MOD=https://www.curseforge.com/minecraft/modpacks/voltz-community-modpack/files/2729127` should work...but would be a slightly older version of modpack.

**Comment by Frenzoid** [comment]
Ooo thanks!
So it was my fault, hehe sorry.

btw, i've tried to install it now, and after a bit it crashes:
https://pastebin.com/WtBBryPq


and the logs:
```[20:28:28] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.

[20:28:28] [Server thread/INFO] [FML]: Applying holder lookups

[20:28:28] [Server thread/INFO] [FML]: Holder lookups applied

[20:28:28] [Server thread/ERROR] [ae2stuff]: Skipping event FMLServerStoppedEvent and marking errored mod ae2stuff since required dependency appliedenergistics2 has errored

[20:28:28] [Server thread/ERROR] [extracells]: Skipping event FMLServerStoppedEvent and marking errored mod extracells since required dependency appliedenergistics2 has errored

[20:28:28] [Server thread/ERROR] [ae2wct]: Skipping event FMLServerStoppedEvent and marking errored mod ae2wct since required dependency appliedenergistics2 has errored

[20:28:28] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.

[20:28:28] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

2019/07/28 20:28:29 Done
```

That crash must be because of the modpack, right? or did i did something wrong again at launching?
Ive changed the forgeversion to recommended, because it didn't work with .

Sorry to bother you with this, and thanks a lot of the tip! (that it must be the server pkg) it seems i got some instructions wrong hehe.

**Comment by Frenzoid** [comment]
I tried another modpack and i still get the same errors:
https://pastebin.com/S6ahN9SH

I know it doesnt have to do with this issue, but do you have any idea what could it be?

Best regards!

**Comment by itzg** [comment]
Mod packs tend to be resource intensive so it might not be something you’re doing. I’ll try them out too.

**Comment by itzg** [comment]
What was the second modpack you tried? That error about the GUI class is odd.

**Comment by itzg** [comment]
Back to the voltz pack, I don't think they built the server-side mod pack correctly since it seems to have a client-side mod bundle judging by the exception cause I got:

```
Caused by: java.lang.RuntimeException: Attempted to load class bdw for invalid side SERVER
        at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        at reauth.Main.preInit(Main.java:35) ~[Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) ~[Loader.class:?]
        ... 5 more
```

**Comment by Frenzoid** [comment]
Yeah, it was the modpack, and only that one, i checked that today again.

Thanks alot for the help, you are very polite! :D
