### ISSUE TITLE
1.14.4 does not seem to work as version

### ISSUE THREAD

**Issue by tjsd** [itzg/docker-minecraft-server#361]
Hello!
The docker image seems to not know about 1.14.4 version of minecraft, when I change VERSION=1.14.4 and TYPE=FABRIC
it doesnt work at all, but it does work with 1.14.3

**Comment by vorburger** [comment]
This is probably specific to `TYPE=FABRIC` as a regular (vanilla) `VERSION=1.14.4` works just fine for me.

**Comment by itzg** [comment]
@tjsd can you double you have pulled the latest image? It starts fine for me, as shown here:

```
> docker run -it --rm -e EULA=TRUE -e TYPE=PAPER -e VERSION=1.14.4 itzg/minecraft-server
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Aug  3 00:16 /data'
Checking version information.
Checking type information.
Downloading Paper 1.14.4 from https://papermc.io/api/v1/paper/1.14.4/latest/download ...
Creating server.properties in /data/server.properties
Setting server-name to 'Dedicated Server' in /data/server.properties
Setting server-port to '25565' in /data/server.properties
Setting motd to 'A Paper Minecraft Server powered by Docker' in /data/server.properties
Skip setting allow-nether
Skip setting announce-player-achievements
Skip setting enable-command-block
Skip setting spawn-animals
Skip setting spawn-monsters
Skip setting spawn-npcs
Skip setting generate-structures
Skip setting view-distance
Skip setting hardcore
Skip setting snooper-enabled
Skip setting max-build-height
Skip setting force-gamemode
Skip setting max-tick-time
Skip setting enable-query
Skip setting query.port
Setting enable-rcon to 'true' in /data/server.properties
Setting rcon.password to 'minecraft' in /data/server.properties
Setting rcon.port to '25575' in /data/server.properties
Skip setting max-players
Skip setting max-world-size
Setting level-name to 'world' in /data/server.properties
Skip setting level-seed
Setting pvp to 'true' in /data/server.properties
Skip setting generator-settings
Setting online-mode to 'true' in /data/server.properties
Skip setting allow-flight
Setting level-type to 'DEFAULT' in /data/server.properties
Setting difficulty to '1' in /data/server.properties
Checking for JSON files.
Copying any mods over...
Copying any Bukkit plugins over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
Downloading original jar...
Patching original jar...
System Info: Java 1.8 (OpenJDK 64-Bit Server VM 25.212-b04) Host:  Linux 4.9.125-linuxkit (amd64)
Loading libraries, please wait...
2019-08-03 00:16:58,696 main WARN Advanced terminal features are not available in this environment
[00:17:08 INFO]: Starting minecraft server version 1.14.4
[00:17:08 INFO]: Loading properties
[00:17:09 INFO]: This server is running Paper version git-Paper-156 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
.
.
.
```

**Comment by tgkenney** [comment]
I might be having the same issue.  I use a docker-compose file, and I have added VERSION: 1.14.4 while using TYPE: PAPER and the server still starts using 1.14.3 according to the logs
`[15:37:07 INFO]: Starting minecraft server version 1.14.3`

**Comment by itzg** [comment]
@tjsd sorry, I had tested your issue with the wrong `TYPE` initially. I just re-tested correctly with `TYPE=FABRIC` and it is able to install and run 1.14.4. I wonder if their installer and/or metadata needed to be updated. Below is where I tested this out. Can you see if this issue still exists for you?

```
ver> docker run -it --rm -e EULA=TRUE -e TYPE=FABRIC -e VERSION=1.14.4 itzg/minecraft-server
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Aug 10 22:13 /data'
Checking version information.
Checking type information.
Checking Fabric version information.
Downloading 0.5.0.33
...trying https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.5.0.33/fabric-installer-0.5.0.33.jar
Installing Fabric 0.5.0.33 using /tmp/fabric-installer-0.5.0.33.jar
Loading Fabric Installer: 0.5.0.33
Using latest loader version
Installing Fabric Loader 0.4.8+build.159(1.14.4) on the server
Downloading required files
Downloading library net.fabricmc:tiny-mappings-parser:0.1.1.8
Downloading library net.fabricmc:sponge-mixin:0.7.11.38
Downloading library net.fabricmc:tiny-remapper:0.1.0.33
Downloading library net.fabricmc:fabric-loader-sat4j:2.3.5.4
Downloading library com.google.jimfs:jimfs:1.1
Downloading library org.ow2.asm:asm:7.1
Downloading library org.ow2.asm:asm-analysis:7.1
Downloading library org.ow2.asm:asm-commons:7.1
Downloading library org.ow2.asm:asm-tree:7.1
Downloading library org.ow2.asm:asm-util:7.1
Downloading library com.google.guava:guava:21.0
Downloading library net.fabricmc:fabric-loader:0.4.8+build.159
Downloading library net.fabricmc:intermediary:1.14.4
Generating server launch JAR
Generating server launch JAR: tiny-mappings-parser-0.1.1.8.jar
Generating server launch JAR: sponge-mixin-0.7.11.38.jar
Generating server launch JAR: tiny-remapper-0.1.0.33.jar
Generating server launch JAR: fabric-loader-sat4j-2.3.5.4.jar
Generating server launch JAR: jimfs-1.1.jar
Generating server launch JAR: asm-7.1.jar
Generating server launch JAR: asm-analysis-7.1.jar
Generating server launch JAR: asm-commons-7.1.jar
Generating server launch JAR: asm-tree-7.1.jar
Generating server launch JAR: asm-util-7.1.jar
Generating server launch JAR: guava-21.0.jar
Generating server launch JAR: fabric-loader-0.4.8+build.159.jar
Generating server launch JAR: intermediary-1.14.4.jar
Done, start server by running fabric-server-launch.jar
Downloading Minecraft server
Done
Using server fabric-server-launch.jar
Creating server.properties in /data/server.properties
Setting server-name to 'Dedicated Server' in /data/server.properties
Setting server-port to '25565' in /data/server.properties
Setting motd to 'A Fabric Minecraft Server powered by Docker' in /data/server.properties
Skip setting allow-nether
Skip setting announce-player-achievements
Skip setting enable-command-block
Skip setting spawn-animals
Skip setting spawn-monsters
Skip setting spawn-npcs
Skip setting generate-structures
Skip setting view-distance
Skip setting hardcore
Skip setting snooper-enabled
Skip setting max-build-height
Skip setting force-gamemode
Skip setting max-tick-time
Skip setting enable-query
Skip setting query.port
Setting enable-rcon to 'true' in /data/server.properties
Setting rcon.password to 'minecraft' in /data/server.properties
Setting rcon.port to '25575' in /data/server.properties
Skip setting max-players
Skip setting max-world-size
Setting level-name to 'world' in /data/server.properties
Skip setting level-seed
Setting pvp to 'true' in /data/server.properties
Skip setting generator-settings
Setting online-mode to 'true' in /data/server.properties
Skip setting allow-flight
Setting level-type to 'DEFAULT' in /data/server.properties
Setting difficulty to '1' in /data/server.properties
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
[22:13:22] [main/INFO]: Loading for game Minecraft 1.14.4
.
.
.
```

**Comment by itzg** [comment]
@tjsd @falkowich , I discovered the startup logic for Fabric wasn't handling upgrade scenarios properly. Can you pull the latest image (`sha256:1cf5cc10de2cc1a61ea7ad9069f4b7734970572aae7db9540a6404ecdf9d0f03`) and confirm that fixes the use of `VERSION=1.14.4`?

**Comment by falkowich** [comment]
Hi,
I removed old stuff and did this:

```
mc@minecraft:~$ docker pull itzg/minecraft-server@sha256:1cf5cc10de2cc1a61ea7ad9069f4b7734970572aae7db9540a6404ecdf9d0f03
sha256:1cf5cc10de2cc1a61ea7ad9069f4b7734970572aae7db9540a6404ecdf9d0f03: Pulling from itzg/minecraft-server
--8x--
Digest: sha256:1cf5cc10de2cc1a61ea7ad9069f4b7734970572aae7db9540a6404ecdf9d0f03
Status: Downloaded newer image for itzg/minecraft-server@sha256:1cf5cc10de2cc1a61ea7ad9069f4b7734970572aae7db9540a6404ecdf9d0f03
docker.io/itzg/minecraft-server@sha256:1cf5cc10de2cc1a61ea7ad9069f4b7734970572aae7db9540a6404ecdf9d0f03
```
And this is my docker-compose.yml:
```
version: '3'
services:
  minecraft-server:
    ports:
      - "25565:25565"
      - "8123:8123"
      - "8804:8804"
    environment:
      EULA: "TRUE"
      VERSION: "1.14.4"
      TYPE: "PAPER"
      UID: "1001"
      GID: "1001"
    image: itzg/minecraft-server:latest
    container_name: mc
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - /home/mc/data:/data
```
But for me it still starts up 1.14.3, perhaps I am doing something wrong with the compose file?

```  
Loading libraries, please wait...
mc                  | 2019-09-15 11:15:49,486 main WARN Disabling terminal, you're running in an unsupported environment.
mc                  | [11:15:55 INFO]: Starting minecraft server version 1.14.3
mc                  | [11:15:55 INFO]: Loading properties
mc                  | [11:15:56 INFO]: This server is running Paper version git-Paper-132 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
.......
```

--
Regards Falk

**Comment by itzg** [comment]
@falkowich , can you do me a favor and pull again the latest image and add a

```
  DEBUG: "TRUE"
```

to your compose `environment`. With that can you provide the logs near the beginning that should look like:

```
Checking Fabric version information.
DEBUG: Checking for installMarker .fabric-installed-1.14.4-0.5.0.35
Downloading 0.5.0.35
...trying https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.5.0.35/fabric-installer-0.5.0.35.jar
DEBUG: Installing Fabric 0.5.0.35 using /tmp/fabric-installer-0.5.0.35.jar with mcversion 1.14.4
Loading Fabric Installer: 0.5.0.35
Using latest loader version
Installing Fabric Loader 0.6.1+build.165(1.14.4) on the server
```

**Comment by falkowich** [comment]
Hi, 
I don't know if we hijacked the bug.
I use Paper as in TYPE: "PAPER".

And when I enable debug in my settings with latest image nothing debugs?
Is it beq I run Paper?
--
Regards Falk

**Comment by itzg** [comment]
Ha, yes, I’m getting the types mixed up too. Yes, the debug was only added for Fabric, but I’ll look at Paper since it might have the same upgrade issue.

**Comment by itzg** [comment]
@falkowich , yep, Paper setup had a similar issue where upgrades were not getting handled. I just pushed a new image (`sha256:986e2e7de5f34302f81a164f6eef1b57793f9c560724fac5fead16e5eb6110d4`), that should fix this.

**Comment by falkowich** [comment]
Hi,

Thanks for the hard work!
```
mc                  | [09:01:25 INFO]: Starting minecraft server version 1.14.4
mc                  | [09:01:25 INFO]: Loading properties
mc                  | [09:01:25 INFO]: This server is running Paper version git-Paper-192 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```
--
Regards Falk

**Comment by karlbright** [comment]
@itzg Are you able to confirm that running with FABRIC type set works correctly? I am unable to run with the same `docker run` command as you provided. I believe this is most likely a fabricloader issue and trying to look into it.

```
[03:10:46] [main/INFO]: [FabricLoader] Loading 2 mods: minecraft@1.14.4, fabricloader@0.7.0+build.171
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
	... 2 more
Caused by: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available. Services: INVALID[ModLauncher] and 2 other invalid services.
	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:159)
	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:125)
	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:120)
	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:78)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
	... 7 more
```

**Comment by itzg** [comment]
@karlbright strange our results differ, but pulling the latest image and then running with the following started up fine:

    docker run -it --rm -e EULA=TRUE -e TYPE=FABRIC itzg/minecraft-server

The initial logs look like:

```
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Nov 19 23:28 /data'
Checking version information.
Checking type information.
Checking Fabric version information.
Downloading 0.5.1.37
...trying https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.5.1.37/fabric-installer-0.5.1.37.jar
Installing Fabric 0.5.1.37 using /tmp/fabric-installer-0.5.1.37.jar
Loading Fabric Installer: 0.5.1.37
Using latest loader version
Installing Fabric Loader 0.7.0+build.171(1.14.4) on the server
Downloading required files
```

and the logs from what I think is the same point in the startup are:
```
[23:29:22] [main/INFO]: [FabricLoader] Loading 2 mods: minecraft@1.14.4, fabricloader@0.7.0+build.171
[23:29:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/data/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[23:29:37] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:29:37] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:29:37] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:29:37] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:29:37] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[23:29:37] [Server thread/INFO]: Starting minecraft server version 1.14.4
```

**Comment by karlbright** [comment]
@itzg Can confirm that this was an issue with one of the newest builds of fabric-loader and was fixed with https://github.com/FabricMC/fabric-loader/issues/171

Working as expected now as using fabric installer 0.5.1.37.

**Comment by itzg** [comment]
Thanks for the followup and all the details.
