### ISSUE TITLE
"false" spam in docker log possibly due to healthcheck

### ISSUE THREAD

**Issue by iamtpage** [itzg/docker-minecraft-server#373]
Hi again,

```
  minecraft-server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    volumes:
      - /opt/docker-local/minecraft-server:/data
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: "https://www.curseforge.com/minecraft/modpacks/dmt-survival/download/2754796"
      MANIFEST: "/data/FeedTheBeast/manifest.json"
      VERSION: "1.12.2"
      ENABLE_QUERY: "true"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"
      SNOOPER_ENABLED: "false"
      MAX_BUILD_HEIGHT: "512"
      GENERATE_STRUCTURES: "true"
      ENABLE_RCON: "false"
      REMOVE_OLD_MODS: "true"
    restart: "always"
```

Successfully downloads the mods specified and boots up the server, however in the docker logs for the container I see a lot of:
```
false
false
false
false
false
false
false
false
false
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreRedstone : Nether Redstone Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherRedstone : Nether Redstone Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreIron : Nether Iron Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherIron : Nether Iron Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreGold : Nether Gold Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherGold : Nether Gold Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreCoal : Nether Coal Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherCoal : Nether Coal Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreLapis : Nether Lapis Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherLapis : Nether Lapis Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEmerald : Nether Emerald Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherEmerald : Nether Emerald Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreDiamond : Nether Diamond Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherDiamond : Nether Diamond Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreRedstone : End Redstone Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndRedstone : End Redstone Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreCoal : End Coal Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndCoal : End Coal Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreLapis : End Lapis Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndLapis : End Lapis Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEmerald : End Emerald Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndEmerald : End Emerald Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreDiamond : End Diamond Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndDiamond : End Diamond Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreGold : End Gold Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndGold : End Gold Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreIron : End Iron Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndIron : End Iron Ore
false
false
false
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry workbench : Block{cyclicmagic:block_workbench}
false
false
false
false
false
false
false
false
[19:55:49] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `furnace`, expected `fastfurnace`. This could be a intended override, but in most cases indicates a broken mod.
```

This continues on until the server finishes starting up. Taking a look at the `latest.log` within the container yields no `false` spam:

```
[19:55:48] [Server thread/INFO] [grimoireofgaia]: Item registration complete.
[19:55:48] [Server thread/INFO] [Netherending Ores]: Registered ItemBlocks
[19:55:48] [Server thread/INFO] [Netherending Ores]: Registered Ore Dictionary Entries
[19:55:48] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `shield`, expected `inspirations`. This could be a intended override, but in most cases indicates a broken mod.
[19:55:48] [Server thread/WARN] [FML]: ****************************************
[19:55:48] [Server thread/WARN] [FML]: * Registry Item: The object net.theexceptionist.coherentvillages.main.items.ItemModShield@2349fefb has been registered twice for the same name coherentvillages:nord_shield_0.
[19:55:48] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:300)
[19:55:48] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
[19:55:48] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
[19:55:48] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
[19:55:48] [Server thread/WARN] [FML]: *  at net.theexceptionist.coherentvillages.main.items.ModItems.registerItems(ModItems.java:129)
[19:55:48] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_517_ModItems_registerItems_Register.invoke(.dynamic)...
[19:55:48] [Server thread/WARN] [FML]: ****************************************
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreRedstone : Nether Redstone Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherRedstone : Nether Redstone Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreIron : Nether Iron Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherIron : Nether Iron Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreGold : Nether Gold Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherGold : Nether Gold Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreCoal : Nether Coal Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherCoal : Nether Coal Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreLapis : Nether Lapis Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherLapis : Nether Lapis Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEmerald : Nether Emerald Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherEmerald : Nether Emerald Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreDiamond : Nether Diamond Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreNetherDiamond : Nether Diamond Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreRedstone : End Redstone Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndRedstone : End Redstone Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreCoal : End Coal Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndCoal : End Coal Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreLapis : End Lapis Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndLapis : End Lapis Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEmerald : End Emerald Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndEmerald : End Emerald Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreDiamond : End Diamond Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndDiamond : End Diamond Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreGold : End Gold Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndGold : End Gold Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreIron : End Iron Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry oreEndIron : End Iron Ore
[19:55:49] [Server thread/INFO] [cyclicmagic]: Registered ore dict entry workbench : Block{cyclicmagic:block_workbench}
[19:55:49] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `furnace`, expected `fastfurnace`. This could be a intended override, but in most cases indicates a broken mod.
[19:55:49] [Server thread/INFO] [FML]: Applying holder lookups
[19:55:49] [Server thread/INFO] [FML]: Holder lookups applied
```

So it seems that something is spamming stdout in the docker container with `false`, a lot. My theory is it might be the healtcheck:

`HEALTHCHECK CMD mcstatus localhost:$SERVER_PORT ping`

Reasoning:
- `false` is a common return value for python functions
- By default, healthchecks start as soon as the container starts, so the server isn't ready, which means all healtchecks will fail (fail = false?)
- By default, healthchecks retry 3 times when they fail (could explain the spam)
- By default, healtchecks run every 30s (that + retries = spam)
- There is no instances of `false` spam in the server logs themselves, meaning it's not a minecraft mod doing this.
- The `false` spam disappears once the server is finished starting up

**Comment by itzg** [comment]
Your theory sounds right, but then I'm not sure why I've never seen that. I might play with a combination of the settings you show in your compose file, since I tend to leave things like `ENABLE_RCON` at the default value.

**Comment by iamtpage** [comment]
I've done some testing, and running the server within the docker container via `StartServer.sh` does not result in `false` spam. If you need any more testing/information from me let me know

**Comment by itzg** [comment]
I gave it a quick test, but didn't too far since the modpack URL wasn't cooperating for me:

```
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Aug  5 02:44 /data'
Checking version information.
Checking type information.
Looking for Feed-The-Beast / CurseForge server modpack.
Downloading FTB modpack...
  https://www.curseforge.com/minecraft/modpacks/dmt-survival/download/2754796/file -> /data/2754796.zip
Unpacking FTB server modpack /data/2754796.zip ...
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Please make sure you are using the server version of the FTB modpack!
```

In the mean time, can you try `ENABLE_RCON: "true"` just to eliminate that as a difference? Also, have you noticed this with vanilla servers and/or other modpacks?

**Comment by iamtpage** [comment]
```
  minecraft-server:
    image: hub.tpage.io/tyler/minecraft-server:latest
    ports:
      - 25565:25565
    volumes:
      - /opt/docker-local/minecraft-server:/data
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: "https://www.curseforge.com/minecraft/modpacks/dmt-survival/download/2754906"
      MANIFEST: "/data/FeedTheBeast/manifest.json"
      VERSION: "1.12.2"
      ENABLE_QUERY: "true"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"
      SNOOPER_ENABLED: "false"
      MAX_BUILD_HEIGHT: "512"
      GENERATE_STRUCTURES: "true"
      ENABLE_RCON: "true"
      REMOVE_OLD_MODS: "true"
    restart: "always"
```

Produces the same result, it seems like `ENABLE_RCON` doesn't impact the `false` spam

**Comment by itzg** [comment]
Maybe it's not the healthcheck since in this section

https://docs.docker.com/engine/reference/builder/#healthcheck

it says

> To help debug failing probes, any output text (UTF-8 encoded) that the command writes on stdout or stderr will be stored in the health status and can be queried with docker inspect.

**Comment by iamtpage** [comment]
Yeah, you're right. I just hunted it down and it was an annoying coremod library mod that was causing it. Lots of process of elimination later and I found it (`tenshilib` FYI), closing due to having nothing to do with the docker image

**Comment by itzg** [comment]
Aha, thanks for chasing that down.
