### ISSUE TITLE
FTB not starting

### ISSUE THREAD

**Issue by Gabb1995** [itzg/docker-minecraft-server#381]
> [19:18:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.Class.forName0(Native Method)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.Class.forName(Class.java:348)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement.<init>(LegacyJavaFixer.java:54)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer.<init>(LegacyJavaFixer.java:30)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.Class.newInstance(Class.java:442)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.reflect.Method.invoke(Method.java:498)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)

My compose file:
```
minecraft-server:
    ports:
       - "25565:25565"
    volumes:
      - '../mc:/data'
    environment:
       EULA: "TRUE"
       TYPE: "FTB"
       FTB_SERVER_MOD: "FTB_Academy-1.0.0.zip"
       SERVER_NAME: "T47 MC"
       FTB_LEGACYJAVAFIXER: "TRUE"
    image: itzg/minecraft-server
    container_name: mc
    tty: true
    stdin_open: true
    restart: unless-stopped
```

I have tried with different FTB mods, without FTB_LEGACYJAVAFIXER, none work.

**Comment by Gabb1995** [comment]
Full log:
<details>

> Starting server
> 2019-08-29 19:18:10,012 main WARN Disabling terminal, you're running in an unsupported environment.
> [19:18:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
> [19:18:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
> [19:18:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
> [19:18:10] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2838 for Minecraft 1.12.2 loading
> [19:18:10] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_212, running on Linux:amd64:4.15.0-1040-aws, installed at /usr/lib/jvm/java-1.8-openjdk/jre
> [19:18:10] [main/INFO] [FML]: Searching /data/FeedTheBeast/./mods for mods
> [19:18:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.10.20.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [19:18:11] [main/WARN] [FML]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [19:18:11] [main/INFO] [Astral Core]: [AstralCore] Initialized.
> [19:18:11] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
> [19:18:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.3.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [19:18:11] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [19:18:11] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
> [19:18:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.5-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [19:18:11] [main/WARN] [FML]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [19:18:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [19:18:11] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [19:18:11] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
> [19:18:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [19:18:11] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [19:18:11] [main/INFO] [FML]: Loading tweaker net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer from legacyjavafixer.jar
> [19:18:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-177.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [19:18:11] [main/WARN] [FML]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
> [19:18:11] [main/WARN] [FML]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [19:18:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [19:18:11] [main/WARN] [FML]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [19:18:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in SmoothFont-mc1.12.2-2.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [19:18:11] [main/WARN] [FML]: The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [19:18:11] [main/WARN] [FML]: The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
> [19:18:11] [main/WARN] [FML]: The coremod pl.asie.splashanimation.core.SplashAnimationCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [19:18:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in splashlogofix-1.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [19:18:11] [main/WARN] [FML]: The coremod me.modmuss50.splashlogofix.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [19:18:11] [main/WARN] [FML]: The coremod LoadingPlugin (me.modmuss50.splashlogofix.asm.LoadingPlugin) is not signed!
> [19:18:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in StructureUtils-1.1.0.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [19:18:11] [main/WARN] [FML]: The coremod StructureUtilsASM (me.modmuss50.structureutils.SLoadingCore) is not signed!
> [19:18:11] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.6+build50-universal.jar
> [19:18:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
> [19:18:11] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[19:18:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.Class.forName0(Native Method)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.Class.forName(Class.java:348)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement.<init>(LegacyJavaFixer.java:54)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer.<init>(LegacyJavaFixer.java:30)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.Class.newInstance(Class.java:442)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at java.lang.reflect.Method.invoke(Method.java:498)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement:<init>:61]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[19:18:11] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
at com.google.common.base.Throwables.propagate(Throwables.java:240) ~[minecraft_server.1.12.2.jar:?]
at net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement.<init>(LegacyJavaFixer.java:62) ~[legacyjavafixer.jar:?]
at net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer.<init>(LegacyJavaFixer.java:30) ~[legacyjavafixer.jar:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_212]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [FTBserver-1.12.2-14.23.5.2838-universal.jar:?]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [FTBserver-1.12.2-14.23.5.2838-universal.jar:?]
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
at net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement.<init>(LegacyJavaFixer.java:54) ~[legacyjavafixer.jar:?]
... 14 more
A problem occurred running the Server launcher.[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at java.lang.reflect.Method.invoke(Method.java:498)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Runtime.exit(Runtime.java:107)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.System.exit(System.java:971)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:18:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: ... 6 more
2019/08/29 19:18:11 Done

</details>

**Comment by Gabb1995** [comment]
Server zip used (tried direct with link as well):

https://www.feed-the-beast.com/projects/ftb-academy/files/2766338#additional-files

**Comment by Gabb1995** [comment]
Issue was with docker still using the FTB_LEGACY command when I removed it.

**Comment by itzg** [comment]
Cool, since I was about to post this compose snippet worked for me:

```
version: '3.4'

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment: 
      EULA: "TRUE"
      TYPE: "FTB"
      FTB_SERVER_MOD: https://www.feed-the-beast.com/projects/ftb-academy/files/2766343/download
```
