### ISSUE TITLE
FML was unable to install the security manager (HELP! PLEASE!)

### ISSUE THREAD

**Issue by SirTrixYT** [itzg/docker-minecraft-server#422]
Hello guys,
whenever I start the Server (FORGE 1.7.10) I get this issue. On Forge 1.15.1 is everything fine (when I clone it works with 1.15.1). I tried everything but it doesnt works. Thank you!

Starting the Minecraft server...
[14:17:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[14:17:20] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[14:17:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[14:17:20] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[14:17:20] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_212, running on Linux:amd64:4.19.79-1.ph3-esx, installed at /usr/lib/jvm/java-1.8-openjdk/jre
[14:17:20] [main/INFO] [FML]: Loading tweaker cpw.mods.fml.common.launcher.FMLTweaker from forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
[14:17:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:17:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:17:20] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: FML was unable to install the security manager. The game will not start
	at cpw.mods.fml.common.launcher.FMLTweaker.<init>(FMLTweaker.java:39) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_212]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
Caused by: java.lang.SecurityException: Cannot replace the FML security manager
	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at java.lang.System.setSecurityManager0(System.java:300) ~[?:1.8.0_212]
	at java.lang.System.setSecurityManager(System.java:291) ~[?:1.8.0_212]
	at cpw.mods.fml.common.launcher.FMLTweaker.<init>(FMLTweaker.java:35) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	... 13 more
A problem occurred running the Server launcher.[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:971)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:17:20] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 6 more
2020/01/08 14:17:20 Done
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    7 1000     1000          4096 Jan  8 14:30 /data'
Checking version information.
Checking type information.

**Comment by itzg** [comment]
You seem to be using a custom forge server jar, so I am unable to recreate the problem using:

```
docker run -it --rm -e EULA=TRUE -e TYPE=FORGE -e VERSION=1.7.10 itzg/minecraft-server
```
Output logs here https://gist.github.com/itzg/08c7c581a993021ba548f5687faa357f#file-gistfile1-txt

I am not able to identity any clues from the exception trace Forge throws there.

**Comment by SirTrixYT** [comment]
Here is a Video
https://youtu.be/LOPWM62PnTk

**Comment by itzg** [comment]
The video was a great way to provide more details. Thanks!

I still wasn't able to recreate using the same configs you shared there. The command-line I used was:

```
docker run -it --rm -e EULA=TRUE -e TYPE=FORGE -e VERSION=1.7.10 -e FORGEVERSION=10.13.4.1614 itzg/minecraft-server
```

What I did notice from the video is that you are probably picking up from an existing volume a previous copy of a server jar that has the issue. Looking at your volume configs:

![bac3404a](https://user-images.githubusercontent.com/988985/72211509-44102600-3492-11ea-88b9-a1d76c0fe9a0.png)

Can you make a couple of changes to test out:
1. Delete off the `/config` and `/mods` volume mappings. If left in place, they should point to volume names different from each of the others.
2. Use a fresh volume instead of `mcVolume - local` such as putting a new volume name there like `forge-1.7.10` to help d
