### ISSUE TITLE
NSS initialization failed

### ISSUE THREAD

**Issue by technik-dude** [itzg/docker-minecraft-server#532]
Hello.

I tried to set up the MC Server like in this video: https://www.youtube.com/watch?v=zegNYtCzC5E
The Server starts without error (Vanilla) or with some SSL error (Spigot) but it starts.
When i now try to connect in game "encryption" is shown and after that "connection timeout".
What did I forget or do wrong?
In the Docker log somethine like this is shown:

**[15:03:23] [User Authenticator #1/ERROR]: Caught previously unhandled exception :
java.lang.ExceptionInInitializerError: null**
	at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:188) ~[?:1.8.0_212]
	at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:152) ~[?:1.8.0_212]
	at sun.security.ssl.SSLSessionImpl.<clinit>(SSLSessionImpl.java:79) ~[?:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.init(SSLSocketImpl.java:598) ~[?:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:536) ~[?:1.8.0_212]
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:72) ~[?:1.8.0_212]
	at sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:405) ~[?:1.8.0_212]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:162) ~[?:1.8.0_212]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_212]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_212]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_212]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_212]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_212]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_212]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_212]
	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:130) ~[minecraft_server.1.15.2.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66) ~[minecraft_server.1.15.2.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.hasJoinedServer(YggdrasilMinecraftSessionService.java:100) ~[minecraft_server.1.15.2.jar:?]
	at xx$1.run(SourceFile:162) ~[minecraft_server.1.15.2.jar:?]

**Caused by: java.security.ProviderException: Could not initialize NSS**
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:223) ~[sunpkcs11.jar:1.8.0_212]
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103) ~[sunpkcs11.jar:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:224) ~[?:1.8.0_212]
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206) ~[?:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206) ~[?:1.8.0_212]
	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187) ~[?:1.8.0_212]
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:233) ~[?:1.8.0_212]
	at sun.security.jca.ProviderList.getIndex(ProviderList.java:263) ~[?:1.8.0_212]
	at sun.security.jca.ProviderList.getProviderConfig(ProviderList.java:247) ~[?:1.8.0_212]
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:253) ~[?:1.8.0_212]
	at java.security.Security.getProvider(Security.java:503) ~[?:1.8.0_212]
	at sun.security.ssl.SignatureAndHashAlgorithm.<clinit>(SignatureAndHashAlgorithm.java:415) ~[?:1.8.0_212]
	
	
**Caused by: java.io.IOException: NSS initialization failed**
	at sun.security.pkcs11.Secmod.initialize(Secmod.java:234) ~[sunpkcs11.jar:1.8.0_212]
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:218) ~[sunpkcs11.jar:1.8.0_212]
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103) ~[sunpkcs11.jar:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:224) ~[?:1.8.0_212]
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206) ~[?:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206) ~[?:1.8.0_212]
	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187) ~[?:1.8.0_212]
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:233) ~[?:1.8.0_212]
	at sun.security.jca.ProviderList.getIndex(ProviderList.java:263) ~[?:1.8.0_212]
	at sun.security.jca.ProviderList.getProviderConfig(ProviderList.java:247) ~[?:1.8.0_212]
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:253) ~[?:1.8.0_212]
	at java.security.Security.getProvider(Security.java:503) ~[?:1.8.0_212]
	at sun.security.ssl.SignatureAndHashAlgorithm.<clinit>(SignatureAndHashAlgorithm.java:415) ~[?:1.8.0_212]

**Comment by itzg** [comment]
Strange, I have never seen that error. What Docker run arguments are you using?

**Comment by technik-dude** [comment]
I found a solution. I change the Java Version from "Default" to Java 11. Now it works.
I used no arguments. Only Path changed.

**Comment by itzg** [comment]
I’m glad that fixed it
