### ISSUE TITLE
Magma Server Forge Version

### ISSUE THREAD

**Issue by CaptainCookLP** [itzg/docker-minecraft-server#558]
Hello everyone,

I've got a Problem with the creation of an Magma Modpack Server. 

Install Command:

`docker run -d -e EULA=TRUE -e TYPE=magma -e VERSION="1.12.2" -e FORGEVERSION=14.23.5.2847  -v /home/minecraft:/data -p 25565:25565 --name mc itzg/minecraft-server`

Log Snippet:

`[init] Starting the Minecraft server...
Starting Magma
Downloading Minecraft Server Jar ...
Downloading Server Libraries ...
Extracting Zip
2020-06-17 11:01:38,973 main WARN Disabling terminal, you're running in an unsupported environment.
[11:01:39] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[11:01:39] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[11:01:39] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[11:01:39] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2838 for Minecraft 1.12.2 loading`

Says Forge Version: 14.23.5.2838

Error:

`[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderio (Ender IO) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderioconduitsappliedenergistics (Ender IO Applied Energistics Conduits) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderioconduitsopencomputers (Ender IO Open Computers Conduits) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderioconduitsrefinedstorage (Ender IO Refined Storage Conduits) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderioconduits (Ender IO Conduits) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderiointegrationforestry (Ender IO Integration with Forestry) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderiointegrationtic (Ender IO Integration with Tinkers' Construct) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderiomachines (Ender IO Machines) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod enderiozoo (Ender IO Zoo) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod fairylights (Fairy Lights) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod forestry (Forestry) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod mysticallib (Mystical Lib) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod netherendingores (Netherending Ores) requires [forge@[14.23.5.2847,)]
[11:12:34] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.MultipleModsErrored: 
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
Missing Mods:
	unknown : need [14.23.5.2847,): have 14.23.5.2838
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:301) ~[Loader.class:2798a77]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:573) ~[Loader.class:2798a77]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:102) ~[FMLServerHandler.class:2798a77]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:334) ~[FMLCommonHandler.class:2798a77]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:164) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:654) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

Says: need [14.23.5.2847,): have 14.23.5.2838

How do I change the Forge Version of the Magma Type Server?

**Comment by itzg** [comment]
The download choices for Magma are extremely limited:

https://magmafoundation.org/#download

Right now the startup script always downloads the latest, but I could enhance it allow picking one of the tags there.

Otherwise, it sounds like you need to report an issue with Magma.

**Comment by CaptainCookLP** [comment]
When I install Magma on another System it justs works fine

**Comment by itzg** [comment]
It sounds like Magma released an update that probably fixed your issue. Can we close this issue now?
