### ISSUE TITLE
FTB/Curseforge 

### ISSUE THREAD

**Issue by v0idp** [itzg/docker-minecraft-server#591]
I am stuck in this infinitive bootloop where it can't find the forge file and then wants to install it and then can't find it and wants to install it again. 

![image](https://user-images.githubusercontent.com/39016303/87882115-41bcf480-c9fe-11ea-9379-3eef0be1fabe.png)

if I look into the FeedTheBeast folder I can find the jar file there:
![image](https://user-images.githubusercontent.com/39016303/87882129-513c3d80-c9fe-11ea-8aa6-9d68c50ca264.png)

here are the complete logs:
```
[init] Skip setting max-tick-time,
[init] Skip setting enable-query,
[init] Skip setting query.port,
[init] Setting enable-rcon to 'true' in /data/FeedTheBeast/server.properties,
[init] Setting rcon.password to 'minecraft' in /data/FeedTheBeast/server.properties,
[init] Setting rcon.port to '25575' in /data/FeedTheBeast/server.properties,
[init] Skip setting max-players,
[init] Skip setting max-world-size,
[init] Setting level-name to 'world' in /data/FeedTheBeast/server.properties,
[init] Skip setting level-seed,
[init] Setting pvp to 'true' in /data/FeedTheBeast/server.properties,
[init] Skip setting generator-settings,
[init] Setting online-mode to 'true' in /data/FeedTheBeast/server.properties,
[init] Skip setting allow-flight,
[init] Setting level-type to 'DEFAULT' in /data/FeedTheBeast/server.properties,
[init] Skip setting resource-pack,
[init] Skip setting resource-pack-sha1,
[init] Skip setting player-idle-timeout,
[init] Skip setting broadcast-console-to-ops,
[init] Skip setting broadcast-rcon-to-ops,
[init] Skip setting enable-jmx-monitoring,
[init] Skip setting sync-chunk-writes,
[init] Skip setting enable-status,
[init] Skip setting entity-broadcast-range-percentage,
[init] Skip setting function-permission-level,
[init] Skip setting network-compression-threshold,
[init] Skip setting op-permission-level,
[init] Skip setting prevent-proxy-connections,
[init] Skip setting use-native-transport,
[init] Skip setting enforce-whitelist,
[init] Setting difficulty to 'easy' in /data/FeedTheBeast/server.properties,
[init] Creating log4j2.xml in /data/log4j2.xml,
[init] Checking for JSON files.,
[init] Setting initial memory to 8G and max to 8G,
[init] Running FTB /data/FeedTheBeast/ServerStart.sh in /data/FeedTheBeast ...,
Ping to Google DNS successful,
Required files not found, need to install Forge,
Starting install of Forge/Minecraft server binaries,
Moving current installer to ./DELETEME,
No installer found will try to download it,
Moving unneeded files/folders to ./DELETEME,
Installing Forge Server, please wait...,
Required files not found, need to install Forge,
Starting install of Forge/Minecraft server binaries,
Moving current installer to ./DELETEME,
No installer found will try to download it,
Moving unneeded files/folders to ./DELETEME,
Installing Forge Server, please wait...,
Required files not found, need to install Forge,
Starting install of Forge/Minecraft server binaries,
Moving current installer to ./DELETEME,
No installer found will try to download it,
Moving unneeded files/folders to ./DELETEME,
Installing Forge Server, please wait...,
Starting server,
Error: Unable to access jarfile ,
Server will restart in ~10 seconds. No input needed...,
,
Rebooting now!,
Ping to Google DNS successful,
Required files not found, need to install Forge,
Starting install of Forge/Minecraft server binaries,
Moving current installer to ./DELETEME,
No installer found will try to download it,
Moving unneeded files/folders to ./DELETEME,
Installing Forge Server, please wait...,
Required files not found, need to install Forge,
Starting install of Forge/Minecraft server binaries,
Moving current installer to ./DELETEME,
No installer found will try to download it,
Moving unneeded files/folders to ./DELETEME,
Installing Forge Server, please wait...,
Required files not found, need to install Forge,
Starting install of Forge/Minecraft server binaries,
Moving current installer to ./DELETEME,
No installer found will try to download it,
Moving unneeded files/folders to ./DELETEME,
Installing Forge Server, please wait...,
Starting server,
Error: Unable to access jarfile ,
Server will restart in ~10 seconds. No input needed...,
,
Rebooting now!,
Ping to Google DNS successful,
Required files not found, need to install Forge,
Starting install of Forge/Minecraft server binaries,
Moving current installer to ./DELETEME,
No installer found will try to download it,
Moving unneeded files/folders to ./DELETEME,
Installing Forge Server, please wait...,
Required files not found, need to install Forge,
Starting install of Forge/Minecraft server binaries,
Moving current installer to ./DELETEME,
No installer found will try to download it,
Moving unneeded files/folders to ./DELETEME,
Installing Forge Server, please wait...,
Required files not found, need to install Forge,
Starting install of Forge/Minecraft server binaries,
Moving current installer to ./DELETEME,
No installer found will try to download it,
```

**Comment by itzg** [comment]
It looks like a bug in that modpack's `ServerStart.sh`. What modpack are you trying? I'll see if it does the same thing to me.

**Comment by v0idp** [comment]
Additional information first. I forgot:
```
docker run -d -p 25565:25565 --name="minecraft" \
-v /opt/minecraft:/data \
-e TYPE=CURSEFORGE \
-e CF_SERVER_MOD=ATM3-5.12.3_Server-FULL.zip \
-e EULA=TRUE \
-e VIRTUAL_HOST=CENSORED  \
-e VIRTUAL_PORT=25565 \
-e LETSENCRYPT_HOST=CENSORED  \
-e LETSENCRYPT_EMAIL=CENSORED \
itzg/minecraft-server
```

exact modpack and version I am using: https://www.curseforge.com/minecraft/modpacks/all-the-mods-3/files/2756954
under additional files: ATM3-5.12.3_Server-FULL

**Comment by itzg** [comment]
There's a 6.0.0 available here

https://www.curseforge.com/minecraft/modpacks/all-the-mods-3/files

I'm going to try that first since that's what the Twitch client had me download.

**Comment by v0idp** [comment]
Yes I know about 6.0.0 but it's a much more newer minecraft game version and not all the mods are available for that version. Also it's still buggy. That's why I stay on 1.12.2 which is stable and has all the mods working. running it locally works just fine but seems to have issues with docker. I have a user with GUID and UID 1000. Not sure what's the issue here.

**Comment by itzg** [comment]
well, that one's even worse since it's practically empty

![image](https://user-images.githubusercontent.com/988985/87882576-6f864700-c9c6-11ea-9f69-0cc2eb85ab1a.png)

**Comment by v0idp** [comment]
If you can give my version a try and lemme know if it works or not.

**Comment by itzg** [comment]
Yep, same failure for me. Please report an issue against the modpack and provide the `logs/serverstart.log` to them.

```
mc_1  | Ping to Google DNS successful
mc_1  | Required files not found, need to install Forge
mc_1  | Starting install of Forge/Minecraft server binaries
mc_1  | Moving current installer to ./DELETEME
mc_1  | No installer found will try to download it
mc_1  | Moving unneeded files/folders to ./DELETEME
mc_1  | Installing Forge Server, please wait...
mc_1  | Required files not found, need to install Forge
mc_1  | Starting install of Forge/Minecraft server binaries
mc_1  | Moving current installer to ./DELETEME
mc_1  | No installer found will try to download it
mc_1  | Moving unneeded files/folders to ./DELETEME
mc_1  | Installing Forge Server, please wait...
mc_1  | Required files not found, need to install Forge
```

**Comment by v0idp** [comment]
Also something I noticed the mod is not FeedTheBeast but the folder it unpacked it into is called exactly that. why is that ?

**Comment by v0idp** [comment]
I also found this error in the serverstart logs:
```We appear to be missing one or more essential library files.
You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:52)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)```

looks like the installer.jar is crashing because some essential library files are missing and then it says that the universal.jar file is missing afterwards and then it tries to do it again from beginning. this is how it got stuck in the loop. the question now is what kinda essential libraries it is missing in the container environment ?

**Comment by itzg** [comment]
I have gotten tired of these buggy modpack scripts, so I will push an update in a just a few minutes that adds the option `-e AVOID_MODPACK_START_SCRIPT=true` . Stay tuned...

**Comment by itzg** [comment]
...actually I'm going to rename it to `USE_MODPACK_START_SCRIPT` and default to "false". Stay tuned just a bit more...

**Comment by v0idp** [comment]
Thank you. Your help is appreciated here. Will your script also make sure to have the proper forge version for the modpack and so on ?

**Comment by itzg** [comment]
Yep, it'll take of running the forge installer bundled with the modpack and running that installed forge server jar. It's building now...

**Comment by itzg** [comment]
Updated image is pushed and here's the compose file I used for testing

https://github.com/itzg/mc-modpacks-starter/blob/master/all-the-mods/docker-compose.yml

**Comment by itzg** [comment]
Oops, I need to optimize the startup to skip all the unzipping and installing when it's already present, but should work fine for now.

**Comment by v0idp** [comment]
I will run a test and let you know!

**Comment by v0idp** [comment]
server is running just fine now! thank you so much. Can you make sure that the optimization is added tho ? Don't wanna download and install forge everytime it starts.

**Comment by itzg** [comment]
In the latest image the EULA file and others are now brought over properly. It also supports skipping the unzip and forge install if already present. It will also upgrade the modpack when the `FTB_SERVER_MOD` is changed.

**Comment by v0idp** [comment]
thank you a lot. amazing work and everything works just fine now. I appreciate your help on this matter.

**Comment by itzg** [comment]
I have been wanting to enhance that bit for a while, so I appreciate the final motivation 😀
