### ISSUE TITLE
QNAP TS-431P2 / 

### ISSUE THREAD

**Issue by T4haha** [itzg/docker-minecraft-server#637]
Hi,

Could you please advice with this problem:

**Status:** I'm starting Minecraft server (itzg/minecraft-server:1.8.0-multiarch) on QNAP but it failed. QNAP processor is ( AL314 Quad-core ARM Cortex-A15 CPU @ 1.70GHz). It should be AMR 32 based, therefore I did use multiarch packege.

**The result message is:**

[init] Resolved version given LATEST into 1.16.3                                                                                                             
[init] Resolving type given VANILLA                                                                                                                          
[init] server.properties already created, skipping                                                                                                           
[init] log4j2.xml already created, skipping                                                                                                                  
[init] Checking for JSON files.                                                                                                                              
[init] Setting initial memory to 1G and max to 1G                                                                                                            
[init] Starting the Minecraft server...                                                                                                                      
[12:44:25] [main/FATAL]: Failed to start the Minecraft  server                                                                                                
joptsimple.UnrecognizedOptionException: name is not a recognized option                                                                                      
        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[minecraft_server.1.16.3.jar:?]                                          
        at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510) ~[minecraft_server.1.16.3.jar:?]                                             
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56) ~[minecraft_server.1.16.3.jar:?]                                         
        at joptsimple.OptionParser.parse(OptionParser.java:396) ~[minecraft_server.1.16.3.jar:?]                                                             
        at net.minecraft.server.Main.main(SourceFile:79) [minecraft_server.1.16.3.jar:?]                                                                     
2020-09-22T12:44:25.265Z        INFO    mc-server-runner        Done

**Comment by itzg** [comment]
Can you provide more information about how you created the container? It looks like there's a `name` argument that is misplaced on the final command line.

**Comment by T4haha** [comment]
Hi itzg,

you are right, I did mesaup the name, so I did remove docker and install it again. Now I have issue with EULA.

![image](https://user-images.githubusercontent.com/71708905/94540438-c15d1000-0246-11eb-8db6-797ea7a6e665.png)

Could you please advice where to add eula, I did tried, but without sucess

![image](https://user-images.githubusercontent.com/71708905/94540617-f1a4ae80-0246-11eb-9164-1fe9c1280d3c.png)

**Comment by itzg** [comment]
It will be set wherever container environment variables are set. Maybe via that "settings" button.

**Comment by T4haha** [comment]
Hi itzg, 

thanks for the prompt response. You was right again, in the settings during installation is a ADD button. So I added the EULA=TRUE. 

Docker reports now an error with "name". :(, seems I got on the start again. Should you have any ideas its welcome. Thanks for help. 

        at joptsimple.OptionParser.parse(OptionParser.java:396) ~[minecraft_server.1.16.3.jar:?]                                                             
        at net.minecraft.server.Main.main(SourceFile:79) [minecraft_server.1.16.3.jar:?]                                                                     
2020-09-29T14:38:30.981Z        INFO    mc-server-runner        Done                                                                                         
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 4 1000 1000 4096 Sep 29 14:38 /data'                                                           
[init] Resolved version given LATEST into 1.16.3                                                                                                             
[init] Resolving type given VANILLA                                                                                                                          
[init] server.properties already created, skipping                                                                                                           
[init] log4j2.xml already created, skipping                                                                                                                  
[init] Checking for JSON files.                                                                                                                              
[init] Setting initial memory to 1G and max to 1G                                                                                                            
[init] Starting the Minecraft server...                                                                                                                      
[14:38:42] [main/FATAL]: Failed to start the minecraft server                                                                                                
joptsimple.UnrecognizedOptionException: name is not a recognized option                                                                                      
        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[minecraft_server.1.16.3.jar:?]                                          
        at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510) ~[minecraft_server.1.16.3.jar:?]                                             
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56) ~[minecraft_server.1.16.3.jar:?]                                         
        at joptsimple.OptionParser.parse(OptionParser.java:396) ~[minecraft_server.1.16.3.jar:?]                                                             
        at net.minecraft.server.Main.main(SourceFile:79) [minecraft_server.1.16.3.jar:?]                                                                     
2020-09-29T14:38:42.864Z        INFO    mc-server-runner        Done

**Comment by itzg** [comment]
Looking again at your first screenshot, I think you should probably be leaving "Command" blank. (Sorry I'm not able to give very specific advice along the way here since I am not familiar with ContainerStation or other Docker UIs.)

**Comment by T4haha** [comment]
Hi itzg,

well done man, you are the star! 

It helps and server is now up and running.

Many thanks for advices
Take care

**Comment by T4haha** [comment]
for the record.
