### ISSUE TITLE
Server can't connect to mariadb.

### ISSUE THREAD

**Issue by japietru2004** [itzg/docker-minecraft-server#745]
I have recently updated my linux mint from 19 to 20 and for some reason my server luckperms now has problem with connecting to sql server. I have error that connection has been refused. Could you mayby help with this ?

Error:
`[13:40:59] [Server thread/INFO]: [LuckPerms] Loading configuration...
[13:41:03] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[13:41:03] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[13:41:03] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[13:41:08] [Server thread/ERROR]: [LuckPerms] Failed to init storage implementation
[13:41:08] [Server thread/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5016ms.
[13:41:08] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:689)
[13:41:08] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
[13:41:08] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
[13:41:08] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[13:41:08] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
...`

**Comment by japietru2004** [comment]
I know this might not be your problem but I want still to ask this becouse It happened during ussage of your docker image.

**Comment by itzg** [comment]
Nothing comes to mind that would influence that, but let's see if others land here to give some ideas. 

In the meantime, I would suggest double checking the db container has the name you expect, isn't throwing any errors itself, and that the luckyperms is still configured as you expect.

**Comment by japietru2004** [comment]
I have nothing changed in db or config during update (I checked this).
For some reason connection is being refused.

**Comment by japietru2004** [comment]
I think I will just reroll with timeshift (I see some viaver errors too) - closing.
