### ISSUE TITLE
Minecraft Forge 1.12 does not work

### ISSUE THREAD

**Issue by jalphonso** [itzg/docker-minecraft-server#775]
I haven't been able to get 1.12 to work. 1.16 works but unfortunately most of the mods my kids wants to use require 1.12.

```
docker run -d -p 25578:25575 -p 25568:25565 --name minecraft3 -e TZ=US/Eastern -e EULA=TRUE -v $PWD/minecraft3:/data -e TYPE=FORGE -e VERSION=1.12.2 -e FORGEVERSION=14.23.5.2855 itzg/minecraft-server
```

Results in the following stack trace

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    4 1000     1000          4096 Feb 20 21:30 /data'
[init] Resolved version given 1.12.2 into 1.12.2
[init] Resolving type given FORGE
[init] **********************************************************************
[init] WARNING: The image tag itzg/minecraft-server:java8 is recommended
[init]          since some mods require Java 8
[init] **********************************************************************
[init] Checking Forge version information.
[init] server.properties already created, skipping
[init] log4j2.xml already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
2021-02-21T14:29:43.331-0500	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
2021-02-21T14:29:43.332-0500	INFO	mc-server-runner	Done
```

**Comment by jalphonso** [comment]
you know what, after pasting the message in I read the warning and tried the java8 tag. it works now.

```
itzg/minecraft-server:java8
```

**Comment by itzg** [comment]
I should probably include a reference to "A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException" in that warning message :)
