### ISSUE TITLE
More information needed for Remote JMX

### ISSUE THREAD

**Issue by Colin-XKL** [itzg/docker-minecraft-server#786]
I want to enable remote JMX for profiling. But after I followed the instruction in the README, the server can not start.
part of the log:
```
[init] Starting the Minecraft server...
OpenJDK 64-Bit Server VM warning: CMSFullGCsBeforeCompaction is deprecated and will likely be removed in a future release.
Error: JMX connector server communication error: service:jmx:rmi://{{My server domain}}:7091
sun.management.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 7091; nested exception is: 
	java.net.BindException: Address not available (Bind failed)
	at sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:800)
	at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:468)
	at sun.management.Agent.startAgent(Agent.java:262)
	at sun.management.Agent.startAgent(Agent.java:452)
Caused by: java.rmi.server.ExportException: Port already in use: 7091; nested exception is: 
	java.net.BindException: Address not available (Bind failed)
	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:346)
	at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:254)
	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411)
	at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
	at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:237)
	at sun.management.jmxremote.ConnectorBootstrap$PermanentExporter.exportObject(ConnectorBootstrap.java:199)
	at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:146)
	at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:122)
	at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:404)
	at sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:796)
	... 3 more
Caused by: java.net.BindException: Address not available (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at sun.management.jmxremote.ConnectorBootstrap$HostAwareSocketFactory.createServerSocket(ConnectorBootstrap.java:864)
	at sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:666)
	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)
	... 12 more
```

I have already check the host and did not find any process that is using the port 7091. Besides, I turned off the firewall and tested it again, but the errors are the same.

**Comment by Colin-XKL** [comment]
part of my docker-compose file
``` image: itzg/minecraft-server:java8
    container_name: "MCServer"
    ports:
      - "25565:25565"
      - "7091:7091"
    environment:
      # ......
      # jmx
      ENABLE_JMX: "true"
      JMX_HOST: {{my server domain}}
    restart: unless-stopped
```

**Comment by itzg** [comment]
JMX is such a pain to get working. It took me many combinations to finally get that one example working. 

In your case it's acting like another Java process within the container is also binding 7091, but that seems odd.

**Comment by jhlwscom** [comment]
Have the same issue, not a fix but you can get it working by manually setting the options:
`JVM_DD_OPTS: "com.sun.management.jmxremote.ssl=false com.sun.management.jmxremote.authenticate=false com.sun.management.jmxremote.port=1098 com.sun.management.jmxremote.rmi.port=1098 java.rmi.server.hostname=HOSTNAME_HERE com.sun.management.jmxremote.local.only=false "`

**Comment by itzg** [comment]
Hmm, the `ENABLE_JMX` option does the same thing here:

https://github.com/itzg/docker-minecraft-server/blob/861aec6bd616cc0b3a84ca8c1cb6e2d10fa9f610/start-minecraftFinalSetup#L95

A port conflict sounds like a different issue though.

**Comment by itzg** [comment]
oh @jhlwscom I see you set yours to port 1098, can do the same with `JMX_PORT` looking at the broader code block

https://github.com/itzg/docker-minecraft-server/blob/861aec6bd616cc0b3a84ca8c1cb6e2d10fa9f610/start-minecraftFinalSetup#L87-L95
