### ISSUE TITLE
Fabric installer appears to wish for root directory access. Fails install.

### ISSUE THREAD

**Issue by sfxworks** [itzg/docker-minecraft-server#797]
Hello,

```bash
[init] Running as uid=1001 gid=1000 with /data as 'drwxrwxrwx    2 1001     1000             1 Mar 10 21:30 /data'
[init] Resolved version given 1.16.4 into 1.16.4
[init] Resolving type given FABRIC
[init] Checking Fabric version information.
[init] Downloading installer version 0.7.2
[init] ...trying https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.7.2/fabric-installer-0.7.2.jar
[init] Installing Fabric using /tmp/fabric-installer-0.7.2.jar
Loading Fabric Installer: 0.7.2
Using latest loader version
Installing Fabric Loader 0.11.2(1.16.4) on the server
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
        at net.fabricmc.installer.Main.main(Main.java:79)
Caused by: java.io.IOException: Could not create /.cache/fabric-installer/libraries!
        at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:51)
        at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:63)
        at net.fabricmc.installer.Main.main(Main.java:77)
Loading Fabric Installer: 0.7.2
Using latest loader version
Installing Fabric Loader 0.11.2(1.16.4) on the server
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
        at net.fabricmc.installer.Main.main(Main.java:79)
Caused by: java.io.IOException: Could not create /.cache/fabric-installer/libraries!
        at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:51)
        at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:63)
        at net.fabricmc.installer.Main.main(Main.java:77)
Loading Fabric Installer: 0.7.2
Using latest loader version
Installing Fabric Loader 0.11.2(1.16.4) on the server
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
        at net.fabricmc.installer.Main.main(Main.java:79)
Caused by: java.io.IOException: Could not create /.cache/fabric-installer/libraries!
        at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:51)
        at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:63)
        at net.fabricmc.installer.Main.main(Main.java:77)
[init] Fabric failed to install after several tries.
```

When running a new fabric server on the latest image, fabric appears to try to write to /.cache. This fails to work in scenarios where permissions from the /data directory and root directory are different. I was wondering if `-dir` could automatically be passed here to target the `/data` directory as referenced as an optional argument in https://fabricmc.net/wiki/install? It appears here https://github.com/itzg/docker-minecraft-server/blob/master/start-deployFabric#L57 that it could be applied. I am not sure if the current working directory for the installer is a temporary folder at root or the data directory. If so I can create an issue in their repository. 

For reference, I am using this rendering:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2021-03-09T15:44:29Z"
  generation: 5
  name: server1
  namespace: awesome-gorilla
  ownerReferences:
  - apiVersion: mcserverhosting.net/v2
    blockOwnerDeletion: true
    controller: true
    kind: MinecraftServer
    name: server1
    uid: bdbd947d-a66b-41f3-99bb-a9da19b87bd3
  resourceVersion: "1019816"
  uid: 2180fd32-6da1-417d-9ffe-adb1f1ffe498
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: server1
  serviceName: server1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server1
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: server1
        image: docker.io/itzg/minecraft-server:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 1
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: minecraft-tcp
          timeoutSeconds: 1
        name: server1
        ports:
        - containerPort: 25565
          name: minecraft-udp
          protocol: UDP
        - containerPort: 25565
          name: minecraft-tcp
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: minecraft-tcp
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 7Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 1000
          runAsUser: 1001
        startupProbe:
          failureThreshold: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: minecraft-tcp
          timeoutSeconds: 1
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        tty: true
        volumeMounts:
        - mountPath: /data
          name: minecraft-volume
          subPath: servers/server1
        - mountPath: /web
          name: minecraft-volume
          subPath: web
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1001:1000 /data
        image: busybox
        imagePullPolicy: Always
        name: permissions
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: minecraft-volume
          subPath: servers/server1
      nodeSelector:
        node-role.kubernetes.io/game: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: ns-pvc
      - emptyDir:
          medium: HugePages-2Mi
        name: hugepage-2mi
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  ```

**Comment by itzg** [comment]
I can't recreate the issue, but I did add `-dir /data` in the latest image. So please re-test with that. In general though this seems to be a bug in the Fabric installer since that page you linked states:

> -dir Used to select the installation dir, defaults to the current working directory.

and `/data` is the working directory.

**Comment by voruti** [comment]
The `-dir` parameter is not the problem here.
The Fabric installer stores its cache files at `new File(System.getProperty("user.home", "."), ".cache" + File.separator + "fabric-installer" + File.separator + "libraries");`. This "translates" into `/.cache/fabric-installer/libraries` for some reason.

It is also not quite clear to me, how you started the container @sfxworks. How did you set uid to 1001?

**Comment by itzg** [comment]
Good catch @voruti . Since it is 1001 and not uid 1000, this home directory setting doesn't get used:

https://github.com/itzg/docker-minecraft-server/blob/master/Dockerfile#L27

@sfxworks why did you use 1001? Are you constrained by the persistent volume storage class?

In any case, the issue opened with FabricMC would help if the uid can't be aligned on 1000.

**Comment by sfxworks** [comment]
Our users have the ability to set the user and group IDs as they please to manage access among themselves and others. For example, one could have access to server1 but not server2 and enforce that with user/group permissions. An init container adjusts chown as root on the server directory before launch.

It is enforced by https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ via:
```yaml
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 1000
          runAsUser: 1001
```
which I believe is similar to `docker run --user=1001:1000 docker.io/itzg/minecraft-server:latest`.  

The workaround for setting the userID to 1000 works. I passed it to the user's config and it runs.
![image](https://user-images.githubusercontent.com/5921035/111077414-0c05d800-84c7-11eb-9e49-469d5045dbdc.png)

```
[init] Installing Fabric using /tmp/fabric-installer-0.7.2.jar
Loading Fabric Installer: 0.7.2
Using latest loader version
Installing Fabric Loader 0.11.3(1.16.4) on the server
Downloading required files
Downloading library net.fabricmc:tiny-mappings-parser:0.2.2.14
Downloading library net.fabricmc:sponge-mixin:0.9.2+mixin.0.8.2
Downloading library net.fabricmc:tiny-remapper:0.3.0.70
Downloading library net.fabricmc:access-widener:1.0.0
Downloading library net.fabricmc:fabric-loader-sat4j:2.3.5.4
Downloading library com.google.jimfs:jimfs:1.2-fabric
Downloading library org.ow2.asm:asm:9.1
Downloading library org.ow2.asm:asm-analysis:9.1
Downloading library org.ow2.asm:asm-commons:9.1
Downloading library org.ow2.asm:asm-tree:9.1
Downloading library org.ow2.asm:asm-util:9.1
Downloading library net.fabricmc:intermediary:1.16.4
Downloading library net.fabricmc:fabric-loader:0.11.3
Downloading library com.google.guava:guava:21.0
Generating server launch JAR
Generating server launch JAR: tiny-mappings-parser-0.2.2.14.jar
Generating server launch JAR: sponge-mixin-0.9.2+mixin.0.8.2.jar
Generating server launch JAR: tiny-remapper-0.3.0.70.jar
Generating server launch JAR: access-widener-1.0.0.jar
Generating server launch JAR: fabric-loader-sat4j-2.3.5.4.jar
Generating server launch JAR: jimfs-1.2-fabric.jar
Generating server launch JAR: asm-9.1.jar
Generating server launch JAR: asm-analysis-9.1.jar
duplicate file: module-info.class
Generating server launch JAR: asm-commons-9.1.jar
duplicate file: module-info.class
Generating server launch JAR: asm-tree-9.1.jar
duplicate file: module-info.class
Generating server launch JAR: asm-util-9.1.jar
duplicate file: module-info.class
Generating server launch JAR: intermediary-1.16.4.jar
Generating server launch JAR: fabric-loader-0.11.3.jar
Generating server launch JAR: guava-21.0.jar
Done, start server by running fabric-server-launch.jar
Downloading Minecraft server
Done
[init] Using server fabric-server-launch.jar
[init] Creating server.properties in /data/server.properties
[init] Adding server-name with 'server1' in /data/server.properties
[init] Setting server-port to '25565' in /data/server.properties
[init] Setting motd to 'Your new MCSH minecraft serve
```

**Comment by itzg** [comment]
Having the initContainer doing the same as

https://github.com/itzg/docker-minecraft-server/blob/28810fcba3e85415b4beca42a908238ee3a3eb3d/start#L16

might work too if you are still needing arbitrary UIDs.

**Comment by sfxworks** [comment]
Will test https://github.com/FabricMC/fabric-installer/pull/70 to confirm

**Comment by sfxworks** [comment]
Their PR fixed this issue
