### ISSUE TITLE
Installation Skyopolis 4 via Curseforge gives mismatched mod channel list

### ISSUE THREAD

**Issue by Severe1** [itzg/docker-minecraft-server#829]
Downloaded the server files archive for https://www.curseforge.com/minecraft/modpacks/skyopolis-4/files and placed in a modpack volume. The server boots up, but it appears to not have any mods in it (/mods folder empty). When connecting to the server the mismatched mod channel list error is given.

Have tried the server archive locally on windows machine and works correctly.

**Comment by itzg** [comment]
Well, this is a new variant...the modpack includes an `install.sh` that is very helpful but new to me:

```
#!/bin/sh

wget -O forge.jar https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.0.46/forge-1.16.5-36.0.46-installer.jar

java -jar forge.jar --installServer

clear

rm forge.jar
rm installer.log

mkdir -p mods

wget -O mods/jei-1.16.4-7.6.0.62.jar https://edge.forgecdn.net/files/3136/600/jei-1.16.4-7.6.0.62.jar
wget -O mods/AppleSkin-mc1.16.2-forge-1.0.14.jar https://edge.forgecdn.net/files/3035/787/AppleSkin-mc1.16.2-forge-1.0.14.jar
wget -O mods/ftb-backups-2.1.1.6.jar https://edge.forgecdn.net/files/3038/811/ftb-backups-2.1.1.6.jar
wget -O mods/woodenutilities-1.0.6-1.16.4.jar https://edge.forgecdn.net/files/3109/27/woodenutilities-1.0.6-1.16.4.jar
```

I'll have to add support for that.

**Comment by itzg** [comment]
I added support for the `install.sh` however with https://www.curseforge.com/minecraft/modpacks/skyopolis-4/files/3271144 mine crashes on startup, so I was wondering what version of the modpack worked for you.

Fails with:
```
[15:38:16] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:?] {}
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:?] {}
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.ForgeConfigSpec.correct(ForgeConfigSpec.java:236) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec.isCorrect(ForgeConfigSpec.java:139) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec.setConfig(ForgeConfigSpec.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ModConfig.setConfigData(ModConfig.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:105) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[forge:?] {re:classloading}
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?] {}
	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:95) ~[forge:?] {re:mixin,re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:APP:globaldataandresourcepacks.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:APP:globaldataandresourcepacks.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}
```

**Comment by itzg** [comment]
> I added support for the `install.sh` however with https://www.curseforge.com/minecraft/modpacks/skyopolis-4/files/3271144 mine crashes on startup, so I was wondering what version of the modpack worked for you.

nm, maybe it's because I was using java 11

**Comment by Severe1** [comment]
I've downloaded and tested the java8 branch, the project now runs. Thank you for quick thinking and off course the fix. Keep up the good work!
