### ISSUE TITLE
cannot access class sun.security.util.ManifestEntryVerifier

### ISSUE THREAD

**Issue by lettucetrail** [itzg/docker-minecraft-server#832]
Alright, So when starting my server the container exits and the logs I'm left with show the following:
```
[init] Starting the Minecraft server...


2021-04-16 18:25:08,278 main WARN Advanced terminal features are not available in this environment


[18:25:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.4, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]


[18:25:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 16 by AdoptOpenJDK


Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x3e6d8c1c) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x3e6d8c1c


	at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)


	at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)


	at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)


	at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)


	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)


	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)


	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)


	at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)


	at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)


	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)


	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)


	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)


	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)


2021-04-16T18:25:08.407Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}


2021-04-16T18:25:08.407Z	INFO	mc-server-runner	Done
```

Based on my previous experience with this image I went ahead and created a fresh container in a new directory, as that's become my go to start for debugging. Same error

Looks like running minecraft or forge with java 16+ is the issue so I'm going to switch from the multiarch-latest image to multiarch and see if this resolves. Ultimately had to use java8-multiarch because of a specific mod. Eitherway thought I'd post this so you're aware of possible incompatibility.

**Comment by itzg** [comment]
Yes, most Forge things require Java 8. There's a warning at he start that mentions compatibility issues.
