### ISSUE TITLE
Failed to start the minecraft server -- ModPack Valhelsia+3-3.2.4-SERVER.zip

### ISSUE THREAD

**Issue by Stephen-Hilton** [itzg/docker-minecraft-server#835]
Not urgent, and may well be an issue with the modpack, but in case i'm missing something blindingly obvious:

Trying to:

```
## Minecraft-valhelsia
docker run -d --name minecraft-valhelsia \
 -p 55560:25565 \
 --net famhil-net \
 -e EULA=TRUE \
 -e VERSION=1.16.5 \
 -e TYPE=CURSEFORGE \
 -e OVERRIDE_SERVER_PROPERTIES=TRUE \
 -e CF_SERVER_MOD=/modpacks/Valhelsia+3-3.2.4-SERVER.zip \
 -v /opt/docker/volumes/minecraft-valhelsia:/data \
 -v /opt/docker/volumes/modpacks:/modpacks \
 itzg/minecraft-server 
```

and getting the error:

```
Crash Report UUID: 0622d9e2-1ad6-475f-ad1f-f770eef1604b[18:44:59] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Structurize (structurize) has failed to load correctly

§7java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/ldtteam/structurize/api/blocks/IBlockCollection. Method 'net.minecraft.block.Block lambda$create$0(com.ldtteam.structurize.api.blocks.BlockType)' at index 147 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
]
```

full error text below.   I repulled the docker image, and re-downloaded the modpack, just to have everything up-to-date:
[https://www.curseforge.com/minecraft/modpacks/valhelsia-3/files](https://www.curseforge.com/minecraft/modpacks/valhelsia-3/files).

I tried with and without the OVERRIDE_SERVER_PROPERTIES, which I have needed to successfully run the image with other modpacks, so i know the image works elsewhere.  Both have same error.    Again, maybe an incompatibility with Valhelsia, but thought i'd ask - maybe someone has a suggestion.

Thanks!
Stephen

Full error text:

```
...
		Transport-1.16.5-3.6.0.jar                        |Transport                     |transport                     |3.6.0               |CREATE_REG|NOSIGNATURE
		ferritecore-2.0.4-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.4               |CREATE_REG|41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		engineersdecor-1.16.4-1.1.11.jar                  |Engineer's Decor              |engineersdecor                |1.1.11              |CREATE_REG|bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		refinedstorageaddons-0.7.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.7.2               |CREATE_REG|NOSIGNATURE
		valhelsia_core-16.0.6.jar                         |Valhelsia Core                |valhelsia_core                |16.0.6              |CREATE_REG|NOSIGNATURE
		forbidden_arcanus-16.2.0-beta-3.jar               |Forbidden & Arcanus           |forbidden_arcanus             |16.2.0-beta-3       |CREATE_REG|NOSIGNATURE
		valhelsia_tweaks-16.0.6.jar                       |Valhelsia Tweaks              |valhelsia_tweaks              |16.0.6              |CREATE_REG|NOSIGNATURE
		chiselsandbits-0.3.4-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |CREATE_REG|NOSIGNATURE
		OpenLoader-1.16.5-9.0.3.jar                       |OpenLoader                    |openloader                    |9.0.3               |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
	Crash Report UUID: 0622d9e2-1ad6-475f-ad1f-f770eef1604b[18:44:59] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Structurize (structurize) has failed to load correctly
§7java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/ldtteam/structurize/api/blocks/IBlockCollection. Method 'net.minecraft.block.Block lambda$create$0(com.ldtteam.structurize.api.blocks.BlockType)' at index 147 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
]

	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.1.4.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.1.4.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.1.4.jar:?] {}
```

**Comment by itzg** [comment]
Try using the Java 8 image with `itzg/minecraft-server:java8` since Forge and most mods seem to not work with Java 11.

**Comment by Empiress** [comment]
Hi. I have the same issue but with with TYPE=FTBA (FTB_MODPACK_ID = 79). 
I tried to switch to itzg/minecraft-server:java8-multiarch since FTBA is only working with the multiarch images, but this leads to another error:
`[init] FTB modpack ID 79, version ID 2045 is ready to go
jq: error: Could not open file version.json: No such file or directory`

btw: the same jq error appears when I use the multiarch-latest image.

@itzg you said the most mods don't work with java 11. I only can speak for FTB Modpack 79 but this worked fine until a few days ago.

Thanks in advance.

**Comment by Jaymasaur** [comment]
I'm a bit newer to this (forgive if this is noobish), but I was able to get a Valhelsia 3 server up and running with this script:

`docker run -it -v /home/docker/mcVal3/_data:/data \
-e EULA=TRUE \
-e TYPE=CURSEFORGE -e CF_SERVER_MOD=https://media.forgecdn.net/files/3293/967/Valhelsia+3-3.3.1-SERVER.zip \
-e MEMORY=6G \
-e JVM_XX_OPTS="+UseG1GC" \
-e JVM_XX_OPTS="+ParallelRefProcEnabled" \
-e JVM_XX_OPTS=MaxGCPauseMillis=200 \
-e JVM_XX_OPTS="+UnlockExperimentalVMOptions" \
-e JVM_XX_OPTS="+DisableExplicitGC" \
-e JVM_XX_OPTS=-OmitStackTraceInFastThrow \
-e JVM_XX_OPTS="+AlwaysPreTouch" \
-e JVM_XX_OPTS=G1MaxNewSizePercent=40 \
-e JVM_XX_OPTS=G1HeapRegionSize=8M \
-e JVM_XX_OPTS=G1ReservePercent=20 \
-e JVM_XX_OPTS=G1HeapWastePercent=5 \
-e JVM_XX_OPTS=G1MixedGCCountTarget=8 \
-e JVM_XX_OPTS=InitiatingHeapOccupancyPercent=15 \
-e JVM_XX_OPTS=G1MixedGCLiveThresholdPercent=90 \
-e JVM_XX_OPTS=G1RSetUpdatingPauseTimePercent=5 \
-e JVM_XX_OPTS=SurvivorRatio=32 \
-e JVM_XX_OPTS=MaxTenuringThreshold=1 \
-e JVM_XX_OPTS=G1NewSizePercent=20 \
-e JVM_XX_OPTS=G1ReservePercent=20 \
-e JVM_XX_OPTS=MaxGCPauseMillis=50 \
-e JVM_DD_OPTS=using.aikars.flags=true \
-e JVM_DD_OPTS=aikars.new.flags=true \
-e JVM_DD_OPTS=sun.rmi.dgc.server.gcInterval=2147483646 \
--name val3 \
-p 25565:25565 itzg/minecraft-server:java15`

I see that the master itzg recommends java8 (and I still need to try that) but for some reason this works with java15, and "slightly" improved performance (over default).  TBH, I'm still looking for optimizations for this server, as i'm hitting 80% CPU usage with 1 person logged on- but alas, I will create another issue for that!

**Comment by itzg** [comment]
I didn't say you **must** use Java 8. I was only going off this line in the error:

```
§7java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/ldtteam/structurize/api/blocks/IBlockCollection. Method 'net.minecraft.block.Block lambda$create$0(com.ldtteam.structurize.api.blocks.BlockType)' at index 147 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
```

where in my long experience with Java I find `java.lang` package exceptions referring to "class" sometimes indicates Java version incompatibilities or use of JVM internal APIs.

FYI, I don't think it works to repeat `-e JVM_XX_OPTS` declarations. I'm guessing only the last one was accepted by Docker and passed to the container startup scripts. Add `-e DEBUG_EXEC=true` if you want to double check what got passed to the java command-line.

**Comment by itzg** [comment]
@Empiress please open a new issue. FTBA usage is not related to the original issue description.

**Comment by Jaymasaur** [comment]
@itzg you are actually my hero for not only creating this resource but actively maintaining and supporting it. Thank you so much!!! I've learned a ton about docker and running a server, all thanks to you!

Anyway, regarding your reply above, you're right. Is there a way to pass multiple parameters inside one JVM_XX_OPTS env variable? I can update my previous response with a better format

**Comment by itzg** [comment]
@Jaymasaur there's two answers:

1. You'll have to pass one big, space delimited string with each prefixed with `-XX:`, unfortunately. Such as `-e JVM_XX_OPTS="-XX:+UseG1GC -XX:+ParallelRefProcEnabled" -XX:MaxGCPauseMillis=200"`
2. The good news is that Aikar's flags is already supported with `-e USE_AIKAR_FLAGS=true`

**Comment by Jaymasaur** [comment]
That's great, thanks for the tips!
