### ISSUE TITLE
Overriding ops/whitelist prevents the server from starting due to authentication failure

### ISSUE THREAD

**Issue by fwcd** [itzg/docker-minecraft-server#859]
This is probably not a direct issue with this Docker image, but e.g. specifying ops/whitelist by passing variables to the container, seems to cause authentication failures once the server tries to convert the `.txt` list of players into a `.json`:

```
minecraft_1  | [21:47:01 ERROR]: Conversion failed, please try again later
minecraft_1  | net.minecraft.server.v1_16_R3.NameReferencingFileConverter$FileConversionException: Could not request user ... from backend systems
minecraft_1  | 	at net.minecraft.server.v1_16_R3.NameReferencingFileConverter$3.onProfileLookupFailed(NameReferencingFileConverter.java:253) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at com.destroystokyo.paper.profile.PaperGameProfileRepository$PreProfileLookupCallback.onProfileLookupFailed(PaperGameProfileRepository.java:64) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:89) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at com.destroystokyo.paper.profile.PaperGameProfileRepository.findProfilesByNames(PaperGameProfileRepository.java:44) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at net.minecraft.server.v1_16_R3.NameReferencingFileConverter.a(NameReferencingFileConverter.java:71) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at net.minecraft.server.v1_16_R3.NameReferencingFileConverter.d(NameReferencingFileConverter.java:258) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at net.minecraft.server.v1_16_R3.DedicatedServer.convertNames(DedicatedServer.java:634) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:202) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at java.lang.Thread.run(Unknown Source) [?:?]
minecraft_1  | Caused by: com.mojang.authlib.exceptions.AuthenticationException
minecraft_1  | 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:119) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:99) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:56) ~[patched_1.16.5.jar:git-Paper-643]
minecraft_1  | 	... 8 more
minecraft_1  | [21:47:01 WARN]: Encountered a problem while converting the whitelist, retrying in a few seconds
```

Specifying the `.json` file directly works as intended, also opping players via the game works, suggesting that the usual authentication servers seem to be available. Perhaps the converter for `ops.txt`/`white-list.txt` uses a legacy API that is being phased out?

**Comment by itzg** [comment]
It's not the container doing that conversion, it's the Minecraft server jar doing it. Please report this issue to Mojang.

**Comment by itzg** [comment]
Someone reported the bug

https://bugs.mojang.com/projects/WEB/issues/WEB-4457?filter=allopenissues

**Comment by NotErikUden** [comment]
I have the same issue: any workarounds?

**Comment by NotErikUden** [comment]
Can I use an older version of the paper-1.16.5.jar file to change this?

**Comment by fwcd** [comment]
@NotErikUden It'a an API issue so we have to wait for Mojang to fix it. For now the only workaround is probably to write an ops.json/white-list.json manually or run the server in offline mode.

**Comment by itzg** [comment]
It's an issue with their authentication/user lookup endpoint. So, no known workaround unless you have a whitelist.json already populated from before their system broke.

**Comment by NotErikUden** [comment]
Yes! I didn't have a whitelist to begin with, however, I removed the `- OP=Username` from my stack and redeployed the server. Everything works now! Thank you very much.

**Comment by fwcd** [comment]
Fixed upstream.
