### ISSUE TITLE
Java FileSystemException: Operation not permitted

### ISSUE THREAD

**Issue by plasmatech8** [itzg/docker-minecraft-server#881]
Simply running the command shown in the instructions does not appear to work. Thoughts?

Command:
```
docker run -d -it -p 25565:25565 -e EULA=TRUE itzg/minecraft-server
```
Logs:
```
> Executing task: docker logs --tail 1000 -f 35aef5186994c052f758eddeecd97fe8aff89a054d9b49ab30c2a12c373655be <

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 May 20 13:12 /data'
[init] Resolved version given LATEST into 1.16.5
[init] Resolving type given VANILLA
[init] Downloading minecraft_server.1.16.5.jar ...
[init] Creating server.properties in /data/server.properties
[init] Disabling whitelist
[init] Setting whitelist to 'false' in /data/server.properties
[init] Setting white-list to 'false' in /data/server.properties
[init] Adding server-name with 'Dedicated Server' in /data/server.properties
[init] Setting server-port to '25565' in /data/server.properties
[init] Setting motd to 'A Vanilla Minecraft Server powered by Docker' in /data/server.properties
[init] Setting enable-rcon to 'true' in /data/server.properties
[init] Setting rcon.password to 'minecraft' in /data/server.properties
[init] Setting rcon.port to '25575' in /data/server.properties
[init] Setting level-name to 'world' in /data/server.properties
[init] Setting online-mode to 'true' in /data/server.properties
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
[13:12:15] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:12:15] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: java.nio.file.FileSystemException: .: Operation not permitted
        at cyg.<init>(SourceFile:98) ~[minecraft_server.1.16.5.jar:?]
        at cyg.a(SourceFile:105) ~[minecraft_server.1.16.5.jar:?]
        at net.minecraft.server.Main.main(SourceFile:117) [minecraft_server.1.16.5.jar:?]
Caused by: java.nio.file.FileSystemException: .: Operation not permitted
        at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.UnixPath.toRealPath(Unknown Source) ~[?:?]
        at cyg.<init>(SourceFile:96) ~[minecraft_server.1.16.5.jar:?]
        ... 2 more
2021-05-20T13:12:15.254Z        INFO    mc-server-runner        Done
```

**Comment by plasmatech8** [comment]
`itzg/minecraft-server:2021.12.0-java16` does work though

**Comment by chrisimi** [comment]
Same here, latest does not work but `itzg/minecraft-server:2021.12.0-java16` does work

**Comment by kstunger** [comment]
I'm seeing the same thing.

**Comment by nmills3** [comment]
same here

**Comment by itzg** [comment]
I have confirmed I'm also seeing this, but am not sure yet what happened in the image to cause this. 

Please use `itzg/minecraft-server:java16` in the meantime, especially since that will become "latest" along with the 1.17 release of Minecraft.

**Comment by itzg** [comment]
I went ahead and switched over `latest` to be Java 16 and now the original issue has been resolved/avoided. I'll investigate more into the root cause, but it might remain a mystery.

**Comment by plasmatech8** [comment]
> I went ahead and switched over `latest` to be Java 16 and now the original issue has been resolved/avoided. I'll investigate more into the root cause, but it might remain a mystery.

Works 😄 looks good
