### ISSUE TITLE
Problems with cloning world: read-only error in logs

### ISSUE THREAD

**Issue by jgalak** [itzg/docker-minecraft-server#895]
I'm trying to set up a MC server and use it to run an existing modded world (previously played in local multiplayer by using the "Open to LAN" command in a windows version of MC Java).   I am using Docker 20.10.1 on Ubuntu 20.04.2 LTS.

I have created the following `docker-compose.yaml` file:  
```
version: "3.6"

services:
    mc:
        image: itzg/minecraft-server:java8

        ports:
            - 25565:25565

        environment:
            EULA: "TRUE"
            VERSION: "1.16.5"
            TYPE: FORGE
            FORGEVERSION: "36.1.0"
            SERVER_NAMME: "ClarendonAbbey"
            WORLD: "/worlds/CreateLan"
            #LEVEL: "CreateLan"
            ENABLE_RCON: "true"
            RCON_PASSWORD: "testing"
            #ALLOW_NETHER: "true"
            ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
            SNOOPER_ENABLED: "false"
            FORCE_WORLD_COPY: "true"


        volumes:
            - ./mc_forge:/data
            - ./mods:/mods:ro
            - ./worlds:/worlds:ro

        tty: true
        stdin_open: true
        restart: always
```

On the linux server I have the following directory structure:
```
~/minecraft
~/minecraft/mc_forge
~/minecraft/mods
~/minecraft/worlds
```

I copied the entire `CreateLan` directory from `%appdata%\.minecraft\saves\` to the `~/minecraft/worlds` directory on the Linux server.  

When I bring up the container, I get the following error message: 

```[22:02:48] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
java.nio.file.FileSystemException: /worlds/CreateLan/session.lock: Read-only file system
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.8.0_212] {}
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_212] {}
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_212] {}
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177) ~[?:1.8.0_212] {}
        at java.nio.channels.FileChannel.open(FileChannel.java:287) ~[?:1.8.0_212] {}
        at java.nio.channels.FileChannel.open(FileChannel.java:335) ~[?:1.8.0_212] {}
        at net.minecraft.server.SessionLockManager.func_232998_a_(SourceFile:37) ~[?:?] {re:classloading}
        at net.minecraft.world.storage.SaveFormat$LevelSave.<init>(SaveFormat.java:277) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.storage.SaveFormat.func_237274_c_(SaveFormat.java:265) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.Main.main(Main.java:116) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.1.0.jar:36.1] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.1.0.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.1.0.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.1.0.jar:?] {}
```
I've tried running `sudo chmod -R a+rw .` from the `~/minecraft` directory, to no avail.

I see that it's created a `CreateLan` directory inside `mc_forge`, but it looks like it's trying to write back to `/worlds/CreateLan` directory, which it should only be cloning from?  

Help?

**Comment by itzg** [comment]
I am not able to recreate the issue using your compose file and some placeholder files/directories. Can you provide the output of `docker image inspect itzg/minecraft-server:java8 -f '{{json .Config.Labels}}'` ?

**Comment by jgalak** [comment]
```
jgalak@dock:~/minecraft$ docker image inspect itzg/minecraft-server:java8 -f '{{json .Config.Labels}}'
{"org.opencontainers.image.authors":"Geoff Bourne <itzgeoff@gmail.com>","org.opencontainers.image.documentation":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.revision":"5f95d135f51f6a9e2c129e46844f3f3d90dac7aa","org.opencontainers.image.source":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.version":"java8"}

```

**Comment by MayurMhatre** [comment]
%appdata%\.minecraft\saves\ 

try changing permission to both read and write, maybe that could solve the issue.

**Comment by itzg** [comment]
Thanks @jgalak that confirms you're using the latest image and that's the same as my test. I'm wondering if something is lingering in your server.properties that is calling out that path.

**Comment by jgalak** [comment]
> 
> 
> Thanks @jgalak that confirms you're using the latest image and that's the same as my test. I'm wondering if something is lingering in your server.properties that is calling out that path.

I think that was it.  I found a line like `level name = /worlds/CreateLan` in `server.properties`.  Out of an abundance of caution, I just deleted everything in the `mc_forge` directory and it seems to be working fine now.  

Thanks!

**Comment by itzg** [comment]
Aha, that's the one I suspected. Glad you got it working. Good to close?

**Comment by jgalak** [comment]
> Aha, that's the one I suspected. Glad you got it working. Good to close?

Yup, thanks for the help!
