### ISSUE TITLE
Repeatedly crashing on startup. (Vannila) 1.17

### ISSUE THREAD

**Issue by MockyX50** [itzg/docker-minecraft-server#919]
Followed this guide. https://drfrankenstein.co.uk/2021/05/03/minecraft-java-server-in-docker-on-a-synology-nas-including-mods/

Server seems to be crashing on startup every time.
I've given it no limitations on how much of my cpu or ram can use.

Here's the crash log.
[crash-2021-06-11_05.44.50-server.txt](https://github.com/itzg/docker-minecraft-server/files/6636188/crash-2021-06-11_05.44.50-server.txt)

**Comment by itzg** [comment]
I can't seem to access that crash log, but in any case the container logs would actually be more helpful. Can you also provide more info about container variables you have set and what image+tag you're using?

**Comment by markusjohnsson** [comment]
I'm getting this error:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/server/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
So, probably need a bumped Java version?

**Comment by itzg** [comment]
Yep that was going to be the definite solution, but also re-pulling the latest image tag gets Java 16

**Comment by stevedwray** [comment]
I'm having the same problem with the java16 tag and the latest tag too.
In the container logs I can see:
minecraft_1  | [20:42:39] [Server Watchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
minecraft_1  | [20:42:39] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.

I'm running this on a pi 4 with 4G RAM. 
It was running 1.16 just fine for some time, with 2 players.

**Comment by MockyX50** [comment]
> I can't seem to access that crash log, but in any case the container logs would actually be more helpful. Can you also provide more info about container variables you have set and what image+tag you're using?


[itzg-minecraft-server1.17.csv](https://github.com/itzg/docker-minecraft-server/files/6641486/itzg-minecraft-server1.17.csv)
here's the container log. 
I have 2G's of RAM since it's only for 2 people and 2 cores running at 2GHz.

**Comment by itzg** [comment]
@MockyX50 I see your host CPU is a `Celeron(R) CPU J3355 @ 2.00GHz`. It is going to be tough for you to get good performance on that CPU type. Try using `TYPE=PAPER` since they have included some optimizations that might help.

**Comment by MockyX50** [comment]
@itzg Seems to be causing it to crash even faster! haha. I'm gonna move this server over to another more higher spec station I have. I would think most of the issues I'm having are coming from how low spec my Synolgy Station is.
