### ISSUE TITLE
[Question]: Autopause - Disable WatchDog with PaperMC

### ISSUE THREAD

**Issue by SILENCE-ETERNAL** [itzg/docker-minecraft-server#963]
I'm running a Paper server and testing out the Autopause feature, however I am unable to find a way to disable the watchdog in the Paper configs. The documentation mentions that this is separate from the standard server.properties, but doesn't list where. Has anyone figured this out or should I open this question over at the PaperMC repo? Thanks for taking a look!

Following are excerpts of the configs along with a watchdog crash example

docker-compose.yml:
```
version: '2'
services:
    minecraft-server:
        volumes:
            - '/home/user/mc:/data'
        ports:
            - '25565:25565'
            - '8123:8123'
        environment:
            - EULA=TRUE
            - VERSION=LATEST
            - TYPE=PAPER
            - SPIGET_RESOURCES=274,1331
            - USE_AIKAR_FLAGS=true
            - MEMORY=2G
            - OVERRIDE_SERVER_PROPERTIES=true
            - MAX_TICK_TIME=-1
            - ENABLE_AUTOPAUSE=true
            - AUTOPAUSE_TIMEOUT_EST=120
            - AUTOPAUSE_TIMEOUT_INIT=60
        container_name: mc
        image: itzg/minecraft-server
        restart: always
```

server.properties
```
max-tick-time=-1
```

spigot.yml
```
settings:
  timeout-time: 0
```

paper.yml
```
settings:
  watchdog:
    early-warning-every: 5000
    early-warning-delay: 99999999999
```

docker logs mc
```
[11:41:09 INFO]: MinecraftUser left the game
[Autopause loop] All clients disconnected - stopping in 120 seconds
[Autopause loop] No client reconnected - stopping
[11:43:18 INFO]: Thread RCON Client /127.0.0.1 started
[11:43:18 INFO]: [Rcon: Saved the game]
[11:43:18 INFO]: Thread RCON Client /127.0.0.1 shutting down
[2021-07-08T11:43:18-05:00] [Autopause] Pausing Java process
[12:03:52 ERROR]: ------------------------------
[12:03:52 ERROR]: The server has stopped responding! This is (probably) not a Paper bug.
[12:03:52 ERROR]: If you see a plugin in the Server thread dump below, then please report it to that author
[12:03:52 ERROR]:        *Especially* if it looks like HTTP or MySQL operations are occurring
[12:03:52 ERROR]: If you see a world save or edit, then it means you did far more than your server can handle at once
[12:03:52 ERROR]:        If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes
[12:03:52 ERROR]: If you are unsure or still think this is a Paper bug, please report this to https://github.com/PaperMC/Paper/issues
[12:03:52 ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[12:03:52 ERROR]: Paper version: git-Paper-90 (MC: 1.17.1)
[12:03:52 ERROR]: ------------------------------
[12:03:52 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[12:03:52 ERROR]: ------------------------------
[12:03:52 ERROR]: Current Thread: Server thread
[12:03:52 WARN]: Can't keep up! Is the server overloaded? Running 1233193ms or 24663 ticks behind
[12:03:52 ERROR]:       PID: 27 | Suspended: false | Native: false | State: RUNNABLE
[12:03:52 ERROR]:       Stack:
[12:03:52 ERROR]:               app//it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:356)
...etc....
[12:03:53 ERROR]: ------------------------------
[Autopause loop] Server was knocked - waiting for clients or timeout
[12:03:54 INFO]: Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[12:03:54 ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
        at java.lang.Thread.stop(Unknown Source) [?:?]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:947) ~[patched_1.17.1.jar:git-Paper-90]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:806) ~[patched_1.17.1.jar:git-Paper-90]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:919) ~[patched_1.17.1.jar:git-Paper-90]
        at org.spigotmc.WatchdogThread.run(WatchdogThread.java:161) ~[patched_1.17.1.jar:git-Paper-90]
[12:03:54 INFO]: Stopping server
[12:03:54 INFO]: [SuperVanish] Disabling SuperVanish v6.2.6
[12:03:54 INFO]: [dynmap] Disabling dynmap v3.2-beta-2-483
[12:03:54 INFO]: [dynmap] Unloaded 11 components.
[12:03:54 INFO]: [dynmap] Stopping map renderer...
[12:03:55 INFO]: [dynmap] Disabled
[12:03:55 INFO]: Saving players
[12:03:55 INFO]: Saving worlds
[12:03:55 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[12:03:55 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[12:03:55 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[12:03:55 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:03:55 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:03:55 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:03:55 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[12:03:55 INFO]: Flushing Chunk IO
[12:03:55 INFO]: Closing Thread Pool
[12:03:55 INFO]: Closing Server

---- docker container restarts, Paper server starts back up ---
```

This doesn't happen every time, there seems to be some cutoff time (5 minutes?) after which the Watchdog will reliably crash the server. See this log where it didn't crash:
```
[23:04:48 INFO]: Running delayed init tasks
[23:04:48 INFO]: Done (20.612s)! For help, type "help"
[23:04:48 INFO]: Timings Reset
[23:04:48 INFO]: [dynmap] Loading default resource pack
[23:04:49 INFO]: UUID of player MinecraftUser is xxxxxxxxxxxxxxxxxxxxxxxxxxxx
[23:04:50 INFO]: MinecraftUser joined the game
[23:04:50 INFO]: MinecraftUser[/xxxxxxxxxxxxxxxxxxxxx] logged in with entity id 306 at ([world]318.52731907022263, 79.5625, 193.24344409991264)
[00:19:27 INFO]: MinecraftUser lost connection: Disconnected
[00:19:27 INFO]: MinecraftUser left the game
[Autopause loop] All clients disconnected - stopping in 120 seconds
[Autopause loop] No client reconnected - stopping
[00:21:28 INFO]: Thread RCON Client /127.0.0.1 started
[00:21:28 INFO]: [Rcon: Saved the game]
[00:21:28 INFO]: Thread RCON Client /127.0.0.1 shutting down
[2021-07-09T00:21:28-05:00] [Autopause] Pausing Java process
[00:25:16 WARN]: Can't keep up! Is the server overloaded? Running 227427ms or 4548 ticks behind
[Autopause loop] Client connected - waiting for disconnect
[00:25:16 INFO]: UUID of player MinecraftUser is xxxxxxxxxxxxxxxxxxxxxxxx
[00:25:17 INFO]: MinecraftUser joined the game
[00:25:17 INFO]: MinecraftUser[/xxxxxxxxxxxxxxxxx] logged in with entity id 16131 at ([world]602.9228774579246, 13.0, 924.9436658426872)
[01:10:03 INFO]: MinecraftUser lost connection: Disconnected
[01:10:03 INFO]: MinecraftUser left the game
[Autopause loop] All clients disconnected - stopping in 120 seconds
[Autopause loop] No client reconnected - stopping
[01:12:11 INFO]: Thread RCON Client /127.0.0.1 started
[01:12:11 INFO]: [Rcon: Saved the game]
[01:12:11 INFO]: Thread RCON Client /127.0.0.1 shutting down
[2021-07-09T01:12:11-05:00] [Autopause] Pausing Java process
```

**Comment by itzg** [comment]
Yeah, I'd say ask around with the PaperMC people. Please report back here if you find out anything.

**Comment by SILENCE-ETERNAL** [comment]
Heard back from some helpful people in the PaperMC Discord:

The necessary config change here is a JVM flag: `-Ddisable.watchdog=true`

The docker environment variable to pass this would be `JVM_DD_OPTS=disable.watchdog:true`

I've tested this and confirmed that it will successfully resume a Paper server that's been paused for more than 5 hours. I'll see if I can open a pull request to edit this part of the README to add this info, then we can close this. Thanks!

**Comment by itzg** [comment]
Fantastic and thanks for following up. A PR will be great.

**Comment by itzg** [comment]
Closed by #967

**Comment by widescreenFR** [comment]
> The docker environment variable to pass this would be `JVM_DD_OPTS=disable.watchdog:true`

Hi, where should this variable be included? In the main docker compose or the paper yml?

**Comment by itzg** [comment]
Put it in compose file's environment variables.
