### ISSUE TITLE
[FABRIC/1.16.5] [mod] requires any version of mod fabric, which is missing!

### ISSUE THREAD

**Issue by ee6f8317** [itzg/docker-minecraft-server#980]
Hi, tried to install those following mode on a fresh docker install on unraid:
ferritecore-2.0.5-fabric
krypton-0.1.2
lithium-fabric-mc1.16.5-0.6.6
overworld-two-1.0.4

Here's what the log say:
```
[init] Resolving type given FABRIC
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 3G and max to 3G
[init] Using Aikar's flags
[init] Starting the Minecraft server...
[21:03:26] [main/INFO]: Loading for game Minecraft 1.16.5
[21:03:26] [main/FATAL]: A critical error occurred

net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
- Mod 'Overworld 2' (overworld_two) requires any version of mod fabric, which is missing!
- You must install any version of fabric.
- Mod 'FerriteCore' (ferritecore) requires any version of mod fabric, which is missing!
- You must install any version of fabric.
at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:342) ~[fabric-server-1.16.5.jar:?]
at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-server-1.16.5.jar:?]
at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-server-1.16.5.jar:?]
at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-server-1.16.5.jar:?]
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-server-1.16.5.jar:?]
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-1.16.5.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-1.16.5.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-1.16.5.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-1.16.5.jar:?]
2021-07-16T21:03:27.157-0500 WARN mc-server-runner sub-process failed {"exitCode": 1}

2021-07-16T21:03:27.157-0500 INFO mc-server-runner Done
2021-07-16T21:03:27.157-0500 WARN mc-server-runner sub-process failed {"exitCode": 1}
```

and then the container shut down

**Comment by itzg** [comment]
This is not an issue with the docker image. You're missing the fabric api jar along with the mods

https://fabricmc.net/wiki/tutorial:adding_mods
